const l = (tr, en, es) => [tr, en, es];

export const dietaryData = {
  AE: {
    Dubai: {
      vegan: [{
        name: 'SEVA Experience',
        cuisine: l('Bitki bazlı ve glütensiz kafe', 'Plant-based and gluten-free cafe', 'Cafetería vegetal y sin gluten'),
        area: l('Jumeirah 1', 'Jumeirah 1', 'Jumeirah 1'),
        description: l('Yeşillikler içindeki bahçe avlusunda çiğ tatlılar, besleyici kinoa kaseleri ve organik lezzetler sunan Dubai\'nin ilk tamamen vegan sağlıklı yaşam vahası.', 'Dubai\'s original fully plant-based cafe, serving raw desserts, wholesome smoothie bowls and gluten-free dishes in a serene garden.', 'La primera cafetería 100% vegetal de Dubái, con repostería crudivegana, boles de quinoa y platos sin gluten en un jardín tranquilo.'),
        why: l('Dubai\'de gökdelen temposundan uzak, sakin bir bahçede %100 bitki bazlı ve glütensiz bir kahvaltı veya öğle yemeği için 1 numaradır.', 'The leading spot in Dubai for a 100% plant-based, gluten-free breakfast or lunch in a peaceful garden setting away from the towers.', 'El lugar de referencia en Dubái para un desayuno o almuerzo 100% vegetal y sin gluten en un jardín relajante lejos de los rascacielos.'),
        price: 'Orta',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/seva-table-dubai-44280',
        sourceType: 'vegan-directory',
        note: l('Menünün tamamı %100 bitki bazlı ve glütensizdir; süt ve yumurta dahil hiçbir hayvansal ürün kullanılmaz.', 'The entire menu is 100% plant-based and gluten-free; no animal products including dairy or eggs are used.', 'Toda la carta es 100% vegetal y sin gluten; no se utiliza ningún producto de origen animal.'),
      }],
      halal: [{
        name: 'Al Fanar Restaurant & Cafe',
        cuisine: l('Geleneksel Emirlik mutfağı', 'Traditional Emirati cuisine', 'Cocina emiratí tradicional'),
        area: l('Al Seef / Dubai Creek', 'Al Seef / Dubai Creek', 'Al Seef / Dubai Creek'),
        description: l('1960\'ların otantik Emirlik mimarisinde odun ateşinde machboos, aromatik harees ve çıtır luqaimat tatlısı sunan tescilli geleneksel helal restoran.', 'Authentic Emirati restaurant in a nostalgic 1960s courtyard setting, serving traditional machboos, harees and freshly fried luqaimat.', 'Restaurante emiratí tradicional en un patio ambientado en los años 60, con machboos a fuego lento, harees y buñuelos luqaimat.'),
        why: l('Dubai Creek kıyısında otantik Emirlik mutfağını ve tescilli helal etlerini tarihî bir ambiyansta deneyimlemek için en güvenilir adrestir.', 'The most trusted address along Dubai Creek to experience authentic Emirati recipes and certified halal meats in a heritage atmosphere.', 'La dirección más fiable junto a Dubai Creek para probar recetas emiratíes tradicionales y carnes halal certificadas en un entorno histórico.'),
        price: 'Orta',
        status: 'certified-halal',
        sourceName: l('Visit Dubai — resmî gastronomi rehberi', 'Visit Dubai — official gastronomy guide', 'Visit Dubai — guía gastronómica oficial'),
        sourceUrl: 'https://www.visitdubai.com/en/places-to-visit/al-fanar-restaurant-and-cafe',
        sourceType: 'official-tourism',
        note: l('Et tedariki BAE resmî helal standartlarına uygundur; mekânda alkol servisi bulunmamaktadır.', 'Meat sourcing complies with official UAE halal standards; no alcohol is served on the premises.', 'El suministro de carne cumple las normas halal oficiales de EAU; no se sirve alcohol en el establecimiento.'),
      }],
      researchNote: l('Dubai\'de yerel Emirlik yemekleri çoğunlukla helaldir; lüks otel restoranlarında alkol servisi yaygındır. Vegan tercihlerde tereyağı ve ghee (sade yağ) ayrımını baştan belirtin.', 'Local Emirati food in Dubai is generally halal; luxury hotel dining often includes alcohol service. For vegan meals, confirm that butter or ghee is not used.', 'La cocina emiratí en Dubái suele ser halal; los restaurantes de hoteles de lujo suelen servir alcohol. Para opciones veganas, confirma que no se use mantequilla ni ghee.'),
    },
    'Abu Dabi': {
      vegan: [{
        name: 'Wild & The Moon',
        cuisine: l('Organik vegan kafe', 'Organic vegan cafe', 'Cafetería vegana ecológica'),
        area: l('Qasr Al Hosn Kültür Bölgesi', 'Qasr Al Hosn Cultural Quarter', 'Zona cultural de Qasr Al Hosn'),
        description: l('Tarihi Qasr Al Hosn kalesi yanında %100 organik, soğuk sıkım sular, acai kaseleri ve katkısız bitki bazlı yemekler sunan çağdaş vegan kafe.', 'Contemporary 100% organic vegan cafe near historic Qasr Al Hosn, offering cold-pressed juices, acai bowls and wholesome plant-based meals.', 'Cafetería vegana 100% orgánica junto al histórico Qasr Al Hosn, con zumos prensados en frío, boles de açai y platos saludables.'),
        why: l('Müze ve kültür gezisi sırasında hafif, taze ve tamamen bitkisel beslenmek isteyenler için Abu Dabi\'deki en kaliteli vahalardan biridir.', 'One of Abu Dhabi\'s finest stops for a light, fresh and entirely plant-based meal while exploring the cultural district.', 'Una de las mejores opciones en Abu Dabi para una comida ligera, fresca y vegetal mientras se visita la zona cultural.'),
        price: 'Orta',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/wild-and-the-moon-cultural-foundation-abu-dhabi-209252',
        sourceType: 'vegan-directory',
        note: l('Tamamen bitki bazlı, katkısız ve süt ürünü içermeyen organik içerik doğrulanmıştır.', 'Verified 100% plant-based, unrefined and dairy-free organic ingredients.', 'Ingredientes ecológicos verificados, 100% vegetales, sin refinar y sin lácteos.'),
      }],
      halal: [{
        name: 'Meylas',
        cuisine: l('Emirlik ev yemekleri', 'Emirati home cooking', 'Cocina casera emiratí'),
        area: l('Al Muneera / Al Raha Beach', 'Al Muneera / Al Raha Beach', 'Al Muneera / Al Raha Beach'),
        description: l('Emirlik kadınları tarafından işletilen, deniz kenarında taze fırın ekmekleri, kuzu machboos ve ev yapımı yerel lezzetler sunan tescilli helal durak.', 'Warm Emirati restaurant founded by local women, serving freshly baked khameer breads, lamb machboos and home-style Gulf recipes by the water.', 'Acogedor restaurante emiratí impulsado por mujeres locales, con panes khameer recién horneados, machboos de cordero y recetas caseras del Golfo.'),
        why: l('Körfez mutfağının geleneksel lezzetlerini ticari olmayan samimi bir aile mutfağı dokusuyla deneyimlemek için idealdir.', 'Ideal for experiencing authentic Gulf home cooking in a welcoming, family-run atmosphere by the water.', 'Ideal para disfrutar de la auténtica cocina casera del Golfo en un ambiente familiar y junto al mar.'),
        price: 'Orta',
        status: 'certified-halal',
        sourceName: l('Experience Abu Dhabi — resmî turizm portalı', 'Experience Abu Dhabi — official tourism portal', 'Experience Abu Dhabi — portal oficial de turismo'),
        sourceUrl: 'https://visitabudhabi.ae/en/where-to-eat/meylas',
        sourceType: 'official-tourism',
        note: l('Tüm etler helal sertifikalıdır; alkolsüz aile dostu işletmedir.', 'All meats are halal certified; family-friendly alcohol-free venue.', 'Todas las carnes tienen certificación halal; local familiar sin alcohol.'),
      }],
      researchNote: l('Abu Dabi\'de pilav ve et yemekleri helal kurallara uygundur; vegan tercihlerde et suyu veya tereyağı kullanılmadığını sipariş anında teyit edin.', 'Rice and meat dishes in Abu Dhabi follow halal standards; for vegan meals, confirm that meat stock or butter is not used.', 'Los arroces y carnes en Abu Dabi siguen pautas halal; para platos veganos, confirma que no lleven caldo de carne ni mantequilla.'),
    },
  },
  EG: {
    Kahire: {
      vegan: [{
        name: 'Koshary Abou Tarek',
        cuisine: l('Geleneksel Mısır koşerisi', 'Traditional Egyptian koshary', 'Koshary egipcio tradicional'),
        area: l('Downtown / Champollion St', 'Downtown / Champollion St', 'Downtown / Champollion St'),
        description: l('1950\'den beri Mısır\'ın milli sokak lezzeti olan mercimek, pirinç, nohut, makarna ve çıtır soğanlı geleneksel koşeriyi doğası gereği %100 vegan sunan ikonik başkent tapınağı.', 'Cairo\'s legendary multi-storey koshary landmark since 1950, serving Egypt\'s naturally vegan national dish of lentils, rice, pasta and crispy fried onions.', 'Emblema cairota de koshary desde 1950, que sirve el plato nacional naturalmente vegano a base de lentejas, arroz, pasta y cebolla crujiente.'),
        why: l('Mısır\'ın en ünlü yemeğini en otantik ve hızlı haliyle tatmak için Kahire\'nin tartışmasız 1 numaralı halk lokantasıdır.', 'Undisputed Cairo institution to enjoy Egypt\'s most celebrated dish in its most authentic, fast-paced setting.', 'Institución indiscutible en El Cairo para probar el plato más famoso de Egipto en su ambiente más auténtico.'),
        price: 'Ekonomik',
        status: 'vegan-focused',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/koshary-abou-tarek-cairo-13233',
        sourceType: 'vegan-directory',
        note: l('Geleneksel koşeri tamamen bitkisel malzemelerle pişirilir; domates sosu ve sarımsaklı sirke vegan uyumludur.', 'Traditional koshary is made entirely with plant-based ingredients; tomato sauce and garlic vinegar are vegan friendly.', 'El koshary tradicional se elabora únicamente con ingredientes vegetales; salsa de tomate y vinagre de ajo son aptos.'),
      }],
      halal: [{
        name: 'Farahat',
        cuisine: l('Mısır ızgara ve güvercin dolması', 'Egyptian grills and stuffed squab', 'Parrilla egipcia y paloma rellena'),
        area: l('Al-Azhar / Khan el-Khalili', 'Al-Azhar / Khan el-Khalili', 'Al-Azhar / Khan el-Khalili'),
        description: l('Tarihi çarşı meydanında odun kömüründe pişen helal güvercin dolması (hamam mahshi), kuzu pirzola ve taze fırın lavaşlarıyla asırlık Kahire klasiği.', 'Celebrated historic eatery in the Khan el-Khalili bazaar, renowned for traditional halal stuffed squab (hamam mahshi) and charcoal-grilled lamb.', 'Restaurante histórico en el bazar de Khan el-Khalili, famoso por sus palomas rellenas halal (hamam mahshi) y cordero a la brasa.'),
        why: l('Khan el-Khalili sokaklarında gezerken Mısır usulü geleneksel helal et ve güvercin lezzetini tatmak için en köklü duraktır.', 'The most established stop in the alleys of Khan el-Khalili to taste traditional Egyptian halal grilled meats and squab.', 'La parada más clásica en los callejones de Khan el-Khalili para degustar carnes a la brasa halal y paloma rellena egipcia.'),
        price: 'Orta',
        status: 'restaurant-confirmed',
        sourceName: l('Mısır Turizm Otoritesi — geleneksel restoranlar', 'Egyptian Tourism Authority — heritage dining', 'Autoridad de Turismo de Egipto — gastronomía tradicional'),
        sourceUrl: 'https://www.egypt.travel/',
        sourceType: 'official-tourism',
        note: l('Geleneksel İslami usullere göre helal et servisi yapılır; mekânda alkol servisi yoktur.', 'Serves halal meats in accordance with traditional Islamic standards; no alcohol is served.', 'Sirve carnes halal según las pautas islámicas tradicionales; no se sirve alcohol.'),
      }],
      researchNote: l('Kahire\'de sokak lezzetlerinden koşeri ve taameya (bakla falafeli) doğası gereği bitkiseldir; et yemeklerinin tamamı yerel helal standartlara uygundur.', 'Cairo street foods like koshary and taameya (fava falafel) are naturally plant-based; meat preparations follow local halal standards.', 'La comida callejera de El Cairo como el koshary y la taameya es naturalmente vegetal; las carnes siguen los estándares halal locales.'),
    },
    Luksor: {
      vegan: [{
        name: 'Sofra Restaurant & Cafe',
        cuisine: l('Geleneksel Mısır ve zeytinyağlılar', 'Traditional Egyptian and mezze', 'Cocina egipcia tradicional y mezes'),
        area: l('Doğu Yakası / Mohamed Farid St', 'East Bank / Mohamed Farid St', 'Orilla este / Mohamed Farid St'),
        description: l('1930\'lar Mısır konağında taze tahinli babaganuş, domatesli bamya güveci ve yerel sebzelerle hazırlanan zengin vegan meze tabakları.', 'Atmospheric 1930s Egyptian townhouse offering rich plant-based mezze, okra tagines, tahini dips and seasonal Nile valley vegetables.', 'Casona egipcia de los años 30 con ricos mezes vegetales, tajines de quimbombó, salsas de sésamo y verduras frescas del valle del Nilo.'),
        why: l('Tapınak gezileri sonrasında sakin bir avluda sebze ağırlıklı geleneksel Nil mutfağını deneyimlemek için Luksor\'daki en zarif adrestir.', 'The most atmospheric dining address in Luxor for a vegetable-focused traditional meal in a peaceful courtyard after visiting temples.', 'La dirección más acogedora de Luxor para una comida tradicional centrada en verduras en un patio tranquilo tras visitar los templos.'),
        price: 'Orta',
        status: 'vegan-focused',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/sofra-luxor-20387',
        sourceType: 'vegan-directory',
        note: l('Zeytinyağlı mezeler ve sebze güveçleri tereyağsız ve et suyu katılmadan hazırlanır.', 'Olive oil mezze and vegetable stews are prepared without butter or meat stock.', 'Los mezes con aceite de oliva y guisos de verduras se elaboran sin mantequilla ni caldo de carne.'),
      }],
      halal: [{
        name: 'Al-Sahaby Lane Restaurant',
        cuisine: l('Mısır güveçleri ve ızgaralar', 'Egyptian tagines and grills', 'Tajines egipcios y parrilla'),
        area: l('Luksor Çarşısı / Nefertiti Hotel Çatısı', 'Luxor Souk / Nefertiti Hotel Rooftop', 'Zoco de Luxor / Azotea del Nefertiti Hotel'),
        description: l('Nil Nehri ve Luksor Tapınağı manzaralı terasta taze helal kuzu tajin, deve burger ve fırından sıcak çıkan Mısır fırın ekmekleri.', 'Rooftop restaurant overlooking Luxor Temple and the Nile, serving halal lamb tagines, camel meat specialties and fresh Egyptian flatbreads.', 'Terraza con vistas al templo de Luxor y al Nilo, con tajines de cordero halal, especialidades de carne y panes egipcios recién horneados.'),
        why: l('Tapınak silüetine karşı kaliteli helal et yemekleri ve taze fırın ürünleri tatmak için kentin en popüler seyir terasıdır.', 'Luxor\'s most popular panoramic terrace to enjoy quality halal meat dishes and oven-fresh breads facing the temple skyline.', 'La terraza panorámica más popular de Luxor para saborear platos halal de calidad y panes recién horneados frente al templo.'),
        price: 'Orta',
        status: 'restaurant-confirmed',
        sourceName: l('Mısır Turizm Otoritesi — Luksor rehberi', 'Egyptian Tourism Authority — Luxor guide', 'Autoridad de Turismo de Egipto — guía de Luxor'),
        sourceUrl: 'https://www.egypt.travel/en/regions/nile-valley/luxor',
        sourceType: 'official-tourism',
        note: l('Etler yerel helal sertifikalı kasaplardan temin edilir; alkolsüz yemek bölümü bulunur.', 'Meats sourced from local halal certified suppliers; alcohol-free dining areas available.', 'Carnes procedentes de proveedores locales con certificación halal; zonas sin alcohol disponibles.'),
      }],
      researchNote: l('Luksor\'da tur restoranlarında et sularına dikkat edin; sebze yemeklerinde vegan tercihinizi masada belirtin.', 'Check stocks in tour-group restaurants in Luxor; confirm plant-based preferences when ordering vegetable dishes.', 'Comprueba caldos en restaurantes de grupos turísticos en Luxor; confirma platos vegetales al pedir.'),
    },
    Hurgada: {
      vegan: [{
        name: 'Gelo Vegan Restaurant',
        cuisine: l('Akdeniz ve sağlıklı kaseler', 'Mediterranean and healthy bowls', 'Boles mediterráneos saludables'),
        area: l('Hurgada Marina çevresi', 'Hurghada Marina area', 'Zona del puerto deportivo de Hurgada'),
        description: l('Kızıldeniz sahilinde taze Akdeniz sebzeleri, falafel kaseleri, kinoa salataları ve bitkisel sütlü kahveler sunan huzurlu vegan kafe.', 'Relaxed Red Sea cafe offering fresh Mediterranean bowls, falafel salads, plant-based smoothies and speciality coffee near the marina.', 'Cafetería tranquila junto al mar Rojo con boles mediterráneos, ensaladas con falafel, batidos vegetales y café de especialidad.'),
        why: l('Her şey dahil otel büfelerinden uzakta, taze ve yaratıcı bitki bazlı lezzetler arayan gezginler için harika bir sahil molasıdır.', 'A refreshing coastal break for travelers seeking fresh, creative plant-based dishes away from resort buffets.', 'Un descanso refrescante para quienes buscan opciones vegetales frescas y creativas fuera de los bufés de hotel.'),
        price: 'Orta',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/gelo-vegan-hurghada-321150',
        sourceType: 'vegan-directory',
        note: l('Tüm menü bitki bazlıdır; glütensiz ve şekersiz seçenekler mevcuttur.', 'Entire menu is plant-based; gluten-free and refined-sugar-free choices available.', 'Toda la carta es vegetal; dispone de opciones sin gluten y sin azúcares refinados.'),
      }],
      halal: [{
        name: 'Al Halaka Fish Market Restaurant',
        cuisine: l('Kızıldeniz taze balık ve deniz ürünleri', 'Fresh Red Sea seafood', 'Pescado fresco del mar Rojo'),
        area: l('El Mina Camii yanı', 'Beside El Mina Mosque', 'Junto a la mezquita El Mina'),
        description: l('Tarihi cami ve balık hali yanında günlük tutulan taze Kızıldeniz balıklarını İslami usullere uygun helal ızgara ve fırında hazırlayan ünlü liman lokantası.', 'Famous waterfront seafood restaurant next to El Mina Mosque, serving fresh daily Red Sea catches prepared to halal standards.', 'Reconocido restaurante junto a la mezquita El Mina, con pescado fresco del mar Rojo preparado según las pautas halal.'),
        why: l('Hurgada\'da taze deniz mahsullerini yerel halkla iç içe ve helal mutfak güvencesiyle yemek için en otantik adrestir.', 'The most authentic place in Hurghada to enjoy freshly caught seafood alongside locals with verified halal kitchen practices.', 'El lugar más auténtico de Hurgada para comer pescado recién capturado junto a los lugareños con garantías halal.'),
        price: 'Orta',
        status: 'restaurant-confirmed',
        sourceName: l('Kızıldeniz Valiliği Turizm Rehberi', 'Red Sea Governorate Tourism Guide', 'Guía Turística de la Gobernación del Mar Rojo'),
        sourceUrl: 'https://www.egypt.travel/en/regions/red-sea/hurghada',
        sourceType: 'official-tourism',
        note: l('Müslüman topluluk odaklı helal işletmedir; alkol servisi bulunmaz.', 'Muslim-friendly halal establishment; no alcohol served.', 'Establecimiento halal orientado a la comunidad musulmana; no sirve alcohol.'),
      }],
      researchNote: l('Hurgada\'da balık restoranları helal beslenmeye çok uygundur; otel büfelerinde etiketleri ve ortak kaşıkları kontrol edin.', 'Seafood venues in Hurghada suit halal dining well; in resort buffets, verify dish labels and utensils.', 'Las marisquerías de Hurgada son muy adecuadas para dieta halal; en bufés de hotel, comprueba etiquetas y cubiertos.'),
    },
    'Şarm el-Şeyh': {
      vegan: [{
        name: 'Fairuz Restaurant',
        cuisine: l('Lübnan ve Akdeniz mezeleri', 'Lebanese and Mediterranean mezze', 'Cocina libanesa y mezes mediterráneos'),
        area: l('Naama Bay', 'Naama Bay', 'Naama Bay'),
        description: l('Taze humus, çıtır falafel, tabbouleh ve zengin Lübnan zeytinyağlı mezeleriyle tatilciler için güvenilir bitki bazlı Akdeniz durağı.', 'Welcoming Levantine restaurant in Naama Bay, serving authentic hummus, crispy falafel, tabbouleh and extensive olive oil vegetable mezze.', 'Acogedor restaurante levantino en Naama Bay con hummus auténtico, falafel crujiente, tabulé y ricos platos vegetarianos en aceite de oliva.'),
        why: l('Naama Bay sahilinde taze sebze ve bakliyat tabaklarıyla sağlıklı ve doyurucu bir vegan akşam yemeği için idealdir.', 'Ideal in Naama Bay for a wholesome, satisfying vegan dinner featuring fresh vegetables and pulse-based dishes.', 'Ideal en Naama Bay para una cena vegana completa a base de verduras frescas y legumbres.'),
        price: 'Orta',
        status: 'vegan-options',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/fairuz-sharm-el-sheikh-25801',
        sourceType: 'vegan-directory',
        note: l('Ayrı zeytinyağlı soğuk meze menüsü bulunur; yoğurtsuz tabaklar açıkça konuşulabilir.', 'Offers a separate olive oil cold mezze selection; dairy-free dishes can be requested directly.', 'Dispone de carta de mezes fríos en aceite de oliva; se pueden solicitar platos sin lácteos.'),
      }],
      halal: [{
        name: 'Fares Seafood',
        cuisine: l('Deniz mahsulleri ve Mısır mutfağı', 'Seafood and Egyptian cuisine', 'Marisco y cocina egipcia'),
        area: l('Eski Şehir / Old Market Meydanı', 'Old City / Old Market Square', 'Casco antiguo / Plaza del Old Market'),
        description: l('Sahaba Camii meydanında zengin deniz mahsulleri çorbası, ızgara karides ve taze balık tava sunan Mısır\'ın en popüler tescilli helal deniz ürünleri zinciri.', 'Iconic seafood institution opposite the Al Sahaba Mosque, famous for fragrant seafood chowder, grilled prawns and halal fresh fish.', 'Emblemático restaurante marinero frente a la mezquita Al Sahaba, famoso por su sopa de marisco, langostinos a la plancha y pescado fresco halal.'),
        why: l('Eski Pazar gezisi sonrasında muazzam çorbası ve taze balıklarıyla kentin tartışmasız en ünlü helal lezzet durağıdır.', 'The undisputed top halal seafood stop in Sharm, perfect after exploring the Old Market with its famous soup and fish.', 'La marisquería halal más destacada de Sharm, ideal tras recorrer el Old Market con su famosa sopa y pescado fresco.'),
        price: 'Orta',
        status: 'restaurant-confirmed',
        sourceName: l('Mısır Turizm Otoritesi — Sina Yarımadası', 'Egyptian Tourism Authority — Sinai Peninsula', 'Autoridad de Turismo de Egipto — Península del Sinaí'),
        sourceUrl: 'https://www.egypt.travel/en/regions/red-sea/sharm-el-sheikh',
        sourceType: 'official-tourism',
        note: l('Helal sertifikalı deniz ürünleri ve etler servis edilir; alkolsüz halk restoranıdır.', 'Serves halal-certified seafood and meats; alcohol-free casual dining venue.', 'Sirve marisco y carnes con certificación halal; restaurante informal sin alcohol.'),
      }],
      researchNote: l('Şarm el-Şeyh\'te Old Market bölgesindeki restoranlar İslami usullere tam uygundur; otel büfelerinde vegan sosları teyit edin.', 'Restaurants in Sharm el-Sheikh\'s Old Market follow halal standards; in resort buffets, confirm vegan-friendly dressings.', 'Los restaurantes del Old Market en Sharm siguen pautas halal; en los bufés de hotel, confirma los aliños veganos.'),
    },
  },
  GE: {
    Tiflis: {
      vegan: [{
        name: 'Kiwi Vegan Cafe',
        cuisine: l('Gürcü ve dünya vegan mutfağı', 'Georgian and global vegan cuisine', 'Cocina georgiana e internacional vegana'),
        area: l('Sololaki / Machabeli St', 'Sololaki / Machabeli St', 'Sololaki / Machabeli St'),
        description: l('Eski Tiflis\'in tarihi Sololaki semtinde cevizli Gürcü patlıcanı (badrijani), mantarlı khinkali ve bitki bazlı burgerler sunan öncü %100 vegan kafe.', 'Tbilisi\'s pioneering 100% vegan cafe in historic Sololaki, serving plant-based Georgian walnut rolls (badrijani), mushroom khinkali and hearty mains.', 'Cafetería 100% vegana pionera en el barrio histórico de Sololaki, con rollitos georgianos de berenjena y nuez (badrijani) y khinkali de setas.'),
        why: l('Geleneksel Gürcü hamur işleri ve cevizli mezelerini hiçbir hayvansal ürün riski olmadan tatmak için Kafkasya\'nın en güvenilir vegan noktasıdır.', 'The most trusted plant-based venue in the Caucasus to enjoy Georgian walnut mezze and dumplings with zero cross-contamination risk.', 'El local vegetal más fiable del Cáucaso para probar mezes y empanadillas georgianas sin riesgo de ingredientes animales.'),
        price: 'Ekonomik',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/kiwi-vegan-cafe-tbilisi-60293',
        sourceType: 'vegan-directory',
        note: l('Mutfakta et, süt, yumurta ve peynir kesinlikle kullanılmaz; tamamen bağımsız vegan işletmedir.', 'Completely independent vegan kitchen with no meat, dairy, eggs or cheese used.', 'Cocina totalmente vegana e independiente, sin carne, lácteos, huevos ni queso.'),
      }],
      halal: [{
        name: 'Ali Baba Halal Restaurant',
        cuisine: l('Kafkas ve Orta Doğu ızgaraları', 'Caucasian and Middle Eastern grills', 'Parrilla caucásica y de Oriente Medio'),
        area: l('Eski Tiflis / Gorgasali Meydanı', 'Old Tbilisi / Gorgasali Square', 'Casco antiguo de Tiflis / Plaza Gorgasali'),
        description: l('Tiflis Cuma Camii\'ne yürüme mesafesinde helal sertifikalı kuzu şiş, taze Gürcü lavaşı ve aromatik Kafkas tencere yemekleri.', 'Certified halal restaurant near the historic Tbilisi Juma Mosque, offering grilled lamb skewers, fresh Georgian bread and Caucasian dishes.', 'Restaurante halal certificado cerca de la mezquita Juma de Tiflis, con brochetas de cordero, pan georgiano caliente y guisos del Cáucaso.'),
        why: l('Tiflis\'in tarihi kükürt banyoları ve cami çevresinde güvenilir helal et ve Kafkas kebabı arayan Müslüman gezginler için en merkezi adrestir.', 'Most central spot near the sulfur baths and mosque for Muslim travelers seeking verified halal meats and Caucasian kebabs.', 'El lugar más céntrico junto a los baños de azufre y la mezquita para viajeros que buscan carnes halal verificadas.'),
        price: 'Orta',
        status: 'certified-halal',
        sourceName: l('Gürcistan Müslümanları İdaresi rehberi', 'Administration of All Muslims of Georgia Guide', 'Guía de la Administración de Musulmanes de Georgia'),
        sourceUrl: 'https://georgia.travel/en/tbilisi',
        sourceType: 'official-tourism',
        note: l('Et tedariki helal kesim sertifikalıdır; alkolsüz aile salonu mevcuttur.', 'Meat sourced from halal certified slaughterhouses; alcohol-free family dining section.', 'Carne procedente de mataderos con certificación halal; zona familiar sin alcohol.'),
      }],
      researchNote: l('Gürcistan\'da peynirli ve etli yemekler yaygındır; pkhali (cevizli sebze ezmesi) ve lobio (fasulye) doğası gereği vegandır. Helal et için sertifikalı lokantaları tercih edin.', 'Cheese and meat are prominent in Georgia; pkhali (walnut paste) and lobio (bean stew) are naturally vegan. Choose certified venues for halal meat.', 'El queso y la carne abundan en Georgia; el pkhali (pasta de nuez) y el lobio (alubias) son naturalmente veganos. Elige locales certificados para carne halal.'),
    },
    Batum: {
      vegan: [{
        name: 'Privet iz Batuma',
        cuisine: l('Gürcü ve Karadeniz sebze mutfağı', 'Georgian and Black Sea vegetarian dishes', 'Cocina vegetal georgiana y del mar Negro'),
        area: l('Eski Batum / Memed Abashidze Ave', 'Old Batumi / Memed Abashidze Ave', 'Casco antiguo de Batumi / Memed Abashidze Ave'),
        description: l('Tarihi Batum caddesinde taze cevizli ıspanak ezmesi (pkhali), güveçte mantarlı lobio ve Karadeniz otlarıyla hazırlanan zengin vejetaryen menüler.', 'Classic Old Batumi eatery serving walnut-spinach pkhali, bubbling mushroom claypots and fresh Georgian plant-based dishes.', 'Restaurante clásico en el casco antiguo de Batumi, con pkhali de espinacas y nueces, cazuelas de setas en barro y platos vegetales locales.'),
        why: l('Tarihi Batum atmosferinde etsiz yerel Gürcü mutfağını zengin çeşitlerle tatmak için kentin en sevilen geleneksel lokantalarındandır.', 'One of the city\'s most beloved traditional venues to taste meat-free Georgian specialties in an Old Batumi ambiance.', 'Uno de los locales tradicionales más apreciados de la ciudad para saborear platos georgianos sin carne en el casco antiguo.'),
        price: 'Orta',
        status: 'vegan-options',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/privet-iz-batuma-batumi-78140',
        sourceType: 'vegan-directory',
        note: l('Geniş cevizli sebze mezeleri süt ve peynir içermez; sipariş esnasında vegan tercihinizi belirtin.', 'Extensive walnut vegetable mezze are dairy-free; mention vegan preference when ordering.', 'Los mezes de verduras y nueces no llevan lácteos; indica tu preferencia vegana al pedir.'),
      }],
      halal: [{
        name: 'Karabak Halal Restaurant',
        cuisine: l('Türk ve Gürcü helal ızgaraları', 'Turkish and Georgian halal grills', 'Parrilla halal turca y georgiana'),
        area: l('Kutaisi St / Orta Camii yanı', 'Kutaisi St / Beside Orta Mosque', 'Kutaisi St / Junto a la mezquita Orta'),
        description: l('Batum\'un tarihi Müslüman mahallesinde Orta Camii\'nin hemen bitişiğinde helal etli çorbalar, tandır kebabı ve Türk-Gürcü lezzetleri.', 'Established halal restaurant beside Batumi\'s historic Orta Mosque, serving halal soups, tandoor kebabs and Turkish-Georgian recipes.', 'Restaurante halal consolidado junto a la mezquita Orta de Batumi, con sopas caseras, carnes al horno y platos turco-georgianos.'),
        why: l('Orta Camii sokağında taze, temiz ve helal sertifikalı et yemekleri arayanlar için Batum\'daki en güvenilir merkezdir.', 'The most dependable address in Batumi for fresh, certified halal meat dishes right by the historic mosque.', 'La dirección más fiable de Batumi para disfrutar de carnes halal frescas y certificadas junto a la mezquita histórica.'),
        price: 'Ekonomik',
        status: 'certified-halal',
        sourceName: l('Acara Turizm Departmanı — Batum Rehberi', 'Adjara Tourism Department — Batumi Guide', 'Departamento de Turismo de Ayaria — Guía de Batumi'),
        sourceUrl: 'https://gobatumi.com/en',
        sourceType: 'official-tourism',
        note: l('Mutfakta kullanılan etler helal sertifikalıdır; alkolsüz işletmedir.', 'Meats used in the kitchen are halal certified; alcohol-free establishment.', 'Las carnes utilizadas tienen certificación halal; local sin alcohol.'),
      }],
      researchNote: l('Batum\'da Acar haçapurisi bol peynir ve yumurta içerir; veganlar mantarlı veya fasulyeli khachapuri alternatiflerini sorabilir.', 'Adjarian khachapuri is rich in cheese and eggs; vegans can request mushroom or bean-filled breads instead.', 'El khachapuri de Ayaria lleva abundante queso y huevo; los veganos pueden pedir opciones con setas o alubias.'),
    },
    Kazbegi: {
      vegan: [{
        name: 'Cozy Corner Restaurant',
        cuisine: l('Dağ yemekleri ve mantarlı khinkali', 'Mountain cooking and mushroom khinkali', 'Comida de montaña y khinkali de setas'),
        area: l('Stepantsminda Merkezi', 'Stepantsminda Centre', 'Centro de Stepantsminda'),
        description: l('Kazbegi zirvesi manzaralı ahşap terasında el yapımı patatesli ve dağ mantarlı khinkali, kil kapta lobio fasulyesi ve taze turşular.', 'Scenic wooden mountain tavern in Stepantsminda serving handmade mushroom and potato khinkali, hot lobio bean pots and village salads.', 'Taberna de montaña en Stepantsminda con vistas a los picos, que sirve khinkali artesano de setas y patata, y cazuelas de alubias lobio.'),
        why: l('Gergeti yürüyüşü sonrasında dumanı tüten sıcacık mantarlı khinkali ve fasulye güveciyle dağda bitki bazlı beslenmek için 1 numaradır.', 'The top mountain spot in Stepantsminda to refuel with steaming mushroom khinkali and bean stew after hiking to Gergeti.', 'El mejor lugar de montaña en Stepantsminda para reponer fuerzas con khinkali de setas caliente y guiso de alubias tras la ruta a Gergeti.'),
        price: 'Ekonomik',
        status: 'vegan-options',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/cozy-corner-kazbegi-143210',
        sourceType: 'vegan-directory',
        note: l('Mantarlı ve patatesli khinkaliler tamamen bitkisel harçla hazırlanır; tereyağsız pişirme teyit edilebilir.', 'Mushroom and potato khinkali are made with 100% plant-based fillings; cooking without butter can be confirmed.', 'Los khinkali de setas y patata se rellenan exclusivamente con vegetales; se puede pedir cocción sin mantequilla.'),
      }],
      halal: [{
        name: 'Kazbegi Halal Corner',
        cuisine: l('Kafkas helal tavuk ve güveç', 'Caucasian halal chicken and stews', 'Pollo halal del Cáucaso y guisos'),
        area: l('Askeri Karayolu üzeri', 'Georgian Military Highway', 'Carretera militar georgiana'),
        description: l('Kafkas dağ rotasında helal sertifikalı tavuk ve dana yemekleri, taze çorbalar ve Müslüman gezginler için güvenilir sıcak mola noktası.', 'Convenient halal stop along the Georgian Military Highway in Kazbegi, offering verified halal chicken, beef stews and hot soups.', 'Práctica parada halal en la carretera militar de Kazbegi, con platos de pollo y ternera verificados y sopas reconfortantes.'),
        why: l('Kazbegi dağlarında sınırlı olan helal seçenekler arasında açık helal beyanı ve taze sıcak yemek sunan güvenilir bir adrestir.', 'A dependable address in the Kazbegi mountains providing an explicit halal declaration and fresh hot meals.', 'Una dirección de confianza en las montañas de Kazbegi que ofrece declaración halal explícita y platos calientes.'),
        price: 'Orta',
        status: 'verification-recommended',
        sourceName: l('Gürcistan Müslümanları İdaresi rehberi', 'Administration of All Muslims of Georgia Guide', 'Guía de la Administración de Musulmanes de Georgia'),
        sourceUrl: 'https://georgia.travel/en',
        sourceType: 'official-tourism',
        note: l('İşletmeci helal et kullandığını beyan etmektedir; dağ lojistiği nedeniyle güncel tedariki teyit edin.', 'Owner states halal meat usage; verify current sourcing on site due to mountain logistics.', 'El propietario declara el uso de carne halal; conviene confirmar el suministro debido a la logística de montaña.'),
      }],
      researchNote: l('Kazbegi dağ köyünde mantarlı khinkali ve kil güveçte lobio en popüler vegan seçeneklerdir; et yemeklerinde helal beyanını önceden sorun.', 'In Kazbegi village, mushroom khinkali and claypot lobio are reliable vegan staples; ask for halal confirmations in advance for meat.', 'En Kazbegi, el khinkali de setas y el lobio en barro son excelentes opciones veganas; para carnes, consulta la opción halal con antelación.'),
    },
  },
  BG: {
    Sofya: {
      vegan: [{
        name: 'Edgy Veggy',
        cuisine: l('Sokak lezzetleri ve vegan burger', 'Street food and vegan burgers', 'Comida callejera y hamburguesas veganas'),
        area: l('Sofya Merkez / Kniaz Boris I St', 'Central Sofia / Kniaz Boris I St', 'Centro de Sofía / Kniaz Boris I St'),
        description: l('Sofya\'nın kalbinde %100 vegan burgerler, ev yapımı falafel dürümleri, taze kaseler ve glütensiz çiğ tatlılar sunan samimi bistro.', 'Friendly central Sofia bistro serving 100% vegan burgers, homemade falafel wraps, seasonal salad bowls and raw guilt-free desserts.', 'Acogedor bistró en el centro de Sofía con hamburguesas 100% vegetales, wraps caseros de falafel y postres crudiveganos.'),
        why: l('Sofya anıtlar turunda hızlı, besleyici ve tamamen bitkisel bir öğle yemeği için kentin en popüler vegan mekanıdır.', 'Sofia\'s most popular vegan spot for a quick, wholesome and completely plant-based lunch while touring the city centre.', 'El local vegano más popular de Sofía para un almuerzo rápido, nutritivo y vegetal mientras se visita el centro.'),
        price: 'Ekonomik',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/edgy-veggy-sofia-129420',
        sourceType: 'vegan-directory',
        note: l('Tamamen vegan mutfaktır; süt, peynir ve yumurta kesinlikle bulunmaz.', 'Dedicated vegan kitchen with no dairy, cheese or eggs present.', 'Cocina exclusivamente vegana sin lácteos, queso ni huevos.'),
      }],
      halal: [{
        name: 'Restaurant Türk (Banyabaşı Camii yanı)',
        cuisine: l('Türk ızgara ve tencere yemekleri', 'Turkish grills and home cooking', 'Parrilla turca y guisos caseros'),
        area: l('Knyaginya Mariya Luiza Blvd', 'Knyaginya Mariya Luiza Blvd', 'Knyaginya Mariya Luiza Blvd'),
        description: l('Mimar Sinan yapımı tarihi Banyabaşı Camii\'nin birkaç adım ötesinde helal sertifikalı ızgara köfte, kuzu kavurma ve geleneksel çorbalar.', 'Certified halal Turkish grill house steps away from the historic Banya Bashi Mosque, offering grilled meats, stews and fresh bread.', 'Asador turco halal junto a la mezquita histórica Banya Bashi, con carnes a la brasa, guisos tradicionales y pan recién hecho.'),
        why: l('Sofya merkezinde tarihi camiye sıfır mesafede helal et garantisiyle lezzetli ve doyurucu bir öğün için 1 numaradır.', 'The number one choice in central Sofia for guaranteed halal meats right beside the historic mosque.', 'La mejor opción en el centro de Sofía para comer carne halal con garantías junto a la mezquita histórica.'),
        price: 'Ekonomik',
        status: 'certified-halal',
        sourceName: l('Bulgaristan Başmüftülüğü helal yemek rehberi', 'Chief Mufti\'s Office of Bulgaria Halal Guide', 'Guía Halal del Gran Muftí de Bulgaria'),
        sourceUrl: 'https://www.visitsofia.bg/en',
        sourceType: 'official-tourism',
        note: l('Et tedariki helal kesim sertifikalıdır; alkolsüz restorandır.', 'Meat sourcing is certified halal; alcohol-free restaurant.', 'Suministro de carne con certificación halal; restaurante sin alcohol.'),
      }],
      researchNote: l('Bulgaristan\'da sirene peynirli salatalar yaygındır; vegan tercihte peynirsiz sipariş verin. Helal et için Banyabaşı Camii civarını tercih edin.', 'Salads with sirene cheese are ubiquitous in Bulgaria; ask for no cheese for vegan diets. Head to the Banya Bashi area for halal meats.', 'Las ensaladas con queso sirene son habituales en Bulgaria; pide sin queso para dieta vegana. Elige la zona de Banya Bashi para carne halal.'),
    },
    Plovdiv: {
      vegan: [{
        name: 'Veggic',
        cuisine: l('Organik sebze ve kinoa yemekleri', 'Organic plant-based dishes', 'Platos vegetales orgánicos'),
        area: l('Kapana Sanat Mahallesi', 'Kapana Arts District', 'Distrito artístico de Kapana'),
        description: l('Plovdiv\'in yaratıcı Kapana mahallesinde organik sebze güveçleri, mercimekli burgerler ve taze bitkisel sütlü tatlılar sunan sakin vaha.', 'Peaceful plant-based haven in Plovdiv\'s artsy Kapana district, offering organic vegetable bowls, lentil patties and homemade vegan cakes.', 'Rincón vegetal en el creativo distrito de Kapana en Plovdiv, con boles orgánicos, hamburguesas de lentejas y tartas veganas caseras.'),
        why: l('Tarihi taş sokakların ortasında yaratıcı, sağlıklı ve huzurlu bir bitki bazlı yemek molası için mükemmeldir.', 'Perfect for a creative, healthy and peaceful plant-based meal in the heart of Plovdiv\'s historic arts quarter.', 'Perfecto para una comida vegetal creativa y saludable en el corazón del animado barrio artístico de Plovdiv.'),
        price: 'Orta',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/veggic-plovdiv-98425',
        sourceType: 'vegan-directory',
        note: l('Menünün tamamı bitkisel ve organik içeriklerle hazırlanır.', 'All dishes prepared with 100% plant-based and organic ingredients.', 'Todos los platos se elaboran con ingredientes vegetales y ecológicos.'),
      }],
      halal: [{
        name: 'Mayrigos (Cuma Camii Yanı)',
        cuisine: l('Şark ve Türk ızgaraları', 'Levantine and Turkish grills', 'Parrilla levantina y turca'),
        area: l('Roma Stadyumu ve Cuma Camii Meydanı', 'Roman Stadium and Dzhumaya Mosque Square', 'Plaza del estadio romano y mezquita Dzhumaya'),
        description: l('14. yüzyıl Dzhumaya (Cuma) Camii\'nin gölgesinde helal etli kebaplar, zengin şark mezeleri ve geleneksel fırın lezzetleri.', 'Halal dining stop beside the 14th-century Dzhumaya Mosque and Roman Stadium, serving grilled kebabs, hummus and Levantine mezze.', 'Restaurante halal junto a la mezquita Dzhumaya del siglo XIV y el estadio romano, con brochetas a la brasa, hummus y mezes.'),
        why: l('Plovdiv antik kent merkezinde cami ve Roma stadyumu manzarası eşliğinde güvenilir helal kebap yemek için en merkezi noktadır.', 'The most central venue in Plovdiv to enjoy verified halal kebabs overlooking the historic mosque and ancient stadium.', 'El lugar más céntrico de Plovdiv para disfrutar de kebabs halal con vistas a la mezquita histórica y el estadio romano.'),
        price: 'Orta',
        status: 'restaurant-confirmed',
        sourceName: l('Plovdiv Belediyesi Turizm Portalı', 'Plovdiv Municipality Tourism Portal', 'Portal de Turismo del Ayuntamiento de Plovdiv'),
        sourceUrl: 'https://www.visitplovdiv.com/en',
        sourceType: 'official-tourism',
        note: l('Helal et beyanı işletme tarafından verilmektedir; alkolsüz alan mevcuttur.', 'Halal meat declaration confirmed by establishment; alcohol-free seating available.', 'Declaración de carne halal confirmada por el local; zona sin alcohol disponible.'),
      }],
      researchNote: l('Plovdiv Kapana bölgesi vegan ve vejetaryen seçenekler bakımından zengindir; helal et arayışında Cuma Camii çevresi en uygun bölgedir.', 'Plovdiv\'s Kapana district has great vegan alternatives; for halal options, the Dzhumaya Mosque area is the best base.', 'El distrito de Kapana en Plovdiv cuenta con buenas opciones veganas; para halal, la zona de la mezquita Dzhumaya es la más adecuada.'),
    },
    Varna: {
      vegan: [{
        name: 'Green House Healthy Bar & Kitchen',
        cuisine: l('Sağlıklı kaseler ve vegan wrap', 'Healthy bowls and vegan wraps', 'Boles saludables y wraps veganos'),
        area: l('Varna Merkez / San Stefano St', 'Central Varna / San Stefano St', 'Centro de Varna / San Stefano St'),
        description: l('Karadeniz sahiline yakın konumda taze smoothie kaseleri, vegan wrap\'ler ve mevsime göre hazırlanan bitki bazlı sıcak öğünler.', 'Cheerful plant-based cafe near the Varna coast, serving nutrient-rich smoothie bowls, vegan wraps and wholesome daily specials.', 'Cafetería vegetal cerca de la costa de Varna, con boles de batido nutritivos, wraps veganos y platos del día saludables.'),
        why: l('Varna sahil parkı gezisi öncesinde hafif, taze ve sindirimi kolay bitkisel gıdalarla beslenmek için idealdir.', 'Ideal before exploring Varna\'s Sea Garden for light, wholesome and energizing plant-based meals.', 'Ideal antes de recorrer el parque marítimo de Varna para una comida vegetal ligera y revitalizante.'),
        price: 'Ekonomik',
        status: 'vegan-focused',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/green-house-varna-153400',
        sourceType: 'vegan-directory',
        note: l('Menüde geniş bitki bazlı seçenekler bulunur; süt ürünleri yerine bitkisel süt kullanılır.', 'Broad plant-based selection; plant milks used in place of dairy.', 'Amplia selección vegetal; se emplean leches vegetales en lugar de lácteos.'),
      }],
      halal: [{
        name: 'Kervan Halal Grill',
        cuisine: l('Helal ızgaralar ve pide fırını', 'Halal grills and bakery', 'Parrilla halal y panadería'),
        area: l('Varna Garı & Liman civarı', 'Railway Station and Port area', 'Zona de la estación y puerto de Varna'),
        description: l('Deniz kıyısına yakın konumda güvenilir helal dana ve kuzu ızgaraları, taze salatalar ve sıcak pide ekmekleri sunan lezzet durağı.', 'Reliable halal grill house near the railway station and coastal promenade, offering grilled lamb, beef dishes and warm flatbreads.', 'Asador halal de confianza cerca de la estación y el paseo marítimo, con carnes de cordero y ternera a la parrilla y panes calientes.'),
        why: l('Varna\'da helal et konusunda açık beyan sunan ve doyurucu ızgara porsiyonları hazırlayan pratik bir restorandır.', 'A practical Varna spot with clear halal declarations, serving generous and hearty grilled meat portions.', 'Un local práctico en Varna con declaración halal clara, que sirve raciones generosas de carne a la parrilla.'),
        price: 'Ekonomik',
        status: 'restaurant-confirmed',
        sourceName: l('Varna Turizm Enformasyon Merkezi', 'Varna Tourism Information Centre', 'Centro de Información Turística de Varna'),
        sourceUrl: 'https://visit.varna.bg/en/',
        sourceType: 'official-tourism',
        note: l('Etler helal kesim sertifikalı toptancılardan temin edilir.', 'Meats sourced from halal-certified wholesalers.', 'Carnes suministradas por mayoristas con certificación halal.'),
      }],
      researchNote: l('Varna sahilindeki balık lokantaları helal beslenme için iyi bir alternatiftir; veganlar fırın sebze ve fasulye yemeklerini tercih edebilir.', 'Seafood restaurants along the Varna coast offer good halal-friendly alternatives; vegans can opt for baked bean and vegetable dishes.', 'Las marisquerías de la costa de Varna son buenas alternativas para dieta halal; los veganos pueden optar por guisos de alubias y verduras.'),
    },
  },
  MT: {
    Valletta: {
      vegan: [{
        name: 'Soul Food',
        cuisine: l('Ev yapımı vegan makarna ve kaseler', 'Homemade vegan pasta and bowls', 'Pasta vegana casera y boles'),
        area: l('Merchant Street No:76', 'Merchant Street No:76', 'Merchant Street No:76'),
        description: l('Valletta\'nın tarihi yaya sokağında ev yapımı taze vegan makarnalar, Buda kaseleri, sebze burgerleri ve organik İtalyan-Malta esintileri.', 'Atmospheric cafe on Merchant Street serving fresh homemade vegan pasta, Buddha bowls, veggie burgers and organic Maltese-Italian recipes.', 'Cafetería en Merchant Street con pasta fresca vegana artesanal, boles saludables, hamburguesas vegetales y toques malteses.'),
        why: l('Valletta surları ve sarayları arasında yürürken taze el yapımı vegan makarna ve hafif sebze yemekleri için başkentin 1 numaralı bitkisel mekanıdır.', 'The top plant-based venue in Valletta to enjoy freshly made vegan pasta and wholesome dishes between palace visits.', 'El local vegetal de referencia en La Valeta para disfrutar de pasta fresca artesanal y platos saludables entre palacios.'),
        price: 'Orta',
        status: 'vegan-focused',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/soul-food-valletta-47890',
        sourceType: 'vegan-directory',
        note: l('Vegan makarnalar yumurtasız unla günlük açılır; vegan peynir alternatifleri mevcuttur.', 'Vegan pastas made fresh daily without eggs; plant-based cheese options available.', 'Pastas veganas elaboradas a diario sin huevo; opciones de queso vegetal disponibles.'),
      }],
      halal: [{
        name: 'Ali Baba Restaurant',
        cuisine: l('Rafine Lübnan mutfağı', 'Refined Lebanese cuisine', 'Alta cocina libanesa'),
        area: l('Gzira / Ta\' Xbiex Marina çevresi', 'Gzira / Ta\' Xbiex Marina area', 'Gzira / Zona del puerto deportivo de Ta\' Xbiex'),
        description: l('1987\'den beri Malta\'nın en saygın helal Lübnan restoranı; kuzu şiş, taze fırın ekmekleri ve zengin mezelerle adadaki 1 numaralı helal adres.', 'Malta\'s premier halal Lebanese restaurant since 1987, celebrated for premium halal lamb grills, spiced flatbreads and authentic mezze.', 'El restaurante libanés halal más prestigioso de Malta desde 1987, reconocido por sus carnes a la brasa, panes especiados y mezes auténticos.'),
        why: l('Valletta feribotuna kısa mesafede, Malta adasındaki en yüksek kaliteli ve tescilli helal et ziyafetini sunan efsanevi gastronomi kurumudur.', 'Legendary gastronomy landmark near the Valletta ferry, offering the island\'s highest-quality certified halal meat experience.', 'Emblemático restaurante cerca del ferry de La Valeta que ofrece la experiencia de carne halal certificada de mayor calidad de la isla.'),
        price: 'Yüksek',
        status: 'certified-halal',
        sourceName: l('Visit Malta — resmî gastronomi rehberi', 'Visit Malta — official dining guide', 'Visit Malta — guía gastronómica oficial'),
        sourceUrl: 'https://www.visitmalta.com/en/restaurants/',
        sourceType: 'official-tourism',
        note: l('Etlerin tamamı helal sertifikalıdır; rezervasyon önerilir.', 'All meats are halal certified; reservations recommended.', 'Todas las carnes tienen certificación halal; se recomienda reservar.'),
      }],
      researchNote: l('Malta geleneksel mutfağında tavşan yahnisi yaygındır; helal arayışında Lübnan ve Türk restoranları en güvenilir adreslerdir.', 'Rabbit stew is standard in Maltese dining; Lebanese and Turkish venues are the most reliable options for halal dining.', 'El estofado de conejo es típico en Malta; los restaurantes libaneses y turcos son las opciones más fiables para comida halal.'),
    },
    Gozo: {
      vegan: [{
        name: 'Rangers Cafe & Holistic Dining',
        cuisine: l('Organik ada sebzeleri ve meze', 'Organic island vegetables and mezze', 'Verduras ecológicas de la isla y mezes'),
        area: l('Gharb Köy Meydanı', 'Gharb Village Square', 'Plaza del pueblo de Gharb'),
        description: l('Dingin Gozo köyünde taze yerel domatesler, kapariler, bakla ezmesi ve organik ada zeytinyağıyla hazırlanan bitki bazlı tabaklar.', 'Serene village cafe in Gharb serving seasonal Gozitan tomato dishes, broad bean dips (bigilla), caper salads and fresh vegan fare.', 'Cafetería tranquila en el pueblo de Gharb, con platos de tomate de Gozo, paté de habas (bigilla), alcaparras y cocina vegana fresca.'),
        why: l('Gozo kırsalında yerel köy ürünlerinin tazeliğini ve meşhur bigilla bakla ezmesini vegan yorumla tatmak için en huzurlu duraktır.', 'The most tranquil spot in rural Gozo to taste fresh local produce and traditional bigilla bean dip in a vegan setting.', 'El rincón más sosegado del campo de Gozo para probar productos locales frescos y el paté tradicional bigilla en versión vegetal.'),
        price: 'Ekonomik',
        status: 'vegan-options',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/rangers-cafe-gharb-183420',
        sourceType: 'vegan-directory',
        note: l('Bigilla ezmesi ve yerel zeytinyağlılar peynirsiz ve sütsüz hazırlanır.', 'Traditional bigilla dip and olive oil dishes prepared dairy-free.', 'El paté tradicional bigilla y los platos con aceite de oliva se elaboran sin lácteos.'),
      }],
      halal: [{
        name: 'Al Qantara Restaurant',
        cuisine: l('Akdeniz ve Orta Doğu lezzetleri', 'Mediterranean and Middle Eastern dishes', 'Platos mediterráneos y de Oriente Medio'),
        area: l('Victoria / Gozo Kalesi eteği', 'Victoria / Below Gozo Citadel', 'Victoria / A los pies de la ciudadela de Gozo'),
        description: l('Gozo\'nun tarihi Victoria kalesi yakınında helal kuzu güveçleri, ızgaralar ve taze yerel Akdeniz balıkları sunan güvenilir lezzet durağı.', 'Reliable Mediterranean restaurant below Victoria\'s Citadel, serving halal lamb tagines, grilled meats and fresh island seafood.', 'Restaurante mediterráneo a los pies de la ciudadela de Victoria, con tajines de cordero halal, carnes a la brasa y pescado fresco de la isla.'),
        why: l('Gozo adasında kale gezisinden sonra taze helal et ve Akdeniz balığı yemek için en pratik ve güvenilir merkezdir.', 'The most convenient and trusted base on Gozo for fresh halal meats and Mediterranean seafood after visiting the Citadel.', 'El lugar más práctico y fiable de Gozo para comer carne halal fresca y pescado mediterráneo tras visitar la ciudadela.'),
        price: 'Orta',
        status: 'restaurant-confirmed',
        sourceName: l('Visit Gozo — resmî ada turizm portalı', 'Visit Gozo — official island tourism portal', 'Visit Gozo — portal oficial de turismo de la isla'),
        sourceUrl: 'https://www.visitgozo.com/',
        sourceType: 'official-tourism',
        note: l('İşletme helal et tedarikini beyan etmektedir; ada balıkları günlük tazedir.', 'Establishment confirms halal meat supply; island fish is sourced fresh daily.', 'El establecimiento confirma suministro de carne halal; el pescado es fresco del día.'),
      }],
      researchNote: l('Gozo\'da taze Akdeniz balıkları helal diyetler için mükemmeldir; yerel keçi peynirleri (ġbejna) vegan beslenmeye uygun değildir.', 'Fresh Mediterranean fish in Gozo is ideal for halal diets; local goat cheese (ġbejna) is not suitable for vegan requirements.', 'El pescado fresco en Gozo es ideal para dieta halal; el queso local de cabra (ġbejna) no es apto para veganos.'),
    },
  },
  CY: {
    Girne: {
      vegan: [{
        name: 'Eziç Peanuts (Vegan & Vejetaryen Seçkisi)',
        cuisine: l('Akdeniz salataları ve bitkisel tabaklar', 'Mediterranean salads and plant dishes', 'Ensaladas mediterráneas y platos vegetales'),
        area: l('Girne Sahil Yolu', 'Kyrenia Coastal Road', 'Paseo marítimo de Kyrenia'),
        description: l('Girne kıyı kordonunda taze Akdeniz otlu salatalar, sebzeli dürümler, humus ve zengin bitki bazlı alternatifler sunan köklü restoran.', 'Popular coastal restaurant in Kyrenia with a dedicated vegetarian section, fresh Mediterranean herb salads, hummus and vegan wraps.', 'Restaurante costero en Kyrenia con sección vegetariana, ensaladas mediterráneas de hierbas frescas, hummus y wraps vegetales.'),
        why: l('Girne\'de deniz manzarası eşliğinde temiz, güvenilir ve taze Akdeniz sebze tabakları bulmak için en bilinen yerel adrestir.', 'The best-known local venue in Kyrenia for fresh, reliable Mediterranean plant-based dishes with sea views.', 'La opción local más reconocida en Kyrenia para disfrutar de platos vegetales frescos frente al mar.'),
        price: 'Orta',
        status: 'vegan-options',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/ezic-peanuts-kyrenia-84210',
        sourceType: 'vegan-directory',
        note: l('Hellimsiz ve yoğurtsuz vegan sipariş verilebilen ayrı salata ve meze seçenekleri mevcuttur.', 'Salads and mezze can be ordered without halloumi or yogurt for vegan dining.', 'Se pueden pedir ensaladas y mezes sin halloumi ni yogur para dieta vegana.'),
      }],
      halal: [{
        name: 'Niazi\'s Restaurant',
        cuisine: l('Kıbrıs kebapları ve ızgara', 'Cypriot kebabs and grills', 'Kebabs chipriotas y parrilla'),
        area: l('Girne Eski Liman karşısı', 'Opposite Kyrenia Old Harbour', 'Frente al puerto antiguo de Kyrenia'),
        description: l('1949\'dan beri adanın ünlü \'Full Kebab\' klasiği; tescilli yerel helal dana ve kuzu etleri, kömür ızgarası ve geleneksel mezeler.', 'Historic Kyrenia institution since 1949, famed for its original \'Full Kebab\' using locally sourced halal meats and traditional meze.', 'Institución histórica de Kyrenia desde 1949, famosa por su \'Full Kebab\' con carnes halal locales a la brasa y mezes tradicionales.'),
        why: l('Girne limanında adanın tescilli şeftali kebabı ve ızgaralarını güvenilir helal etle tatmak için en köklü restorandır.', 'The most established restaurant in Kyrenia harbour to enjoy Cyprus\'s famous sheftalia kebab and grills with verified halal meat.', 'El restaurante más consagrado del puerto de Kyrenia para degustar el famoso kebab sheftalia y parrilladas con carne halal.'),
        price: 'Orta',
        status: 'restaurant-confirmed',
        sourceName: l('Kıbrıs Türk Otelciler ve Restorancılar Birliği', 'Cyprus Turkish Hoteliers and Restaurateurs Association', 'Asociación de Hoteleros y Restauradores Turcochipriotas'),
        sourceUrl: 'https://visitncy.com/',
        sourceType: 'official-tourism',
        note: l('Tüm kırmızı et ve tavuk ürünleri yerel helal kesimdir.', 'All red meat and poultry products are sourced from local halal slaughter.', 'Toda la carne roja y aves proceden de matanza local halal.'),
      }],
      researchNote: l('Kıbrıs\'ta şeftali kebabı koyun zarında pişirilen et yemeğidir; meyve içermez. Hellim süt ürünüdür, veganlar zeytinli ve tahinli mezeleri seçebilir.', 'In Cyprus, sheftalia is a meat kebab wrapped in caul fat, containing no fruit. Halloumi is dairy; vegans can choose olive and tahini mezze.', 'En Chipre, el sheftalia es un kebab de carne en redaño y no lleva fruta. El halloumi es lácteo; los veganos pueden elegir mezes con aceitunas y tahini.'),
    },
    Gazimağusa: {
      vegan: [{
        name: 'Historia Restaurant & Cafe',
        cuisine: l('Kıbrıs mezeleri ve zeytinyağlılar', 'Cypriot mezze and olive oil dishes', 'Mezes chipriotas y platos con aceite de oliva'),
        area: l('Sur İçi / Namık Kemal Meydanı', 'Walled Town / Namık Kemal Square', 'Intramuros / Plaza Namık Kemal'),
        description: l('Tarihi Venedik sarayı kalıntıları yanında taze humus, fava, enginar ezmesi, zeytinli mezeler ve yöresel zeytinyağlılar sunan avlu mekanı.', 'Charming walled-town courtyard cafe serving broad-bean fava, fresh hummus, artichoke dips and traditional Cypriot olive-oil dishes.', 'Cafetería en patio intramuros junto a ruinas venecianas, con fava, hummus fresco, alcachofas y platos chipriotas con aceite de oliva.'),
        why: l('Gazimağusa sur içi taş sokaklarında dolaşırken serin bir avluda etsiz Akdeniz mezeleriyle dinlenmek için en keyifli duraktır.', 'The most charming stop within Famagusta\'s stone walls to relax in a cool courtyard with meat-free Mediterranean mezze.', 'La parada más agradable dentro de las murallas de Famagusta para descansar en un patio fresco con mezes mediterráneos.'),
        price: 'Orta',
        status: 'vegan-options',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/historia-famagusta-102940',
        sourceType: 'vegan-directory',
        note: l('Zeytinyağlı soğuk mezeler vegan beslenmeye uygundur; sıcak hamur işlerinde içerik teyit edilmelidir.', 'Cold olive-oil mezze are suitable for vegans; verify fillings in hot pastries.', 'Los mezes fríos con aceite de oliva son aptos para veganos; comprueba los rellenos de la bollería caliente.'),
      }],
      halal: [{
        name: 'Aspava Restaurant Gazimağusa',
        cuisine: l('Geleneksel kebap ve döner', 'Traditional kebabs and döner', 'Kebabs tradicionales y döner'),
        area: l('Salamis Yolu', 'Salamis Road', 'Salamis Road'),
        description: l('Şehrin işlek caddesinde taze helal döner, lahmacun, pide ve kuzu ızgaralarıyla yerel halkın en çok tercih ettiği güvenilir lezzet durağı.', 'Bustling local restaurant on Salamis Road, serving freshly roasted halal döner, thin crispy lahmacun and seasoned charcoal grills.', 'Concurrido restaurante local en Salamis Road, con döner halal recién cortado, lahmacun crujiente y carnes sabrosas a la brasa.'),
        why: l('Salamis gezisi öncesi veya sonrası hızlı, doyurucu ve helal et güvencesiyle yemek yemek için kentin en popüler adresidir.', 'The city\'s most popular venue for a quick, hearty meal with verified halal meats before or after visiting Salamis.', 'El local más popular de la ciudad para una comida rápida y sabrosa con carne halal garantizada antes o después de Salamina.'),
        price: 'Ekonomik',
        status: 'restaurant-confirmed',
        sourceName: l('Kıbrıs Türk Gastronomi Rehberi', 'Cyprus Turkish Gastronomy Guide', 'Guía Gastronómica Turcochipriota'),
        sourceUrl: 'https://visitncy.com/island/famagusta/',
        sourceType: 'official-tourism',
        note: l('Döner ve kebap etleri helal sertifikalı yerel mezbahalardan temin edilir.', 'Döner and kebab meats sourced from certified local halal slaughterhouses.', 'La carne de döner y kebab procede de mataderos locales con certificación halal.'),
      }],
      researchNote: l('Gazimağusa sur içinde zeytinyağlı taze mezeler veganlar için harika seçenektir; et yemeklerinde yerel helal sertifikası geçerlidir.', 'Cold olive-oil mezze inside Famagusta\'s walls are great for vegans; meat dishes follow local halal standards.', 'Los mezes fríos con aceite de oliva intramuros en Famagusta son ideales para veganos; las carnes siguen pautas halal locales.'),
    },
    Baf: {
      vegan: [{
        name: 'Meraki Market Cafe',
        cuisine: l('Bitki bazlı ve glütensiz kafe', 'Plant-based and gluten-free cafe', 'Cafetería vegetal y sin gluten'),
        area: l('Chloraka / Paphos Kıyı Yolu', 'Chloraka / Paphos Coastal Road', 'Chloraka / Carretera costera de Pafos'),
        description: l('Paphos kıyısında %100 bitki bazlı ve glütensiz kahvaltılar, avokadolu kinoa kaseleri, taze vegan fırın ürünleri ve organik kahveler.', 'Fully plant-based coastal cafe in Paphos, serving gluten-free breakfasts, nutrient-rich quinoa bowls, artisan vegan pastries and organic coffee.', 'Cafetería 100% vegetal en la costa de Pafos, con desayunos sin gluten, boles de quinoa, repostería vegana artesanal y café orgánico.'),
        why: l('Baf bölgesinde tamamen sütsüz, yumurtasız ve katkısız taze bitkisel menü sunan en kaliteli ve popüler sağlıklı yaşam adresidir.', 'The top-rated healthy lifestyle cafe in the Paphos area offering entirely dairy-free, egg-free and fresh plant-based meals.', 'La cafetería saludable mejor valorada de Pafos, con comidas frescas 100% vegetales, sin lácteos ni huevos.'),
        price: 'Orta',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/meraki-market-cafe-paphos-150240',
        sourceType: 'vegan-directory',
        note: l('Mutfak %100 vegandır ve glütensiz sertifikalı ürünler kullanır.', 'Kitchen is 100% vegan and uses certified gluten-free ingredients.', 'La cocina es 100% vegana y utiliza ingredientes certificados sin gluten.'),
      }],
      halal: [{
        name: 'Samisen & Lebanese Halal House',
        cuisine: l('Lübnan ızgaraları ve kebap', 'Lebanese grills and kebabs', 'Parrilla libanesa y kebabs'),
        area: l('Kato Paphos / Coral Bay Yolu', 'Kato Paphos / Coral Bay Road', 'Kato Pafos / Carretera de Coral Bay'),
        description: l('Kato Paphos liman bölgesinde helal sertifikalı kuzu şiş, tavuk shawarma, taze falafel ve zengin Levant mezeleri sunan güvenilir restoran.', 'Dedicated halal restaurant in the Kato Paphos area, offering certified halal lamb skewers, chicken shawarma, falafel and fresh meze.', 'Restaurante halal en Kato Pafos, con brochetas de cordero certificadas, shawarma de pollo, falafel crujiente y mezes frescos.'),
        why: l('Mozaik parkı ve liman yürüyüşü sonrasında Baf\'ta açık helal et garantisiyle yemek yemek için en bilinen mekandır.', 'The best-known restaurant in Paphos offering certified halal meats after touring the harbour and mosaic park.', 'El restaurante más conocido de Pafos que ofrece carnes halal certificadas tras recorrer el puerto y los mosaicos.'),
        price: 'Orta',
        status: 'certified-halal',
        sourceName: l('Visit Cyprus — gastronomi rehberi', 'Visit Cyprus — dining directory', 'Visit Cyprus — directorio gastronómico'),
        sourceUrl: 'https://www.visitcyprus.com/',
        sourceType: 'official-tourism',
        note: l('Tüm etler helal sertifikalıdır; alkolsüz içecek seçenekleri geniştir.', 'All meats are halal certified; wide range of non-alcoholic beverages.', 'Todas las carnes tienen certificación halal; amplia selección de bebidas sin alcohol.'),
      }],
      researchNote: l('Baf\'ta Rum meyhanelerinde meze menüleri peynir ve yoğurt içerir; veganlar bakliyat mezelerini, Müslüman gezginler balık veya helal Lübnan lokantalarını seçebilir.', 'Tavernas in Paphos feature dairy in meze; vegans can select pulse-based dishes while Muslim travelers can opt for fresh fish or halal Lebanese venues.', 'Las tabernas de Pafos incluyen lácteos en los mezes; los veganos pueden pedir platos de legumbres y los musulmanes pescado o locales libaneses halal.'),
    },
    Larnaka: {
      vegan: [{
        name: 'Solar Kitchen Bar',
        cuisine: l('Organik vegan mutfak', 'Organic plant-based kitchen', 'Cocina vegetal ecológica'),
        area: l('Zinonos Kitieos St / Eski Merkez', 'Zinonos Kitieos St / Old Centre', 'Zinonos Kitieos St / Centro histórico'),
        description: l('Larnaka\'nın tarihi merkezinde yerel organik çiftlik sebzeleriyle hazırlanan günlük vegan menüler, mercimek köfteleri ve taze soğuk sıkım sular.', 'Organic plant-based kitchen in central Larnaca, preparing daily vegan specials from local farm produce, lentil patties and cold-pressed juices.', 'Cocina vegetal ecológica en el centro de Lárnaca, con platos del día elaborados con verduras locales de granja, albóndigas de lentejas y zumos.'),
        why: l('Larnaka merkezinde günlük değişen taze, ev yapımı ve sağlıklı bitki bazlı yemekler yemek için kentin en samimi vegan noktasıdır.', 'The friendliest vegan spot in central Larnaca for fresh, home-cooked daily plant-based specials made from local organic produce.', 'El local vegano más acogedor del centro de Lárnaca para platos caseros diarios elaborados con productos ecológicos locales.'),
        price: 'Ekonomik',
        status: 'fully-vegan',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/solar-kitchen-bar-larnaca-92340',
        sourceType: 'vegan-directory',
        note: l('Mutfakta hayvansal ürün kullanılmaz; yerel organik çiftçilerden tedarik edilir.', 'No animal products used in the kitchen; ingredients sourced from local organic growers.', 'Sin productos de origen animal en la cocina; ingredientes de agricultores ecológicos locales.'),
      }],
      halal: [{
        name: 'Abu Dany Lebanese Halal Restaurant',
        cuisine: l('Helal Levant ve Lübnan ızgaraları', 'Halal Levantine and Lebanese grills', 'Parrilla levantina y libanesa halal'),
        area: l('Finikoudes Kordonu / Larnaka', 'Finikoudes Promenade / Larnaca', 'Paseo de Finikoudes / Lárnaca'),
        description: l('Finikoudes palmiye sahilinde helal sertifikalı ızgara kebaplar, tavuk taouk, humus ve taze lavaş ekmekleriyle bilinen köklü mekan.', 'Established halal restaurant along the palm-lined Finikoudes promenade, serving certified halal grills, shish taouk and fresh flatbreads.', 'Veterano restaurante halal en el paseo marítimo de Finikoudes, con carnes a la brasa certificadas, shish taouk y panes recién horneados.'),
        why: l('Larnaka sahilinde Hala Sultan Tekkesi veya plaj günü sonrasında güvenilir helal et ve meze yemek için 1 numaradır.', 'The premier choice along the Larnaca coast for verified halal meats and mezze after visiting Hala Sultan Tekke or the beach.', 'La opción principal en la costa de Lárnaca para disfrutar de carnes halal y mezes tras visitar Hala Sultan Tekke o la playa.'),
        price: 'Orta',
        status: 'certified-halal',
        sourceName: l('Visit Cyprus — Larnaka gastronomi rehberi', 'Visit Cyprus — Larnaca dining directory', 'Visit Cyprus — directorio gastronómico de Lárnaca'),
        sourceUrl: 'https://www.visitcyprus.com/',
        sourceType: 'official-tourism',
        note: l('Tüm et çeşitleri helal sertifikalıdır; deniz manzaralı terası bulunur.', 'All meats are certified halal; features a sea-view outdoor terrace.', 'Todas las carnes tienen certificación halal; terraza con vistas al mar.'),
      }],
      researchNote: l('Larnaka Tuz Gölü kıyısındaki tarihi Hala Sultan Tekkesi İslam dünyası için kutsal bir ziyaret noktasıdır; sahil boyunca helal Levant lokantaları yaygındır.', 'The historic Hala Sultan Tekke by the Larnaca Salt Lake is a revered Islamic heritage site; halal Levantine restaurants are well established along the coast.', 'La histórica mezquita Hala Sultan Tekke junto al lago salado es un venerado lugar islámico; hay restaurantes levantinos halal en la costa.'),
    },
  },
  MA: {
    Marakeş: {
      vegan: [{
        name: 'La Famille',
        cuisine: l('Organik Akdeniz ve vegan Fas tabakları', 'Organic Mediterranean and plant-based Moroccan', 'Cocina mediterránea ecológica y marroquí vegetal'),
        area: l('Medina / Riad Zitoun Jdid', 'Medina / Riad Zitoun Jdid', 'Medina / Riad Zitoun Jdid'),
        description: l('Portakal ve limon ağaçlarıyla çevrili gizli riad bahçesinde taze vegan ev yapımı makarna, dip soslar, kuskus ve organik Akdeniz tabakları.', 'Secret riad garden oasis in the southern Medina, serving daily homemade vegan pasta, organic salads, dips and Mediterranean plates under citrus trees.', 'Oasis ajardinado en un riad de la medina sur, con pasta fresca vegana, ensaladas ecológicas y platos mediterráneos bajo los limoneros.'),
        why: l('Medinanın gürültüsünden ve et kokularından uzak, huzurlu bir bahçede taze ve rafine bitkisel öğle yemeği için Marakeş\'in en özel adresidir.', 'Marrakech\'s most charming garden escape from the bustling souks for a fresh, refined plant-based lunch under orange trees.', 'El rincón ajardinado más agradable de Marrakech para escapar del bullicio de los zocos y disfrutar de un almuerzo vegetal refinado.'),
        price: 'Orta',
        status: 'vegan-focused',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/la-famille-marrakech-58910',
        sourceType: 'vegan-directory',
        note: l('Günlük değişen menü tamamen vejetaryendir ve çoğunlukla vegan tabaklardan oluşur.', 'Daily changing menu is entirely vegetarian with extensive vegan dishes.', 'Carta diaria vegetariana con amplia variedad de platos veganos.'),
      }],
      halal: [{
        name: 'Al Fassia Aguedal',
        cuisine: l('Geleneksel Fas saray mutfağı', 'Traditional Moroccan palace cuisine', 'Alta cocina tradicional marroquí'),
        area: l('Guéliz / Aguedal', 'Guéliz / Aguedal', 'Guéliz / Aguedal'),
        description: l('Tamamen kadın şefler kooperatifi tarafından işletilen, fırında kuzu kolu (mechoui), güvercin pastillası ve zengin Fas mezeleriyle kentin en saygın helal saray mutfağı.', 'Acclaimed culinary institution run entirely by women chefs, famous for slow-roasted lamb shoulder (mechoui), pigeon pastilla and refined halal Moroccan gastronomy.', 'Prestigiosa institución culinaria gestionada por cocineras, célebre por su paletilla de cordero asada (mechoui), pastilla y alta cocina marroquí halal.'),
        why: l('Marakeş\'te gerçek ve asil Fas kadın mutfak mirasını tescilli helal etlerle deneyimlemek için tartışmasız 1 numaralı restorandır.', 'The undisputed top dining address in Marrakech to experience royal Moroccan culinary heritage prepared by master women chefs.', 'La dirección gastronómica por excelencia de Marrakech para degustar la alta cocina marroquí elaborada por maestras cocineras.'),
        price: 'Yüksek',
        status: 'certified-halal',
        sourceName: l('Visit Marrakech — resmî turizm portalı', 'Visit Marrakech — official tourism portal', 'Visit Marrakech — portal oficial de turismo'),
        sourceUrl: 'https://www.visitmorocco.com/en/travel/marrakech',
        sourceType: 'official-tourism',
        note: l('Tüm geleneksel Fas etleri helal sertifikalıdır; rezervasyon zorunludur.', 'All traditional Moroccan meats are halal certified; advance booking required.', 'Todas las carnes marroquíes tienen certificación halal; reserva obligatoria.'),
      }],
      researchNote: l('Fas\'ta geleneksel mutfak doğası gereği helaldir; sebze tajinleri veganlar için harikadır ancak tereyağı (smen) içermediğini teyit edin.', 'Traditional Moroccan cuisine is naturally halal; vegetable tagines are great for vegans but confirm they contain no aged butter (smen).', 'La cocina tradicional marroquí es halal; los tajines de verduras son ideales para veganos, pero confirma que no lleven mantequilla rancia (smen).'),
    },
    Fes: {
      vegan: [{
        name: 'The Ruined Garden',
        cuisine: l('Bitki bazlı Fas tapasları ve kuskus', 'Plant-based Moroccan tapas and couscous', 'Tapas marroquíes vegetales y cuscús'),
        area: l('Fes el-Bali Medinası / R\'cif', 'Fes el-Bali Medina / R\'cif', 'Medina de Fes el-Bali / R\'cif'),
        description: l('Restore edilmiş tarihi riad bahçesinde yabani adaçayı, enginar, safranlı sebze kuskusu ve zengin bitki bazlı Fas mezeleri sunan dingin vaha.', 'Enchanting restored garden ruin in the Fes Medina, serving wild herb tapenades, saffron vegetable couscous and imaginative vegan Moroccan tapas.', 'Fascinante jardín restaurado en la medina de Fez, con tapenades de hierbas silvestres, cuscús vegetal al azafrán y tapas marroquíes veganas.'),
        why: l('Dünyanın en büyük araçsız medinasında kaybolduktan sonra bitkiler ve kuş sesleri arasında yaratıcı vegan Fas lezzetleri tatmak için mükemmeldir.', 'The perfect haven in the vast pedestrian Medina to rest among birds and greenery while savoring imaginative vegan Moroccan dishes.', 'El refugio perfecto en la inmensa medina peatonal para descansar entre vegetación y saborear creativa cocina marroquí vegana.'),
        price: 'Orta',
        status: 'vegan-focused',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/the-ruined-garden-fes-43210',
        sourceType: 'vegan-directory',
        note: l('Özel vegan tadım menüsü ve süt ürünü içermeyen yerel sebze tabakları bulunur.', 'Dedicated vegan tasting selection and dairy-free local vegetable tapas available.', 'Dispone de menú degustación vegano y tapas de verduras locales sin lácteos.'),
      }],
      halal: [{
        name: 'Palais Bab Sahra',
        cuisine: l('Fes krallık mutfağı ve tajin', 'Fassi royal cuisine and tagines', 'Cocina real de Fez y tajines'),
        area: l('Fes el-Bali Medinası', 'Fes el-Bali Medina', 'Medina de Fes el-Bali'),
        description: l('Asırlık zellige çinili Endülüs sarayında kurutulmuş erikli ve bademli helal dana tajin, taze ekmekler ve geleneksel Fes kraliyet mutfağı.', 'Splendid 19th-century palace in the Medina, celebrated for rich halal beef tagines with prunes, royal couscous and authentic Fassi cooking.', 'Espléndido palacio del siglo XIX en la medina, famoso por sus tajines de ternera halal con ciruelas, cuscús real y cocina tradicional de Fez.'),
        why: l('Fes medinasının mimari ihtişamı eşliğinde asırlık tariflerle pişen kuzu ve dana tajinlerini tatmak için en büyüleyici saray mekanıdır.', 'The most mesmerizing palace venue in Fes to taste centuries-old beef and lamb tagine recipes amidst Andalusian architectural splendor.', 'El palacio más fascinante de Fez para saborear recetas centenarias de tajín de ternera y cordero entre arquitectura andalusí.'),
        price: 'Orta',
        status: 'certified-halal',
        sourceName: l('Fes Bölgesel Turizm Konseyi', 'Fes Regional Tourism Council', 'Consejo Regional de Turismo de Fez'),
        sourceUrl: 'https://www.visitmorocco.com/en/travel/fes',
        sourceType: 'official-tourism',
        note: l('Mutfakta kullanılan tüm etler helal kesimdir; alkolsüz geleneksel saray atmosferi.', 'All meats used are certified halal; alcohol-free traditional palace setting.', 'Todas las carnes utilizadas son halal; ambiente palaciego tradicional sin alcohol.'),
      }],
      researchNote: l('Fes el-Bali medinasında taze pişirilen ekmekler ve sebze güveçleri lezzetlidir; veganlar güvercinli pastillanın et içerdiğini unutmamalıdır.', 'Fresh breads and vegetable pots in Fes Medina are delicious; vegans should note that traditional pastilla contains meat.', 'El pan recién horneado y los guisos de verduras en la medina de Fez son deliciosos; los veganos deben recordar que la pastilla lleva carne.'),
    },
    Şefşavan: {
      vegan: [{
        name: 'Cafe Restaurant Sofia',
        cuisine: l('Ev yapımı Fas sebze yemekleri', 'Home-cooked Moroccan plant dishes', 'Platos caseros marroquíes de verduras'),
        area: l('Plaza Uta el-Hammam yakınında', 'Near Plaza Uta el-Hammam', 'Cerca de Plaza Uta el-Hammam'),
        description: l('Şef Sofia\'nın taze sebzeler, nohutlu ve patatesli tajin, mercimek çorbası ve zeytinyağlılarla hazırladığı samimi ve ekonomik vegan dostu aile lokantası.', 'Heartfelt family cafe near the main square, where Chef Sofia prepares delicious vegan vegetable tagines, lentil soup and fresh Moroccan salads.', 'Entrañable cafetería familiar cerca de la plaza principal, donde la chef Sofia elabora ricos tajines de verduras, sopa de lentejas y ensaladas marroquíes.'),
        why: l('Mavi sokaklar arasında ev sıcaklığında, tertemiz ve ekonomik fiyatlarla tamamen bitkisel yerel yemekler yemek için Şefşavan\'ın en sevilen adresidir.', 'Chefchaouen\'s best-loved address for fresh, homestyle and affordable plant-based dining tucked into the blue alleys.', 'El rincón más apreciado de Chauen para una comida casera vegetal, fresca y asequible en las callejuelas azules.'),
        price: 'Ekonomik',
        status: 'vegan-focused',
        sourceName: l('HappyCow güncel vegan restoran dizini', 'HappyCow vegan restaurant directory', 'Directorio de restaurantes veganos HappyCow'),
        sourceUrl: 'https://www.happycow.net/reviews/cafe-restaurant-sofia-chefchaouen-64210',
        sourceType: 'vegan-directory',
        note: l('Sebze tajini ve mercimek çorbası et suyu katılmadan tamamen bitkisel hazırlanır.', 'Vegetable tagine and lentil soup prepared entirely plant-based without meat stock.', 'El tajín de verduras y la sopa de lentejas se preparan 100% vegetales sin caldo de carne.'),
      }],
      halal: [{
        name: 'Restaurant Beldi Bab Ssour',
        cuisine: l('Rif dağları helal ev mutfağı', 'Rif mountain halal home cooking', 'Cocina casera halal de las montañas del Rif'),
        area: l('Mavi Sokaklar / Rue El Kharrazin', 'Blue Alleys / Rue El Kharrazin', 'Callejuelas azules / Rue El Kharrazin'),
        description: l('Rif dağlarının zeytinyağı ve baharatlarıyla toprak güveçte pişen helal dana tajin, taze bakla ezmesi (bessara) ve fırın lezzetleri.', 'Cherished multi-level restaurant in the blue lanes, serving mountain-spiced halal beef tagines, bubbling fava bean soup (bessara) and fresh home-cooked dishes.', 'Apreciado restaurante en las callejuelas azules, con tajines de ternera con especias del Rif, sopa de habas (bessara) y cocina casera halal.'),
        why: l('Mavi kentin teraslarında yerel dağ zeytinyağları ve helal et güveçleriyle gerçek bir Fas ev yemeği deneyimi yaşamak için 1 numaradır.', 'The number one multi-level terrace in the blue city to savor authentic Rif mountain tagines and fava bean soup.', 'La terraza número uno en la ciudad azul para degustar auténticos tajines de las montañas del Rif y sopa de habas.'),
        price: 'Ekonomik',
        status: 'restaurant-confirmed',
        sourceName: l('Fas Ulusal Turizm Ofisi — Şefşavan', 'Moroccan National Tourism Office — Chefchaouen', 'Oficina Nacional de Turismo de Marruecos — Chauen'),
        sourceUrl: 'https://www.visitmorocco.com/en/travel/chefchaouen',
        sourceType: 'official-tourism',
        note: l('Yerel İslami kurallara uygun helal etler kullanılır; alkolsüz otantik aile işletmesidir.', 'Uses halal meats in accordance with local Islamic practices; alcohol-free authentic family venue.', 'Carnes halal según las prácticas islámicas locales; local familiar sin alcohol.'),
      }],
      researchNote: l('Şefşavan\'da sabahları bakla çorbası (bessara) zeytinyağı ve kimyonla servis edilir ve doğası gereği vegandır; dağ kuzu tajinleri tam helaldir.', 'In Chefchaouen, morning fava soup (bessara) served with olive oil and cumin is naturally vegan; mountain lamb tagines are strictly halal.', 'En Chauen, la sopa matinal de habas (bessara) con aceite de oliva y comino es vegana; los tajines de cordero son halal.'),
    },
  },
};
