import {l,section as s,sight as p,source,tourism} from './shared.mjs';
const city = {
 name:l('Can Tho','Can Tho','Can Tho'),key:'can-tho',
 title:l('Can Tho Gezi Rehberi: Mekong, Cai Rang ve 2 Günlük Rota','Can Tho Travel Guide: Cai Rang, River Life and 2 Days','Can Tho: mercado Cai Rang y ruta de 2 días por el Mekong'),
 meta:l('Can Tho gezi rehberi: Cai Rang için erken tekne, Ninh Kieu, Binh Thuy ve delta yaşamı; konaklama, yemekler ve Mekong’da iki günlük sakin bir rota.','Plan Can Tho with an early Cai Rang boat trip, Ninh Kieu and Binh Thuy: where to stay, local meals and two unhurried days in the Mekong Delta.','Organiza Can Tho con barco temprano a Cai Rang, Ninh Kieu y Binh Thuy: alojamiento, comidas locales y dos días tranquilos en el delta del Mekong.'),
 card:l('Cai Rang’ın erken saatlerinden Ninh Kieu akşamlarına; pazarın ötesinde Mekong’da kalmaya değer iki gün.','From early Cai Rang visits to Ninh Kieu evenings: two delta days that extend beyond the floating market.','De Cai Rang temprano a las tardes de Ninh Kieu: dos días en el delta más allá del mercado flotante.'),
 lede:l('Can Tho’ya yalnız sabah fotoğrafı için gelip aynı gün dönmek mümkün, ama biraz eksik kalabilir. Tekne gezisinden sonra karaya çıkıp kahvaltı etmek, öğleden sonra dinlenmek ve akşam kıyıya tekrar dönmek başka bir deneyim. Mekong’u görmekle onun yanında bir gece geçirmek aynı şey değil.','You can come to Can Tho for a morning photograph and leave the same day, but staying changes the experience. Breakfast after the boat, an afternoon rest and an evening back by the water create a different chapter. Seeing the Mekong and spending a night beside it are not quite the same journey.','Puedes venir por una foto matinal y marcharte, pero quedarse cambia la experiencia. Desayunar después del barco, descansar por la tarde y volver al agua al anochecer crean otro viaje. Ver el Mekong y pasar una noche junto a él no son lo mismo.'),
 facts:[l('2 tam gün; erken turdan önce geceleme','2 full days; stay before an early tour','2 días completos; dormir antes de la salida temprana'),l('Aralık–nisan; sıcak ve nehir koşuluna göre','December–April; consider heat and river conditions','Diciembre–abril; según calor y río'),l('Tekne, kısa merkez yürüyüşleri ve araç','Boats, short central walks and vehicles','Barco, paseos cortos y vehículo')],
 sections:[
 s('sehri-anlamak',l('Pazarın öncesindeki gece de geziye ait','The night before the market is part of the trip','La noche anterior también forma parte del viaje'),
 l('İlk akşam Can Tho’ya yerleşip Ninh Kieu çevresinde yemek yemek, ertesi sabahki erken çıkışı kolaylaştırır. Ho Chi Minh City’den gece yarısı yola çıkıp bütün delta deneyimini birkaç saate sıkıştırmak zorunda değilsiniz. Mümkünse varış ile tekne gezisini ayrı günlere koyun; uykusuzluk manzarayı da sohbeti de küçültüyor.','Settling in and dining around Ninh Kieu makes the following early start easier. You need not leave Ho Chi Minh City in the middle of the night and compress the whole delta visit into a few hours. Separate arrival from the boat outing where possible; fatigue reduces room for both scenery and conversation.','Instalarte y cenar por Ninh Kieu facilita la salida temprana. No necesitas partir de Ciudad Ho Chi Minh de madrugada y comprimir todo en unas horas. Separa llegada y barco cuando puedas: el cansancio deja menos espacio para paisaje y conversación.'),
 l('Can Tho yaşayan bir şehir; bütün Mekong Deltası’nın küçük bir maketi değil. Cai Rang’ı gördükten sonra bir ev ziyareti, nehir kıyısı veya seçilmiş bahçe deneyimiyle devam edin. Fotoğraftaki yoğun tekne kalabalığını her gün aynı miktarda bulacağınız garantisi yok; güncel pazar durumunu dürüstçe anlatan bir rehber daha değerlidir.','Can Tho is a living city, not a miniature version of the entire Mekong Delta. Follow Cai Rang with a house visit, riverside time or a selected garden experience. Do not expect the same dense boat scene every day; a guide who honestly explains current market activity is more useful than a guaranteed photograph.','Can Tho es una ciudad viva, no una maqueta de todo el delta. Combina Cai Rang con una casa, la orilla o un huerto elegido. No se garantiza la misma multitud de barcos cada día: un guía honesto sobre la actividad actual aporta más que prometer una foto.')),
 s('ulasim',l('Can Tho’ya varış: otogar ile iskeleyi ayırın','Arriving in Can Tho: terminal and pier are different','Llegar a Can Tho: terminal y embarcadero son distintos'),
 l('Ho Chi Minh City’den kara yoluyla gelirken biletteki bırakma noktasını ve son otel bağlantısını kontrol edin. Can Tho (VCA) uçuşu varsa gerçek tarihinizde seferi doğrulayın; havalimanının olması her şehirden her gün uçuş demek değildir. Uzun yolun ardından ilk akşamı alışma ve dinlenmeye ayırın.','For road travel from Ho Chi Minh City, check the drop-off point and final hotel connection. If flying to Can Tho (VCA), verify the service on your actual dates; an airport does not imply daily flights from every city. Keep the first evening easy after a long journey.','Por carretera desde Ciudad Ho Chi Minh, comprueba bajada y último enlace al hotel. Si vuelas a Can Tho (VCA), verifica tu fecha: tener aeropuerto no significa vuelos diarios desde todas las ciudades. Deja tranquila la primera tarde.'),
 l('Sabah teknesi için “otelinizden alınacaksınız” sözünün araç, yürüyüş veya doğrudan iskele buluşması mı olduğunu sorun. İskele adını, saati ve dönüş noktasını yazılı netleştirin. Güneşten önce kalkmak tek başına iyi bir tur sağlamaz; doğru tekneye ve anlaşılır bir programa geçmek de gerekir.','For morning boats, clarify whether hotel pick-up means a vehicle, a walk or meeting directly at a pier. Confirm the pier, time and return point in writing. Waking before sunrise is only one part of a worthwhile outing; the right boat and a clearly understood programme matter too.','Aclara si la recogida incluye coche, paseo o reunión en el embarcadero. Confirma lugar, hora y regreso por escrito. Madrugar es solo una parte: también importan barco adecuado y programa claro.')),
 s('mahalle-yasami',l('Cai Rang’ı bir gösteri gibi okumayın','Read Cai Rang as a working place','Mira Cai Rang como un lugar de trabajo'),
 l('Cai Rang ticaretin yapıldığı bir pazar; satıcıların sabahını ziyaretçiler için oynanan bir sahne sanmayın. İşlerine yaklaşırken rehberin yönlendirmesini izleyin, fotoğraf için bir teknenin geçişini durdurmaya çalışmayın. Alışveriş veya kahvaltı varsa kimin satış yaptığını ve ödemenin nasıl yapıldığını anlayın.','Cai Rang is a working market, not a scene staged for visitors. Follow your guide when approaching traders and avoid obstructing a boat for a photograph. If the outing includes shopping or breakfast, understand who is selling and how payment works.','Cai Rang es un mercado de trabajo, no una escena montada para turistas. Sigue indicaciones al acercarte y no obstaculices barcos por una foto. Si compras o desayunas, entiende quién vende y cómo se paga.'),
 l('Tekne dönüşünde hemen başka bir tur almak yerine Ninh Kieu çevresine yürüyüp oturun. Sabah erken gördüğünüz suyu akşam kıyıdan yeniden görmek, günün değiştiğini hissettirir. Bir bankta veya masada geçirilen yarım saat de delta gezisine dahildir; her dakikayı hareket ederek doldurmanız gerekmiyor.','After the boat, try a walk and a seated break around Ninh Kieu instead of immediately joining another tour. Returning to the water in the evening lets you notice a different day unfolding around it. Half an hour on a bench or at a table also belongs to a delta visit.','Después del barco, pasea y descansa por Ninh Kieu en vez de contratar otra excursión enseguida. Volver al agua al atardecer deja ver cómo cambia el día. Media hora en un banco o una mesa también es viajar por el delta.')),
 s('konaklama',l('Merkezde mi, bahçe ve nehir çevresinde mi kalmalı?','Central stays or a garden-and-river setting?','¿Centro o estancia entre huertos y río?'),
 l('Ninh Kieu çevresi merkez yemeği ve akşam kıyı yürüyüşü için pratik olabilir. Daha dışarıdaki bahçe veya nehir konaklamaları farklı bir dinlenme fikri sunar; merkeze dönüşü, tekneye alma koşulunu ve gerçek ulaşımını kontrol edin. “Mekong manzarası” tek başına her turun otel kapısından başladığı anlamına gelmez.','Ninh Kieu can be practical for dining and evening waterfront walks. Outlying garden or riverside stays offer a different retreat, but check town access and boat pick-up arrangements. A Mekong-view description does not mean every excursion starts at the accommodation’s door.','Ninh Kieu puede facilitar comidas y paseos nocturnos. Alojamientos exteriores entre huertos o río ofrecen otra calma, pero revisa accesos y recogida del barco. “Vistas al Mekong” no significa que todas las excursiones salgan del hotel.'),
 l('Erken pazar gezisinden önce resepsiyona kahvaltı ve çıkış saatini konuşun. Dönüşte duş ve dinlenme isteyebilirsiniz; hemen check-out gerektiren tek gecelik program yorucu olabilir. İki gece, Can Tho’yu yalnız yatılan bir yerden çıkartıp yavaş bir öğleden sonranın da yaşandığı yere dönüştürür.','Discuss early breakfast and departure with reception. You may want a shower and rest after the boat, which an immediate check-out makes awkward. Two nights can turn Can Tho from merely somewhere to sleep into a place where you also enjoy an unhurried afternoon.','Habla con recepción de desayuno y salida temprana. Tras el barco puede apetecer ducha y descanso; salir enseguida del hotel lo dificulta. Dos noches permiten que Can Tho sea también una tarde sin prisas, no solo una cama.')),
 s('yeme-icme',l('Nehirde kahvaltı, karada uzun bir yemek','Breakfast on the water, an unhurried meal ashore','Desayuno en el agua, comida tranquila en tierra'),
 l('Hu tieu, erişte ve et suyuyla sabahın doyurucu seçeneklerinden; teknede servis ediliyorsa içeriği, fiyatı ve oturma düzenini kontrol edin. Erken kalkmış olmak aç karnına bütün turu geçireceğiniz anlamına gelmemeli. Meyve veya hafif bir atıştırmalığı tekne öncesi hazırlamak da rahat bir başlangıç sağlayabilir.','Hu tieu offers noodles and broth for a substantial breakfast; if served on a boat, clarify ingredients, price and seating. An early departure need not mean staying hungry throughout the outing. Preparing fruit or a light snack beforehand can also make the morning more comfortable.','Hu tieu ofrece fideos y caldo para desayunar; en barco, aclara ingredientes, precio y cómo te sentarás. Madrugar no obliga a pasar hambre toda la excursión. Preparar fruta o un tentempié ligero puede facilitar la mañana.'),
 l('Karada banh xeo veya yerel bir sebze ve meyve molasıyla farklı öğünler kurabilirsiniz. Vegan istekte et suyu, balık sosu ve iç malzemeyi ayrıca sorun; helal uygunluk için işletmenin tedarik bilgisi gerekir. Yerel yemeği tanımak bir “en egzotik ne var?” yarışması değil, alıştığınız tatların dışına kendi rahatlığınızda çıkmak olabilir.','A meal ashore can explore banh xeo or selected vegetables and fruit. Ask about stock, fish sauce and fillings for vegan preferences, and sourcing for halal needs. Knowing local food need not become a contest for the most exotic order; move beyond familiar flavours at a pace that feels comfortable.','En tierra puedes probar banh xeo o elegir verduras y fruta. Para veganismo pregunta por caldo, salsa y relleno; para halal, procedencia. Conocer comida local no es competir por lo más exótico, sino salir de sabores familiares a tu ritmo.')),
 s('mevsim-butce',l('Tekne gününün ayrıntıları: gölge, dönüş ve kapsam','A boat day’s details: shade, return and inclusions','Detalles del barco: sombra, regreso y servicios'),
 l('Güneyin sıcağı ve yağışı planı etkiler; açık su üzerindeki uzun molalarda gölge ve içme suyunu düşünün. Can yeleği, tekneye geçiş ve hava nedeniyle değişiklik koşulları önemlidir. Yağmur varsa operatörle programı yeniden değerlendirin; fotoğraf için güvenlikten taviz vermeyin.','Southern heat and rain affect the day, and exposed time on the water needs shade and drinking water. Check life jackets, boarding arrangements and weather-change conditions. Reassess the programme with the operator when necessary instead of sacrificing safety for the photograph you expected.','Calor y lluvia afectan la jornada; sobre el agua necesitas sombra y agua potable. Comprueba chalecos, embarque y cambios por tiempo. Revisa el programa con el operador cuando haga falta; una foto no justifica comprometer seguridad.'),
 l('Tur ücretini tekne büyüklüğü, rehberlik, kahvaltı, transfer ve ek bahçe ziyaretleriyle birlikte karşılaştırın. Özel ve paylaşımlı tur aynı serbestliği sunmaz. Her durakta alışveriş beklenen bir programa girmek istemiyorsanız önceden sorun; sizin için iyi rota, ihtiyaçlarınızı açıklayabildiğiniz rotadır.','Compare boat size, guiding, breakfast, transfers and any extra garden visits together. Private and shared outings offer different flexibility. Ask beforehand about shopping stops if they are not what you want; the most suitable route is the one whose terms you can understand and shape around your needs.','Compara tamaño de barco, guía, desayuno, traslado y visitas adicionales. Privado y compartido dan flexibilidad distinta. Pregunta por paradas comerciales si no te interesan: una buena ruta permite entender condiciones y explicar tus necesidades.')),
 ],
 sights:[
 p(l('Cai Rang Yüzen Pazarı','Cai Rang Floating Market','Mercado flotante Cai Rang'),l('Nehir pazarı','River market','Mercado fluvial'),l('Ziyaretin erken zamanını ve güncel pazar hareketini yerel operatörle konuşun. Teknelerin satış ve taşıma düzenine saygı gösterin; eski fotoğraflardaki kalabalığı bugünün garantisi sanmayın.','Discuss an early visit and current activity with a local operator. Respect trade and transport on the water rather than treating old crowded photographs as a promise of today’s scene.','Habla de hora temprana y actividad actual con el operador. Respeta comercio y transporte; fotos antiguas de multitudes no garantizan la escena de hoy.'),l('Ticareti su üzerinden görmek.','Observe commerce on the water.','Observar comercio sobre el agua.'),l('Alışveriş ve kahvaltı kapsamını sorun.','Clarify shopping and breakfast arrangements.','Aclara compras y desayuno.')),
 p(l('Ninh Kieu kıyısı','Ninh Kieu waterfront','Orilla de Ninh Kieu'),l('Merkez kıyısı','Central waterfront','Orilla céntrica'),l('Akşam kısa bir kıyı yürüyüşünü yemekle birleştirin. Sabah teknesinin alma iskelesiyle her gezi teknesinin aynı yerden kalktığını varsaymayın; rezervasyonun buluşma noktasını esas alın.','Pair a short evening walk with dinner. Do not assume every boat departs from the same place along the waterfront; rely on the meeting point in your reservation.','Une paseo breve y cena. No todos los barcos salen del mismo lugar de la orilla: guíate por el punto de reunión reservado.'),l('Tekne gününün ardından şehirde kalmak.','Stay with the city after the boat trip.','Quedarse en la ciudad después del barco.'),l('Dönüş bağlantısını baştan öğrenin.','Clarify the return connection beforehand.','Aclara antes el regreso.')),
 p(l('Binh Thuy tarihî evi','Binh Thuy ancestral house','Casa histórica Binh Thuy'),l('Binh Thuy','Binh Thuy','Binh Thuy'),l('Evi cephe fotoğrafından fazlası olarak gezin: odaların düzeni ve aile yaşamının izleri ziyaretin asıl güzel tarafı olabilir. Açık alanlar ve iç mekân erişimini güncel koşullarla kontrol edin.','Look beyond the facade to the arrangement of rooms and traces of family life. Confirm which interiors and outdoor areas are available under current visiting arrangements.','Mira distribución de habitaciones y huellas de vida familiar, además de la fachada. Consulta espacios interiores y exteriores accesibles actualmente.'),l('Delta yaşamını bir ev üzerinden okumak.','Read delta life through a family home.','Leer vida del delta a través de una casa.'),l('Konuttaki ziyaret sınırlarına uyun.','Respect the house’s visitor boundaries.','Respeta límites de visita de la casa.')),
 ],
 itinerary:[{title:l('1. Gün — Şehre yerleşme','Day 1 — Settle into the city','Día 1 — Llegada tranquila'),morning:l('Can Tho’ya ulaşım','Travel to Can Tho','Viaje a Can Tho'),afternoon:l('Binh Thuy ve dinlenme','Binh Thuy and rest','Binh Thuy y descanso'),evening:l('Ninh Kieu çevresinde yemek','Dinner around Ninh Kieu','Cena por Ninh Kieu')},{title:l('2. Gün — Erken tekne ve yavaş dönüş','Day 2 — Early boat, slower return','Día 2 — Barco temprano y regreso tranquilo'),morning:l('Cai Rang tekne gezisi','Cai Rang boat trip','Barco a Cai Rang'),afternoon:l('Dinlenme; isteğe göre bir bahçe ziyareti','Rest; an optional garden visit','Descanso; huerto opcional'),evening:l('Kıyıda son yürüyüş','A final waterfront walk','Último paseo por la orilla')}],
 faqs:[{q:l('Can Tho’da kaç gece kalmalı?','How many nights should you stay in Can Tho?','¿Cuántas noches dormir en Can Tho?'),a:l('Erken tekne turundan önce en az bir gece; dönüşte dinlenme ve şehir için iki gece daha rahat olabilir. Otel çıkışını tekne dönüşüyle birlikte planlayın.','Stay at least the night before an early boat trip; two nights can better allow rest and city time. Coordinate check-out with the boat’s return.','Al menos la noche anterior al barco; dos noches permiten descansar y ver la ciudad. Coordina salida del hotel con regreso del barco.')},{q:l('Cai Rang her gün aynı kalabalıkta mı?','Is Cai Rang equally busy every day?','¿Cai Rang tiene siempre la misma actividad?'),a:l('Hayır; ticaret, ziyaret saati ve koşullar değişebilir. Güncel durum için yerel operatöre danışın; belli sayıda tekne veya fotoğraftaki sahne garantisi aramayın.','No: trading activity, timing and conditions vary. Ask a local operator about the current situation instead of expecting a fixed boat count or guaranteed photographic scene.','No: comercio, hora y condiciones cambian. Consulta situación actual sin esperar un número fijo de barcos o una escena fotográfica garantizada.')}],
 sources:[source(tourism,'https://vietnam.travel/places-to-go/southern-vietnam/can-tho'),source(l('Vietnam Tourism — Can Tho nehri ve bahçeleri','Vietnam Tourism — Can Tho river and gardens','Vietnam Tourism — río y huertos de Can Tho'),'https://www.vietnam.travel/things-to-do/can-tho-glimpse-river-and-garden'),source(l('Vietnam Tourism — Vietnam içi ulaşım','Vietnam Tourism — transport within Vietnam','Vietnam Tourism — transporte por Vietnam'),'https://vietnam.travel/plan-your-trip/transport-within-vietnam')],
};

export default city;
