import {l} from './shared.mjs';
export const country={
 name:l('Vietnam','Vietnam','Vietnam'),code:'VN',flag:'🇻🇳',image:'/images/vietnam-hanoi.avif',coordinates:{lat:21.0285,lng:105.8542},iata:'HAN',gateway:l('Hanoi','Hanoi','Hanói'),capital:l('Hanoi','Hanoi','Hanói'),flightTime:'9sa 30dk+',accent:'#bc6354',budget:'Ekonomik',
 bestSeason:l('Bölgeye göre değişir','Varies by region','Depende de la región'),
 description:l('Göl kıyısında sabah, küçük tabaklarla uzun öğle ve Mekong’da yavaşlayan akşam; Vietnam’ı günlük hayatın içinden keşfedin.','Lakeside mornings, lingering lunches and slower Mekong evenings: discover Vietnam through everyday life.','Mañanas junto al lago, comidas largas y tardes lentas en el Mekong: descubre Vietnam desde la vida cotidiana.'),
 signature:l('Bir kahve molasında yolculuğun hızını değiştirmek','Letting a coffee break change the pace of the journey','Dejar que una pausa con café cambie el ritmo del viaje'),
 title:l('Vietnam Gezi Rehberi: 6 Şehir, Yemekler ve Rota Planı','Vietnam Travel Guide: Six Cities, Food and Route Planning','Vietnam: 6 ciudades, gastronomía y rutas de viaje'),
 meta:l('Vietnam gezi rehberi: Hanoi, Hue, Da Nang, Hoi An, Ho Chi Minh City ve Can Tho; mevsime göre rota, yerel yemekler ve kapsamlı şehir yazıları.','Plan Vietnam through Hanoi, Hue, Da Nang, Hoi An, Ho Chi Minh City and Can Tho: regional weather, local food and detailed city travel guides.','Viaja por Vietnam con guías de Hanói, Hue, Da Nang, Hoi An, Ciudad Ho Chi Minh y Can Tho: rutas, clima regional, platos locales y dónde alojarte.'),
 intro:[
 l('Vietnam’da bir yolculuğu bazen ilk yediğiniz çorba, bazen yağmurdan kaçıp oturduğunuz masa açıyor. Bir yanda Hanoi’nin göl çevresinde kısa yürüyüşler, diğer yanda Hue’de küçük tabaklarla uzayan öğle yemekleri var. Da Nang’da kıyıyla şehir aynı güne sığıyor; Hoi An’da sabah eski sokaklara, akşam nehre dönüyorsunuz. Güneyde Ho Chi Minh City’nin temposunu Can Tho’da bir gece kalarak yavaşlatmak mümkün. Bu rehberin altı durağı aynı Vietnam fotoğrafının tekrarları değil.','A Vietnam journey can open with a first bowl of noodles or a table found while sheltering from rain. Hanoi offers short lakeside walks; Hue lets lunch linger over small dishes. Da Nang brings coast and city into one day, while Hoi An invites a return to the old streets and river at different hours. In the south, an overnight stay in Can Tho can slow the pace after Ho Chi Minh City. These six stops offer different experiences, not six versions of the same photograph.','Un viaje a Vietnam puede empezar con un primer cuenco de fideos o una mesa donde refugiarse de la lluvia. Hanói invita a paseos junto al lago; Hue, a comidas largas de pequeños platos. Da Nang une costa y ciudad, mientras Hoi An cambia entre mañana y noche. Al sur, una estancia en Can Tho baja el ritmo después de Ciudad Ho Chi Minh. Son seis experiencias distintas, no seis versiones de la misma foto.'),
 l('Bu ülkeyi ilk kez gezerken her güzel fotoğrafın bulunduğu yere gitmek zorunda değilsiniz. Haritada kuzeyden güneye tek çizgi görünen rota; havalimanı, otel, tren ve valiz işleriyle gerçek hayatta bölümlere ayrılıyor. Bir şehre ayırdığınız üçüncü sabah bazen yeni bir uçuş gününden daha değerli. Bu yüzden önce neyi sevdiğinizi seçin: sokakta zaman geçirmek, tarih okumak, denize girmek veya uzun sofralar. Sonra şehir sayısını buna göre belirleyin.','A first visit does not need to include every place with an appealing photograph. The neat north-to-south line on a map breaks into airports, hotels, trains and luggage in practice. A third morning in one city may be worth more than another flight day. Start with what you enjoy: neighbourhood time, historical visits, the coast or long meals. Choose the number of stops afterwards, allowing the journey to grow from your interests rather than a checklist.','No hace falta visitar cada lugar que aparece en una foto bonita. La línea de norte a sur se divide en aeropuertos, hoteles, trenes y maletas. Una tercera mañana en una ciudad puede valer más que otro día de vuelo. Decide primero qué disfrutas: barrios, historia, mar o mesas largas. El número de paradas viene después.'),
 l('Hanoi ile Ho Chi Minh City’yi iki büyük giriş kapısı; Hue, Da Nang ve Hoi An’ı birlikte düşünülebilen ama ayrı geceleme ihtiyaçları olan orta bölüm; Can Tho’yu ise delta için bağımsız bir devam olarak okuyun. Kısa tatilde üçünü birden bağlamak yerine bir veya iki bölge seçmek daha rahat olabilir. Kuzeyde güneşli bir gün, orta kıyıda aynı hava demek değil; bütün ülke için tek bir “en iyi ay” aramak planı gereğinden fazla basitleştirir.','Treat Hanoi and Ho Chi Minh City as major gateways, Hue–Da Nang–Hoi An as a central chapter with distinct overnight needs, and Can Tho as a separate delta continuation. For a shorter holiday, one or two regions may work better than all three. Sunshine in the north says little about the central coast that day; looking for one universally best month oversimplifies a long country with regional weather differences.','Piensa en Hanói y Ciudad Ho Chi Minh como entradas principales; Hue, Da Nang y Hoi An como un capítulo central con estancias diferentes; y Can Tho como continuación propia del delta. En viajes breves elige una o dos regiones. El sol del norte no describe la costa central: buscar un único mes perfecto simplifica demasiado.'),
 ],
 planning:l('Vietnam rotası: daha az valiz, daha çok şehir zamanı','Build a Vietnam route with fewer moves and more city time','Rutas con menos maletas y más tiempo en cada ciudad'),
 essentialsHeading:l('Gitmeden önce: giriş, ödeme ve günlük bağlantılar','Before travelling: entry, payments and everyday connections','Antes de viajar: entrada, pagos y conexiones'),
 citiesHeading:l('Vietnam’da gezilecek 6 şehir','Six Vietnamese cities to explore','Seis ciudades de Vietnam para descubrir'),
 grid:l('Hanoi’de göl ve mahalle, Hue’de tarih ve sofra, Da Nang’da şehir ve deniz, Hoi An’da eski liman sokakları, Ho Chi Minh City’de güneyin gündeliği, Can Tho’da delta gecesi. Rehberleri sevdiğiniz gezi biçimine göre bir araya getirin.','Choose lakes and neighbourhoods in Hanoi, history and food in Hue, city and sea in Da Nang, old port streets in Hoi An, southern urban life in Ho Chi Minh City and an overnight delta chapter in Can Tho. Combine the guides around how you like to travel.','Lagos y barrios en Hanói, historia y mesa en Hue, ciudad y mar en Da Nang, calles de puerto en Hoi An, vida urbana sureña y una noche en el delta. Combina guías según tu forma de viajar.'),
 essentials:[
 [l('Pasaport ve giriş koşulları','Passport and entry requirements','Pasaporte y requisitos de entrada'),l('Giriş koşulları pasaport, kalış süresi ve kullanılan sınır noktasına göre değerlendirilir. E-vize gerekip gerekmediğini Vietnam’ın resmî portalından kontrol edin; onaydaki tarih, isim ve giriş koşullarını biletle birlikte okuyun. Sosyal medyadaki başka bir yolcunun deneyimini kendi pasaportunuz için karar yerine kullanmayın.','Entry requirements depend on passport, stay and border arrangements. Check Vietnam’s official portal for whether you need an e-visa and read the approved details alongside your ticket. Another traveller’s social-media experience is not a substitute for checking the rules applicable to your passport.','Los requisitos dependen de pasaporte, estancia y acceso. Consulta el portal oficial para saber si necesitas visado electrónico y revisa aprobación junto al billete. La experiencia de otra persona en redes no sustituye las normas de tu pasaporte.')],
 [l('Dong, kart ve küçük ödemeler','Dong, cards and smaller payments','Dong, tarjetas y pagos pequeños'),l('Para birimi Vietnam dongu (VND). Büyük otel veya ulaşım ödemeleriyle küçük tezgâh alışverişinin ödeme düzeni aynı olmayabilir. Küçük kupür hazırlayın; çok sıfırlı fiyatlarda tutarı ve para birimini birlikte kontrol edin. ATM işleminde ücret ve dönüşüm seçimini okuyup günlük bütçeyi tek seferde harcamayın.','The currency is the Vietnamese dong (VND). Large hotel or transport payments and small-stall purchases may use different payment arrangements. Carry suitable small notes and read amount and currency together in prices with many zeros. Check ATM fees and conversion options rather than treating every withdrawal as identical.','La moneda es el dong vietnamita (VND). Hoteles y transporte pueden aceptar pagos distintos de pequeños puestos. Lleva billetes adecuados y revisa cantidad y moneda en cifras con muchos ceros. Lee comisiones y conversión del cajero.')],
 [l('Telefon ve buluşma noktası','Phone connection and meeting points','Teléfono y puntos de encuentro'),l('SIM veya eSIM almadan cihaz uyumluluğu, veri kapsamı ve etkinleştirmeyi kontrol edin. Tekne, araç ve otel girişlerinin harita pinlerini çevrimdışı da saklayın. Bir meydanın adını bilmek her turda aynı iskeleye geleceğiniz anlamına gelmez; buluşma noktasını ekran görüntüsü ve açık adresle birlikte tutmak işe yarar.','Check device compatibility, coverage and activation before buying a SIM or eSIM. Keep boat, vehicle and hotel entrance locations available offline. A waterfront name does not mean every tour uses the same pier; a clear address and saved map screenshot make meeting arrangements easier.','Revisa compatibilidad, cobertura y activación de SIM o eSIM. Guarda sin conexión accesos de hotel, barco y vehículo. Un nombre de paseo marítimo no significa el mismo embarcadero: conserva dirección y captura del punto de encuentro.')],
 [l('Bölgesel hava ve Tet dönemi','Regional weather and Tet travel','Clima regional y viajes durante Tet'),l('Kuzey, orta kıyı ve güney için hava beklentisini ayrı kurun. Yağış veya fırtına döneminde değiştirilebilir rezervasyon ve yedek kapalı mekân planı değerli. Tet çevresinde ulaşım talebi ve işletme düzeni değişebilir; gerçek seyahat tarihiniz için seferleri ve açık olma durumunu önceden kontrol edin.','Plan weather separately for the north, central coast and south. Flexible bookings and an indoor alternative help during heavy rain or storms. Around Tet, transport demand and business schedules may change; check services and openings for the dates you will actually travel.','Planifica clima por separado para norte, costa central y sur. Reservas flexibles y alternativa interior ayudan con lluvias o tormentas. En torno a Tet pueden cambiar demanda y horarios: verifica servicios para tus fechas reales.')],
 ],
 routes:[
 {title:l('Orta Vietnam’a yerleşen ilk gezi','A first trip centred on central Vietnam','Primer viaje centrado en Vietnam central'),duration:l('9–11 gün','9–11 days','9–11 días'),cities:['Hue','Da Nang','Hoi An'],description:l('Hue’ye üç gün, Da Nang’a üç gün, Hoi An’a üç gün ayırıp araya transfer payı koyun. Daha kısa tatilde Da Nang veya Hoi An’dan birini ana üs seçebilirsiniz; saray, şehir, bahçe ve kıyı günlerini ayrı tutun.','Allow three days each for Hue, Da Nang and Hoi An with transfer time between. On a shorter holiday, choose either Da Nang or Hoi An as the main base. Keep palace, city, countryside and coast days distinct.','Dedica tres días a cada destino y añade traslados. En viajes breves, elige Da Nang o Hoi An como base principal. Separa jornadas de palacios, ciudad, campo y costa.')},
 {title:l('Kuzeyden deltaya, acele etmeden','From the north to the delta without rushing','Del norte al delta sin prisas'),duration:l('18–21 gün','18–21 days','18–21 días'),cities:['Hanoi','Hue','Da Nang','Hoi An','Ho Chi Minh City','Can Tho'],description:l('Altı şehri üç büyük bölge gibi düşünün. Hanoi’de üç, orta bölümde sekiz veya dokuz, Ho Chi Minh City’de üç, Can Tho’da iki gün; kalan zamanı uçuş ve kara geçişlerine bırakın. Daha az gününüz varsa bir bölgeyi çıkarın, her şehirdeki dinlenmeyi değil.','Treat the six cities as three regional chapters: three Hanoi days, eight or nine in the centre, three in Ho Chi Minh City and two in Can Tho, with the remainder for flights and road journeys. Shorten the route by removing a region, not every rest interval.','Piensa en tres capítulos: tres días en Hanói, ocho o nueve en el centro, tres en Ciudad Ho Chi Minh y dos en Can Tho; el resto para viajes. Con menos tiempo, quita una región, no todos los descansos.')},
 ],
};
