import {l,section as s,sight as p,source,tourism} from './shared.mjs';
const city = {
 name:l('Da Nang','Da Nang','Da Nang'),key:'da-nang',
 title:l('Da Nang Gezi Rehberi: My Khe, Şehir ve Nerede Kalınır','Da Nang Travel Guide: My Khe, Cham Museum and City Life','Da Nang: qué ver, playa My Khe y dónde alojarse'),
 meta:l('Da Nang gezi rehberi: My Khe, Cham Heykel Müzesi ve Mermer Dağları; nehir ile plaj arasında konaklama, mi quang ve üç günlük şehir-kıyı dengesi.','Plan Da Nang with My Khe Beach, Cham sculpture and Marble Mountains: riverside or beach stays, mi quang and a balanced three-day coastal visit.','Organiza Da Nang con My Khe, el Museo Cham y las Montañas de Mármol: alojamiento junto al río o la playa, mi quang y una ruta costera de tres días.'),
 card:l('Bir sabah plaj, öğlen Cham sanatı, akşam nehir kıyısı: orta Vietnam’da şehirle denizin buluşması.','Beach mornings, Cham art and riverside evenings connect city life with the central Vietnamese coast.','Mañanas de playa, arte cham y tardes junto al río unen vida urbana y costa vietnamita.'),
 lede:l('Da Nang’ı yalnız Hoi An’a geçerken uyuyacağınız şehir diye düşünürseniz, sabah denizin kenarında başlayan gündelik hayatı kaçırırsınız. Burada iyi bir gün plajla başlayıp bir müzede serinleyebilir, akşam nehrin kıyısında uzayabilir. Şehri bütün uzak turların kalkış noktasına çevirmeden kendisine de zaman verin.','Treat Da Nang only as a bed before Hoi An and you miss the everyday city that begins beside the sea. A good day can start on the beach, pause in a museum and stretch into an evening on the riverbank. Leave time for the place itself instead of using every morning to depart on another tour.','Si Da Nang es solo una cama antes de Hoi An, te pierdes una ciudad que empieza el día junto al mar. Una jornada puede pasar de la playa al museo y terminar junto al río. Dale tiempo propio, además de usarla como salida de excursiones.'),
 facts:[l('3 tam gün','3 full days','3 días completos'),l('İlkbahar; deniz ve yağışa göre plan','Spring; plan around sea conditions and rain','Primavera; según mar y lluvia'),l('Plaj ve merkez arasında araç bağlantısı','Vehicle connections between beach and centre','Vehículo entre playa y centro')],
 sections:[
 s('sehri-anlamak',l('Da Nang’ın iki yüzü: nehir ve deniz','Da Nang’s two settings: river and sea','Dos ambientes: río y mar'),
 l('Nehir kıyısındaki merkezle My Khe çevresini aynı yürüme bölgesi sanmayın. Oteli seçmeden hangi akşamı istediğinize karar verin: kıyıda sakin bir dönüş mü, şehirde yemek ve nehir yürüyüşü mü? İkisini görmek mümkün, fakat günü sürekli köprü geçerek geçirmek zorunda değilsiniz.','The riverside centre and My Khe coast are not one small walking neighbourhood. Before choosing a hotel, decide which evening matters more: returning to the beach or dining in town before a river walk. You can enjoy both without spending the day repeatedly crossing between them.','Centro junto al río y costa de My Khe no forman un único barrio peatonal. Antes del hotel, decide qué tarde prefieres: volver a la playa o cenar en la ciudad y pasear junto al río. Puedes conocer ambos sin cruzar continuamente.'),
 l('İlk gün şehir ve müze, ikinci gün kıyı, üçüncü gün Mermer Dağları gibi tek bir dış ziyaret iyi bir denge. Ba Na Hills isterseniz onu ayrı bir gezi günü olarak değerlendirin; Altın Köprü şehir merkezindeki sıradan bir köprü değil, tesis gezisinin parçasıdır. Fotoğrafı güzel olan her şeyi aynı günün içine koymayın.','A city-and-museum day, a coastal day and one outing such as Marble Mountains create a useful balance. If Ba Na Hills appeals, give it a separate excursion day: the Golden Bridge is part of that destination, not an ordinary bridge in central Da Nang. Photogenic places still need travel time.','Un día urbano con museo, otro costero y una salida a las Montañas de Mármol dan equilibrio. Ba Na Hills necesita excursión propia: el Puente Dorado pertenece a ese destino, no al centro. Las fotos bonitas también requieren tiempo de desplazamiento.')),
 s('ulasim',l('Varış kolay; doğru otel bağlantısı önemli','An easy arrival still needs the right hotel connection','Una llegada sencilla exige buen enlace al hotel'),
 l('Da Nang (DAD) havalimanı ve tren istasyonu farklı varış noktalarıdır. Transferi “Da Nang merkez” yerine otelin tam adresine göre seçin. Hoi An oteliniz varsa son kara bağlantısını ayrıca planlayın; tren biletinde Da Nang yazması Hoi An’ın eski sokaklarına vardığınız anlamına gelmez.','Da Nang airport (DAD) and the railway station are different arrival points. Compare transfers to your actual hotel rather than a generic city-centre destination. A Hoi An booking needs its own final road connection; a ticket to Da Nang does not deliver you to Hoi An’s old streets.','Aeropuerto Da Nang (DAD) y estación son llegadas distintas. Compara traslado al hotel exacto, no a un centro genérico. Para Hoi An necesitas otro tramo por carretera: el billete a Da Nang no te deja en sus calles antiguas.'),
 l('Merkezde ve plaj çevresinde kısa yürüyüşleri araç bağlantılarıyla birleştirin. Son Tra’ya çıkış veya dağ yolları, sahil boyunca kısa bir bisiklet turuyla aynı hazırlığı gerektirmez. Güncel erişim koşullarını kontrol edin; motor deneyiminiz yoksa geziyi sürücülü araçla kurmak daha doğru bir tercih olabilir.','Combine shorter walks with vehicle journeys between areas. Son Tra and hill roads call for different preparation from an easy coastal cycle. Check current access arrangements and choose a driver if you lack riding experience; renting a motorbike is not a prerequisite for seeing the city.','Combina paseos cortos con vehículo entre zonas. Son Tra y carreteras de montaña exigen preparación distinta a una vuelta costera. Consulta accesos actuales; sin experiencia en moto, un vehículo con conductor puede ser mejor opción.')),
 s('mahalle-yasami',l('Sabah plajını yalnız yüzme saati saymayın','The morning beach is more than swimming time','La playa de mañana no es solo para bañarse'),
 l('Kıyıda erken bir yürüyüş, günün sıcak saatindeki şezlong molasından başka bir deneyim. Deniz uygunsa yüzün, değilse sırf plaj günü ayırdınız diye suya girmeyin. Kahvaltıyı yürüyüşün sonuna koymak, bütün sabahı yeni bir tur için acele etmeden şehre ayırmanın kolay yolu.','An early coastal walk is a different experience from a lounger in the midday heat. Swim when conditions allow, not simply because you assigned the day to the beach. Breakfast after the walk is an easy way to give the morning to Da Nang without rushing off on a tour.','Pasear temprano por la costa ofrece algo distinto a una tumbona al mediodía. Báñate si el mar lo permite, no porque toque día de playa. Desayunar después permite dedicar la mañana a la ciudad sin correr hacia una excursión.'),
 l('Akşam Han Nehri çevresinde seçtiğiniz bir bölümde yürüyüp yakında yemek yiyin. Köprü gösterisini görmek istiyorsanız güncel tarih ve saati doğrulayın; onu bütün akşamın tek nedeni yapmayın. Kentin sıradan bir kahve molası veya sakin dönüş yolu da tatilin güzel anlarından biri olabilir.','Choose a section of the Han River for an evening walk and dinner nearby. If a bridge performance is important, verify its current schedule without making it the sole purpose of the evening. An ordinary coffee break or quiet route back can be just as memorable.','Elige un tramo del río Han para paseo y cena cerca. Si quieres un espectáculo del puente, consulta horario actual sin convertirlo en el único motivo de la tarde. Un café cotidiano o el regreso tranquilo también pueden dejar recuerdo.')),
 s('konaklama',l('My Khe mi, nehir merkezi mi?','My Khe or the riverside centre?','¿My Khe o el centro junto al río?'),
 l('My Khe çevresi sabah kıyı erişimini, nehir merkezi ise müze ve şehir akşamlarını öncelemek için düşünülebilir. Sahil otelinde fotoğraftaki deniz kadar yol geçişini, oda yönünü ve yapım gürültüsünü de inceleyin. Bir otelin “beachfront” tanımı odadan kuma engelsiz geçiş vaat etmeyebilir.','My Khe prioritises mornings by the sea; the riverside centre suits museums and urban evenings. For coastal hotels, check road crossings, room orientation and recent construction-noise comments as carefully as the sea photograph. A beachfront label may not mean an uninterrupted walk from the room to the sand.','My Khe favorece mañanas junto al mar; el centro, museos y tardes urbanas. Revisa cruces, orientación y ruido de obras además de la foto. “Frente a la playa” no siempre implica acceso directo de la habitación a la arena.'),
 l('Daha güneydeki resort konumları ayrı bir dinlenme tercihi. Şehirde her gece yemek arayacaksanız dönüş masrafını ve araç bulunurluğunu ekleyin. Üç gecede otel değiştirmek yerine hangi tarafta daha çok zaman geçirmek istediğinizi baştan seçmek, tatilin küçük lojistiklerini azaltır.','Resorts farther south offer a different kind of stay. If you plan to dine in the city every evening, factor in return transport. For three nights, choosing the setting where you most want to spend time can be easier than changing hotels merely to sample both.','Los resorts más al sur ofrecen otra estancia. Si quieres cenar cada noche en la ciudad, añade transporte de vuelta. En tres noches, elegir dónde pasar más tiempo suele ser más sencillo que cambiar de hotel para probar ambas zonas.')),
 s('yeme-icme',l('Mi quang ve deniz ürünleri: tabağın ayrıntısını okuyun','Mi quang and seafood: pay attention to the dish','Mi quang y marisco: mira los detalles del plato'),
 l('Mi quang’da erişte, otlar, yer fıstığı ve farklı üst malzemeler bir araya gelir; yalnız büyük bir çorba beklemeyin. Bir öğünü buna, diğerini seçtiğiniz deniz ürününe ayırmak bölgenin iki farklı tarafını gösterir. Yemekleri karşılaştırırken “en iyi” sıralaması yerine hangi doku ve tadı sevdiğinizi düşünün.','Mi quang combines noodles, herbs, peanuts and varied toppings; do not expect simply another large bowl of soup. Let one meal explore that dish and another your chosen seafood. Comparing textures and flavours you enjoy is more useful than trying to establish a universal “best” ranking.','Mi quang combina fideos, hierbas, cacahuetes y acompañamientos; no esperes solo otra sopa grande. Dedica una comida a ese plato y otra al marisco elegido. Comparar sabores y texturas que disfrutas aporta más que decidir un “mejor” universal.'),
 l('Deniz ürününde fiyatın adet, tabak veya ağırlık üzerinden mi verildiğini ve pişirme ücretini siparişten önce sorun. Kabuklu, yer fıstığı ve balık sosu içeriğini beslenme ihtiyacınıza göre kontrol edin. Nehir manzarasına değil düzgün bir yemeğe öncelik verdiğiniz akşam da güzel bir Da Nang akşamıdır.','For seafood, clarify whether prices refer to an item, dish or weight, and whether preparation is extra. Check shellfish, peanuts and fish sauce according to your dietary needs. An evening chosen for a satisfying meal rather than a river view can be a very good Da Nang evening too.','En marisco, pregunta si cobran por pieza, plato o peso y si cocinar cuesta aparte. Revisa marisco, cacahuetes y salsa de pescado según tus necesidades. Elegir una buena comida en vez de vistas también puede dar una tarde estupenda.')),
 s('mevsim-butce',l('Plaj gününe esneklik, gezi bütçesine ayrı kalemler','Flexible beach days and separate excursion costs','Playa flexible y excursiones presupuestadas aparte'),
 l('Orta Vietnam’ın yağış düzenini kuzey veya güneydeki havayla aynı kabul etmeyin. İlkbahar yürüyüş için düşünülebilir; yağışlı ve fırtınalı dönemlerde kıyı planı değişebilir. Deniz rengi güzel görünse bile bayrak, akıntı ve yerel uyarıları izleyin; müze gününü gerektiğinde plaj günüyle değiştirebilmek işe yarar.','Central Vietnam’s weather should not be inferred from the north or south. Spring can suit walking, while rainy or stormy periods may alter coastal plans. Follow flags and local guidance even when the water looks inviting. Keeping museum and beach days interchangeable gives the itinerary useful flexibility.','No deduzcas el tiempo del centro por el del norte o sur. Primavera puede facilitar paseos; lluvias y tormentas alteran costa. Respeta banderas y avisos aunque el agua parezca bonita. Poder intercambiar museo y playa ayuda a adaptar el viaje.'),
 l('Şehir yemeği, plaj hizmetleri ve dış turları ayrı bütçeleyin. Bir resort günüyle gündelik şehir günü aynı maliyette değildir. Uzak bir tesis gezisine ulaşım, giriş ve beklemeyi birlikte ekleyin; yalnız ana bilet fiyatına bakmak günün gerçek yükünü eksik gösterir.','Separate city meals, beach services and excursions in the budget. A resort day and an everyday city day have different cost structures. Add travel, admission and waiting time together for distant attractions; the main ticket alone does not describe the whole day.','Separa comidas urbanas, servicios de playa y excursiones. Un día de resort y uno cotidiano no cuestan igual. En visitas alejadas suma transporte, entrada y esperas: el billete principal no representa toda la jornada.')),
 ],
 sights:[
 p(l('My Khe Plajı','My Khe Beach','Playa My Khe'),l('Şehir kıyısı','City coast','Costa urbana'),l('Kıyının bir bölümünü seçip yürüyüş ve kahvaltıyı birleştirin. Aynı gün bütün plaj şeridini bitirmeyi hedeflemek yerine dinlenmeye alan bırakın; yüzme kararını günlük koşula göre verin.','Choose one coastal section for a walk and breakfast. Leave room to rest rather than trying to complete the entire shoreline; decide about swimming from conditions that day.','Elige un tramo para paseo y desayuno. Deja descanso en vez de recorrer toda la costa; decide el baño según las condiciones del día.'),l('Şehrin denizle ilişkisini gündelik hâliyle görmek.','See the city’s everyday relationship with the sea.','Ver la relación cotidiana con el mar.'),l('Güneş ve gölgeyi birlikte planlayın.','Plan shade as well as sun.','Planifica sombra además de sol.')),
 p(l('Cham Heykel Müzesi','Museum of Cham Sculpture','Museo de Escultura Cham'),l('Nehir merkezi','Riverside centre','Centro junto al río'),l('Taş eserleri yalnız ayrı heykeller gibi değil, geldikleri yer ve inanç bağlamıyla okuyun. Sonrasında My Son’a gidecekseniz bu müze ziyareti oradaki yapıları anlamanız için iyi bir başlangıç olabilir.','Read the objects through their place of origin and religious context, not simply as isolated sculptures. If you later visit My Son, the museum can provide a useful introduction to what you will see.','Lee origen y contexto religioso de las piezas. Si después visitas My Son, el museo puede ayudarte a entender mejor sus construcciones.'),l('Orta Vietnam’ın Cham mirasına yaklaşmak.','Encounter central Vietnam’s Cham heritage.','Acercarse al patrimonio cham.'),l('Açıklamalara zaman ayırın.','Leave time for interpretation.','Dedica tiempo a las explicaciones.')),
 p(l('Mermer Dağları','Marble Mountains','Montañas de Mármol'),l('Şehrin güneyi','South of the city','Sur de la ciudad'),l('Basamak, mağara ve ibadet alanlarını aynı yürüyüşün farklı parçaları olarak düşünün. Uygun ayakkabı giyip kaygan yüzeylere dikkat edin; dik bölümleri gezmek sizin için uygunsa programa ekleyin.','Steps, caves and religious spaces form different parts of this outing. Wear suitable shoes and consider slippery surfaces; choose the steeper sections according to your mobility and comfort.','Escaleras, cuevas y espacios religiosos requieren atención distinta. Usa calzado adecuado y valora superficies resbaladizas y tramos empinados según tu movilidad.'),l('Kent gününe ayrı bir kaya ve tapınak gezisi eklemek.','Add a distinct rock-and-temple outing to the stay.','Añadir una salida propia entre roca y templos.'),l('Plaj sandaletiyle uzun tırmanış planlamayın.','Avoid planning steep walks in beach footwear.','Evita subidas largas con calzado de playa.')),
 ],
 itinerary:[{title:l('1. Gün — Şehir ve Cham mirası','Day 1 — City and Cham heritage','Día 1 — Ciudad y patrimonio cham'),morning:l('Cham Heykel Müzesi','Museum of Cham Sculpture','Museo de Escultura Cham'),afternoon:l('Yerel yemek ve dinlenme','Local lunch and rest','Comida local y descanso'),evening:l('Han Nehri çevresi','Han River area','Entorno del río Han')},{title:l('2. Gün — My Khe','Day 2 — My Khe','Día 2 — My Khe'),morning:l('Kıyı yürüyüşü ve kahvaltı','Coastal walk and breakfast','Paseo costero y desayuno'),afternoon:l('Koşullara göre plaj veya kapalı mekân','Beach or indoor time according to conditions','Playa o interior según condiciones'),evening:l('Kıyıya yakın yemek','Dinner near the coast','Cena cerca de la costa')},{title:l('3. Gün — Mermer Dağları','Day 3 — Marble Mountains','Día 3 — Montañas de Mármol'),morning:l('Mermer Dağları ziyareti','Visit Marble Mountains','Visita a las Montañas de Mármol'),afternoon:l('Dönüş ve serbest zaman','Return and free time','Regreso y tiempo libre'),evening:l('Hoi An veya Hue bağlantısını hazırlama','Prepare onward travel to Hoi An or Hue','Preparar continuación a Hoi An o Hue')}],
 faqs:[{q:l('Da Nang yalnız bir transfer şehri mi?','Is Da Nang only a transit stop?','¿Da Nang es solo una escala?'),a:l('Hayır. Plaj, şehir yemekleri, Cham müzesi ve nehir akşamları için üç tam gün ayrılabilir. Hoi An bağlantısını bu günlerin yerine değil, devamına koyun.','No. Beaches, food, Cham art and riverside evenings can fill three full days. Treat Hoi An as an onward stay rather than replacing all your Da Nang time.','No. Playa, gastronomía, arte cham y río permiten tres días. Considera Hoi An una continuación en vez de sustituir toda la estancia.')},{q:l('Altın Köprü Da Nang merkezinde mi?','Is the Golden Bridge in central Da Nang?','¿El Puente Dorado está en el centro de Da Nang?'),a:l('Hayır; Ba Na Hills tesis gezisiyle bağlantılıdır. Yolculuk ve tesis erişimi gerekir; merkez yürüyüşünün kısa bir durağı gibi planlamayın.','No: it belongs to the Ba Na Hills outing, with travel and attraction access involved. It is not a quick stop on a central walking route.','No: forma parte de la excursión a Ba Na Hills y necesita traslado y acceso. No es una parada breve de un paseo céntrico.')}],
 sources:[source(tourism,'https://vietnam.travel/places-to-go/central-vietnam/da-nang'),source(l('Da Nang turizmi — Cham Müzesi','Da Nang Tourism — Cham Museum','Turismo de Da Nang — Museo Cham'),'https://danangfantasticity.com/en/overview-da-nang-museum-of-cham-sculpture'),source(l('Vietnam Tourism — Da Nang yemekleri','Vietnam Tourism — Da Nang food','Vietnam Tourism — gastronomía de Da Nang'),'https://vietnam.travel/things-to-do/foodie-guide-da-nang')],
};

export default city;
