import {l,section as s,sight as p,source,tourism} from './shared.mjs';
const city = {
 name:l('Hanoi','Hanoi','Hanói'),key:'hanoi',
 title:l('Hanoi Gezi Rehberi: Mahalleler, Yemekler ve 3 Günlük Rota','Hanoi Travel Guide: Old Quarter, Food and a 3-Day Itinerary','Hanói: qué ver, dónde comer y ruta de 3 días'),
 meta:l('Hanoi gezi rehberi: Hoan Kiem, Eski Mahalle, Edebiyat Tapınağı ve Truc Bach; konaklama bölgeleri, yerel yemekler, kahve molaları ve üç günlük rota.','Explore Hanoi through Hoan Kiem, the Old Quarter and Truc Bach: where to stay, local dishes, coffee breaks and a thoughtful three-day itinerary.','Descubre Hanói entre Hoan Kiem, el casco antiguo y Truc Bach: qué ver, dónde alojarte, platos locales, pausas con café y una ruta de tres días.'),
 card:l('Hoan Kiem çevresinde sabah yürüyüşleri, dar sokaklar, avlular ve uzun kahve molalarıyla kuzeyin başkenti.','Northern Vietnam’s capital through lakeside mornings, narrow streets, courtyards and leisurely coffee breaks.','La capital del norte entre paseos junto al lago, callejuelas, patios y pausas largas con café.'),
 lede:l('Hanoi’de ilk gün kulağınız kornalara, ikinci gün gözünüz sokak aralarına alışıyor. Sonra bir kahvenin yanında otururken fark ediyorsunuz: bu şehir yalnız geçilecek bir kapı değil. Göl kenarındaki sabahı, çorba başında verilen molayı ve aynı sokağın akşam başka bir yere dönüşmesini biraz yaşamak gerekiyor.','At first Hanoi arrives as noise; then you begin noticing the small passages between the busy streets. A coffee break can change the way you see the city. This is more than a gateway to northern Vietnam: give its lakeside mornings, everyday meals and changing evening streets time to become part of your trip.','Al principio Hanói parece ruido; después empiezas a descubrir los pasajes entre calles. Una pausa con café cambia la mirada. La ciudad merece más que una noche antes de seguir al norte: deja que sus mañanas junto al lago, sus comidas y sus tardes formen parte del viaje.'),
 facts:[l('3 tam gün','3 full days','3 días completos'),l('İlkbahar ve sonbahar; hava değişebilir','Spring and autumn; weather varies','Primavera y otoño; tiempo variable'),l('Bölge bölge yürüyüş ve araç bağlantısı','Neighbourhood walks with vehicle connections','Paseos por zonas y enlaces en vehículo')],
 sections:[
 s('sehri-anlamak',l('Hanoi’ye bir sabah, bir öğle, bir de akşam verin','Let Hanoi have a morning, an afternoon and an evening','Dale a Hanói una mañana, una tarde y una noche'),
 l('İlk sabah Hoan Kiem çevresinde kısa bir yürüyüşle başlayın. Bütün Eski Mahalle’yi aynı anda çözmeye çalışmak yerine göle geri dönebileceğiniz küçük bir halka kurun. İlk günün amacı haritada çok nokta toplamak değil; suyun, sokakların ve otelinizin birbirine göre nerede olduğunu anlamak olsun.','Start with a short circuit around Hoan Kiem rather than trying to decode the whole Old Quarter. Keep the lake as your reference point. Your first morning is for finding your bearings and learning how your hotel connects to the streets, not collecting the largest possible number of pins.','Empieza con una vuelta corta por Hoan Kiem, sin intentar descifrar todo el casco antiguo. Usa el lago como referencia. La primera mañana sirve para orientarte y entender dónde queda el hotel; no hace falta acumular puntos en el mapa.'),
 l('Üç günlük gezide bir günü göl ve Eski Mahalle’ye, birini Edebiyat Tapınağı ile seçtiğiniz müzeye, üçüncüyü Truc Bach çevresine ayırabilirsiniz. Aynı yere farklı saatte dönmek tekrar sayılmaz: Hanoi’yi bazen yeni bir sokaktan çok, bildiğiniz sokağın değişen hâli anlatır.','Give one day to the lake and old streets, another to the Temple of Literature and a chosen museum, and a third to Truc Bach. Returning at a different hour is not wasted time. Watching a familiar street change can tell you more than rushing to another attraction.','Dedica un día al lago y las calles antiguas, otro al Templo de la Literatura y un museo elegido, y otro a Truc Bach. Volver a distinta hora también es descubrir: una calle conocida que cambia puede contar más que otra visita apresurada.')),
 s('ulasim',l('Hanoi’ye nasıl gidilir, şehirde nasıl gezilir?','Getting to Hanoi and moving around','Cómo llegar a Hanói y moverse'),
 l('Uçakla varışta biletinizde Noi Bai (HAN) havalimanını kontrol edin. Merkeze transferi uçuş saati, bagaj ve otelin araçla ulaşılabilen girişine göre seçin. Eski Mahalle’de kısa görünen son bağlantı bavulla zorlaşabilir; otelden tam bırakma noktasını istemek ilk karşılaşmayı kolaylaştırır.','Check that your flight arrives at Noi Bai (HAN). Choose the transfer around arrival time, luggage and the entrance vehicles can reach. A short final stretch in the Old Quarter may be awkward with a suitcase; ask the hotel for its practical drop-off point before you travel.','Comprueba la llegada a Noi Bai (HAN) y elige traslado según hora, equipaje y acceso al hotel. Un tramo corto por el casco antiguo puede complicarse con maleta. Pedir al alojamiento el punto exacto de bajada facilita mucho la llegada.'),
 l('Yürüyüşü kısa mahalle parçalarıyla kurun; uzaktaki ziyaretleri araçla bağlayın. Yol geçişinde ışık, yaya geçidi ve uygun boşluk arayın; trafiğin sizi otomatik fark edeceğini varsaymayın. Tren raylarına kahve fotoğrafı için girmek gezi önerisi değildir; erişim kısıtlarını izleyip ray hattının dışında kalın.','Build walks from manageable neighbourhood sections and connect distant visits by vehicle. Use crossings, signals and safe gaps instead of assuming traffic will make way. A railway coffee photograph is not a reason to enter the tracks: respect access restrictions and stay outside the rail corridor.','Une paseos cortos con vehículo para lugares alejados. Busca semáforos, pasos y huecos seguros; no presupongas que el tráfico cederá. Una foto con café no justifica entrar en las vías: respeta restricciones y permanece fuera del corredor ferroviario.')),
 s('mahalle-yasami',l('Eski Mahalle ile Truc Bach arasında şehir değişiyor','Between the Old Quarter and Truc Bach','Del casco antiguo a Truc Bach'),
 l('Eski Mahalle’de adresinize giderken dükkânlara bakmak, bir girişin ardındaki avluyu fark etmek ve oturarak dinlenmek yürüyüşün kendisi kadar değerli. Dar sokakları yalnız dekor olarak görmeyin: insanlar çalışıyor, mal taşıyor ve evine dönüyor. Fotoğraftan önce kısa bir izin istemek güzel bir karşılaşmaya alan açar.','In the Old Quarter, browsing a shop or pausing near a courtyard can matter as much as completing a route. These streets are workplaces and homes as well as sightseeing spaces. Ask before photographing people; a brief exchange may become the most memorable part of the walk.','Mirar una tienda o descansar junto a un patio también forma parte del paseo. Estas calles son lugares de trabajo y viviendas, además de visitas. Pide permiso antes de fotografiar personas: una conversación breve puede ser el recuerdo más bonito.'),
 l('Truc Bach’a geçişi “ikinci bir göl gördüm” diye bitirmeyin. Bir kıyı parçası seçip öğle yemeği ve kahveyle birleştirin. Çok uzun yürümek istemiyorsanız iki gölü aynı turda tamamen dolaşma hedefi koymayın. Hanoi’de iyi bir öğleden sonra, bazen tek bir masadan kalkmak istemediğiniz öğleden sonradır.','Visit Truc Bach for a slower stretch of the day, not simply another lake ticked off. Choose a section of shore and pair it with lunch and coffee. You need not complete both lakes on foot. Sometimes the best afternoon is the one spent at a table you are reluctant to leave.','Truc Bach merece algo más que marcar otro lago. Elige un tramo de orilla y combínalo con comida y café. No necesitas rodear todos los lagos a pie. A veces la mejor tarde es aquella en la que no apetece levantarse de la mesa.')),
 s('konaklama',l('Hanoi’de nerede kalınır: gürültü de adresin parçası','Where to stay: noise is part of the address','Dónde alojarse: también importa el ruido'),
 l('Hoan Kiem çevresi ilk gelişte merkez yürüyüşlerini kolaylaştırır. Ancak “Old Quarter’da” yazması her odanın aynı sessizlikte olduğu anlamına gelmiyor. Odanın caddeye yönünü, pencere durumunu ve gece yorumlarını okuyun; iyi uyku, ertesi sabahki gezinin görünmeyen hazırlığıdır.','Hoan Kiem makes central walks easy on a first visit, but an Old Quarter address does not guarantee the same sleeping conditions in every room. Check street-facing windows and recent noise comments. A good night’s rest is the invisible preparation for tomorrow’s sightseeing.','Hoan Kiem facilita la primera visita, pero una dirección céntrica no asegura silencio. Revisa orientación de la habitación, ventanas y comentarios recientes sobre ruido. Dormir bien es parte de la preparación del día siguiente.'),
 l('Truc Bach veya Batı Gölü çevresini seçerseniz daha farklı bir mahalle gündeliği kazanabilir, eski merkeze araçla dönmeyi göze alabilirsiniz. Üç gecelik gezide sırf iki semti denemek için otel değiştirmeyin; valiz yerine bir akşam yemeği için yeni mahalleye gitmek daha keyifli olabilir.','Truc Bach or the West Lake area offers a different daily setting, with more vehicle journeys to the old centre. On a three-night stay, visiting another neighbourhood for dinner may be more rewarding than moving hotels just to sample two addresses.','Truc Bach o el Lago del Oeste ofrecen otra vida de barrio, con más desplazamientos al centro antiguo. En tres noches suele ser más agradable ir a cenar a otra zona que cambiar de hotel solo para probar dos direcciones.')),
 s('yeme-icme',l('Hanoi sofrası: bir güne bütün yemekleri sığdırmayın','Hanoi at the table: leave room for tomorrow','La mesa de Hanói: deja algo para mañana'),
 l('Pho ile başlayan sabahı bun cha öğle yemeğiyle sürdürebilirsiniz; banh cuon da ayrı bir denemeyi hak ediyor. Bun cha’da ızgara et, erişte ve otlar ayrı parçalarla gelir: hepsini tek büyük çorba gibi düşünmeden küçük lokmalarla kendi dengenizi kurun. Merak iştahı açıyor, ama her öğünde yeni üç tabak şart değil.','A pho breakfast and a bun cha lunch make two different encounters with the city; save another meal for banh cuon. With bun cha, explore the grilled meat, noodles and herbs in smaller combinations rather than treating everything as one large soup. Curiosity is a good appetite, but three new dishes at every meal are unnecessary.','Un desayuno con pho y un almuerzo de bun cha son dos formas distintas de conocer la ciudad; deja otra comida para banh cuon. Combina carne, fideos y hierbas poco a poco. La curiosidad abre el apetito, pero no obliga a pedir tres novedades cada vez.'),
 l('Yumurtalı kahveyi sıradan kahvenin yerine değil, küçük bir tatlı molası gibi deneyin. Siparişte yoğunlaştırılmış süt ve yumurta içeriğini hesaba katın. Vegan yemek için yalnız “sebzeli” demek yetmeyebilir; et suyu ve balık sosunu sorun. Bir kafenin asıl güzelliği bazen manzarasından çok, acele etmeden oturmanıza izin veren atmosferidir.','Treat egg coffee as a small dessert break rather than an interchangeable coffee order, remembering its egg and condensed-milk ingredients. For vegan meals, ask about stock and fish sauce as well as vegetables. A cafe’s greatest quality can be the simple pleasure of being able to sit without rushing.','Prueba el café con huevo como una pausa dulce, teniendo en cuenta huevo y leche condensada. Para comer vegano pregunta también por caldo y salsa de pescado. Lo más agradable de una cafetería puede ser simplemente poder quedarse sin prisas.')),
 s('mevsim-butce',l('Hava ve bütçe: yağmurlu saat de geziye ait','Weather and budget: a rainy hour belongs to the trip','Tiempo y presupuesto: la lluvia también cuenta'),
 l('Hanoi’de yılın her ayı aynı hava beklenmez. İlkbahar ve sonbahar yürüyüş için düşünülebilir; yazın sıcak ve yağmur, kışın daha serin ve kapalı günler planı değiştirir. Müze ile açık hava ziyaretini farklı saatlere yerleştirip kısa yağmuru bütün günü kaybetmişsiniz gibi görmeyin.','Hanoi does not have one climate setting all year. Spring and autumn can suit walking; summer heat and rain or cooler, overcast winter days change the programme. Pair indoor and outdoor visits flexibly. A rainy hour need not mean a wasted sightseeing day.','Hanói cambia durante el año. Primavera y otoño pueden favorecer paseos; calor y lluvias estivales o días frescos de invierno modifican el plan. Combina interiores y exteriores con flexibilidad: una hora de lluvia no significa perder el día.'),
 l('Yemekler, transferler, anıt girişleri ve kuzeye devam edeceğiniz ulaşımı ayrı bütçeleyin. Uygun bir öğünün ardından pahalı bir transfer yapmanız günün toplamını değiştirir. Bir sokakta yemek bulmak kolay olsa da her gün otelin karşısına dönmek yerine yakın ziyaret bölgesinde mola vermek daha az yorucu olur.','Budget meals, transfers, admission and onward northern travel separately. An inexpensive lunch followed by a long private transfer changes the day’s total. Planning a break near the places you visit can also be easier than returning across the city to the same hotel street.','Separa comidas, traslados, entradas y continuación al norte. Un almuerzo económico seguido de un traslado largo cambia el total. Descansar cerca de las visitas suele ser más cómodo que cruzar la ciudad para volver siempre a la calle del hotel.')),
 ],
 sights:[
 p(l('Hoan Kiem Gölü','Hoan Kiem Lake','Lago Hoan Kiem'),l('Merkez','Centre','Centro'),l('Gölü ilk gün yön bulma noktası yapın; erken bir yürüyüşü kahveyle birleştirin. Ngoc Son Tapınağı’nı eklediğinizde ziyaretin ayrı giriş koşullarını kontrol edin. Kıyıdan görülen Kaplumbağa Kulesi, göl içindeki ayrı bir yapıdır.','Use the lake to orient your first day and pair an early walk with coffee. Check separate access conditions for Ngoc Son Temple. Turtle Tower, seen from the shore, is a different structure within the lake.','Usa el lago para orientarte y combina paseo temprano con café. Consulta acceso a Ngoc Son. La Torre de la Tortuga, visible desde la orilla, es otra construcción dentro del lago.'),l('Şehre yavaş bir başlangıç.','A gentle introduction to the city.','Una entrada tranquila a la ciudad.'),l('Tapınak ile kuleyi karıştırmayın.','Do not confuse the temple and tower.','No confundas templo y torre.')),
 p(l('Edebiyat Tapınağı','Temple of Literature','Templo de la Literatura'),l('Van Mieu','Van Mieu','Van Mieu'),l('Avlular arasında acele etmeden ilerleyin; bu ziyaret yalnız güzel bir kapı fotoğrafından ibaret değil. Eğitim mirasını anlatan açıklamalara zaman ayırıp sonrasında yakındaki sokaklarda yemek molası verin.','Walk the courtyards slowly and spend time with the explanations of the site’s educational heritage. This is more than a gateway photograph; leave space for lunch nearby afterwards.','Recorre patios despacio y lee las explicaciones del patrimonio educativo. La visita ofrece más que una foto de la puerta; reserva después tiempo para comer cerca.'),l('Hanoi’nin eğitim hafızasına yaklaşmak.','Encounter the city’s educational heritage.','Acercarse al patrimonio educativo.'),l('Sıcak saatlerde gölge molası verin.','Take shade breaks in hot weather.','Descansa a la sombra cuando haga calor.')),
 p(l('Thang Long İmparatorluk Kalesi','Imperial Citadel of Thang Long','Ciudadela Imperial de Thang Long'),l('Ba Dinh','Ba Dinh','Ba Dinh'),l('Kale alanını bağımsız bir ziyaret olarak ele alın. Yer üstündeki yapılar ile arkeolojik katmanların ilişkisini anlamak için harita ve açıklamalara bakın; bütün durakları aynı hanedan dönemi sanmayın.','Give the citadel its own visit. Read the map and interpretation to connect standing buildings with archaeological layers; the different parts do not all belong to one dynastic period.','Dedica una visita propia a la ciudadela. Mapas y explicaciones conectan edificios y estratos arqueológicos; sus partes no pertenecen todas al mismo periodo.'),l('Şehrin farklı tarih katmanlarını görmek.','See the city’s layered history.','Entender las capas de historia.'),l('Güncel açık alanları kontrol edin.','Check which areas are open.','Consulta los espacios abiertos.')),
 ],
 itinerary:[['Hoan Kiem ve eski sokaklar','Lake and old streets','Lago y calles antiguas'],['Avlular ve tarih','Courtyards and history','Patios e historia'],['Truc Bach ve kahve','Truc Bach and coffee','Truc Bach y café']].map((title,i)=>({title:l(...title),morning:[l('Hoan Kiem yürüyüşü','Hoan Kiem walk','Paseo por Hoan Kiem'),l('Edebiyat Tapınağı','Temple of Literature','Templo de la Literatura'),l('Truc Bach kıyısı','Truc Bach shore','Orilla de Truc Bach')][i],afternoon:[l('Eski Mahalle ve yemek','Old Quarter and lunch','Casco antiguo y comida'),l('Thang Long Kalesi','Thang Long Citadel','Ciudadela de Thang Long'),l('Serbest mahalle zamanı','Unhurried neighbourhood time','Tiempo libre por el barrio')][i],evening:l('Otele yakın yemek ve kısa yürüyüş','Dinner and a short walk near your hotel','Cena y paseo breve cerca del hotel')})),
 faqs:[{q:l('Hanoi kaç günde gezilir?','How many days do you need in Hanoi?','¿Cuántos días dedicar a Hanói?'),a:l('İlk şehir gezisi için üç tam gün iyi bir başlangıçtır. Ha Long veya Ninh Binh gibi şehir dışı geziler bu sürenin içine kaybolmamalı; ulaşım ve konaklamayı ayrıca planlayın.','Three full days make a good first city stay. Treat Ha Long or Ninh Binh as additional trips with their own travel and accommodation time.','Tres días completos son un buen comienzo. Ha Long o Ninh Binh requieren tiempo adicional de traslado y estancia.')},{q:l('Hanoi’de nerede kalınır?','Where should you stay in Hanoi?','¿Dónde alojarse en Hanói?'),a:l('İlk ziyaret için Hoan Kiem çevresi pratik; Truc Bach ve Batı Gölü farklı mahalle deneyimleri sunar. Harita konumu kadar odanın gece gürültüsünü de değerlendirin.','Hoan Kiem is practical for a first visit; Truc Bach and West Lake offer different neighbourhood settings. Compare room noise as well as location.','Hoan Kiem es práctico en la primera visita; Truc Bach y el Lago del Oeste ofrecen otros ambientes. Compara ubicación y ruido de la habitación.')}],
 sources:[source(tourism,'https://vietnam.travel/node/95'),source(l('Vietnam Tourism — Hanoi yemekleri','Vietnam Tourism — Hanoi food','Vietnam Tourism — gastronomía de Hanói'),'https://vietnam.travel/node/1560'),source(l('Vietnam Tourism — Hanoi ziyaretleri','Vietnam Tourism — Hanoi attractions','Vietnam Tourism — visitas de Hanói'),'https://vietnam.travel/node/187'),source(l('UNESCO — Thang Long','UNESCO — Thang Long','UNESCO — Thang Long'),'https://whc.unesco.org/en/list/1328/')],
};

export default city;
