import {l,section as s,sight as p,source,tourism} from './shared.mjs';
const city = {
 name:l('Hoi An','Hoi An','Hoi An'),key:'hoi-an',
 title:l('Hoi An Gezi Rehberi: Eski Şehir, Plaj ve Sakin Bir Rota','Hoi An Travel Guide: Old Town, Beaches and Where to Stay','Hoi An: casco antiguo, playas y dónde alojarse'),
 meta:l('Hoi An gezi rehberi: eski liman sokakları, An Bang, Tra Que, cao lau ve terzi provaları; konaklama seçimi, ulaşım ve üç günlük dengeli gezi planı.','Explore Hoi An beyond lanterns: Old Town mornings, An Bang Beach, Tra Que, cao lau, tailoring and a balanced three-day plan with places to stay.','Descubre Hoi An más allá de los farolillos: casco antiguo, An Bang, Tra Que, cao lau, talleres de costura y una ruta equilibrada de tres días.'),
 card:l('Fenerli akşamların öncesinde sessiz sabah sokakları, bahçeler, terzi provaları ve kıyıda uzun molalar.','Quiet morning streets, gardens, tailoring visits and coastal breaks before the lantern-lit evening.','Calles tranquilas por la mañana, huertos, pruebas de ropa y descansos junto al mar antes de los farolillos.'),
 lede:l('Hoi An’ın fotoğrafını çoğu kişi gece çekiyor; şehirle tanışmak için sabahı da saklayın. Kepenkler açılırken eski sokakların rengi başka, nehir kıyısında akşamın sesi başka. Burada güzel bir tatil, bütün fenerleri fotoğraflamakla değil, aynı sokağa acele etmeden iki kere dönmekle başlayabilir.','Most photographs of Hoi An are taken at night; keep a morning for yourself too. The old streets feel different as shutters open, and the river takes on another mood in the evening. A good stay can begin with returning to the same lane without rushing, rather than photographing every lantern.','Muchas fotos de Hoi An se hacen de noche; guarda también una mañana para ti. Las calles cambian cuando abren las tiendas y el río adquiere otro ambiente al atardecer. El viaje puede empezar volviendo sin prisas a una calle, no fotografiando todos los farolillos.'),
 facts:[l('3 tam gün','3 full days','3 días completos'),l('Mart–mayıs; kıyı ve yağışı ayrıca değerlendirin','March–May; assess coast and rain separately','Marzo–mayo; valora costa y lluvia por separado'),l('Eski şehirde yürüyüş; kıyıya ayrı bağlantı','Old Town walks; separate coastal connections','Paseos por el centro y enlaces a la costa')],
 sections:[
 s('sehri-anlamak',l('Hoi An’ın üç günü: sokak, bahçe, deniz','Three Hoi An days: streets, gardens and sea','Tres días: calles, huertos y mar'),
 l('İlk günü eski şehrin birkaç sokağıyla sınırlamak eksik gezi değildir. Sabah bir tarihî ev veya toplantı salonu, öğlen yemek, akşam nehir kıyısı iyi bir başlangıç. Gündüz okuduğunuz kapılar akşam ışıkların altında başka görünür; ilk gece bütün tatilin fotoğrafını çekmek zorunda değilsiniz.','Limit the first day to a few old streets without feeling you have missed the town. A historic house or assembly hall, lunch and an evening by the river make a strong introduction. The doors you study by daylight look different after dark; the first night need not contain all your holiday photographs.','Un primer día de pocas calles no es una visita incompleta. Una casa histórica o sala de asamblea, comida y río al atardecer forman una buena entrada. Las puertas vistas de día cambian de noche; no necesitas hacer todas las fotos la primera tarde.'),
 l('İkinci gün Tra Que çevresindeki bahçe yaşamına, üçüncü gün hava uygunsa An Bang kıyısına açılabilirsiniz. My Son ekleyecekseniz bu günlerden birini ona ayırın. Eski şehir, plaj, kırsal tur ve arkeolojik alanı tek güne koymak aynı tatilin dört ayrı güzel tarafını birbirine karşı yarıştırır.','Give another day to the Tra Que area and, conditions permitting, a third to An Bang. If My Son matters more, replace one of those outings. Combining old streets, beach, countryside and an archaeological site in one day makes four worthwhile experiences compete for your attention.','Dedica otro día a Tra Que y, si acompaña el tiempo, otro a An Bang. Si prefieres My Son, sustituye una salida. Juntar centro, playa, campo y arqueología en una jornada hace competir cuatro experiencias que merecen atención propia.')),
 s('ulasim',l('Da Nang’dan Hoi An’a: son bağlantıyı unutmayın','From Da Nang: plan the final connection','Desde Da Nang: cuenta el último tramo'),
 l('Hoi An’a uçak veya trenle giderken çoğunlukla Da Nang üzerinden son kara bağlantısı gerekir. Biletin varış şehrini otelinizin şehriyle aynı sanmayın. Havalimanı veya istasyondan transferi, otelin eski şehirde araç girişinin mümkün olduğu noktaya kadar netleştirin; gece varışında açık bir karşılama planı rahatlatır.','Flights and rail journeys to a Hoi An stay commonly require a final road transfer from Da Nang. Do not confuse the city on your ticket with the town where you sleep. Clarify the hotel’s vehicle-access point, especially in the old centre, and arrange a clear reception plan for late arrivals.','Llegar en avión o tren suele exigir un último traslado desde Da Nang. No confundas la ciudad del billete con la del hotel. Aclara el punto accesible en coche del casco antiguo y cómo te recibirán si llegas tarde.'),
 l('Eski şehirde yürüyüş, çevrede uygun yollarda bisiklet düşünülebilir; bisikletin olması bütün güzergâhın sakin olduğu anlamına gelmez. Gece aydınlatması, yağmur ve ana yol geçişlerini değerlendirin. Terziye, plaja veya akşam yemeğine giderken aynı gün üç kez uzun transfer yapmamak için durakları bölge bölge birleştirin.','Walking suits the old centre, while selected surrounding roads may suit cycling. Having a bicycle does not make every route quiet: consider lighting, rain and major-road crossings. Group tailoring appointments, beach time and dinners geographically so you do not spend the day making repeated long transfers.','El centro se disfruta a pie; algunas rutas exteriores pueden hacerse en bici. Valora iluminación, lluvia y cruces: no todas las carreteras son tranquilas. Agrupa sastrería, playa y cenas por zonas para evitar traslados repetidos.')),
 s('mahalle-yasami',l('Fenerlerin ötesinde: bir ev, bir bahçe, bir prova','Beyond lanterns: a house, a garden, a fitting','Más allá de los farolillos: casas, huertos y pruebas'),
 l('Eski ticaret evlerine ve toplantı salonlarına girerken cephe ile içerideki yaşam izlerini birlikte okuyun. Çok sayıda benzer yapı yerine birini dikkatle gezmek daha kalıcı olabilir. Nehir kıyısındaki fotoğraf molasının ardından bir ara sokağa dönüp yemek veya kahve için oturun; turistik görünmesi bir mahallenin gündelik hayatını yok etmez.','Read historic trading houses and assembly halls through their interiors as well as their facades. One attentive visit can last longer in memory than several hurried ones. After a riverside photograph, turn into a side street for a meal or coffee; popularity does not erase everyday neighbourhood life.','Mira interiores además de fachadas en casas comerciales y salas de asamblea. Una visita atenta puede durar más en la memoria que varias rápidas. Después de la foto del río, entra en otra calle para comer o tomar café: el turismo no borra toda vida cotidiana.'),
 l('Terzi işi düşünüyorsanız ilk gün kumaş ve model konuşup prova için ayrı zaman ayırın. Teslimi ayrılış saatinizin hemen önüne bırakmayın. Dikiş, astar ve hareket rahatlığını deneyerek değerlendirin; “bir gecede hazır” sözü tek başına iyi oturan bir kıyafet vaat etmez. Buradan götürdüğünüz güzel şey bir eşya da olabilir, sabırlı bir süreç de.','For tailoring, discuss fabric and design early and reserve separate fitting time. Avoid collecting a garment immediately before departure. Try movement, stitching and lining rather than relying on a promise of overnight completion. What you take home can be an object, but also the pleasure of a patient process.','Si quieres ropa a medida, habla de tejido y diseño al principio y deja tiempo para pruebas. No recojas justo antes de marcharte. Comprueba movimiento, costuras y forro: estar listo rápido no asegura buen ajuste. También puede quedar el recuerdo de un proceso cuidado.')),
 s('konaklama',l('Eski şehir mi, Cam Chau mu, An Bang mı?','Old Town, Cam Chau or An Bang?','¿Centro antiguo, Cam Chau o An Bang?'),
 l('Eski şehir çevresi akşam yürüyüşüne yakın olmak isteyenler için; Cam Chau, merkez ile kırsal çevre arasında bir konum arayanlar için; An Bang ise kıyı molalarını önceleyenler için düşünülebilir. Haritada suya yakın görünen otelin nehir mi deniz mi gördüğünü ve gerçek plaj girişini ayrıca kontrol edin.','The old-centre area suits evening walks, Cam Chau can work for a position between town and countryside, and An Bang prioritises coastal time. A hotel near water may overlook a river rather than the sea: check actual beach access as well as the photograph.','El centro facilita paseos nocturnos; Cam Chau puede equilibrar ciudad y campo; An Bang prioriza la costa. Estar junto al agua no significa estar junto al mar: comprueba si es río y dónde está el acceso real a la playa.'),
 l('Plajda kalıp her akşam eski şehre dönmek veya merkezde kalıp her sabah denize gitmek mümkündür; ikisinin günlük maliyeti aynı olmayabilir. Kısa gezide iki otel yerine bir üs seçmek daha rahat. Dinlenmek istediğiniz saatle görmek istediğiniz akşamı birlikte düşünün, konaklamayı yalnız en güzel fotoğrafa göre seçmeyin.','Sleeping by the beach and dining in town, or staying centrally and visiting the coast, are both possible but bring different daily journeys. One base often works better for a short trip. Match accommodation to the hours you want to rest and the evenings you want to enjoy, not only the prettiest photograph.','Dormir en la playa y cenar en el centro, o al revés, implica trayectos distintos. Una sola base suele funcionar mejor en viajes breves. Elige según descansos y tardes que quieres disfrutar, además de la foto más bonita.')),
 s('yeme-icme',l('Cao lau’dan uzun bir öğle yemeğine','From cao lau to an unhurried lunch','Del cao lau a una comida sin prisas'),
 l('Cao lau, Hoi An mutfağına iyi bir giriş; eriştenin dokusunu, otları ve üst malzemeleri ayrı ayrı fark ederek tadın. White rose olarak anılan küçük hamur işleri farklı bir öğüne bırakılabilir. İlk masada her şeyi denemek yerine birkaç gün içinde bir yemek alışkanlığı oluşturmak şehri daha yakın hissettirir.','Cao lau makes a good introduction: notice the noodle texture, herbs and toppings separately. Save the small dumplings known as white rose for another meal. Rather than ordering everything at the first table, let a few days develop into a gentle food routine that makes the town feel familiar.','Cao lau permite fijarse en textura de fideos, hierbas y acompañamientos. Deja los pequeños dumplings llamados white rose para otra comida. Crear una rutina durante varios días puede acercarte más a la ciudad que pedirlo todo en la primera mesa.'),
 l('Sebzeli tabakta bile et suyu, balık sosu veya hayvansal dolgu olabilir. Vegan tercihinizi içerikleri sayarak belirtin. Yemek atölyesi seçerken pazar ziyareti, hazırlama ve gerçekten pişirmeye ayıracağınız süreyi sorun; iyi bir deneyim, yalnız hazır bir tabağın yanında fotoğraf çekmekten fazlasını bırakır.','Vegetable dishes may still contain stock, fish sauce or animal-based fillings; describe vegan needs explicitly. For a cooking class, ask how much time goes to the market, preparation and actual cooking. A useful experience should leave more than a photograph beside a finished plate.','Un plato de verduras puede llevar caldo, salsa de pescado o rellenos animales. Explica ingredientes que evitas. En un taller pregunta por tiempo de mercado, preparación y cocina real; debería dejar algo más que una foto junto a un plato acabado.')),
 s('mevsim-butce',l('Fenerli akşamı ve yağmurlu günü birlikte düşünün','Plan for rain as well as lantern-lit evenings','Cuenta con lluvia además de farolillos'),
 l('Mart–mayıs yürüyüş ve açık hava için düşünülebilir; sıcak aylarda öğle molası önemli. Yağışlı dönemlerde taşkın ve fırtına kıyı ile eski şehir programını etkileyebilir. Otelin değişiklik koşullarını ve güncel yerel uyarıları kontrol edin; plaj beklentisini ülkenin başka bölgesindeki güneşli fotoğrafla kurmayın.','March to May can suit outdoor days; hotter months call for midday breaks. Rainy periods, floods or storms can affect both the old town and coast. Check accommodation flexibility and current local guidance; a sunny image from another Vietnamese region does not describe conditions here.','Marzo–mayo puede favorecer exteriores; con calor conviene parar al mediodía. Lluvias, inundaciones o tormentas pueden alterar centro y costa. Comprueba flexibilidad del hotel y avisos locales: una foto soleada de otra región no describe Hoi An.'),
 l('Eski şehirde ziyaret bileti, tekne, terzi işi ve yemek atölyesini ayrı kalemler sayın. Biletin hangi yapı ziyaretlerini kapsadığını okuyun; köprüden geçmek ile bütün tarihî evlere girmek aynı şey değildir. Alışveriş bütçesini gezi bütçesine fark etmeden eklememek için ilk gün kendinize bir sınır belirleyin.','Treat heritage access, boats, tailoring and cooking classes as separate costs. Read which building visits a ticket includes; crossing a bridge is not the same as entering every historic house. Set a shopping allowance early so purchases do not quietly consume the rest of the holiday budget.','Separa acceso patrimonial, barco, ropa a medida y talleres. Lee qué edificios incluye el billete: cruzar un puente no equivale a entrar en todas las casas. Fija presupuesto de compras para que no absorban sin darte cuenta el resto del viaje.')),
 ],
 sights:[
 p(l('Eski Şehir ve Japon Köprüsü','Ancient Town and Japanese Bridge','Casco antiguo y Puente Japonés'),l('Nehir çevresi','Riverside centre','Centro junto al río'),l('Köprüyü bütün geziyi bitiren tek kareye çevirmeyin. Yakındaki eski evler ve toplantı salonlarından birini seçip liman geçmişini daha yakından okuyun; erişim ve bilet koşullarını yerinde kontrol edin.','Make the bridge a starting point rather than the single photograph that completes your visit. Choose a nearby house or assembly hall to explore the trading history, checking current entry conditions.','Haz del puente un comienzo. Una casa o sala de asamblea cercana permite entender el pasado comercial; consulta condiciones actuales de entrada.'),l('Eski limanın farklı kültür izlerini görmek.','Read the old port’s cultural layers.','Leer las huellas culturales del puerto.'),l('Sabah ve akşam ayrı deneyimlerdir.','Morning and evening offer different experiences.','Mañana y tarde ofrecen experiencias distintas.')),
 p(l('Tra Que çevresi','Tra Que area','Entorno de Tra Que'),l('Bahçe ve kırsal çevre','Gardens and countryside','Huertos y campo'),l('Üretim yapılan bahçeleri serbest fotoğraf alanı sanmayın. Ziyaretli bir deneyimde izin ve rehberlik düzenini öğrenin; tadım veya pişirme varsa içeriğini baştan sorun.','These are working gardens, not unrestricted photo sets. Clarify permission and guiding arrangements for visits, including any tasting or cooking activity.','Son huertos de trabajo, no decorados de acceso libre. Consulta permisos y organización de visitas, incluidas degustaciones o cocina.'),l('Sofra ile üretim arasındaki bağı görmek.','Connect meals with their growing landscape.','Conectar la mesa con su paisaje agrícola.'),l('Ekili alanlara izinsiz girmeyin.','Do not enter planted areas without permission.','No entres en cultivos sin permiso.')),
 p(l('An Bang Plajı','An Bang Beach','Playa An Bang'),l('Kıyı','Coast','Costa'),l('Bir öğleden sonrayı deniz koşulları uygunsa burada yavaşlatın. Şezlong ve tüketim düzenini oturmadan sorun; gölge, geri dönüş ve hava payını günün parçası yapın.','Slow down for an afternoon when sea conditions permit. Clarify lounger and spending arrangements before settling in, leaving time for shade, weather and the return journey.','Baja el ritmo una tarde si el mar lo permite. Pregunta por tumbonas y consumo, y deja margen para sombra, tiempo y regreso.'),l('Şehir gezisine ayrı bir kıyı günü eklemek.','Give coastal time its own place in the trip.','Dar espacio propio a la costa.'),l('Yüzme uyarılarını izleyin.','Follow swimming guidance.','Respeta avisos de baño.')),
 ],
 itinerary:[{title:l('1. Gün — Eski liman','Day 1 — Old port','Día 1 — Puerto antiguo'),morning:l('Eski sokaklar ve bir tarihî yapı','Old streets and one heritage building','Calles antiguas y un edificio histórico'),afternoon:l('Yemek, dinlenme ve varsa ilk prova','Lunch, rest and an optional first fitting','Comida, descanso y primera prueba opcional'),evening:l('Nehir kıyısında yürüyüş','Riverside walk','Paseo junto al río')},{title:l('2. Gün — Bahçe ve mahalle','Day 2 — Gardens and neighbourhoods','Día 2 — Huertos y barrios'),morning:l('Tra Que çevresi','Tra Que area','Entorno de Tra Que'),afternoon:l('Serbest yemek ve alışveriş zamanı','Unhurried food and shopping time','Tiempo tranquilo para comer y comprar'),evening:l('Eski şehre farklı bir sokaktan dönüş','Return through another old-town street','Regreso al centro por otra calle')},{title:l('3. Gün — Kıyı veya My Son','Day 3 — Coast or My Son','Día 3 — Costa o My Son'),morning:l('An Bang; arkeoloji önceliğinde My Son','An Bang, or My Son if prioritising archaeology','An Bang o My Son si priorizas arqueología'),afternoon:l('Dinlenme ve son prova','Rest and final fitting','Descanso y última prueba'),evening:l('Ayrılış öncesi sakin yemek','A relaxed meal before departure','Cena tranquila antes de partir')}],
 faqs:[{q:l('Hoi An’da kaç gün kalmalı?','How long should you stay in Hoi An?','¿Cuántos días quedarse en Hoi An?'),a:l('Eski şehir, bahçe ve kıyı için üç tam gün iyi bir başlangıç. Terzi provaları veya My Son eklenirse daha fazla zaman bırakın; her şeyi bir geceye sıkıştırmayın.','Three full days allow the old town, gardens and coast. Leave more time for fittings or My Son rather than compressing everything into one night.','Tres días permiten centro, huertos y costa. Deja más tiempo para pruebas de ropa o My Son en vez de concentrarlo en una noche.')},{q:l('Hoi An mı Da Nang mı?','Should you stay in Hoi An or Da Nang?','¿Alojarse en Hoi An o Da Nang?'),a:l('Eski sokaklarda akşam geçirmek öncelikse Hoi An; şehir, ulaşım ve plajı birlikte isteyenler için Da Nang düşünülebilir. Aynı tatil deneyimi olmadıkları için gecelerinizi önceliğinize göre ayırın.','Choose Hoi An for evenings in old streets, or consider Da Nang for city life, transport and beaches together. Allocate nights around those different priorities.','Hoi An favorece tardes entre calles antiguas; Da Nang combina vida urbana, transporte y playa. Distribuye noches según esas prioridades distintas.')}],
 sources:[source(tourism,'https://vietnam.travel/places-to-go/central-vietnam/hoi-an'),source(l('UNESCO — Hoi An','UNESCO — Hoi An','UNESCO — Hoi An'),'https://whc.unesco.org/en/list/948/'),source(l('Vietnam Tourism — Hoi An alışverişi','Vietnam Tourism — Hoi An shopping','Vietnam Tourism — compras en Hoi An'),'https://vietnam.travel/node/116'),source(l('UNESCO — My Son','UNESCO — My Son','UNESCO — My Son'),'https://whc.unesco.org/en/list/949/')],
};

export default city;
