import {l,section as s,sight as p,source,tourism} from './shared.mjs';
const city = {
 name:l('Hue','Hue','Hue'),key:'hue',
 title:l('Hue Gezi Rehberi: Saraylar, Yerel Sofralar ve 3 Gün','Hue Travel Guide: Citadel, Royal Tombs and Local Food','Hue: ciudadela, tumbas imperiales y ruta de 3 días'),
 meta:l('Hue gezi rehberi: İmparatorluk Kalesi, Minh Mang, Tu Duc, Thien Mu ve Dong Ba; yerel yemekler, nehir çevresinde konaklama ve üç günlük sakin rota.','Plan Hue around the Imperial Citadel, Minh Mang, Tu Duc and Thien Mu: local dishes, riverside neighbourhoods and a relaxed three-day itinerary.','Organiza Hue entre la ciudadela, Minh Mang, Tu Duc y Thien Mu: platos locales, zonas donde dormir y una ruta de tres días sin visitas apresuradas.'),
 card:l('Saray avluları, Parfüm Nehri ve küçük tabaklardan kurulan sofralarıyla daha yavaş bir Vietnam günü.','Palace courtyards, the Perfume River and meals built from small dishes make a slower Vietnamese chapter.','Patios de palacio, el río Perfume y mesas de pequeños platos para otra forma de viajar por Vietnam.'),
 lede:l('Hue’de günün en güzel anı bazen büyük bir kapıdan geçmek değil, gezinin ortasında oturup önünüze gelen küçük tabakları paylaşmak. Saraylar ve mezarlar şehrin hikâyesini açıyor; nehir kıyısı ile günlük sofralar o hikâyenin içinde kalmanıza yardım ediyor. Buraya yalnız bir transfer arası ayırmayın.','In Hue, the best moment may come after the grand gateway, when you sit down and share a table of small dishes. Palaces and royal tombs open the city’s story; the river and everyday meals let you linger inside it. Give the city more than the gap between two transfers.','En Hue, el mejor momento puede llegar después de la gran puerta, al sentarse a compartir pequeños platos. Palacios y tumbas abren la historia; el río y las comidas cotidianas invitan a quedarse en ella. La ciudad merece más que unas horas entre traslados.'),
 facts:[l('3 tam gün','3 full days','3 días completos'),l('Şubat–nisan; yağışa göre esnek plan','February–April; plan around rain','Febrero–abril; flexibilidad con la lluvia'),l('Merkezde yürüyüş, mezarlara araç','Central walks, vehicles for the tombs','Paseos céntricos y vehículo para tumbas')],
 sections:[
 s('sehri-anlamak',l('Hue’yi kale ve mezar listesinden biraz çıkarın','Give Hue room beyond its monuments','Hue más allá de una lista de monumentos'),
 l('İlk gün İmparatorluk Kalesi’ne geniş bir zaman bırakın. Sabah saray alanı, öğlen yemek ve dinlenme, akşam nehir kıyısı yeterli bir gün olabilir. Her boş saate yeni bir tapınak eklemek yerine, gördüğünüz mekânın kafanızda yerleşmesine izin verin; Hue’de yavaşlık programın eksiği değil, güzel tarafı.','Give the Imperial Citadel a generous first morning, followed by lunch, rest and an evening beside the river. That can be a complete day. Allow what you have seen to settle instead of filling every interval with another monument. A slower pace is part of Hue’s appeal, not a failure of planning.','Reserva una mañana amplia para la ciudadela y sigue con comida, descanso y río al atardecer. Eso puede llenar bien un día. Deja reposar lo visto en vez de añadir un monumento en cada hueco: la calma forma parte del atractivo de Hue.'),
 l('Kraliyet mezarları aynı yapının farklı kopyaları değil. İki mezarı karşılaştırarak görmek, hepsini hızla dolaşmaktan daha anlamlı olabilir. Minh Mang’ın düzeniyle Tu Duc’un göl ve pavyonlarını farklı ziyaretler gibi düşünün. Üçüncü bir durak eklemeden önce sıcak, ulaşım ve gerçekten okumaya ayıracağınız süreyi hesaba katın.','The royal tombs are not interchangeable copies. Comparing two thoughtfully can be more rewarding than racing through all of them. Approach Minh Mang’s formal layout and Tu Duc’s lakes and pavilions as different experiences. Before adding a third, consider heat, transport and how much interpretation you actually want to read.','Las tumbas no son copias intercambiables. Comparar dos con atención puede aportar más que recorrerlas todas deprisa. Mira la organización de Minh Mang y los lagos y pabellones de Tu Duc como experiencias distintas. Valora calor y trayectos antes de añadir otra.')),
 s('ulasim',l('Hue’ye varış ve Hai Van üzerinden devam','Arriving in Hue and continuing via Hai Van','Llegar a Hue y continuar por Hai Van'),
 l('Uçak biletinde Phu Bai (HUI), tren biletinde Hue istasyonunu kontrol edin. İkisi otelinize aynı mesafede değildir. Da Nang’dan geliyorsanız tren veya kara ulaşımını varış noktasına kadar karşılaştırın; manzaralı bir geçişi seçerken bavul ve son otel bağlantısını da düşünün.','For arrivals, distinguish Phu Bai airport (HUI) from Hue railway station. Compare transfers to your actual hotel, not simply ticket prices. Coming from Da Nang, choose rail or road with luggage and the final connection in mind; a scenic journey still needs practical arrangements at each end.','Distingue el aeropuerto Phu Bai (HUI) de la estación de Hue. Compara el traslado hasta el hotel, además del billete. Desde Da Nang, tren o carretera requieren valorar equipaje y conexión final: un trayecto panorámico también necesita buena logística.'),
 l('Hai Van geçidi üzerinden özel araçla gidecekseniz eski dağ yolunun mu yoksa tünelin mi kullanılacağını sorun. Bunlar aynı manzara deneyimini sunmaz. Motor kullanmayı burada öğrenmeye çalışmayın; fotoğraf durağı, hava ve yol koşullarını değerlendiren bir sürücüyle gitmek geziyi daha rahat kılar.','If booking a car via Hai Van, clarify whether it uses the old pass road or the tunnel; they offer different journeys. Do not make this your first experiment with riding a motorbike. A driver who considers weather, road conditions and sensible photo stops can make the outing more comfortable.','Si reservas coche por Hai Van, aclara si irá por el puerto antiguo o el túnel: son recorridos distintos. No es lugar para aprender a conducir moto. Un conductor que valore tiempo, carretera y paradas puede hacer el viaje mucho más cómodo.')),
 s('mahalle-yasami',l('Nehir kıyısı ile Dong Ba arasında bir öğleden sonra','An afternoon between the river and Dong Ba','Una tarde entre el río y Dong Ba'),
 l('Parfüm Nehri’ne ayırdığınız yürüyüşü “tekne turu almak zorundayım” düşüncesine bağlamayın. Kıyıda bir bölüm seçip dinlenmek de şehri yaşamanın bir yolu. Tekneye binecekseniz turun gerçek duraklarını öğrenin; nehirde gezinme, pagoda ziyareti ve müzikli akşam programı farklı deneyimlerdir.','A river walk does not oblige you to buy a boat tour. Choose a stretch of bank and enjoy sitting there. If you do take a boat, clarify the actual itinerary: a simple cruise, a pagoda visit and an evening music programme are different experiences, rather than one standard river product.','Pasear junto al río no obliga a contratar barco. También puedes elegir una orilla y descansar. Si navegas, aclara el programa: crucero, visita a una pagoda y música por la noche son experiencias diferentes.'),
 l('Dong Ba’yı yalnız hediyelik eşya pazarı gibi okumayın; gündelik alışveriş ile yemek hazırlığı burada yan yana. Dar geçişlerde satıcıların işini bölmeden ilerleyin, siparişten önce porsiyonu konuşun. İyi bir pazar molası, bütün tezgâhları fotoğrafladığınız değil, bir tabakta yeni bir şey fark ettiğiniz moladır.','At Dong Ba, everyday shopping and food preparation sit alongside visitor browsing. Keep working passages clear and clarify portions before ordering. A worthwhile market stop is not necessarily the one with the most photographs; it may be the one in which you notice something new on a plate.','En Dong Ba conviven compras cotidianas y preparación de comida. Deja libres los pasos de trabajo y pregunta por porciones antes de pedir. Una buena pausa no siempre produce muchas fotos: a veces permite descubrir algo nuevo en un plato.')),
 s('konaklama',l('Hue’de nerede kalınır? Nehrin iki yakasını düşünün','Where to stay: consider both riverbanks','Dónde dormir: piensa en ambas orillas'),
 l('Güney yakada merkez restoranlarına ve akşam yürüyüşüne yakın olmak ilk ziyaret için kolaylık sağlayabilir. Kale önceliğinizse kuzey yakanın konumunu ayrıca inceleyin. İlanın “river view” demesi yalnız oda manzarasını anlatır; karşıya geçiş, giriş kapısı ve gece sesini de haritada ve yorumlarda kontrol edin.','The southern central area can be convenient for dining and evening walks; examine the northern bank separately if the citadel is your main focus. A river-view label describes a view, not the whole stay. Compare bridge crossings, the entrance you will use and recent comments on night noise.','La zona central al sur puede facilitar cenas y paseos; mira la orilla norte si priorizas la ciudadela. “Vistas al río” describe una vista, no toda la estancia. Comprueba puentes, acceso real y comentarios sobre ruido.'),
 l('Mezarlar için merkezdeki otelden ayrı bir yarım gün planlayın; “yakın çevre” ifadesi hepsinin yürüme mesafesinde olduğu anlamına gelmez. İki veya üç gecelik gezide aynı odada kalıp dönüşte dinlenmek, her gün yeni bir konaklamaya taşınmaktan daha iyi bir ritim oluşturabilir.','Plan the tomb circuit as a separate outing from a central hotel: “nearby” does not mean everything is walkable. For two or three nights, returning to the same room for a rest can give the trip a better rhythm than moving accommodation each day.','Las tumbas requieren una salida propia desde el hotel: “alrededores” no significa distancia a pie. En dos o tres noches, regresar a la misma habitación para descansar suele dar mejor ritmo que cambiar de alojamiento cada día.')),
 s('yeme-icme',l('Küçük tabaklarla Hue’yi tanımak','Meet Hue through smaller dishes','Conocer Hue con pequeños platos'),
 l('Bun bo Hue şehrin bilinen güçlü başlangıcı; banh beo, banh nam ve banh loc ise farklı dokuları küçük porsiyonlarla keşfetmenin yolu. İsimleri ezberlemekten çok pişirme ve iç malzemesini sorarak ilerleyin. Birlikte geziyorsanız birkaç tabağı paylaşmak hem karşılaştırma hem de uzun bir masa sohbeti için güzel fırsat.','Bun bo Hue offers a substantial introduction, while banh beo, banh nam and banh loc let you explore different textures in smaller portions. Ask about preparation and fillings rather than memorising a list. Sharing several dishes makes room both for comparison and for a longer conversation at the table.','Bun bo Hue es una introducción contundente; banh beo, banh nam y banh loc permiten explorar texturas en porciones pequeñas. Pregunta por preparación y relleno en vez de memorizar nombres. Compartir platos ayuda a comparar y alarga la conversación.'),
 l('Etli erişteler ile karidesli küçük hamur işleri her beslenme tercihine uygun değildir. Vegan siparişte et suyu, balık sosu ve karides ezmesini ayrı ayrı sorun; helal tercihte et kaynağını doğrudan işletmeyle doğrulayın. Acıyı masada eklemek mümkünse önce sade tadı tanıyın; Hue sofrasının bütün hikâyesi acılık değil.','Meat noodles and shrimp-filled dishes do not suit every diet. For vegan orders, ask separately about stock, fish sauce and shrimp paste; confirm meat sourcing directly for halal preferences. If chilli can be added at the table, taste the dish first. Hue’s cuisine has more to say than heat alone.','Fideos con carne y rellenos de gambas no sirven para todas las dietas. Para veganismo consulta caldo, salsa de pescado y pasta de gambas; para halal verifica la carne. Si puedes añadir picante aparte, prueba antes el plato: Hue ofrece más que intensidad.')),
 s('mevsim-butce',l('Saray gününü hava durumuyla birlikte kurun','Plan the palace day with the weather','Organiza los palacios según el tiempo'),
 l('İlkbahar Hue için düşünülebilir; sıcak dönemlerde kale yürüyüşünü erken saate bırakın. Yılın yağışlı bölümünde sel ve ulaşım koşulları programı değiştirebilir. Açık alanlar arasında bir yemek veya kapalı mekân molası bırakmak, yalnız şemsiye taşıyıp aynı yoğun programı sürdürmekten daha iyi çalışır.','Spring can suit Hue; in hotter months, visit the citadel early. Heavy-rain periods may affect access and transport. A meal or indoor break between exposed visits works better than carrying an umbrella while insisting on an unchanged, crowded programme.','La primavera puede ser buena opción; con calor, visita la ciudadela temprano. Las lluvias intensas pueden alterar accesos y transporte. Una comida o pausa interior entre visitas funciona mejor que mantener un programa saturado bajo el paraguas.'),
 l('Anıt girişlerini, mezar transferini ve varsa rehber ücretini ayrı değerlendirin. Kombine biletin hangi yerlere ve hangi süreye karşılık geldiğini satın almadan okuyun. Ucuz görünen bir araç teklifini yalnız fiyatla karşılaştırmayın; bekleme, dönüş ve seçtiğiniz mezarları gerçekten kapsaması günün değerini belirler.','Separate admission, tomb transfers and any guiding fee. Read the sites and validity covered by a combined ticket before buying. Compare a vehicle quote by waiting time, return journey and the actual tombs included, not only the lowest headline price.','Separa entradas, transporte a tumbas y guía. Lee lugares y validez de los billetes combinados. Compara vehículos según espera, regreso y tumbas incluidas; no solo por el precio anunciado.')),
 ],
 sights:[
 p(l('İmparatorluk Kalesi','Imperial Citadel','Ciudadela Imperial'),l('Kuzey yaka','Northern bank','Orilla norte'),l('Geniş alanı tek bir saray salonu gibi düşünmeyin. Haritadan birkaç ana bölüm seçip avlular arasında mola verin; korunmuş, onarılmış ve kaybolmuş yapıları açıklamalarla ayırt etmek ziyareti zenginleştirir.','Choose several main areas rather than treating the citadel as a single palace room. Rest between courtyards and use interpretation to distinguish surviving, restored and lost structures.','Elige varios espacios principales y descansa entre patios. Las explicaciones ayudan a distinguir edificios conservados, reconstruidos y desaparecidos.'),l('Kraliyet mirasını bütün bir alan olarak görmek.','Read the royal legacy across a whole site.','Leer el legado imperial en su conjunto.'),l('Girişten önce alan haritasına bakın.','Look at the site map before starting.','Mira el plano antes de empezar.')),
 p(l('Minh Mang ve Tu Duc mezarları','Minh Mang and Tu Duc tombs','Tumbas de Minh Mang y Tu Duc'),l('Şehir dışı mezar çevresi','Outlying tomb circuit','Recorrido exterior de tumbas'),l('İki ayrı alanı aynı mezarın parçaları sanmayın. Düzen, su ve pavyonların ilişkisine bakarak gezin; geçiş ve dinlenme için zaman bırakın. Aralarında ulaşım gerekir.','These are separate sites. Compare how layout, water and pavilions shape each one, allowing time for transport and rest between them.','Son recintos distintos. Compara orden, agua y pabellones dejando margen de traslado y descanso entre ambos.'),l('İki farklı mekân yaklaşımını karşılaştırmak.','Compare two different approaches to space.','Comparar dos formas de concebir el espacio.'),l('İki girişi ve transferi ayrı planlayın.','Plan separate access and transfers.','Planifica entradas y traslados separados.')),
 p(l('Thien Mu Pagodası','Thien Mu Pagoda','Pagoda Thien Mu'),l('Nehir kıyısı','Riverside','Junto al río'),l('Kule manzarasının ardından alanı sakin gezmeye zaman verin. Burası yalnız fotoğraf noktası değil, dini bir mekân; kıyafet ve ziyaretçi yönlendirmelerine uyun. Tekneyle gelirseniz dönüş bağlantısını baştan netleştirin.','Leave time beyond the tower view for a quiet visit. This is a religious site as well as an attraction; follow dress and visitor guidance. If arriving by boat, clarify the return connection.','Dedica tiempo además de la vista de la torre. Es un lugar religioso: respeta vestimenta e indicaciones. Si llegas en barco, aclara el regreso.'),l('Nehirle dini yaşamın ilişkisini görmek.','See the river’s connection with religious life.','Ver la relación entre río y vida religiosa.'),l('İbadet alanlarında sessiz kalın.','Keep quiet in worship areas.','Mantén silencio en zonas de culto.')),
 ],
 itinerary:[{title:l('1. Gün — Kale ve nehir','Day 1 — Citadel and river','Día 1 — Ciudadela y río'),morning:l('İmparatorluk Kalesi','Imperial Citadel','Ciudadela Imperial'),afternoon:l('Yemek ve dinlenme','Lunch and rest','Comida y descanso'),evening:l('Nehir kıyısında yürüyüş','Riverside walk','Paseo junto al río')},{title:l('2. Gün — İki mezar','Day 2 — Two royal tombs','Día 2 — Dos tumbas'),morning:l('Minh Mang','Minh Mang','Minh Mang'),afternoon:l('Tu Duc ve merkeze dönüş','Tu Duc and return to town','Tu Duc y regreso'),evening:l('Küçük tabaklarla akşam yemeği','Dinner with smaller dishes','Cena de pequeños platos')},{title:l('3. Gün — Pagoda ve pazar','Day 3 — Pagoda and market','Día 3 — Pagoda y mercado'),morning:l('Thien Mu','Thien Mu','Thien Mu'),afternoon:l('Dong Ba çevresi','Dong Ba area','Entorno de Dong Ba'),evening:l('Serbest nehir zamanı','Unhurried time by the river','Tiempo libre junto al río')}],
 faqs:[{q:l('Hue için kaç gün gerekir?','How long should you stay in Hue?','¿Cuántos días hacen falta en Hue?'),a:l('Kale, iki mezar ve mahalle molaları için üç tam gün rahat bir başlangıç. Bir gününüz varsa bütün kraliyet alanlarını bitirmeye çalışmadan kale ve yakın çevreyi seçin.','Three full days allow the citadel, two tombs and neighbourhood breaks. With only one day, focus on the citadel and nearby areas rather than every royal site.','Tres días permiten ciudadela, dos tumbas y pausas. Con un solo día, elige la ciudadela y alrededores sin intentar abarcar todos los recintos.')},{q:l('Hue ile Hoi An aynı yerde mi?','Are Hue and Hoi An in the same place?','¿Hue y Hoi An están en el mismo lugar?'),a:l('Hayır; farklı şehirler ve ayrı konaklama deneyimleri. Aradaki yolculuğu gezi gününe dahil edin; Da Nang üzerinden bağlantıyı ve gerçek varış saatinizi kontrol edin.','No: they are different towns with different stays. Allow a travel day and check your route via Da Nang and actual arrival time.','No: son ciudades y estancias distintas. Reserva tiempo de viaje y comprueba ruta por Da Nang y hora real de llegada.')}],
 sources:[source(tourism,'https://vietnam.travel/places-to-go/central-vietnam/hue'),source(l('UNESCO — Hue anıtları','UNESCO — Hue monuments','UNESCO — monumentos de Hue'),'https://whc.unesco.org/en/list/678/'),source(l('Vietnam Tourism — Hue sofrası','Vietnam Tourism — Hue food','Vietnam Tourism — gastronomía de Hue'),'https://vietnam.travel/things-to-do/how-eat-local-hue'),source(l('Vietnam Tourism — kraliyet mezarları','Vietnam Tourism — royal tombs','Vietnam Tourism — tumbas imperiales'),'https://vietnam.travel/things-to-do/an-inside-guide-hue-tombs')],
};

export default city;
