import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Tiran", countryCode: "AL", focus: "meydanlar, yakın tarih ve canlı mahalleler", lede: "Osmanlı izlerini İtalyan planlaması, komünizm dönemi yapıları, yeni kamusal alanlar ve güçlü kafe kültürüyle buluşturan hareketli başkent.", days: "3–4 gün", arrival: "TIA · Tiran bölgesel otobüs terminalleri", local: "Otobüs, taksi, bisiklet ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Tiran tek bir anıtsal merkezden çok, Skanderbeg Meydanı, Blloku, Pazari i Ri ve Büyük Park arasında değişen gündelik ritmiyle anlaşılır. Yakın tarih mekânlarını renkli cephelerin arkasındaki bağlamla okumak gerekir.",
    sights: [["Skanderbeg Meydanı", "Et'hem Bey Camii, saat kulesi ve meydan kurumlarını bir arada görün; müze/restorasyon saatlerini aynı gün doğrulayın."], ["Bunk'Art ve House of Leaves", "Gözetim ile diktatörlük tarihini en az bir müzede derinleştirin; sığınak atmosferini eğlence dekoruna çevirmeyin."], ["Tiran Piramidi ve Dajti", "Piramidi çağdaş kamusal alan olarak görün; Dajti teleferiğinde hava, bakım ve son inişi kontrol edin."]],
    areas: [["Blloku ve merkez", "Kafe, restoran ve akşam hayatı için yürünebilir; hafta sonu gürültülü ve daha pahalı olabilir."], ["Pazari i Ri ve Büyük Park", "Pazar/yerel yemek veya göl çevresinde daha sakin yaşam için merkezin iki farklı alternatifi."]], foods: [["Byrek ve tavë kosi", "Dolgu, et ve süt içeriğini sorun; fırından sabah taze byrek ile yoğurtlu kuzu güvecini farklı öğünlerde deneyin."], ["Arnavut kahvesi ve tatlı", "Uzun kafe ritmine katılın; trileçe ve şerbetli tatlılarda porsiyonu paylaşın."]], dayTrips: [["Krujë", "Kale, müze ve eski çarşı için otobüs/transferle tam gün; yoğun trafikte dönüş payı bırakın."], ["Durrës", "Roma amfitiyatrosu ve Adriyatik için tren/otobüs; kazı erişimi ve plaj su kalitesini doğrulayın."]], caution: "Tiran trafiğinde yaya geçidinde bile araçları gözleyin; yalnız resmî uygulama/çağrı taksisi kullanın ve ücreti netleştirin. Siyasi gösteri ve kalabalıklardan uzak durun, diktatörlük hafızasında saygılı dil kullanın."
  },
  {
    city: "Berat", countryCode: "AL", focus: "UNESCO mahalleleri, kale ve Osum Vadisi", lede: "Osum'un iki yakasındaki beyaz Osmanlı evlerini yaşayan kale mahallesi, ikon sanatı, bağlar ve güneyin kanyon doğasıyla birleştiren tarih şehri.", days: "2–3 gün", arrival: "Tiran/Durrës'ten otobüs veya araç", local: "Yürüyüş, taksi ve bölgesel otobüs", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Berat'ın Mangalem manzarası başlangıçtır; Gorica, yaşayan Kala mahallesi, Onufri koleksiyonu ve nehir akşamı kenti açık hava dekorundan çıkarır.",
    sights: [["Berat Kalesi", "Yaşayan sur içini kiliseler, cami kalıntıları ve seyirlerle gezin; dik taş yola su ve sağlam ayakkabıyla çıkın."], ["Onufri Müzesi", "İkonları Ortodoks mirası ve sanat tekniği bağlamında görün; kilise/fotoğraf kuralına uyun."], ["Mangalem ve Gorica", "İki mahalleyi köprüyle bağlayıp konut mahremiyetine saygı gösterin; drone ve özel avlu için izin alın."]],
    areas: [["Mangalem", "Kale ve nehir manzarasına yakın atmosferik üs; taş basamak ve turistik yoğunluk vardır."], ["Gorica veya yeni merkez", "Sakin konaklama ya da otobüs/restoran kolaylığı için iki farklı yürünebilir alternatif."]], foods: [["Berat mutfağı", "Pispili, dolma ve fırın yemeklerinde et/süt içeriğini aile lokantasında sorun."], ["Roshnik şarabı ve zeytin", "Yerel üretici tadımını randevu, ölçülü tüketim ve sürücülü dönüşle planlayın."]], dayTrips: [["Osum Kanyonu", "Su seviyesi ve mevsime göre yürüyüş/rafting değişir; lisanslı operatör, kask ve can yeleği kullanın."], ["Roshnik", "Bağ, köy ve Tomorr manzarası için araç/yerel transfer; üretici ziyaretini önceden ayarlayın."]], caution: "Kale taşları yağmurda çok kaygandır; bariyer dışına çıkmayın. Kanyon turunda düşük fiyat uğruna lisans, ekipman ve sigortadan vazgeçmeyin; yaz sıcağında yokuşları öğlene bırakmayın."
  },
  {
    city: "Gjirokastër", countryCode: "AL", focus: "taş evler, kale ve yakın tarih", lede: "Dik yamaçta arduvaz çatılı Osmanlı evlerini büyük kale, yaşayan çarşı, edebiyat ve komünizm dönemi hafızasıyla birleştiren UNESCO kenti.", days: "2–3 gün", arrival: "Tiran/Sarandë'den otobüs veya araç", local: "Yürüyüş ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Gjirokastër'in güzelliği yalnız kale panoramasında değil; Skenduli ve Zekate gibi evlerin iç düzeni, çarşı zanaatı ve 20. yüzyılın zor katmanlarında görünür.",
    sights: [["Gjirokastër Kalesi", "Müze, saat kulesi ve açık alanları gezin; festival kurulumu, sergi kapsamı ve sur güvenliğini kontrol edin."], ["Tarihî evler", "Skenduli veya Zekate evlerinden en az birini rehberli anlatımla görün; yaşayan/özel bölümlere girmeyin."], ["Soğuk Savaş Tüneli", "Yalnız resmî rehberli saatle girin; dar, serin ve basamaklı ortam için erişilebilirliği önceden sorun."]],
    areas: [["Eski çarşı", "Kale, evler ve akşam için atmosferik; dik taş sokak valiz/erişilebilirlik açısından zordur."], ["Yeni şehir", "Otobüs bağlantısı, düz zemin ve yerel fiyatlar için kısa taksi mesafeli alternatif."]], foods: [["Qifqi", "Pirinç, yumurta ve otlarla yapılan yerel köfteyi yanında mevsim yemeğiyle deneyin; alerjenleri sorun."], ["Güney Arnavutluk ev yemekleri", "Dolma, kuzu ve süt ürünlerinde içerik, porsiyon ve ev yapımı içkinin ölçüsünü netleştirin."]], dayTrips: [["Antigonea", "Arkeolojik alan için araç, güncel açılış ve sıcak/gölge planı gerekir."], ["Mavi Göz", "Kaynak alanına erken gidin; koruma bariyeri, yüzme ve servis/park kuralına uyun."]], caution: "Parlak taş sokaklar yağmurda kayar ve eğim yüksektir. Tünel/kalede kapalı alan uyarısına uyun; Mavi Göz'de suya girme yasağını aşmayın, özel evleri izinsiz fotoğraflamayın."
  },
  {
    city: "Shkodër", countryCode: "AL", focus: "Rozafa, göl kültürü ve Arnavut Alpleri kapısı", lede: "Rozafa Kalesi'nin göl ve nehir manzarasını Marubi fotoğraf mirası, bisikletli merkez ve Theth–Komani rotalarının lojistiğiyle birleştiren kuzey şehri.", days: "2–4 gün", arrival: "Tiran/Podgorica'dan otobüs", local: "Bisiklet, otobüs, taksi ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Shkodër yalnız Theth yolunda aktarma değildir; Katolik, Müslüman ve laik şehir katmanları, fotoğraf arşivi, göl kıyısı ve hareketli yaya merkezi en az iki geceyi hak eder.",
    sights: [["Rozafa Kalesi", "Surları erken saatte gezin; dik ve açık zeminde su taşıyın, uçurum kenarında bariyer dışına çıkmayın."], ["Marubi Fotoğraf Müzesi", "Arnavutluk'un toplumsal tarihini geniş arşiv üzerinden okuyun; geçici sergi ve açılış saatini kontrol edin."], ["Shkodër Gölü", "Shirokë kıyısını bisiklet/taksiyle görün; sınır, kuş alanı, yüzme ve tekne kurallarını güncel kaynaktan doğrulayın."]],
    areas: [["Rruga Kole Idromeno", "Müze, kafe ve akşam için yaya merkezli pratik üs."], ["Shirokë", "Göl manzarası ve sakinlik için araç/bisiklet gerektiren kıyı alternatifi."]], foods: [["Krap tava", "Shkodër Gölü sazanında tür, menşe, kılçık ve koruma/mevsim kuralını sorun."], ["Kuzey ev yemekleri", "Mısır ekmeği, fasulye, peynir ve et tabağında içerik/porsiyonu doğrulayın."]], dayTrips: [["Theth", "Günübirlik koşturmaktansa dağ köyünde birkaç gece kalın; yol, hava ve dönüş aracını doğrulayın."], ["Komani Gölü", "Feribot iskelesine çok erken transfer, bilet, operatör ve sonraki bağlantıyı yazılı planlayın."]], caution: "Bisiklet yolunun araçlarla kesiştiği noktalarda görünür olun. Karadağ sınırını pasaport ve güncel giriş koşulu olmadan geçmeyin; dağ/feribot bağlantısını aynı gün sıkı uçuşa bağlamayın."
  },
  {
    city: "Krujë", countryCode: "AL", focus: "Skanderbeg mirası, kale ve tarihî çarşı", lede: "Tiran ovasının üstündeki kaleyi Skanderbeg anlatısı, Bektaşi mirası, ahşap çarşı ve Sari Salltik dağ manzarasıyla birleştiren tarih kasabası.", days: "1–2 gün", arrival: "Tiran'dan Fushë-Krujë aktarmalı otobüs veya transfer", local: "Yürüyüş ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Krujë günübirlik alışveriş durağından fazlasıdır; kale içindeki kurumları, etnografya koleksiyonunu ve yaşayan inanç alanlarını sakin bir gecelemeyle daha iyi okuyabilirsiniz.",
    sights: [["Krujë Kalesi", "Skanderbeg Müzesi ile kale yerleşimini birlikte gezin; ulusal kahraman anlatısını birincil kaynak ve dönem bağlamıyla okuyun."], ["Etnografya Müzesi", "Tarihî evde gündelik yaşam ve zanaatı görün; restorasyon/açılış durumunu gitmeden doğrulayın."], ["Eski Çarşı", "El işi ile seri üretimi ayırmak için malzeme, üretici ve sabit fiyat sorun; dükkân önünü kapatmayın."]],
    areas: [["Kale ve çarşı çevresi", "Ana yerlere yürüyüş ve akşam manzarası için en atmosferik üs."], ["Yeni merkez", "Otobüs, düz zemin ve daha yerel fiyat için yokuş aşağı alternatif."]], foods: [["Krujë ev mutfağı", "Fërgesë, börek ve güveçlerde et/süt içeriğini sorun; küçük aile lokantasını tercih edin."], ["Dağ çayı ve tatlı", "Yerel ot karışımının içeriğini sorun; bal ve ceviz ürünlerinde alerjeni kontrol edin."]], dayTrips: [["Sari Salltik", "Dağ yolu, Bektaşi ziyaret alanı ve manzara için güvenilir taksi, hava ve kıyafet planı gerekir."], ["Tiran", "Başkent bağlantısını trafik payıyla kurun; uçuş gününde Krujë gezisini son saate bırakmayın."]], caution: "Tiran–Krujë trafiği öngörülemez; dönüşte geniş pay bırakın. Dinî alanda kıyafet/sessizlik kuralına uyun, dağ seyirlerinde bariyer dışına çıkmayın ve şüpheli antika satın almayın."
  },
  {
    city: "Theth", countryCode: "AL", focus: "Arnavut Alpleri, köy yaşamı ve yüksek dağ patikaları", lede: "Prokletije zirvelerinin arasında taş kuleleri, kilisesi, şelalesi ve Valbona geçidiyle Arnavut Alpleri'nin en tanınan yürüyüş üssü.", days: "3–5 gün", arrival: "Shkodër'den sezonluk minibüs/4x4", local: "Yürüyüş ve önceden ayarlı transfer", best: "Haziran–Eylül", pulse: "Yeni yol erişimi kolaylaştırsa da Theth hâlâ yüksek dağdır. Mavi Göz, Grunas ve Valbona Geçidi farklı zorlukta günlerdir; konaklama ile transferi hava yedekli kurun.",
    sights: [["Theth Kilisesi ve Kulla", "Köy merkezini yaşayan topluluk ve kan davası tarihinin bağlamıyla gezin; özel alana/fotoğrafa izin sorun."], ["Grunas Şelalesi ve kanyon", "İşaretli patikada kaygan kaya, sıcak ve su durumuna göre yürüyün; uçurum kenarına yaklaşmayın."], ["Mavi Göz", "Nderlysaj yönündeki uzun bağlantıyı taksi/yürüyüşle planlayın; buz gibi suda riskli atlayış yapmayın."]],
    areas: [["Theth merkez", "Kilise, konukevi ve ana rota başlangıçları için pratik; hizmet sınırlı olabilir."], ["Nderlysaj veya Gjelaj", "Mavi Göz ya da Valbona patikasına göre seçilen, transfer gerektiren dağınık alternatifler."]], foods: [["Konukevi sofrası", "Fasulye, börek, peynir ve et çoğunlukla set menüdür; vejetaryen/alerji talebini önceden bildirin."], ["Dağ ürünleri", "Bal, reçel ve peynirde üretici/soğuk zinciri sorun; koruma alanında izinsiz bitki toplamayın."]], dayTrips: [["Valbona Geçidi", "Tek yön yüksek dağ geçişi için bagaj transferi, karşı konaklama, hava, rehber ve ulaşımı birlikte kurun."], ["Shkodër", "Dağdan dönüşü şehirde bir ara geceyle güvenceye alın; aynı gün uluslararası uçuşa bağlamayın."]], caution: "Patika uygulamasına tek başına güvenmeyin; çevrimdışı harita, su, katman, güneş/yağmur koruması ve faaliyet kapsamlı sigorta taşıyın. Fırtına, kar veya park kapanışında dönün; Valbona geçişine deneyimsiz ve geç saatte başlamayın."
  },
  {
    city: "Sarandë", countryCode: "AL", focus: "Butrint, İyon kıyısı ve güney rotaları", lede: "Korfu karşısındaki İyon kıyısında hareketli sahil kentini Butrint'in antik peyzajı, Ksamil koyları ve karst kaynaklarıyla birleştiren güney üssü.", days: "4–6 gün", arrival: "Korfu feribotu veya Tiran/Gjirokastër otobüsü", local: "Otobüs, taksi, tekne ve yürüyüş", best: "Mayıs–Haziran · Eylül", pulse: "Sarandë'nin yoğun apartman kıyısı ulaşım ve akşam için işlevlidir; asıl rota Butrint, Ksamil, Mavi Göz ve kuzeydeki koyları ayrı günlere bölmekle güçlenir.",
    sights: [["Butrint", "Arkeoloji parkına erken gidin; saat, servis, sulak alan, sıcak ve yürüyüş süresini resmî kaynaktan planlayın."], ["Sarandë sahili ve Lëkurësi", "Promenadı akşam, kaleyi gün batımında görün; tepeye güvenilir taksi ve dönüş anlaşması kullanın."], ["Ksamil", "Plaj işletmesi ücretini önceden sorun; ada teknesinde can yeleği, hava ve koruma kurallarını kontrol edin."]],
    areas: [["Promenad ve merkez", "Otobüs, feribot ve akşam için kolay; temmuz-ağustosta gürültülü/kalabalık."], ["Kodrra veya Ksamil", "Daha sakin kıyı ya da Butrint yakınlığı için farklı ulaşım kararları gerektiren alternatifler."]], foods: [["İyon deniz ürünleri", "Balıkta tür, menşe ve kilo/porsiyon fiyatını siparişten önce yazılı netleştirin."], ["Güney mezeleri", "Otlu börek, biber, peynir ve zeytinyağlılarda süt/et suyu içeriğini sorun."]], dayTrips: [["Gjirokastër ve Mavi Göz", "İki alanı tek sıkışık tura doldurmak yerine süreyi ve kaynak erişimini doğrulayın."], ["Korfu", "Yunanistan Schengen giriş hakkı gerektirir; pasaport, vize, feribot limanı ve dönüşü doğrulamadan bilet almayın."]], caution: "Yüksek sezonda yol, plaj ve tekne aşırı yoğunlaşır; fiyatı/iptali yazılı alın. Korfu uluslararası Schengen geçişidir. Yalnız bayraklı alanda yüzün; kayalık kıyıda dalga ve tekne trafiğini küçümsemeyin."
  },
  {
    city: "Himarë", countryCode: "AL", focus: "İyon koyları, taş köyler ve kıyı yürüyüşleri", lede: "Arnavutluk Rivierası'nda berrak koyları Eski Himarë'nin taş evleri, Porto Palermo kalesi ve dağ yamaçlarındaki köylerle buluşturan daha yavaş kıyı üssü.", days: "4–6 gün", arrival: "Tiran/Vlorë/Sarandë'den otobüs veya araç", local: "Otobüs, taksi, tekne ve yürüyüş", best: "Mayıs–Haziran · Eylül", pulse: "Himarë merkez plajıyla sınırlı değildir; Livadhi, Jale, Gjipe, Qeparo ve Porto Palermo farklı ulaşım, gölge ve deniz koşulları isteyen ayrı günlerdir.",
    sights: [["Eski Himarë", "Kale-köy ve kiliseleri sabah/akşam yürüyün; yaşayan evlere ve ibadet alanlarına saygı gösterin."], ["Porto Palermo", "Kale ve koyu yol güvenliği, açılış ve güneşle planlayın; askerî/kapalı yapıya girmeyin."], ["Gjipe Kanyonu ve plajı", "Patika veya lisanslı tekne seçin; sıcak, su, dalga, kamp ve atık kuralını önceden kontrol edin."]],
    areas: [["Spile ve Himarë merkez", "Restoran, otobüs ve akşam için en pratik kıyı üssü."], ["Livadhi, Qeparo veya Dhërmi yönü", "Plaj/köy atmosferi için araç veya seyrek otobüse bağlı daha sakin alternatifler."]], foods: [["Riviera deniz ürünleri", "Günlük balık, ahtapot ve kalamarda tür, gramaj ve toplam fiyatı siparişten önce sorun."], ["Köy mutfağı", "Keçi peyniri, otlu börek, zeytin ve kuzu ürününde içerik/menşei küçük işletmeden doğrulayın."]], dayTrips: [["Qeparo ve Borsh", "Taş köy ile uzun plajı otobüs/taksiyle birleştirin; dönüş saatini önceden kaydedin."], ["Llogara Geçidi", "Dağ manzarası ve yürüyüş için virajlı yol, sis/rüzgâr ve transfer planı gerekir."]], caution: "Kıyı yolu virajlı, yazın yoğun ve bazı bağlantılar seyrektir; gece sürüşünü azaltın. Gjipe'ye su/gölgesiz hazırlıksız inmeyin, izinsiz vahşi kamp/ateş yakmayın ve tekne fiyatı ile güvenlik ekipmanını hareketten önce netleştirin."
  },
];

export const albaniaGuides = makeRegionalGuides(profiles);
