import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Viyana", countryCode: "AT", focus: "saraylar, müzeler ve kahvehaneler", lede: "Habsburg saraylarını çağdaş sanat, klasik müzik ve mahalle kahvehaneleriyle dengeleyen zarif başkent.", days: "3–5 gün", arrival: "VIE · CAT/S-Bahn/Railjet", local: "U-Bahn, tramvay ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Viyana'nın görkemi yalnız Ringstrasse'de değil; belediye konutları, pazarlar ve Tuna kıyısındaki gündelik yaşamda tamamlanır.",
    sights: [["Schönbrunn Sarayı", "Saray odaları, bahçeler ve Gloriette için yarım gün ayırın; saatli bileti resmî kanaldan alın."], ["Hofburg ve Müze Bölgesi", "İmparatorluk mirası ile Kunsthistorisches, Albertina veya Leopold koleksiyonlarından yalnız bir-ikisini seçin."], ["Belvedere ve Karlskirche", "Klimt koleksiyonu, barok bahçeler ve Karlsplatz çevresi birlikte güçlü bir sanat hattı kurar."]],
    areas: [["Innere Stadt", "İlk ziyaretin simgelerine yürüme mesafesinde, pahalı ama çok pratik merkez."], ["Neubau ve Leopoldstadt", "Bağımsız dükkânlar, pazarlar, Prater ve daha yerel akşamlar için iyi iki yön."]], foods: [["Wiener Schnitzel ve tafelspitz", "Porsiyon büyük olabilir; dana eti beklentiniz varsa menüde Kalb yazısını arayın."], ["Kahvehane ve tatlı", "Melange, Apfelstrudel ve Sachertorte'yi tek günde yarışa çevirmeden tarihî salonlarda mola verin."]], dayTrips: [["Bratislava", "Tren veya Tuna bağlantısıyla kolay; ayrı ülke ve bilet koşullarını kontrol edin."], ["Wachau Vadisi", "Melk–Krems hattı bağ, manastır ve nehir manzarasını birleştirir."]], caution: "Fayton, konser satıcısı ve 'Mozart gecesi' paketinde fiyat ile salonu yazılı görmeden ödeme yapmayın; toplu taşımada biletinizi yolculuktan önce doğru biçimde doğrulayın."
  },
  {
    city: "Salzburg", countryCode: "AT", focus: "barok eski şehir, Mozart ve Alp manzarası", lede: "Barok kubbeler, kale silüeti, müzik mirası ve göl–dağ rotalarının kesiştiği kompakt Alp şehri.", days: "2–3 gün", arrival: "Salzburg Hbf · SZG", local: "Yürüyüş, troleybüs ve bölgesel tren", best: "Mayıs–Haziran · Eylül · Aralık", pulse: "Salzburg küçük görünür ama festival, kale ve çevre göller eklenince iki tam günü rahatça doldurur.",
    sights: [["Hohensalzburg Kalesi", "Fünikülerle çıkıp surlar, müzeler ve Alp panoraması için en az iki saat bırakın."], ["Getreidegasse ve Mozart rotası", "Doğum evi, geçitli avlular ve tarihî dükkânları kalabalık büyümeden gezin."], ["Mirabell ve Mönchsberg", "Bahçeden başlayıp yaya veya asansörle tepede şehir silüetini tamamlayın."]], areas: [["Altstadt", "İlk ziyaret için en atmosferik ve yürünebilir üs; festival döneminde pahalı."], ["Andräviertel ve Mülln", "Pazar, yerel lokanta ve nehir kıyısı için merkeze yakın sakin seçenekler."]], foods: [["Salzburger Nockerl", "Paylaşmaya uygun sıcak tatlıyı servis süresini sorarak sipariş edin."], ["Kasnocken ve bira bahçesi", "Peynirli hamur ve manastır bira geleneği için turistik merkez dışına da çıkın."]], dayTrips: [["Salzkammergut", "St. Wolfgang veya Bad Ischl'i tek göl günü olarak planlayın; her köyü aynı güne koymayın."], ["Berchtesgaden", "Almanya sınırındaki dağ rotasında pasaport ve hava koşulunu kontrol edin."]], caution: "Sound of Music turu ile gerçek şehir tarihini birbirine karıştırmayın; festival ve Noel pazarı günlerinde konaklamayı geç bırakmayın."
  },
  {
    city: "Innsbruck", countryCode: "AT", focus: "Alp teleferikleri, eski şehir ve kış sporları", lede: "Altın Çatı'nın Orta Çağ sokaklarından birkaç dakikada yüksek Alp manzaralarına çıkan Tirol başkenti.", days: "2–4 gün", arrival: "Innsbruck Hbf · INN", local: "Tramvay, otobüs ve teleferik", best: "Mayıs–Ekim · Aralık–Mart", pulse: "Innsbruck şehir gezisi ile dağ gününü aynı merkezde birleştirir; hava, teleferik ve ekipman planı başarıyı belirler.",
    sights: [["Nordkette", "Hungerburg–Seegrube hattında son iniş, rüzgâr ve uygun ayakkabıyı çıkmadan kontrol edin."], ["Altstadt ve Altın Çatı", "İmparatorluk Sarayı, Hofkirche ve dar sokakları sabah sessizliğinde yürüyün."], ["Bergisel Kayak Atlama Kulesi", "Zaha Hadid yapısı ve vadi panoraması için merkezden tramvay–otobüsle ulaşılır."]], areas: [["Altstadt", "Simgelere yakın, kısa ziyaret için en rahat ama yüksek fiyatlı merkez."], ["Wilten ve Saggen", "Kafeler, yerel sokaklar ve istasyon/park bağlantıları için dengeli mahalleler."]], foods: [["Tiroler Gröstl", "Patates, soğan ve etli tava; vejetaryen uyarlamayı önceden sorun."], ["Käsespätzle", "Dağ günü sonrası doyurucu peynirli erişte, yanında salatayla dengelenir."]], dayTrips: [["Seefeld", "Bölgesel trenle yayla yürüyüşü veya kış parkurları için kolay kaçamak."], ["Stubai Vadisi", "Buzul ve teleferik erişimini mevsim, yol ve son otobüsle birlikte planlayın."]], caution: "Şehirde hava açık diye zirvenin açık olduğunu varsaymayın; işaretli patika dışına çıkmayın ve şehir ayakkabısıyla yüksek rota denemeyin."
  },
  {
    city: "Graz", countryCode: "AT", focus: "UNESCO eski şehir, tasarım ve Steiermark mutfağı", lede: "Kızıl çatılı tarih merkezini deneysel mimari, öğrenci enerjisi ve güçlü Steiermark sofrasıyla birleştiren şehir.", days: "2–3 gün", arrival: "Graz Hbf · GRZ", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Graz, Viyana'nın küçük kopyası değildir; Akdeniz etkili avlular, tasarım kurumları ve çiftçi pazarlarıyla kendi temposunu kurar.",
    sights: [["Schlossberg ve Saat Kulesi", "Füniküler, asansör veya merdivenle çıkıp eski şehri yukarıdan okuyun."], ["Kunsthaus ve Murinsel", "Mur Nehri çevresindeki çağdaş mimariyi Lend mahallesiyle birlikte gezin."], ["Eggenberg Sarayı", "Gezegen sembollü odalar ve park için tur saatini önceden kontrol edin."]], areas: [["Innere Stadt", "UNESCO merkez, avlular ve ana müzeler için yürünebilir üs."], ["Lend ve Gries", "Pazar, yaratıcı dükkânlar ve çok kültürlü yemekler için nehrin batısı."]], foods: [["Kabak çekirdeği yağı", "Salata, çorba ve dondurmada kullanılan Steiermark imzasını yerel üreticiden tadın."], ["Backhendl ve pazar ürünleri", "Kızarmış tavuk yanında mevsim salatası; Kaiser-Josef-Platz ürünleri iyi tamamlayıcıdır."]], dayTrips: [["Güney Steiermark bağları", "Toplu taşıma sınırlı olabilir; tadım yapacaksanız araç kullanmayın."], ["Riegersburg", "Kale, volkanik tepeler ve üretici durakları için tam gün ayırın."]], caution: "Schlossberg yokuşunu yaz sıcağında öğlene bırakmayın; pazar ve küçük işletmelerin pazar günü/öğle kapanışını kontrol edin."
  },
  {
    city: "Hallstatt", countryCode: "AT", focus: "göl köyü, tuz madeni ve Dachstein", lede: "Kartpostal görünümünün ardında tuz tarihi, dar kıyı şeridi ve hassas yerel yaşam taşıyan Salzkammergut köyü.", days: "1–2 gün", arrival: "Hallstatt tren + feribot · otobüs", local: "Yürüyüş, feribot ve bölgesel otobüs", best: "Mayıs–Haziran · Eylül–Ekim", pulse: "Hallstatt'ı yalnız fotoğraf durağına çevirmemek için kalabalık saatlerin dışına çıkın ve göl–tuz tarihine zaman ayırın.",
    sights: [["Hallstatt eski köyü", "Pazar meydanı, kemik evi ve kıyı yolunu sabah erken veya akşam yürüyün."], ["Salzwelten ve Skywalk", "Maden operasyonu, füniküler ve yaş sınırlarını resmî sayfadan kontrol edin."], ["Dachstein Krippenstein", "Buz mağarası ve Five Fingers için ayrı hava, ulaşım ve ekipman planı gerekir."]], areas: [["Hallstatt Markt", "Atmosferin merkezinde ama pahalı ve günübirlik kalabalığı yoğun."], ["Obertraun", "Tren, göl ve Dachstein bağlantıları için daha sakin ve çoğu zaman daha hesaplı üs."]], foods: [["Göl balığı", "Mevsim ve tedariki sorun; koruma altındaki tür veya belirsiz menşeden kaçının."], ["Avusturya ev yemekleri", "Çorba, knödel ve tatlılar küçük pansiyon–gasthaus menülerinde daha sade sunulur."]], dayTrips: [["Bad Ischl", "İmparatorluk mirası, termal kültür ve tren bağlantısıyla sakin tamamlayıcı."], ["Gosausee", "Dachstein manzaralı göl yürüyüşü; son otobüs ve hava durumunu kontrol edin."]], caution: "Özel ev girişleri ile iskeleleri fotoğraf platformu sanmayın; drone, park ve otobüs kurallarına uyun, köyde yüksek ses ve izinsiz mülk girişinden kaçının."
  },
  {
    city: "Wachau Vadisi", countryCode: "AT", focus: "Tuna, bağlar, Melk ve bisiklet rotası", lede: "Melk Manastırı ile Krems arasında bağ teraslarını, Tuna köylerini ve kayısı bahçelerini birbirine bağlayan yavaş rota.", days: "2–3 gün", arrival: "Melk/Krems tren · mevsimlik tekne", local: "Tren, otobüs, bisiklet ve tekne", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Wachau tek bir kasaba değil; ulaşım yönünü ve geceleme üssünü seçmek, günübirlik koşuşturmayı sakin bir vadi yolculuğuna çevirir.",
    sights: [["Melk Manastırı", "Barok kompleks, kütüphane ve bahçe için saatli turu tren varışıyla eşleştirin."], ["Dürnstein", "Kale patikası, mavi kule ve dar köy sokaklarını dik yokuşu hesaba katarak gezin."], ["Krems ve bağ terasları", "Müze, eski şehir ve üretici duraklarını vadinin doğu üssü olarak birleştirin."]], areas: [["Krems", "Tren, restoran ve müze açısından en güçlü şehir üssü."], ["Dürnstein ve Spitz", "Vadi atmosferi, bağ yürüyüşü ve sakin gece için küçük ama sınırlı seçenekli üsler."]], foods: [["Wachauer Marille", "Kayısı reçeli, likörü ve tatlısını mevsim ve gerçek menşe etiketiyle alın."], ["Grüner Veltliner", "Tadımı bisiklet veya araç sürüşüyle birleştirmeyin; alkolsüz üzüm suyu da arayın."]], dayTrips: [["Göttweig Manastırı", "Krems karşısındaki tepe manastırı ve panoramik teras için yarım gün."], ["Viyana", "Vadinin doğu ucundan trenle kolay; yoğun rotada ayrı gece gerektirmez."]], caution: "Tekne ve bisiklet kiralamayı yıl boyu çalışır sanmayın; şarap tadımı sonrası bisiklet sürmeyin ve Tuna kıyısında taşkın/kapalı yol duyurusuna uyun."
  },
  {
    city: "Linz", countryCode: "AT", focus: "Tuna, medya sanatı ve sanayi dönüşümü", lede: "Ars Electronica'nın gelecek laboratuvarını Tuna kıyısı, çağdaş müzeler ve güçlü sanayi mirasıyla birleştiren şehir.", days: "1–2 gün", arrival: "Linz Hbf", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül", pulse: "Linz'in değeri klasik kartpostal yerine teknoloji, kamusal sanat ve çalışan şehir dokusunu birlikte göstermesinde yatar.",
    sights: [["Ars Electronica Center", "Etkileşimli laboratuvarlar ve Deep Space programını seans saatine göre planlayın."], ["Lentos ve Tuna kıyısı", "Modern sanat koleksiyonunu köprüler, gece ışıkları ve nehir yürüyüşüyle birleştirin."], ["Pöstlingberg", "Dağ tramvayıyla bazilika ve şehir panoramasına çıkın; sis durumunu kontrol edin."]], areas: [["Altstadt ve Hauptplatz", "İstasyon–Tuna arasında yürünebilir, ilk gece için pratik merkez."], ["Urfahr", "Ars Electronica, pazar ve Pöstlingberg bağlantısıyla nehrin kuzeyinde yerel üs."]], foods: [["Linzer Torte", "Gerçek frenk üzümü dolgulu ince dilimi kahveyle paylaşarak tadın."], ["Knödel çeşitleri", "Peynirli, ıspanaklı veya etli içeriği siparişte netleştirin."]], dayTrips: [["Mauthausen Anıtı", "Ağır tarihî mekâna saygılı kıyafet, sessizlik ve yeterli zamanla gidin."], ["Steyr", "Orta Çağ meydanı ve iki nehir birleşimi trenle sakin bir yarım gün sunar."]], caution: "Mauthausen'i sıradan fotoğraf durağı gibi tüketmeyin; Ars Electronica festivalinde oda ve biletleri son haftaya bırakmayın."
  },
  {
    city: "Zell am See", countryCode: "AT", focus: "göl, Schmittenhöhe ve Kaprun", lede: "Yüzülebilen Alp gölünü dağ teleferikleri, buzul manzarası ve dört mevsim açık hava programıyla birleştiren üs.", days: "3–5 gün", arrival: "Zell am See tren istasyonu", local: "Yürüyüş, otobüs, tekne ve teleferik", best: "Haziran–Eylül · Aralık–Mart", pulse: "Zell am See'de iyi plan göl, dağ ve dinlenme gününü ayırır; her teleferiği aynı gün işaretlemek deneyimi zayıflatır.",
    sights: [["Zeller See", "Göl teknesi, yüzme alanı ve kıyı yürüyüşünü rüzgâr ile su güvenliğine göre seçin."], ["Schmittenhöhe", "Panoramik yürüyüş ve teleferik için son iniş, rota zorluğu ve bulutu kontrol edin."], ["Kitzsteinhorn ve Kaprun", "Yüksek irtifa, buzul platformu ve barajlar için ayrı tam gün bırakın."]], areas: [["Zell am See merkezi", "Tren, göl teknesi ve restoranlara yakın; yaz-kış yoğun."], ["Schüttdorf ve Kaprun", "Aile, araç ve dağ bağlantıları için daha geniş konaklama seçenekleri."]], foods: [["Kasnocken", "Dağ peyniri ve kızarmış soğanlı doyurucu tabağı yürüyüş sonrası deneyin."], ["Kaiserschmarrn", "Paylaşılabilir parçalı pancake; erik kompostosuyla servis edilir."]], dayTrips: [["Grossglockner Yüksek Alp Yolu", "Mevsimlik yol; hava, ücret ve sürüş güvenliği olmadan planlamayın."], ["Saalbach", "Dağ bisikleti ve yürüyüş için bölgesel otobüs/teleferik erişimini kontrol edin."]], caution: "Buzul görüntüsü güvenli yürüyüş anlamına gelmez; bariyer ve resmî kapanışa uyun, kayak veya yüksek rota için faaliyet kapsamlı sigorta alın."
  },
];

export const austriaGuides = makeRegionalGuides(profiles);
