import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Brüksel", countryCode: "BE", focus: "Grand-Place, Avrupa kurumları ve Art Nouveau", lede: "Gotik meydanları Art Nouveau evleri, çizgi roman kültürü ve çok dilli Avrupa başkenti ritmiyle birleştiren kent.", days: "3–4 gün", arrival: "BRU · Bruxelles-Midi/Brussel-Zuid", local: "Metro, tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Brüksel'i yalnız Grand-Place ile Avrupa kurumları arasında görmek eksik kalır; Marolles, Saint-Gilles ve Ixelles şehrin gündelik ve yaratıcı yüzünü açar.",
    sights: [["Grand-Place ve tarih merkezi", "Belediye Binası, lonca cepheleri, Galeries Royales ve çevre sokaklarını sabah erken veya akşam ışığında gezin."], ["Magritte Müzesi ve Mont des Arts", "Kraliyet Güzel Sanatlar kompleksi içinde seçtiğiniz koleksiyonları netleştirin; bütün müzeleri tek güne yığmayın."], ["Avrupa Mahallesi ve Atomium", "Birbirinden uzak iki kümeyi metro ile bağlayın; Parlamento deneyimi ve Atomium için saatli giriş kontrol edin."]],
    areas: [["Centre ve Sablon", "İlk ziyaret, tren ve ana müzeler için pratik; turistik fiyat ve gece gürültüsü değişebilir."], ["Saint-Gilles ve Ixelles", "Art Nouveau, pazarlar, çok kültürlü yemekler ve yerel akşamlar için daha güçlü."]], foods: [["Moules-frites ve carbonnade", "Midye sezonu/menşei ile bira bazlı yahni içeriğini sorun; turistik sabit menüde ek ücretleri okuyun."], ["Waffle, çikolata ve bira", "Brüksel ve Liège waffle'ını ayırın; tadımı şeker ve alkol yarışına çevirmeden yerel üretici seçin."]], dayTrips: [["Leuven", "Kısa trenle belediye binası, üniversite mirası ve bira kültürü için rahat gün."], ["Waterloo", "Müze ve savaş alanı erişiminde otobüs, açılış ve dönüş saatini önceden kurun."]], caution: "Bruxelles-Midi çevresi ve kalabalık metroda telefon/çantaya dikkat edin. İstasyonun Fransızca ve Felemenkçe adını birlikte kaydedin; protesto veya AB zirvesinde yol kapanışlarını kontrol edin."
  },
  {
    city: "Brugge", countryCode: "BE", focus: "kanallar, Flaman ustaları ve Orta Çağ mirası", lede: "Kanal kıyısındaki lonca evlerini dünya çapında Flaman resimleri ve yaşayan mahallelerle buluşturan UNESCO kenti.", days: "2–3 gün", arrival: "Brugge Station · Brüksel/Gent üzerinden tren", local: "Yürüyüş, bisiklet, otobüs ve kanal teknesi", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Brugge günübirlik kalabalık çekse de sabah ve akşam saatlerinde kanalların ötesindeki Sint-Anna ile Magdalena mahalleleri daha sakin bir şehir gösterir.",
    sights: [["Markt ve Belfort", "Çan kulesi kapasite ve merdiven nedeniyle saatli olabilir; meydanı tur otobüsleri gelmeden görün."], ["Groeningemuseum ve Sint-Janshospitaal", "Flaman ustaları ile hastane mirasını iki ayrı koleksiyon olarak planlayın; kapanış günlerini kontrol edin."], ["Kanallar ve Begijnhof", "Lisanslı tekne iskelesi, son tur ve hava durumunu doğrulayın; Begijnhof'ta sessizliğe saygı gösterin."]],
    areas: [["Markt–Burg çevresi", "Ana simgelere en yakın ve atmosferik; gün ortasında en kalabalık bölge."], ["Sint-Anna ve 't Zand", "Yel değirmenleri, yerel sokaklar ya da istasyon bağlantısı için daha dengeli üsler."]], foods: [["Flemish stew", "Bira ile pişen yahniyi patates kızartmasıyla tadın; alkol ve et içeriğini gereksiniminize göre sorun."], ["Çikolata ve speculoos", "Atölye üretimi ile seri hediyelik ürünü ayırın; kakao oranı ve alerjeni kontrol edin."]], dayTrips: [["Damme", "Kanal boyunca bisiklet veya mevsimlik tekneyle sakin köy günü; rüzgâr ve dönüşü planlayın."], ["Belçika kıyısı", "Oostende veya De Haan'a tren/tramvayla ulaşılır; Kuzey Denizi hava ve yüzme bayrağını izleyin."]], caution: "Kanal kenarında özel kapı ve sessiz avluyu fotoğraf dekoru sanmayın. Fayton ve tekne fiyatını binmeden görün; bisiklet yolunda yaya olarak durmayın."
  },
  {
    city: "Gent", countryCode: "BE", focus: "Gravensteen, üç kule ve yaratıcı kanal şehri", lede: "Orta Çağ kalesini öğrenci kültürü, güçlü sanat koleksiyonları ve gece aydınlatılan kanal kıyılarıyla birleştiren şehir.", days: "2–3 gün", arrival: "Gent-Sint-Pieters · Brüksel/Brugge treni", local: "Tramvay, otobüs, yürüyüş ve bisiklet", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Gent, Brugge'den daha büyük ve daha gündeliktir; tarih merkezinin dışında Dok Noord ile Zuid çevresinde yaşayan üniversite ve yaratıcı şehir ortaya çıkar.",
    sights: [["Gravensteen", "Kale turunun dar merdivenleri ve mizahi sesli rehberi için yoğun saatlerden kaçının; bileti resmî siteden alın."], ["Aziz Bavo Katedrali ve Mistik Kuzu", "Ghent Altarpiece için ayrı ziyaretçi merkezi ve saatli bilet gerekebilir; ayin saatine saygı gösterin."], ["Graslei–Korenlei ve üç kule", "Kanal kıyısını gün ışığı ile akşam aydınlatmasında iki kez yürümek şehrin dokusunu iyi gösterir."]],
    areas: [["Historisch Centrum", "Ana anıtlar ve akşam yürüyüşü için en pratik; hafta sonu hareketli."], ["Patershol ve Dok Noord", "Dar tarihî sokaklarda yemek ya da dönüştürülmüş sanayi alanlarında yerel yaşam için iki seçenek."]], foods: [["Gentse waterzooi", "Tavuk veya balıkla yapılan kremalı yemeğin versiyonunu ve içeriğini menüden doğrulayın."], ["Cuberdon ve yerel vejetaryen mutfak", "Mor şekerlemeyi küçük porsiyonda tadın; Gent'in güçlü bitki bazlı lokantalarını değerlendirin."]], dayTrips: [["Brugge", "Sık trenle kolay; iki şehri aynı gün görmek yerine ayrı tam gün ayırın."], ["Kortrijk", "Béguinage, Broel kuleleri ve tasarım rotası için kısa tren uzantısı."]], caution: "Tramvay hattı ve bisiklet akışı sessiz olabilir; yola çıkmadan iki yönü kontrol edin. Büyük festival günlerinde merkez erişimi ile gece ulaşımı tamamen değişebilir."
  },
  {
    city: "Anvers", countryCode: "BE", focus: "Rubens, moda ve Scheldt limanı", lede: "Dünyanın büyük limanlarından birini Barok sanat, elmas tarihi, moda ve etkileyici demiryolu mimarisiyle birleştiren Flaman metropolü.", days: "2–4 gün", arrival: "Antwerpen-Centraal", local: "Tramvay, otobüs, bisiklet ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Anvers'in görkemi yalnız Grote Markt'ta değil; Zuid'in müzeleri, Eilandje'nin liman dönüşümü ve Borgerhout'un çok kültürlü mutfağında tamamlanır.",
    sights: [["Antwerpen-Centraal ve Meir", "İstasyondaki farklı katları, mimari salonu ve tarih merkeze uzanan yaya hattını varış gününde değerlendirin."], ["Onze-Lieve-Vrouwe Katedrali ve Rubens", "Katedraldeki eserler ile Rubenshuis'in güncel açılış/yenileme durumunu ayrı kontrol edin."], ["MAS ve Eilandje", "Liman tarihi koleksiyonu, ücretsiz panorama erişimi ve Scheldt yürüyüşünü gün batımına bağlayın."]],
    areas: [["Historisch Centrum ve Zuid", "İlk ziyaret, müze ve restoranlar için pratik; hafta sonu fiyatlı olabilir."], ["Eilandje ve Zurenborg", "Liman mimarisi ya da belle époque sokakları ile daha mahalle ölçekli akşamlar sunar."]], foods: [["Antwerpse handjes", "El biçimli bisküvi/çikolatayı yerel fırından alın; alerjen ve dolgu içeriğini sorun."], ["Bolleke ve Flaman mutfağı", "Yerel birayı küçük ölçüde deneyin; farklı derece ve bardak servisinin fiyatını görün."]], dayTrips: [["Mechelen", "Kısa trenle katedral kulesi, Hof van Busleyden ve sakin merkez günü."], ["Kalmthoutse Heide", "Doğa yürüyüşünde tren–otobüs, yangın riski ve işaretli parkuru kontrol edin."]], caution: "Elmas bölgesinde yalnız tanınan satıcı, yazılı sertifika ve açık iade koşuluyla alışveriş yapın. Liman endüstriyel alanlarına izinsiz girmeyin; bisiklet ve tramvay şeritlerine dikkat edin."
  },
  {
    city: "Leuven", countryCode: "BE", focus: "Gotik belediye binası, üniversite ve bira mirası", lede: "Avrupa'nın köklü üniversite kültürünü Brabant Gotik mimarisi, kitaplıklar ve canlı meydanlarla birleştiren kompakt şehir.", days: "1–2 gün", arrival: "Leuven Station · Brüksel'den tren", local: "Yürüyüş, otobüs ve bisiklet", best: "Mart–Haziran · Eylül–Aralık", pulse: "Leuven küçük ölçekte büyük bir kültür yoğunluğu taşır; öğrenci takvimi, sınav ve festival haftaları şehrin ritmini bir anda değiştirebilir.",
    sights: [["Grote Markt ve Stadhuis", "Belediye binasının heykel cephelerini görün; iç tur ve restorasyon erişimini resmî ofisten kontrol edin."], ["Üniversite Kütüphanesi", "Savaşta yıkım ve yeniden inşa tarihini kule manzarasıyla birlikte okuyun; saatli giriş gerekebilir."], ["M Leuven ve Groot Begijnhof", "Çağdaş/tarihî koleksiyondan UNESCO béguinage'a yürüyerek sakin bir sanat–mimari hattı kurun."]],
    areas: [["Grote Markt ve istasyon aksı", "Kısa ziyaret, tren ve ana simgeler için en pratik merkez."], ["Groot Begijnhof ve Vaartkom", "Sessiz tarihî doku ya da dönüştürülmüş kanal–sanayi çevresi için iki farklı atmosfer."]], foods: [["Brabant yemekleri", "Stoemp, witloof ve mevsimlik ev yemeklerini günlük menüde daha uygun bulabilirsiniz."], ["Leuven bira kültürü", "Büyük marka deneyimiyle bağımsız üreticiyi ayırın; tur rezervasyonu yapın ve tadım sonrası araç kullanmayın."]], dayTrips: [["Brüksel", "Sık trenle yarım saatten kısa; Leuven'ı yalnız yatak şehri yapmadan ayrı gün verin."], ["Tervuren", "Afrika Müzesi ve park için otobüs/tramvay bağlantısını Brüksel üzerinden planlayın."]], caution: "Oude Markt geceleri kalabalık ve gürültülü olabilir; konaklamada öğrenci etkinlik takvimini kontrol edin. Béguinage yaşayan üniversite alanıdır, pencere ve kapılara saygı gösterin."
  },
  {
    city: "Liège", countryCode: "BE", focus: "Meuse kıyısı, merdivenler ve Valon kültürü", lede: "Santiago Calatrava garından tarihî yamaçlara uzanan, pazarları ve güçlü Valon karakteriyle yaşayan Meuse şehri.", days: "2–3 gün", arrival: "Liège-Guillemins", local: "Otobüs, tren ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Liège cilalı bir kartpostal yerine katmanlı sanayi, öğrenci ve nehir şehridir; Guillemins ile tarih merkezi arasındaki mesafeyi yürüyüşe otomatik eklemeyin.",
    sights: [["Liège-Guillemins", "Calatrava'nın istasyonunu yolculuk yapısının bir parçası olarak görün; tarih merkeze otobüs veya tren bağlantısı kullanın."], ["Montagne de Bueren", "374 basamaklı yokuşu serin saatte çıkın; diz, yağmur ve kaygan zemini hesaba katın."], ["La Boverie ve Meuse", "Sanat müzesi, park ve yaya köprüleriyle nehir boyunca yarım günlük çağdaş rota kurun."]],
    areas: [["Le Carré ve Cité", "Yeme içme, tarih ve gece hayatına yakın; hafta sonu gürültülü olabilir."], ["Outremeuse ve Guillemins", "Yerel pazar–folklor ya da ulaşım/mimari odağı için iki kullanışlı üs."]], foods: [["Boulets à la liégeoise", "Tatlı-ekşi soslu köfteyi frites ile deneyin; et ve sos içeriğini sorun."], ["Gaufre de Liège", "Daha yoğun, inci şekerli waffle'ı taze ve sade deneyerek topping maliyetini azaltın."]], dayTrips: [["Spa", "Termal tarih ve Ardenler kapısı için trenle kolay; modern spa rezervasyonu ayrı yapılır."], ["Maastricht", "Kısa uluslararası bağlantıda bilet, operatör ve telefon dolaşımını kontrol edin."]], caution: "Montagne de Bueren'i yağışta aceleyle inmeyin. Gece Le Carré'de kalabalıkta eşyanıza dikkat edin; Fransızca istasyon ve durak adlarını çevrimdışı saklayın."
  },
  {
    city: "Dinant", countryCode: "BE", focus: "Meuse vadisi, sitadel ve saksafon tarihi", lede: "Kayalık sitadel ile renkli nehir cephesini mağaralar, manastırlar ve Ardenler eşiğiyle birleştiren küçük Valon kenti.", days: "1–2 gün", arrival: "Dinant Station · Namur üzerinden tren", local: "Yürüyüş, tekne ve bölgesel otobüs", best: "Nisan–Ekim", pulse: "Dinant merkezde kompakt görünür; sitadel, tekne ve çevre mağara/manastırlarını ekleyince acele bir fotoğraf durağından tam güne dönüşür.",
    sights: [["Dinant Citadel", "Teleferik veya merdivenle çıkın; tarih sergisi, yükseklik ve hareket kısıtını önceden kontrol edin."], ["Notre-Dame de Dinant ve Charles de Gaulle Köprüsü", "Soğan kubbeli kilise, saksafon yerleştirmeleri ve nehir cephesini birlikte yürüyün."], ["Maison Leffe veya Maison de Monsieur Sax", "Bira ve saksafon tarihinden ilginize uygun olanı seçin; açılış ve tadım koşullarını doğrulayın."]],
    areas: [["Nehir merkezi", "İstasyon, sitadel ve restoranlara yürüme mesafesinde en pratik üs."], ["Anseremme", "Lesse birleşimi, kano ve daha sakin doğa akşamı için merkez dışı alternatif."]], foods: [["Couque de Dinant", "Çok sert ballı bisküvi çoğu zaman dekoratif/ıslatılarak yenir; dişle doğrudan ısırmayın."], ["Valon peynirleri ve bira", "Manastır ürünü adının üretim yerini garanti etmediğini bilin; tadım sonrası araç kullanmayın."]], dayTrips: [["Namur", "Meuse boyunca trenle sitadel, eski şehir ve müze günü."], ["Han-sur-Lesse", "Mağara ve yaban hayatı parkı için seyrek toplu taşıma ve saatli bilet gerekir."]], caution: "Nehir kanosu ve mağara turunda su seviyesi, kask/can yeleği ve yaş koşulunu kontrol edin. Kayalık seyir noktalarında bariyer dışına çıkmayın."
  },
  {
    city: "Ardenler", countryCode: "BE", focus: "ormanlar, kaleler ve yürüyüş rotaları", lede: "Valonya'nın orman, vadi, kale ve küçük kasabalarını işaretli patikalar ile yavaş yolculukta birleştiren geniş doğa bölgesi.", days: "3–6 gün", arrival: "Liège/Namur trenleri · son etap otobüs/araç", local: "Bölgesel tren, seyrek otobüs, bisiklet ve araç", best: "Mayıs–Ekim · Aralık kış kasabaları", pulse: "Ardenler tek bir park veya kasaba değildir; Durbuy, La Roche, Bouillon ve Hautes Fagnes farklı yönlerde olduğundan bir-iki üs seçmek gerekir.",
    sights: [["Durbuy ve Ourthe Vadisi", "Taş sokakları sabah/akşam görün; yürüyüş ve kano için su seviyesi ile parkuru doğrulayın."], ["Bouillon Kalesi", "Semois üzerindeki kale ve vadi seyirlerini tek güne bağlayın; gösteri ve tur saatlerini kontrol edin."], ["Hautes Fagnes", "Bataklık yaylasında yalnız tahta yol ve işaretli rotayı kullanın; yangın, av ve hava kapanışına uyun."]],
    areas: [["Durbuy–La Roche-en-Ardenne", "İlk ziyarette kasaba, nehir ve kısa yürüyüşleri birleştiren erişilebilir üs hattı."], ["Bouillon–Hautes Fagnes", "Kale–Semois ya da daha vahşi yayla doğası için birbirinden uzak iki seçenek."]], foods: [["Arden jambonu", "Kurutulmuş etin üretim ve saklama koşulunu sorun; vejetaryen alternatifi önceden planlayın."], ["Av eti ve orman ürünleri", "Mevsimlik menüde av kaynağı, alerjen ve porsiyonu sorun; koruma altındaki ürünü satın almayın."]], dayTrips: [["Bastogne", "Savaş hafızası müzeleri için duygusal ve zamansal alan bırakın; ulaşımı önceden kurun."], ["Spa ve Liège", "Doğa gününden sonra termal veya şehir molası; toplu taşımayla dönüş saatini kontrol edin."]], caution: "Mobil kapsama ve otobüs seyrek olabilir; çevrimdışı harita, su, katman ve dönüş saati taşıyın. Av sezonu, sel, buz ve yangın nedeniyle kapalı patikaya girmeyin; vahşi hayvanı beslemeyin."
  },
];

export const belgiumGuides = makeRegionalGuides(profiles);
