import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Saraybosna", countryCode: "BA", focus: "Baščaršija, çok katmanlı tarih ve dağlar", lede: "Osmanlı çarşısını Avusturya-Macaristan bulvarları, Yugoslav modernizmi, savaş hafızası ve çevredeki Dinar dağlarıyla birleştiren başkent.", days: "4–5 gün", arrival: "SJJ · Sarajevo tren/otobüs terminalleri", local: "Tramvay, troleybüs, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim · kış kültürü", pulse: "Saraybosna'nın birkaç sokakta değişen mimarisi farklı imparatorlukların yan yana gelişini gösterir. 1992–95 kuşatma hafızasını yaşayan şehir hayatını gölgelemeden, saygılı ve kaynaklı biçimde okumak gerekir.",
    sights: [["Baščaršija", "Sebil, Gazi Hüsrev Bey Camii, han ve bakırcılar hattını sabah gezin; yaşayan ibadet ve esnaf alanına saygı gösterin."], ["Latin Köprüsü ve müzeler", "1914 anlatısını şehir müzesiyle; Yahudi, Boşnak ve Yugoslav katmanlarını ilginize göre ayrı kurumlarla derinleştirin."], ["Tünel Müzesi ve Trebević", "Kuşatma tünelini bağlamla gezin; teleferik/dağ rotasında hava, son iniş ve işaretli patikayı kontrol edin."]],
    areas: [["Baščaršija ve merkez", "İlk ziyaret, tarih ve akşam için yürünebilir; arnavut kaldırım ve turistik fiyat yüksektir."], ["Marijin Dvor, Grbavica ve Ilidža", "Müze/modern şehir, yerel yaşam veya park-termal kaynak odağı için üç farklı tramvaylı alternatif."]], foods: [["Ćevapi ve somun", "Porsiyonu köfte adediyle seçin; soğan, kaymak ve yoğurt eşlikçisini sorun."], ["Bosna böreği ve kahvesi", "Burek'in geleneksel olarak etli, sirnica/zeljanica'nın farklı dolgu olduğunu bilin; kahve ritüelini acele etmeyin."]], dayTrips: [["Vrelo Bosne", "Ilidža'dan park yürüyüşü/fayton için su seviyesi, ücret ve dönüş tramvayını kontrol edin."], ["Lukomir", "Yüksek dağ köyüne sezonluk yol, lisanslı yerel rehber ve hava yedeğiyle gidin; özel yaşama saygı gösterin."]], caution: "Savaş mezarlığı, anıt ve izlerini selfie dekoruna çevirmeyin; mayın uyarılı/işaretsiz araziye girmeyin. Takside resmî çağrı kullanın, konaklama kaydını ve nakit KM ihtiyacını kontrol edin."
  },
  {
    city: "Mostar", countryCode: "BA", focus: "Stari Most, mahalle tarihi ve Neretva rotası", lede: "Neretva'nın iki yakasında Osmanlı taş mimarisini Avusturya-Macaristan bulvarları, savaş izleri ve Hersek'in karst peyzajıyla buluşturan şehir.", days: "3–4 gün", arrival: "Mostar tren/otobüs istasyonu · SJJ/DBV bağlantısı", local: "Yürüyüş, otobüs ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Mostar'ın köprü çevresi çok yoğun olabilir; şehrin gerçek katmanları Kujundžiluk, batı bulvarları, Partizan Mezarlığı ve Neretva kıyısında birlikte okunur.",
    sights: [["Stari Most ve eski şehir", "Köprüyü sabah erken ve akşam görün; kaygan taşta dikkatli yürüyün, profesyonel dalışı taklit etmeyin."], ["Koski Mehmed Paşa ve mahalleler", "Cami avlusu/minare erişimini ibadet ve kıyafet kuralıyla planlayın; özel avluya izinsiz girmeyin."], ["Mostar tarih katmanları", "Muslibegović evi, eski hamam ve savaş izlerini güvenilir müze/rehberle gezin; yıkımı romantikleştirmeyin."]],
    areas: [["Eski şehir", "Köprü ve akşam atmosferi için en yakın; kalabalık, merdiven ve daha yüksek fiyat."], ["Musala ve batı merkez", "İstasyon, yerel lokanta ve çağdaş şehir hayatı için yürünebilir alternatif."]], foods: [["Hersek ızgarası ve dolma", "Japrak, sogan-dolma ve et yemeklerinde içeriği/porsiyonu sorun."], ["Hersek şarabı", "Žilavka ve Blatina'yı lisanslı üreticide tadın; tadım sonrası araç kullanmayın."]], dayTrips: [["Blagaj", "Buna kaynağı ve tekke için otobüs/taksi; ibadet, mağara teknesi ve kıyı kalabalığını planlayın."], ["Počitelj ve Kravica", "Taş kasaba ile şelaleyi tur/araçla birleştirin; yüzme, su seviyesi ve dönüş saatini kontrol edin."]], caution: "Neretva'ya köprüden atlamayın; akıntı ve yükseklik ölümcül olabilir. Şehir çevresinde mayın uyarılı araziye girmeyin; savaş tarihi konusunda tarafları basitleştiren dil kullanmayın."
  },
  {
    city: "Blagaj", countryCode: "BA", focus: "Buna kaynağı, tekke ve Hersek karstı", lede: "Dik kireçtaşı uçurumun altından çıkan Buna kaynağını tarihî derviş tekkesi, nehir lokantaları ve yukarıdaki Stjepan Grad ile birleştiren küçük kasaba.", days: "1–2 gün", arrival: "Mostar'dan otobüs veya taksi", local: "Yürüyüş, taksi ve kısa tekne", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Blagaj öğle saatinde tur otobüsü durağına dönüşebilir; sabah/akşam konaklamak kaynağın sesi, tekke ve köy hayatını daha sakin görmeyi sağlar.",
    sights: [["Blagaj Tekkesi", "Yaşayan dinî-kültürel yapıya kıyafet, sessizlik ve fotoğraf kuralıyla girin; açılış ve ibadet saatini kontrol edin."], ["Vrelo Bune", "Kaynak mağarası teknesine yalnız lisanslı işletme, can yeleği ve uygun su seviyesiyle binin."], ["Stjepan Grad", "Dik, açık ve işaret durumu değişebilen patikaya serin saatte, su ve uygun ayakkabıyla çıkın."]],
    areas: [["Tekke ve kaynak çevresi", "Ana deneyime yürüme kolaylığı; gündüz yoğun, akşam sakin."], ["Blagaj köy merkezi", "Otobüs, yerel market ve daha sakin aile pansiyonu için pratik alternatif."]], foods: [["Buna alabalığı", "Balığın çiftlik/yabani menşeini, gramaj ve garnitür fiyatını siparişten önce sorun."], ["Hersek ev yemekleri", "Dolma, börek ve yoğurtlu tabaklarda et/süt içeriğini aile lokantasında doğrulayın."]], dayTrips: [["Mostar", "Kısa otobüs/taksiyle ana şehir; Blagaj'ı yalnız öğle molasına indirmemek için gecelemeyi düşünün."], ["Buna Kanalı", "Nehir yürüyüşü veya kano için su seviyesi, özel arazi ve lisanslı işletme koşulunu kontrol edin."]], caution: "Tekke çevresinde dinî mahremiyete saygı gösterin; mağara teknesinde can yeleğini çıkarmayın. Kaleye aşırı sıcakta veya karanlıkta çıkmayın, uçurum kenarında bariyer dışına geçmeyin."
  },
  {
    city: "Travnik", countryCode: "BA", focus: "vezirler şehri, kale ve Orta Bosna tarihi", lede: "Dar Lašva vadisinde Osmanlı kalesi, renkli cami, vezir türbeleri ve Nobel ödüllü Ivo Andrić'in edebiyat hafızasını birleştiren kent.", days: "2–3 gün", arrival: "Travnik otobüs terminali", local: "Yürüyüş, otobüs ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Travnik'in küçük merkezi Osmanlı idaresi, Avusturya-Macaristan dönüşümü ve Yugoslav edebiyatını birkaç kilometrede yan yana getirir.",
    sights: [["Travnik Kalesi", "Vadi ve şehir manzarasına dik yürüyüşle çıkın; müze/etkinlik saatini ve kaygan zemini kontrol edin."], ["Şarena Džamija", "Boyalı camiyi yaşayan ibadet alanı olarak gezin; kıyafet, namaz ve fotoğraf kuralına uyun."], ["Ivo Andrić Evi", "Yazarın yaşamı ve Travnik anlatısını küçük müzede görün; açılış gününü önceden doğrulayın."]],
    areas: [["Stari Grad ve merkez", "Kale, cami ve çarşıya yürüyüş için en atmosferik üs."], ["Plava Voda", "Kaynak, lokanta ve daha sakin akşam için merkezden kısa yürüyüş alternatifi."]], foods: [["Travnički ćevapi", "Porsiyon, et türü ve somun/pişirme tarzını sorun; yerel çeşit Belgrad/Saraybosna'dan farklıdır."], ["Vlašić peyniri", "Tuzlu koyun peynirinde üretici, pastörizasyon ve soğuk zinciri kontrol edin."]], dayTrips: [["Vlašić", "Dağ yürüyüşü/kayak için mevsim, yol ve transfer planı; sis/kar koşulunu kontrol edin."], ["Jajce", "Otobüsle şelale ve kale rotası; son dönüşü önceden kaydedin."]], caution: "Kale ve dağda mayın/kapalı alan uyarısından sapmayın. Peynir ve et ürününü soğuk zincirsiz taşımayın; dinî yapı ve savaş tarihi konusunda saygılı dil kullanın."
  },
  {
    city: "Jajce", countryCode: "BA", focus: "şehir içi şelale, kale ve Yugoslavya tarihi", lede: "Pliva'nın Vrbas'a döküldüğü büyük şelaleyi Orta Çağ kalesi, yeraltı kilisesi, su değirmenleri ve Yugoslavya'nın kuruluş hafızasıyla birleştiren kent.", days: "2–3 gün", arrival: "Jajce otobüs terminali", local: "Yürüyüş, taksi ve bisiklet", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Jajce'nin şelalesi merkezde olsa da kale, katakomblar, AVNOJ Müzesi ve Pliva Gölleri farklı tarih/doğa kümeleri oluşturur.",
    sights: [["Jajce Şelalesi", "Seyir platformu, su seviyesi ve sisli/kaygan zemini kontrol edin; bariyer dışına çıkmayın."], ["Kale ve katakomblar", "Dik sur yolunu yeraltı mezar/şapel ziyaretiyle birleştirin; dar alan ve açılış saatini okuyun."], ["AVNOJ Müzesi", "Yugoslavya'nın federal kuruluş tarihini özgün salon bağlamında görün; propaganda/nostalji ötesinde eleştirel okuyun."]],
    areas: [["Tarihî merkez", "Şelale, kale ve müzelere yürüyüş için en pratik üs."], ["Pliva Gölleri", "Doğa, değirmen ve sakin konaklama için araç/taksi gerektiren alternatif."]], foods: [["Pliva alabalığı", "Balığın türü, menşei ve gramaj fiyatını sorun; sürdürülebilir ürünü seçin."], ["Orta Bosna yemekleri", "Güveç, dolma ve börekte et/süt içeriğini sorun; porsiyonu paylaşın."]], dayTrips: [["Pliva Gölleri ve mlinčići", "Su değirmenleri, yürüyüş ve kano için hava/su seviyesi ve lisanslı işletme kontrolü."], ["Travnik", "Vezirler şehri ve kale için otobüsle ayrı gün; son dönüşü kaydedin."]], caution: "Şelale, göl savakları ve kaygan kayada bariyeri aşmayın. Kasaba çevresinde işaretsiz patikaya girmeyin; savaş kalıntısı/şüpheli cisme dokunmayın."
  },
  {
    city: "Banja Luka", countryCode: "BA", focus: "Vrbas kıyısı, kale ve Krajina doğası", lede: "Vrbas Nehri boyunca Kastel Kalesi, geniş bulvarlar, Ortodoks ve İslam mirası ile çevredeki kanyon sporlarını birleştiren kuzeybatı merkezi.", days: "2–4 gün", arrival: "BNX · Banja Luka tren/otobüs istasyonu", local: "Otobüs, taksi ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Banja Luka'nın savaş sonrası idari kimliği kadar Osmanlı, Avusturya-Macaristan ve Yugoslav katmanlarını da görmek, şehri tek anlatıya indirgememeyi sağlar.",
    sights: [["Kastel Kalesi", "Vrbas kıyısındaki sur, park ve etkinlik alanını yürüyün; festival kurulumu erişimi değiştirebilir."], ["Kurtarıcı İsa Katedrali ve Ferhadija", "Ortodoks katedral ile yeniden inşa edilen camiyi ibadet ve kıyafet kuralına saygıyla ziyaret edin."], ["Vrbas kıyısı", "Yürüyüş, dajak teknesi veya raftingte lisanslı işletme, can yeleği ve su seviyesi kullanın."]],
    areas: [["Centar", "Kale, pazar, dinî yapılar ve restoranlara yürüyüş için kolay üs."], ["Obilićevo ve Nova Varoš", "Nehir/yerel yaşam veya modern kafe-konaklama için iki farklı alternatif."]], foods: [["Banjalučki ćevap", "Dörtgen blok halinde servis edilen yerel çeşitte porsiyon ve et türünü sorun."], ["Krajina mutfağı", "Pura, peynir, et ve turşu temelli sofrada içerik/porsiyonu aile lokantasında deneyin."]], dayTrips: [["Krupa na Vrbasu", "Şelale, manastır ve değirmen için otobüs/taksi; su seviyesi ve dönüşü planlayın."], ["Vrbas Kanyonu", "Rafting/kano için lisans, ekipman ve yol güvenliğini yazılı doğrulayın."]], caution: "Siyasi sembol ve savaş konularında hassas davranın; gösterilerden uzak durun. Nehir sporunda kask/can yeleğini çıkarmayın, kırsalda mayın uyarılı alana girmeyin."
  },
  {
    city: "Trebinje", countryCode: "BA", focus: "Hersek taş mimarisi, şarap ve Akdeniz iklimi", lede: "Trebišnjica kıyısında taş eski şehir, çınarlı meydan, Ortodoks manastırları ve bağları Akdeniz'e yakın güneşli iklimle birleştiren güney kenti.", days: "2–4 gün", arrival: "Dubrovnik/Mostar'dan otobüs veya araç", local: "Yürüyüş, taksi ve bisiklet", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Trebinje Dubrovnik'e ucuz yatak alternatifi değil, Hersek şarap kültürü, nehir ve çok katmanlı dinî mirasıyla kendi başına kalınacak bir destinasyondur.",
    sights: [["Eski şehir ve Platanlar", "Osmanlı sur içi, pazar ve çınarlı meydanı sabah/akşam yürüyün; yerel pazar gününü kontrol edin."], ["Hercegovačka Gračanica", "Crkvina tepesindeki manastır ve manzaraya taksi/yürüyüşle çıkın; ibadet ve kıyafet kuralına uyun."], ["Tvrdoš Manastırı", "Manastır ve şarap mahzenini yaşayan dinî alan olarak gezin; tadım, kıyafet ve fotoğraf koşulunu sorun."]],
    areas: [["Stari Grad ve nehir", "Restoran, pazar ve akşam için yürünebilir ana üs."], ["Crkvina veya Gorica", "Manzara, bağ ve daha sakin konaklama için araç/taksi bağlantılı alternatif."]], foods: [["Hersek şarabı", "Žilavka, Blatina ve Vranac tadımında ölçü, üretici ve dönüş sürücüsünü planlayın."], ["Akdeniz Hersek mutfağı", "Peynir, incir, bal, kuzu ve zeytinyağında yerel üretici/soğuk zinciri sorun."]], dayTrips: [["Vjetrenica Mağarası", "Ravno yönünde saatli rehber, serinlik ve araç/transfer planı gerekir."], ["Dubrovnik", "Hırvatistan Schengen sınırıdır; geçerli vize/giriş hakkı ve yoğun sınır kuyruğu olmadan planlamayın."]], caution: "Şarap tadımı sonrası araç kullanmayın. Sınır yakınında kestirme/toprak yola girmeyin, mağarada rehber rotasından çıkmayın; yaz sıcağında tepe yürüyüşünü öğlene bırakmayın."
  },
  {
    city: "Una Milli Parkı", countryCode: "BA", focus: "şelaleler, rafting ve Bihać doğa rotası", lede: "Bosna-Hersek'in kuzeybatısında turkuaz Una Nehri'ni Štrbački Buk, Martin Brod, orman ve geleneksel yerleşimlerle koruyan milli park.", days: "3–5 gün", arrival: "Bihać üzerinden araç/transfer", local: "Araç, lisanslı transfer, yürüyüş ve rafting", best: "Mayıs–Eylül", pulse: "Una Milli Parkı tek şelale değildir; Bihać, Štrbački Buk ve Martin Brod farklı yönlere yayılır. Bir günde ikisini koşturmak yerine iki doğa günü planlayın.",
    sights: [["Štrbački Buk", "Park girişine yol/transfer durumunu doğrulayın; seyir platformu ve bariyer dışına çıkmayın."], ["Martin Brod", "Şelaleler, manastır ve değirmenleri su seviyesi/yerel erişimle gezin; özel mülke saygı gösterin."], ["Una rafting", "Zorluk seviyesi, yaş, lisans, kask, can yeleği, su seviyesi ve sigorta kapsamını yazılı alın."]],
    areas: [["Bihać", "Otobüs, restoran, ikmal ve iki park yönüne transfer için en pratik üs."], ["Kulen Vakuf veya Martin Brod", "Park içinde daha sakin doğa deneyimi için sınırlı hizmet ve araç gerektiren alternatif."]], foods: [["Una alabalığı", "Tür, menşe, gramaj ve koruma kuralını sorun; kaçak av ürününden kaçının."], ["Krajina sofrası", "Börek, et, peynir ve ev yapımı reçelde içerik/üretici bilgisini sorun."]], dayTrips: [["Bihać", "Fethija Camii, Una kıyısı ve şehir ikmali için giriş/çıkış gününe ekleyin."], ["Ostrožac", "Kale ve Una manzarası için araç/taksi; restorasyon ve açılış durumunu kontrol edin."]], caution: "Hırvatistan sınırı ve eski çatışma alanları yakındır; yalnız işaretli/izinli yolda kalın, mayın uyarısını asla aşmayın. Nehirde lisanssız rafting/yüzme yapmayın, su seviyesi yüksekse iptale uyun."
  },
];

export const bosniaGuides = makeRegionalGuides(profiles);
