import { makeWorldExpansionGuides, type WorldExpansionProfile } from "./worldExpansionFactory";

const profiles: WorldExpansionProfile[] = [
  {
    city: "Pekin", countryCode: "CN", focus: "Yasak Şehir, Çin Seddi ve 5 Gün", days: "4–6 tam gün",
    lede: "Pekin'in imparatorluk eksenini, hutong mahallelerini, sanat bölgelerini ve Çin Seddi gününü pasaportlu rezervasyon ile büyük mesafelere göre kurar.",
    arrival: "Capital PEK ve Daxing PKX havalimanları farklı yönlerdedir; ikisinden de raylı bağlantı vardır. Otelinizin Çince adını, doğru terminali ve son metro saatini çevrimdışı kaydedin.",
    local: "Metro geniş ve güvenilir; güvenlik kontrolü ile uzun aktarma koridorlarına zaman bırakın. Yasak Şehir–Tiananmen bölgesinde erişim kapıları ve yaya yönlendirmesi değişebilir; pasaportu her gün taşıyın.", best: "Nisan–Mayıs · Eylül–Ekim",
    identity: ["Pekin, Yasak Şehir'den Olimpiyat Parkı'na uzanan katı eksenleri ile hutongların gündelik ölçüsünü aynı anda taşır. Harita kısa görünse bile anıt alanları kilometrelerce yürüyüş demektir.", "İmparatorluk merkezini iki güne, bir Seddi gününe ve çağdaş mahalleler için en az bir güne ayırmak; yalnız meydan ve saray fotoğrafından çok daha iyi bir başkent okuması verir."],
    sights: [["Yasak Şehir ve Jingshan", "Pasaportla belirli güne bağlı resmî rezervasyon gerekebilir. Tiananmen erişimini ayrıca doğrulayın; kuzey çıkışından Jingshan'a geçip imparatorluk eksenini tepeden okuyun."], ["Cennet Tapınağı ve hutonglar", "Cennet Tapınağı parkına yerel sabah egzersizleri sırasında gidin; öğleden sonra Shichahai, Drum Tower ve daha az ticarileşmiş hutong sokaklarını yürüyün."], ["Mutianyu veya Jinshanling Seddi", "Mutianyu daha kolay altyapı, Jinshanling daha uzun yürüyüş sunar. Resmî bilet, transfer, teleferik ve son dönüşü netleştirin; vahşi ve kapalı bölüme girmeyin."]],
    areas: ["**Dongcheng / Wangfujing–Dongsi** ilk ziyaret, saray ve metro için merkezî; büyük otellerde İngilizce desteği daha olasıdır.", "**Gulou–Shichahai** hutong, kafe ve akşam yürüyüşü; **Sanlitun** modern restoran-gece hayatı için uygundur fakat anıtlara uzaktır."],
    tastes: ["Pekin ördeği için ördeğin bütün/yarım fiyatını, servis ve garnitürü sorun. Zhajiangmian, jianbing, baozi ve douzhi yerel gündelik tatları farklı öğünlere yayar.", "Niujie çevresi Çin Müslüman mutfağında kuzu, erişte ve hamur işleri için güçlüdür. Helal işaretini Çince olarak tanıyın; aynı mutfak ve alkol politikasını işletmeyle doğrulayın."],
    stay: "Dongsi, Dengshikou veya Wangfujing çevresinde iki metro hattına yakın otel ilk ziyaret için dengelidir. Hutong avlu otelinde banyo, ses yalıtımı ve yabancı misafir kabul durumunu teyit edin.",
    evenings: "Houhai manzaralı ama turistik; Gulou çevresi küçük bar ve canlı müzik, Sanlitun daha uluslararası gece sunar. Gösteri biletini resmî mekândan alın, son metro sonrasını planlayın.",
    dayTrips: ["Ming Mezarları ancak tarih ilginiz varsa Seddi gününe eklenmeli; iki alanı sıkıştırmak Setteki yürüyüşü kısaltır.", "Chengde Yazlık Sarayı hızlı trenle mümkün ama günübirlik yoğun; saray ve tapınaklar için erken çıkış gerekir."],
    season: "İlkbahar ve sonbahar yürüyüş için en dengeli; kış kuru ve çok soğuk, yaz sıcak ve yağışlıdır. Hava kalitesini günlük resmî veriden kontrol edin.",
    budget: "Metro ve yerel yemek uygun; Yasak Şehir, Seddi transferi ve uluslararası otel ana kalemdir. Ulusal tatil haftasında tren ve oda bütçesi hızla yükselir.",
    cautions: ["Anıt bileti için pasaport numarası ve gerçek ad gerekir; isim sırası hatası girişte sorun yaratabilir. Bileti sosyal medya aracısından değil resmî sistemden alın.", "Tiananmen ve resmî binalarda güvenlik kurallarına eksiksiz uyun; drone, tripod, çakmak ve büyük çanta kısıtını ziyaret gününde kontrol edin."],
  },
  {
    city: "Şanghay", countryCode: "CN", focus: "Bund, Mahalleler ve Su Kasabaları", days: "4–5 tam gün",
    lede: "Şanghay'ın Bund–Pudong silüetini, eski lilong sokaklarını, çağdaş sanatını ve Fransız İmtiyazı mahallelerini metroya göre dengeler.",
    arrival: "Pudong PVG'den metro ve Maglev+metro; Hongqiao SHA'dan metro ile merkeze ulaşılır. Maglev sizi doğrudan Bund'a götürmez; Longyang Road aktarmasını ve son metro saatini kontrol edin.",
    local: "Metro çoğu geziyi çözer; istasyon çıkışları birbirinden uzak olabilir. Bund, Old City, French Concession ve Pudong'u yakın sanıp tek güne koymayın.", best: "Mart–Mayıs · Ekim–Kasım",
    identity: ["Şanghay, 19. yüzyıl ticaret limanı cepheleri, lilong konut dokusu ve Pudong'un finans kulelerini Huangpu'nun iki yakasında yüzleştirir.", "İyi rota bir gün Bund–Pudong, bir gün French Concession, bir gün müze/West Bund ve bir esnek su kasabası günü kurar."],
    sights: [["Bund ve Pudong", "Bund'ı sabah cepheler, gece ışıklar için iki kez görün. Karşı yakada Shanghai Tower veya başka bir gözlem terası seçin; sisli günde pahalı manzara bileti almayın."], ["French Concession ve lilong", "Wukang Road, Fuxing Park ve Sinan Mansions çevresinde yürüyün; yaşayan konut avlularına izinsiz girmeyin. Eski dükkânları çağdaş tasarım-kahve duraklarıyla dengeleyin."], ["Shanghai Museum ve West Bund", "Müze koleksiyonu veya çağdaş sanat için kurumların pasaportlu rezervasyon, kapanış ve sergi koşullarını ayrı kontrol edin; tüm büyük müzeleri tek güne doldurmayın."]],
    areas: ["**People's Square–Nanjing Road** metro, müze ve ilk ziyaret lojistiği için güçlü; yaya caddesi çok turistik olabilir.", "**French Concession / Jing'an** mahalle yaşamı, restoran ve akşam; **Lujiazui** manzara ve iş oteli için uygun ama tarihî dokuya nehir geçişi gerekir."],
    tastes: ["Xiaolongbao, shengjian mantısı, hong shao rou ve scallion oil noodle temel Şanghay tatlarıdır. Çorbalı mantıyı önce delip soğutarak yiyin.", "Yunnan Road ve mahalle lokantalarında bölgesel Çin mutfakları bulunur. Fotoğraflı menüde porsiyon boyunu, acıyı ve kabuklu deniz ürünü alerjisini açıkça belirtin."],
    stay: "Jing'an–People's Square arasındaki metro erişimli bölge ilk sefer için dengelidir. Bund manzarasına yüksek prim ödemeden önce oda gerçekten nehre bakıyor mu kontrol edin.",
    evenings: "Bund gece yürüyüşü, Former French Concession kokteyl barları ve Found 158 gibi kümeler farklı ritim sunar. Çatı mekânında kıyafet, rezervasyon ve minimum harcamayı sorun.",
    dayTrips: ["Zhujiajiao metro ile kolay su kasabasıdır; hafta içi ve erken saat seçin.", "Suzhou hızlı trenle günübirlik yapılabilir, ancak bahçeler ile kanal akşamı için en az bir gece daha iyi sonuç verir."],
    season: "İlkbahar ve sonbahar yürüyüş için iyi; haziran yağmurlu, yaz çok sıcak-nemli, kış rutubetli soğuktur. Tayfun döneminde nehir ve uçuş duyurularını izleyin.",
    budget: "Metro ve lokanta uygun; manzara kuleleri, uluslararası otel ve kokteyl barı bütçeyi büyütür. Hongqiao hızlı tren bağlantısı için ulaşım payını hesaba katın.",
    cautions: ["Nanjing Road çevresindeki 'çay seremonisi/sanat öğrencisi' davetleri pahalı faturaya dönüşebilir; tanımadığınız kişinin önerdiği ikinci mekâna gitmeyin.", "Bisiklet ve scooterlar sessiz yaklaşabilir; kaldırım-bisiklet yolu ayrımına dikkat edin. Yüksek yapıda hava ve görüş yoksa biletinizi erteleyin."],
  },
  {
    city: "Xi'an", countryCode: "CN", focus: "Terracotta Ordusu, Surlar ve Müslüman Mahallesi", days: "3–4 tam gün",
    lede: "Xi'an'ın şehir surlarını, Terracotta Ordusu'nu, Büyük Cami çevresini ve Tang mirasını hızlı tren-havalimanı bağlantılarına göre kurar.",
    arrival: "Xianyang XIY havalimanından metro merkeze ulaşır; hızlı trenler Xi'an North'a gelir. Kuzey istasyonu ile sur içi arası uzun olduğundan otelinizin Çince adresini ve metro çıkışını kaydedin.",
    local: "Surlar içi yürüyüş ve metro kolaydır; Terracotta Ordusu şehir dışındadır. Tur otobüsü, metro+otobüs veya lisanslı araçta dönüş ve müze rezervasyonunu ayrı doğrulayın.", best: "Mart–Mayıs · Eylül–Kasım",
    identity: ["İpek Yolu'nun doğu başlangıcı Xi'an, Qin imparatorluk mirası ile Hui Müslüman mahallesini eksiksiz Ming surları içinde birleştirir.", "Terracotta Ordusu tam günün yarısını alır; kalan zamanı sur, Shaanxi tarihi ve yemek için iki ayrı şehir gününe bölmek gerekir."],
    sights: [["Terracotta Ordusu", "Pasaportlu ve gün-saat bağlı bileti resmî kanaldan alın. Çukurları 1-3 sırasına körü körüne değil kalabalık akışına göre gezin; müze ile Qin mozolesi bağlantısını öğrenin."], ["Şehir surları ve Çan Kulesi", "Sur üzerinde bisiklet kiralarken kapanış, iade noktası ve hava sıcaklığını kontrol edin. Tüm çevre yaklaşık 14 km; yürüyerek tamamlamak zorunlu değildir."], ["Büyük Cami ve Müslüman Mahallesi", "Ana yemek caddesinden yan sokaklara geçin; camide ibadet alanı ve ziyaret saatine saygı gösterin. Beiyuanmen kalabalığı ile gerçek mahalle pazarını ayırın."]],
    areas: ["**Güney Kapısı–Çan Kulesi** sur, metro ve akşam için en pratik üsdür.", "**Qujiang / Büyük Vahşi Kaz Pagodası** müze, park ve Tang temalı gece gösterilerine yakın; eski merkeze metro gerekir."],
    tastes: ["Biangbiang eriştesi, roujiamo, liangpi ve paomo şehrin doyurucu klasikleridir. Paomo'da ekmeği kendiniz küçük parçalayarak ritüele katılabilirsiniz.", "Hui mahallesinde kuzu şiş, hurma-pirinç tatlısı, persimmon cake ve ekmekler öne çıkar. Helal işaretini görün, ancak ortak mutfak ve alkol hassasiyetini teyit edin."],
    stay: "Yongningmen veya Bell Tower metro çevresi ilk ziyaret için dengelidir. Ana yaya caddesine bakan odada gece gürültüsü olabilir.",
    evenings: "Sur ve Çan/Drum Tower ışıkları, Büyük Vahşi Kaz Pagodası çevresindeki gösteriler ve Datang Everbright City öne çıkar. Gösteriyi kültür deneyimiyle birebir tarih sanmayın.",
    dayTrips: ["Hua Shan yüksek, dik ve tam gün isteyen dağ rotasıdır; hava, teleferik ve korkuluklu patika koşulunu ciddiye alın.", "Luoyang hızlı trenle bağlanır ama Longmen Mağaraları için Xi'an'dan günübirlik çok uzun olabilir; ayrı gece düşünün."],
    season: "İlkbahar-sonbahar sur yürüyüşü için iyi; yaz sıcak, kış kuru ve soğuktur. Kum/toz veya hava kalitesi günlerini resmî veriden kontrol edin.",
    budget: "Yemek ve metro uygun; Terracotta bileti-ulaşımı ve Tang gösterileri maliyeti büyütür. Tur paketinde fabrika/mağaza durağı olup olmadığını sorun.",
    cautions: ["Sahte antika ve 'kazıdan çıktı' iddialı üründen uzak durun; kültür varlığını belgesiz satın almayın.", "Terracotta turunda mecburi yeşim mağazası ve yüksek komisyonlu restoranı kabul etmeyin; rota ve toplam ücreti yazılı görün."],
  },
  {
    city: "Chengdu", countryCode: "CN", focus: "Pandalar, Çayevleri ve Sichuan Mutfağı", days: "3–5 tam gün",
    lede: "Chengdu'nun panda merkezlerini, halk parkı çayevlerini, tapınak mahallelerini ve Sichuan mutfağını aceleci günübirliklerden uzak planlar.",
    arrival: "Tianfu TFU merkezden uzaktır; metro yolculuğu uzun sürer. Shuangliu CTU daha yakındır. Hızlı tren istasyonunuzun East, South veya West olduğunu bilette kontrol edin.",
    local: "Metro geniştir; panda üsleri şehir dışında farklı noktalardadır. Hangi panda merkezine gideceğinizi, bilet ve ilk giriş saatini baştan seçin.", best: "Mart–Mayıs · Eylül–Kasım",
    identity: ["Chengdu'nun çekiciliği yalnız pandalarda değil; çayevinde mahjong, bambulu tapınaklar ve Sichuan mutfağının katmanlı mala aromasındaki yavaş gündelik ritimdedir.", "Panda sabahını ayrı tutup öğleden sonrayı People's Park veya Wenshu; ikinci tam günü sanat, mahalle ve uzun hotpot akşamına ayırın."],
    sights: [["Panda üssü", "Chengdu Research Base gibi merkezlere açılışta gidin; pandalar serin sabah daha aktiftir. Pasaportlu bileti resmî kanaldan alın, hayvana seslenmeyin veya flaş kullanmayın."], ["People's Park ve Kuanzhai", "Park çayevinde uzun mola verin; kulak temizliği gibi hizmette ücreti baştan sorun. Kuanzhai'nin turistik ana sokaklarından çevre mahallelere taşın."], ["Wenshu Manastırı ve Taikoo Li", "Wenshu'nun sakin tapınak-bahçe düzenini, modern Taikoo Li ve Daci Temple çevresiyle karşılaştırın; ibadet alanında sessiz kalın."]],
    areas: ["**Tianfu Square–Chunxi Road** metro, yemek ve ilk ziyaret için merkezîdir.", "**Yulin** daha yerel bar-yemek ve müzik; **Wenshu** sakin tarihî doku ve uygun konaklama sunar."],
    tastes: ["Hotpot, mapo tofu, dan dan mian, longchaoshou ve chuanchuan temel tatlardır. Acı ile uyuşturan Sichuan biberinin seviyesini ayrı ayrı belirtin.", "Hotpot'ta et ve sakatatı iyice pişirin, yağ bazını sorun. Vegan için mantar/sebze suyu ayrı kazan ve temiz ekipman talep edin; susam alerjisini açıkça bildirin."],
    stay: "Chunxi Road ile Tianfu Square arasında metroya yakın konum kolaydır; daha yerel akşam için Yulin seçilebilir. TFU sabah uçuşuna şehir merkezinden uzun süre ayırın.",
    evenings: "Sichuan opera 'face-changing' gösterisi, Yulin barları ve Jinli'nin ışıklı turistik yürüyüşü seçeneklerdir. Opera biletinde koltuk, çay ve ek gösteri dahilini kontrol edin.",
    dayTrips: ["Leshan Büyük Buda hızlı tren+yerel bağlantıyla tam gün yapılabilir; su seviyesi ve bakım erişimini kontrol edin.", "Dujiangyan sulama sistemi ile Qingcheng Dağı aynı hatta olsa da fiziksel tempoya göre birini öne çıkarın."],
    season: "İlkbahar-sonbahar ılıman; yaz nemli-sıcak, kış gri ve rutubetlidir. Panda aktivitesi için günün serin saatleri mevsimden önemlidir.",
    budget: "Metro ve yerel yemek uygun; panda giriş/transferi, opera ve günübirlik trenler toplamı büyütür. Hotpot faturasını ürün/adet ve çay-servis ekleriyle okuyun.",
    cautions: ["Panda bileti satan aracıların farklı parkları karıştırmasına izin vermeyin; merkez adı ve adresini Çince doğrulayın.", "Aşırı acı yemek ve yağlı hotpotu ilk akşama büyük porsiyon koymayın; kişisel sağlık durumunuza göre kademeli deneyin."],
  },
  {
    city: "Chongqing", countryCode: "CN", focus: "Katmanlı Şehir, Hotpot ve Yangtze", days: "3–4 tam gün",
    lede: "Chongqing'in üç boyutlu metro-üst geçit coğrafyasını, Hongya Cave kalabalığını, Yangtze manzaralarını ve hotpot kültürünü semt semt çözer.",
    arrival: "Jiangbei CKG havalimanından metro merkeze ulaşır; Chongqing North ve West hızlı tren istasyonları farklıdır. Dikey şehirde son kilometreyi yalnız haritadaki yatay mesafeyle hesaplamayın.",
    local: "Metro en iyi araçtır; Liziba gibi hatlar turistik deneyime dönüşür. Aynı konumun girişleri onlarca metre yükseklik farkında olabilir; yerel harita ve bina kat bilgisini kullanın.", best: "Mart–Mayıs · Ekim–Kasım",
    identity: ["Chongqing, Jialing ile Yangtze'nin birleştiği dik tepelerde metro, asansör, merdiven ve yüksek binaların birbirine bağlandığı gerçek bir üç boyutlu şehirdir.", "Jiefangbei–Hongya Cave, Liziba–Eling ve Nan'an nehir manzaralarını ayrı kümelere ayırmak, sürekli yokuş ve taksi karmaşasını azaltır."],
    sights: [["Hongya Cave ve Jiefangbei", "Hongya Cave'in en iyi görünümü karşı/alt seviyedendir; yapı içinde kat yönünü kaybetmek kolaydır. Gün batımı sonrası yoğunlukta köprü ve merdivenlere geniş zaman ayırın."], ["Liziba, Eling ve Testbed 2", "Binadan geçen metro fotoğrafını belirlenmiş seyir alanından çekin; ardından Eling Park ve dönüştürülmüş sanayi alanında şehrin yüksekliklerini okuyun."], ["Yangtze teleferiği ve Nan'an", "Teleferik için kuyruk, tek yön bilet ve hava durumunu kontrol edin. Karşı yakada Longmenhao veya Nanshan bakışıyla nehirleri görün; sisli günde manzara sınırlı olabilir."]],
    areas: ["**Jiefangbei** ilk ziyaret, yemek ve iki nehre erişim için merkezî ama çok kalabalıktır.", "**Nanbin Road** manzara ve sakin akşam; **Shapingba** genç, yerel yemek ve Ciqikou erişimi için uygundur."],
    tastes: ["Chongqing hotpot yoğun dana yağı, kurutulmuş biber ve Sichuan biberiyle güçlüdür. Mandalina yağ-susam sosu ve acı seviyesi seçimini baştan yapın.", "Xiaomian, suanlafen ve jianghu cai daha hızlı yerel seçeneklerdir. Sakatat ve iç organ içeriklerini fotoğraflı menüde bile ayrıca sorun."],
    stay: "Jiefangbei metrosuna yakın ama ana turistik cepheden birkaç sokak içeride konaklayın. Giriş katının sokak seviyesiyle aynı olmayabileceğini otel tarifinden öğrenin.",
    evenings: "Hongya Cave ışıkları, Nanbin Road yürüyüşü ve hotpot gecesi şehrin temel akşamlarıdır. Nehir teknesinde rota, süre ve dış güverteyi bilette okuyun.",
    dayTrips: ["Dazu Kaya Oymaları erken çıkışlı tam gündür; resmî alan ve ulaşım bağlantısını planlayın.", "Wulong karstı şehirden uzaktır; hızlı tren/otobüs/araç ve park içi servislerle çok uzun bir gün olabilir, geceleme düşünün."],
    season: "İlkbahar-sonbahar daha rahat; yaz Çin'in en sıcak şehirlerinden biridir, kış sisli ve nemlidir. Manzara gününü hava açıklığına göre esnek tutun.",
    budget: "Metro ve erişte uygun; teleferik, nehir turu ve çevre gezileri maliyeti büyütür. Takside kat/kapı yanlışlığı zaman ve ücret yaratabilir.",
    cautions: ["Merdiven ve dik yokuş için kaymaz ayakkabı giyin; engelli/çocuk arabası erişimini önceden kontrol edin.", "Çok acı hotpotu alkol ve sıcak havayla aşırıya kaçırmayın. Nehir kenarında ıslak basamak ve yoğun kalabalıkta bariyere yaslanmayın."],
  },
  {
    city: "Hangzhou", countryCode: "CN", focus: "Batı Gölü, Longjing Çayı ve Kanallar", days: "2–4 tam gün",
    lede: "Hangzhou'nun Batı Gölü kıyılarını, Lingyin Tapınağı'nı, Longjing köylerini ve Grand Canal mirasını farklı yarım günlere böler.",
    arrival: "Hangzhou Xiaoshan HGH havalimanı metroya bağlıdır; hızlı trenler Hangzhou East ve West'e gelebilir. Şanghay'dan tren kısa olsa da istasyon transferiyle kapıdan kapıya süreyi hesaplayın.",
    local: "Metro, otobüs, tekne ve bisiklet kullanılır. Batı Gölü çevresi 15 km'yi aşar; tamamını yürümek yerine kıyı bölümü, tekne ve tepeyi seçin.", best: "Mart–Mayıs · Eylül–Kasım",
    identity: ["Hangzhou, klasik Çin peyzajının simgesi Batı Gölü ile dijital ekonomi metropolünü aynı şehirde taşır; çekiciliği manzarayı yavaş izlemekte yatar.", "Bir göl günü, bir Lingyin–çay köyü günü ve zaman varsa Grand Canal mahalleleri dengeli plandır."],
    sights: [["Batı Gölü", "Su Causeway veya Bai Causeway'i sabah yürüyün; tekne türü ile indiği iskeleyi öğrenin. Leifeng Pagoda ya da tepe bakışlarından yalnız birini seçin."], ["Lingyin ve Feilai Feng", "Tapınak ile kaya oyma alanının bilet düzeni farklı olabilir. Erken gidin, ibadet alanında sessiz kalın ve tütsü yönlendirmesine uyun."], ["Longjing ve Meijiawu", "Çay tarlasını yürüyün ve tadımda yaprak sınıfı, gram fiyatı ile zorunlu satın alma olup olmadığını sorun. Hasat döneminde köy trafiği artar."]],
    areas: ["**Hubin–göl doğusu** metro, akşam ışıkları ve ilk ziyaret için pratiktir.", "**Beishan/Lingyin çevresi** sakin ve manzaralı; **Grand Canal** daha yerel mahalle-kültür deneyimi sunar."],
    tastes: ["Dongpo pork, West Lake fish in vinegar gravy, Longjing shrimp ve beggar's chicken klasiklerdir; bazı tatlar tatlı-sirkeli olabilir.", "Çay evinde Longjing'i tatmak değerlidir fakat turistik satış baskısına dikkat edin. Menüde çay kişi başı servis ücreti ve su yenilemesini sorun."],
    stay: "Gölün doğusunda metroya yakın konaklama, sabah-akşam kıyı erişimi verir. Göl manzaralı oda tanımının gerçekten açık görüş olup olmadığını fotoğraf ve yorumla doğrulayın.",
    evenings: "Hubin kıyısı ışıkları, Grand Canal gece teknesi ve küçük çayevleri öne çıkar. Göl gösterilerinde sezon, sahne, hava iptali ve koltuk konumunu kontrol edin.",
    dayTrips: ["Wuzhen veya Nanxun su kasabası tam gün; hafta içi seçin ve Şanghay bağlantısını doğru terminalle planlayın.", "Shaoxing kanallar, sarı şarap ve edebiyat tarihi için hızlı trenle farklı bir gün sunar."],
    season: "İlkbahar çiçekli ama yağmurlu; sonbahar serin ve açık olabilir. Ulusal tatilde göl çevresi aşırı yoğunlaşır.",
    budget: "Göl yürüyüşü ücretsiz; tekne, tapınak, gösteri ve iyi konumlu otel maliyeti büyütür. Çay alışverişinde premium sınıf iddiasını bağımsız fiyatla karşılaştırın.",
    cautions: ["Çay köyünde 'ücretsiz tadım' sonrası yüksek baskılı satışa girmeyin; ürün, gram ve toplamı ödeme öncesi görün.", "Bisiklet yolunda yaya olarak durmayın; göl kenarı kalabalığında çanta ve telefonu kontrollü taşıyın."],
  },
  {
    city: "Suzhou", countryCode: "CN", focus: "Klasik Bahçeler, Kanallar ve İpek", days: "2–3 tam gün",
    lede: "Suzhou'da Humble Administrator's Garden gibi klasik bahçeleri, Pingjiang kanallarını, müzeyi ve su kasabalarını kalabalığı çoğaltmadan seçer.",
    arrival: "Şanghay'dan hızlı trenler Suzhou Station veya Suzhou North'a gelir; eski şehre Suzhou Station daha yakındır. Aynı isimli Suzhou'nun Anhui'deki şehirle karışmadığını bilette kontrol edin.",
    local: "Metro ve otobüs iyi; eski şehir kanallarında yürüyüş gerekir. Üç büyük bahçeyi art arda görmek yerine bir ana bahçe, müze ve kanal mahallesi seçin.", best: "Mart–Mayıs · Ekim–Kasım",
    identity: ["Suzhou'nun UNESCO bahçeleri küçültülmüş dağ-su peyzajı, ödünç manzara ve şiirsel isimlerle okunur; hızlı fotoğraf turu bu tasarımı kaçırır.", "Şehir aynı zamanda ipek, kanal ve modern Jinji Lake ekonomisine sahiptir. Eski şehir gününü çağdaş göl akşamıyla dengeleyin."],
    sights: [["Humble Administrator's Garden ve Suzhou Museum", "Bahçeye açılışta girin; müze için ayrı pasaportlu rezervasyon gerekebilir. I. M. Pei tasarımını, komşu Lion Grove yerine acele etmeden görün."], ["Pingjiang Road ve kanallar", "Ana yaya yolundan paralel küçük sokaklara çıkın; tekneye binmeden rota, süre ve paylaşım durumunu sorun. Yaşayan evlerin kapısından izinsiz fotoğraf çekmeyin."], ["Lingering Garden veya Tiger Hill", "İkinci ana deneyim olarak birini seçin: Lingering Garden iç mekân-peyzaj; Tiger Hill tarih ve daha geniş alan sunar."]],
    areas: ["**Gusu eski şehir** bahçe, müze ve Pingjiang için en iyi ilk üs; metroya yürünebilir kalın.", "**Jinji Lake / SIP** modern mimari, iş oteli ve gece ışıkları sunar; klasik merkezden farklı bir Suzhou'dur."],
    tastes: ["Squirrel-shaped mandarin fish, sweet-sour braised dishes, Suzhou noodle ve mevsimsel dim sum yerel çizgidir. Balık fiyatını gram/adet üzerinden sorun.", "Biluochun çayı ve tatlı Suzhou hamur işleri hediyeliktir. Eski sokakta tadım ile paket fiyatını ayrı görün."],
    stay: "Pingjiang–Lindun Road çevresi yürüyüş ve metro için dengeli; tarihî pansiyonda nem, ses ve yabancı misafir kabulünü teyit edin.",
    evenings: "Shantang Street ışıkları güzel ama çok kalabalık; Pingjiang'ın yan sokakları daha sakin. Kunqu operası veya pingtan anlatısında İngilizce açıklama ve süreyi kontrol edin.",
    dayTrips: ["Tongli metro+bağlantıyla kolay su kasabasıdır; erken gidin ve son tekne/çıkışı bilin.", "Şanghay veya Hangzhou hızlı trenle bağlanır; istasyonun şehir içi süresini rotaya ekleyin."],
    season: "İlkbahar bahçe çiçekleri ve yağmur; sonbahar serin yürüyüş sunar. Yaz sıcak-nemli, ulusal tatil aşırı kalabalıktır.",
    budget: "Bahçe biletleri ayrı ayrı birikir; her ünlü bahçeye girmek yerine iki farklı ölçek seçin. Tekne ve ipek alışverişinde fiyatı önceden netleştirin.",
    cautions: ["İpek fabrikası turunda zorunlu satış ve gerçek ipek iddiasını sorgulayın; etiketi, iade koşulunu ve bagajı kontrol edin.", "Kanal kenarında bariyersiz dar geçit ve sessiz e-bike trafiğine dikkat edin."],
  },
  {
    city: "Nanjing", countryCode: "CN", focus: "Ming Surları, Müzeler ve Mor Dağ", days: "3–4 tam gün",
    lede: "Nanjing'in Ming surlarını, Cumhuriyet dönemi başkent tarihini, katliam anma alanını ve Purple Mountain rotasını hassasiyet ile mesafelere göre kurar.",
    arrival: "Nanjing Lukou NKG havalimanı metroya bağlıdır; hızlı trenlerin çoğu Nanjing South'a, bazıları Nanjing Station'a gelir. Purple Mountain ve eski şehir için doğru istasyonu seçin.",
    local: "Metro iyi; sur kapıları ile dağ alanları arasında otobüs/taksi gerekir. Purple Mountain tek başına tam gün olabilir; anma müzesiyle aynı güne sıkıştırmayın.", best: "Mart–Mayıs · Ekim–Kasım",
    identity: ["Nanjing, Ming'in ilk başkenti, Cumhuriyet döneminin yönetim merkezi ve 20. yüzyılın ağır hafızasını aynı şehirde taşır.", "Geziyi bir dağ-anıt günü, bir sur-eski şehir günü ve bir müze-hafıza günü olarak ayırmak tarih katmanlarını birbirine karıştırmaz."],
    sights: [["Purple Mountain ve Sun Yat-sen Mozolesi", "Mozole için pasaportlu rezervasyon ve kapalı gün olabilir. Ming Xiaoling ile Linggu Temple'ı fiziksel gücünüze göre seçin; alan geniş ve merdivenlidir."], ["Ming surları ve Xuanwu Gölü", "Zhonghua Gate savunma mimarisini, farklı bir gün Xuanwu kıyısındaki sur kesimiyle karşılaştırın. Bilet ve giriş noktaları tüm duvar boyunca aynı değildir."], ["Nanjing Katliamı Anma Salonu", "Alan ağır ve hassastır; sessiz, saygılı ve acele etmeden ziyaret edin. Fotoğraf kısıtına uyun, çocuklarla içerik yoğunluğunu önceden değerlendirin."]],
    areas: ["**Xinjiekou** metro, yemek ve tüm yönlere bağlantı için merkezîdir.", "**Fuzimiao–Qinhuai** akşam kanalı ve tarih; **Xuanwu** göl, istasyon ve daha sakin konaklama sunar."],
    tastes: ["Nanjing tuzlu ördeği, duck blood vermicelli soup, soup dumpling ve sesame pancake yerel klasiklerdir; kan/sakatat içeriğini tercihlerinize göre sorun.", "Qinhuai atıştırmalıkları popüler ama turistik; mahalle lokantasında erişte, mantı ve mevsim sebzeleriyle denge kurun."],
    stay: "Xinjiekou'da metro kavşağına yakın otel kısa ziyaret için en pratiktir. Fuzimiao'da gece manzarası karşılığında kalabalık ve ses olabilir.",
    evenings: "Qinhuai ışıkları, Laomendong sokakları ve 1912 bölgesi farklı akşamlar sunar. Kanal teknesinde rota ve sürenin ana su yolu mu kısa tur mu olduğunu sorun.",
    dayTrips: ["Yangzhou bahçeleri ve Huaiyang mutfağı hızlı tren/otobüsle ayrı gün değerindedir.", "Zhenjiang Jinshan Temple ve sirke mutfağıyla kısa tren kaçamağıdır."],
    season: "İlkbahar çiçekli ama yağışlı; sonbahar açık ve serin. Yaz çok sıcak, erik yağmuru döneminde nem ve sağanak yüksektir.",
    budget: "Metro ve yemek uygun; Purple Mountain servis/biletleri ve müzeler arası taksi bütçeyi büyütür. Birçok kamu müzesi ücretsiz olsa da rezervasyon isteyebilir.",
    cautions: ["Anma alanında selfie, yüksek ses ve eğlence pozundan kaçının; mekânın yas ve eğitim işlevine saygı gösterin.", "Purple Mountain'da yasak patikaya girmeyin; sıcak, merdiven ve geniş alan için su taşıyın."],
  },
  {
    city: "Guilin ve Yangshuo", countryCode: "CN", focus: "Li Nehri, Karst Dağları ve Kırsal Rota", days: "4–6 tam gün",
    lede: "Guilin ile Yangshuo arasında Li Nehri teknesini, Yulong kırsalını, bisiklet rotalarını ve pirinç teraslarını gerçek transferlerle planlar.",
    arrival: "Guilin Liangjiang KWL havalimanı ve Guilin North/West tren istasyonları farklı yönlerdedir. Yangshuo hızlı tren istasyonu kasabadan uzaktır; istasyon servisi veya araç bağlantısını önceden kurun.",
    local: "Guilin'de otobüs/taksi; Yangshuo'da bisiklet, e-bike, yerel araç ve tekne kullanılır. Li Nehri cruise'u ile bamboo raft farklı rota, süre ve güvenlik standardına sahiptir.", best: "Nisan–Mayıs · Eylül–Kasım",
    identity: ["Guilin şehir gölleri ve ulaşım kapısı; Yangshuo ise karst kuleleri arasındaki kırsal yaşam, Yulong Nehri ve akşam ritmi için ana konaklama üssüdür.", "En iyi plan Guilin'de bir gece, Li Nehri geçişi ve Yangshuo'da en az üç gece kurar; Longji terasları ayrı geceyle daha iyi açılır."],
    sights: [["Li Nehri cruise'u", "Guilin/Yangdi–Yangshuo arasında tekne sınıfı, gerçek iskele, otel transferi ve bagaj koşulunu okuyun. Sis atmosferik olabilir ama manzara görünürlüğünü azaltır."], ["Yulong Nehri ve kırsal bisiklet", "Bambu salın motorlu Li teknesinden farklı olduğunu bilin; yaş/boy/güvenlik kuralını kontrol edin. Bisikletle köy yolunda tur otobüsü ve e-bike trafiğine dikkat edin."], ["Longji Pirinç Terasları", "Ping'an ve Dazhai farklı köylerdir; servis, teleferik ve konaklama seçimini baştan yapın. Basamak, yağmur ve sis için sağlam ayakkabı gerekir."]],
    areas: ["**Guilin Two Rivers–Four Lakes** kısa şehir gecesi ve tren/uçuş için pratiktir.", "**Yangshuo West Street çevresi** yemek ve tur kolaylığı ama gürültülü; **Yulong kırsalı** manzara ve sakinlik için araç/bisiklet bağımlıdır."],
    tastes: ["Guilin rice noodles kahvaltıda; beer fish Yangshuo akşamında öne çıkar. Balığın tür, ağırlık ve toplam fiyatını seçmeden sorun.", "Osmanthus aromalı tatlı/çay ve stuffed river snails bölgeseldir. Batı Caddesi'nin uluslararası menüsü yerine köy lokantasına da şans verin."],
    stay: "Yangshuo'da West Street'e yürünebilir ama ana sesten uzakta veya Yulong kırsalında manzaralı konaklama seçin. Son tren/uçuş için araç erişimini teyit edin.",
    evenings: "West Street kalabalık ve ticaridir; nehir kıyısı daha sakin. Impression Liu Sanjie gösterisinde yağmur iptali, koltuk ve transferi kontrol edin.",
    dayTrips: ["Xingping eski kasaba ve 20 yuan manzarası yarım/tam gün; drone ve tekne kurallarını yerinde öğrenin.", "Sanjiang Dong köyleri kültür-mimari için rotayı kuzeye uzatır; günübirlikten çok geceleme uygundur."],
    season: "İlkbahar yeşil ve yağmurlu, sonbahar daha açık olabilir. Yaz sıcak ve su seviyesi yüksek; kış serin-sisli. Longji'nin ekim hasat görünümü tarihe bağlıdır.",
    budget: "Şehir uygun; cruise, özel transfer ve gösteri bütçeyi büyütür. 'Bambu tekne' ve büyük cruise fiyatlarını aynı ürün sanmayın.",
    cautions: ["Nehirde can yeleği ve resmî iskele olmayan tekneye binmeyin; yüksek su/sel uyarısında turu erteleyin.", "E-bike kiralarken fren, pil, kask ve hasarı videoya alın; uluslararası ehliyet ve sigorta koşulunu ihmal etmeyin."],
  },
  {
    city: "Zhangjiajie", countryCode: "CN", focus: "Wulingyuan, Tianmen ve 4 Günlük Doğa", days: "3–5 tam gün",
    lede: "Zhangjiajie'de Wulingyuan parkını, Tianmen Dağı'nı ve Grand Canyon'u farklı bilet-giriş sistemleriyle; sis ve dev park ölçeğine göre planlar.",
    arrival: "Hehua DYG havalimanı şehir merkezine yakındır; hızlı trenler Zhangjiajie West'e gelir. Wulingyuan konaklama bölgesi şehirden yaklaşık 40 km uzaktır; son otobüs veya transferi kontrol edin.",
    local: "Park içinde servis otobüsü, teleferik, asansör ve yürüyüş birleşir. Wulingyuan ile Tianmen aynı alan değildir; giriş kapısı ve bilet paketini Çince adıyla kaydedin.", best: "Nisan–Mayıs · Eylül–Kasım",
    identity: ["Wulingyuan'ın kuvars-kumtaşı sütunları sisle sürekli şekil değiştirir; park 1-2 saatlik seyir terası değil, birden fazla giriş ve yüzlerce kilometrelik alan sistemidir.", "Wulingyuan'a iki tam gün, Tianmen'e bir gün ayırmak; cam köprü ve mağarayı ancak ek gün varsa koymak sürdürülebilir plandır."],
    sights: [["Yuanjiajie ve Tianzi Mountain", "Bailong Elevator ile yukarı çıkış popülerdir; kuyruk ve tek yön park akışını okuyun. Avatar Hallelujah noktası yerine çevre patikalarda zaman bırakın."], ["Golden Whip Stream", "Vadi yürüyüşü daha sakin ve düz sayılır; maymunlara yiyecek göstermeyin. Patika çıkışının hangi park kapısına bağlandığını bilin."], ["Tianmen Dağı", "Şehirden teleferik veya yol sistemiyle ayrı tam gündür. Cam yürüyüş yolu, 999 basamak ve mağara erişimi hava/bakıma göre değişebilir; rota türünü bilette seçin."]],
    areas: ["**Wulingyuan / East Gate** park günleri için en iyi üs; sabah kuyruk avantajı sağlar.", "**Zhangjiajie şehir merkezi** Tianmen, havaalanı ve tren için pratik; parka her gün uzun transfer gerekir."],
    tastes: ["Tujia sanxia guo, tütsülenmiş et, ekşi sebze ve acılı wok yemekleri bölgeseldir. Et/sakatat ve acı seviyesini fotoğrafla teyit edin.", "Park çevresinde restoranlar turistik fiyatlı olabilir; sabah su-atıştırmalık alın ama çöpünüzü geri taşıyın."],
    stay: "En az iki Wulingyuan gecesi ve gerekiyorsa son gece şehir merkezi, erken park ile Tianmen lojistiğini çözer. Otelin yabancı misafir kabulünü teyit edin.",
    evenings: "Wulingyuan'da Xibu Street ve kültür gösterileri; şehirde 72 Qilou ışıkları bulunur. Gösteri ile gerçek Tujia kültürünü aynı şey sanmayın.",
    dayTrips: ["Grand Canyon ve cam köprü ayrı biletli yarım/tam gündür; pasaport, saat ve sağlık kısıtını kontrol edin.", "Fenghuang hızlı trenle devam rotasıdır; gece ışıkları için bir gece kalmak günübirlikten iyidir."],
    season: "İlkbahar sisli-dramatik ama yağmurlu; sonbahar serin ve açık olabilir. Kışta buzlanma, yazda sıcak ve kalabalık vardır.",
    budget: "Park girişine teleferik/asansörlerin tamamı dahil olmayabilir. Hangi çıkışları kullanacağınızı planlamadan tüm ek biletleri almayın.",
    cautions: ["Sis görüşü kapatırsa bariyer dışına çıkmayın; kaygan merdivende fotoğraf için durmayın. Yağmurluk ve kaymaz ayakkabı taşıyın.", "Park kapısı, şehir ve bilet adları benzer; taksiye ekran görüntüsü ve Çince adres gösterin. Resmî olmayan 'kestirme' rehberlerini reddedin."],
  },
  {
    city: "Guangzhou", countryCode: "CN", focus: "Kanton Mutfağı, Eski Şehir ve İnci Nehri", days: "3–4 tam gün",
    lede: "Guangzhou'nun dim sum sabahlarını, Chen Clan mirasını, Shamian ve çağdaş Zhujiang New Town silüetini sıcak iklim ritmine göre kurar.",
    arrival: "Baiyun CAN havalimanından metro merkeze ulaşır; Guangzhou South hızlı tren istasyonu büyük ve uzaktır. Hong Kong bağlantısında bilet, pasaport kontrolü ve ayrı giriş koşullarını hesaba katın.",
    local: "Metro geniştir; Liwan eski şehir, Yuexiu ve Tianhe'yi ayrı günlere bölün. Otobüs ve nehir vapuru ikinci seçeneklerdir.", best: "Ekim–Aralık · Mart–Nisan",
    identity: ["Tarihi Kanton olan Guangzhou, bin yıllık dış ticaret limanı, Lingnan mimarisi ve dünya çapında Kanton mutfağıyla güney Çin'in en köklü mega kentidir.", "Eski Liwan'ın arcade sokaklarını, Yuexiu tarihini ve Zhujiang New Town'un çağdaş eksenini üç ayrı yarım güne bölmek şehir kontrastını açar."],
    sights: [["Chen Clan Academy ve Liwan", "Taş-ahşap-seramik bezemeyi erken görün; ardından Lychee Bay ve Enning Road'un qilou cephelerine yürüyün. Yaşayan mahallede avlulara izinsiz girmeyin."], ["Shamian ve Qingping", "Eski yabancı imtiyaz adasını sabah yürüyün; çevredeki geleneksel pazarların ürün ve fotoğraf hassasiyetine saygı gösterin."], ["Canton Tower ve Zhujiang New Town", "Huacheng Square'den kuleyi ücretsiz görün; gözlem terası alacaksanız sis, saat ve bilet katını kontrol edin. Akşam nehir ışıkları için vapur veya yürüyüş seçin."]],
    areas: ["**Yuexiu** tarih, metro ve ilk ziyaret için dengeli üsdür.", "**Liwan** eski şehir ve yemek; **Tianhe/Zhujiang New Town** modern otel, alışveriş ve iş bağlantısı sunar."],
    tastes: ["Yum cha sabahında har gow, siu mai, char siu bao, cheung fun ve çayla başlayın; bazı salonlarda fiş/damga veya masa çayı ücreti vardır.", "Roast goose, wonton noodle, claypot rice ve çift kabuklu süt tatlısı diğer klasiklerdir. Kanton mutfağı yalnız 'hafif' değildir; sakatat ve deniz ürünü içeriğini sorun."],
    stay: "Yuexiu–Haizhu Square hattı eski ve yeni şehre metro erişimi verir. Fuar döneminde fiyat ve doluluk çok artabilir; Canton Fair takvimini kontrol edin.",
    evenings: "Pearl River yürüyüşü/teknesi, Tianhe çatı mekânları ve Liwan gece yemeği seçeneklerdir. Nehir turunda iskele ve turun gerçek süresini doğrulayın.",
    dayTrips: ["Foshan ata tapınağı, seramik ve kung fu mirasıyla metro bağlantılı güçlü gündür.", "Kaiping diaolou kuleleri daha uzaktır; özel araç/tur ve tam gün gerekir."],
    season: "Ekim-aralık daha kuru ve rahat; ilkbahar nemli, yaz çok sıcak ve tayfun/sağanaklı olabilir. Canton Fair haftaları ayrıca yoğunlaşır.",
    budget: "Dim sum uygun olabilir, premium deniz ürünü hızla pahalılaşır. Ürünü canlı tanktan seçiyorsanız ağırlık, pişirme ve servis ücretini yazılı görün.",
    cautions: ["Canlı hayvan/şifalı ürün pazarında fotoğraf ve satın almada yasal-kültürel hassasiyete uyun; koruma altındaki tür ürünlerini almayın.", "Sıcak-nemli havada açık rota arasında klimalı mola ve su planlayın; tayfun uyarısında nehir/çatı planını iptal edin."],
  },
  {
    city: "Shenzhen", countryCode: "CN", focus: "Tasarım, Teknoloji ve Sahil Rotaları", days: "2–4 tam gün",
    lede: "Shenzhen'i yalnız Hong Kong sınırı veya teknoloji merkezi değil; tasarım müzeleri, OCT-LOFT, Dapeng kıyısı ve parklarıyla okur.",
    arrival: "Bao'an SZX havalimanı metroya bağlıdır. Shenzhen North, Futian ve Luohu farklı tren/sınır işlevlerine sahiptir; Hong Kong geçişinde iki bölgenin giriş kurallarını ayrı doğrulayın.",
    local: "Metro modern ve geniştir; şehir doğu-batı çok uzundur. Futian–Nanshan ile Dapeng kıyısını aynı gün planlamayın.", best: "Ekim–Aralık · Mart–Nisan",
    identity: ["Shenzhen birkaç on yılda balıkçı yerleşimlerinden küresel teknoloji ve tasarım merkezine dönüşmüştür; tarihî simge azlığı şehircilik, park ve yaratıcı dönüşümü okumayı daha önemli kılar.", "Futian'ın civic ekseni, Nanshan'ın tasarım-teknoloji alanları ve doğu kıyısı üç farklı Shenzhen'dir."],
    sights: [["Museum of Contemporary Art and Planning Exhibition", "Futian'daki müze ve kentsel planlama sergileri şehrin büyümesini anlamak için iyi başlangıçtır; pasaportlu rezervasyon ve sergi gününü kontrol edin."], ["OCT-LOFT ve Nanshan", "Eski sanayi alanındaki galeri-kafeleri, Design Society/Sea World veya Shenzhen Bay parkıyla birleştirin; kurum programını önceden seçin."], ["Dapeng ve doğu kıyısı", "Dapeng Fortress, Jiaochangwei veya sahil patikaları merkezden uzun transfer ister. Tatil gününde araç kotası/rezervasyon ve dönüş trafiğini kontrol edin."]],
    areas: ["**Futian** hızlı tren, civic center ve tüm yönlere metro için en pratik üsdür.", "**Nanshan** tasarım, teknoloji ve sahil parkı; **Luohu** eski ticaret, pazar ve sınır bağlantısı için uygundur."],
    tastes: ["Shenzhen göçmen şehri olduğundan Kanton, Hunan, Chaoshan ve kuzey mutfaklarını yan yana sunar. Tek 'Shenzhen yemeği' yerine bölgesel restoran turu yapın.", "Chaoshan beef hotpot, dim sum ve deniz ürünü öne çıkar. Balık/et ağırlık fiyatını ve çay-servis ücretini sorun."],
    stay: "Futian metro ve hızlı tren için dengeli; Nanshan daha yaratıcı ve modern akşam sunar. Hong Kong sınırına göre otel seçiyorsanız kullanacağınız kapının açık saatini bilin.",
    evenings: "Coco Park çevresi sosyal gece, OCT-LOFT kültür, Shenzhen Bay ise yürüyüş sunar. Elektronik pazarları kapanıştan önce gezin; gece alışverişe güvenmeyin.",
    dayTrips: ["Hong Kong ayrı giriş, internet ve ödeme düzenine sahiptir; pasaport/vize koşulunu Çin ana karasından ayrı kontrol edin.", "Huizhou sahilleri veya Kaiping gibi uzak rotalar için merkezden gerçek araç süresini hesaplayın."],
    season: "Sonbahar-kış başı kuru ve rahat; yaz sıcak, nemli ve tayfun riski taşır. Sahil/çatı planını resmî uyarıya göre değiştirin.",
    budget: "Metro ve yerel yemek uygun; tasarım alışverişi, premium otel ve sınır bağlantısı maliyeti büyütür. Elektronikte garanti ve vergi/iade koşulunu kontrol edin.",
    cautions: ["Huaqiangbei'de sahte marka, kilitli cihaz ve uluslararası garanti sorununa dikkat edin; ürünü test etmeden ödeme yapmayın.", "Hong Kong'a çıkıp geri dönmenin Çin vize giriş sayınızı etkileyebileceğini unutmayın; çok giriş hakkını resmî belgenizden doğrulayın."],
  },
  {
    city: "Kunming", countryCode: "CN", focus: "Yunnan Mutfağı, Taş Ormanı ve Rota Başlangıcı", days: "2–4 tam gün",
    lede: "Kunming'in ılıman parklarını, etnik kültür katmanlarını, Taş Ormanı'nı ve Dali-Lijiang tren bağlantısını Yunnan rotasının sakin başlangıcına dönüştürür.",
    arrival: "Changshui KMG havalimanı metroya bağlı ama merkeze uzaktır. Kunming South hızlı trenlerin ana merkezi; şehir merkezindeki Kunming Station ile karıştırmayın.",
    local: "Metro merkez ve istasyonları bağlar; Green Lake çevresi yürünebilir. Stone Forest ve Western Hills için ayrı tren/otobüs/araç planı gerekir.", best: "Mart–Mayıs · Ekim–Kasım",
    identity: ["'Ebedi Bahar Şehri' Kunming, yüksek rakımda ılıman iklim, çok katmanlı Yunnan mutfağı ve eyaletin Dali–Lijiang–Xishuangbanna hatlarına bağlantısıyla önemlidir.", "Şehri yalnız transit geceye sıkıştırmayıp Green Lake, pazar ve bir çevre günü ayırmak Yunnan çeşitliliğine iyi giriş verir."],
    sights: [["Green Lake ve Yuantong", "Sabah park yaşamını, Yuantong Temple ve yakın üniversite sokaklarıyla birleştirin. Kış kuş sezonunda hayvanı beslemeyin ve kalabalıkta yolu kapatmayın."], ["Stone Forest", "Shilin'e tren/otobüs veya turla gidilir; park içi servis ile yürüyüş rotasını öğrenin. Ana kalabalıktan dış halkalara geçmek için yeterli süre bırakın."], ["Western Hills ve Dianchi", "Teleferik/servis ve Dragon Gate patikası hava ile bakıma bağlı olabilir. Yüksek basamak, göl manzarası ve dönüş ulaşımını yarım/tam gün olarak planlayın."]],
    areas: ["**Green Lake / Wuhua** park, kafe, pazar ve ilk ziyaret için en karakterli üsdür.", "**Kunming Station çevresi** ulaşım için pratik; **Dianchi** resort ve göl manzarası sunar ama merkezden uzaktır."],
    tastes: ["Crossing-the-bridge noodles sıcak suya malzemeleri sırayla eklenen Yunnan klasiğidir; çiğ etin tamamen pişmesini bekleyin.", "Yabani mantar yemekleri mevsimsel ve ünlüdür; yalnız lisanslı, güvenilir restoranda, tamamen pişmiş tüketin. Erkuai, steam-pot chicken ve çiçek pastası diğer tatlardır."],
    stay: "Green Lake çevresi şehir atmosferi; tren bağlantısı ağırsa metro üzerindeki merkez konum mantıklıdır. Erken South Station treni için kapıdan kapıya süreyi hesaplayın.",
    evenings: "Nanqiang Street ve pazar çevresi yemek; Green Lake daha sakin yürüyüş sunar. Etnik gösteriyi yaşayan kültürün tamamı gibi okumayın.",
    dayTrips: ["Dongchuan Red Land mevsim, ışık ve uzun araç süresi ister; günübirlik çok yorucu olabilir.", "Dali hızlı trenle doğal devamdır; en az üç gece ayırıp Kunming'den günübirlik yapmayın."],
    season: "İklim ılıman ama yüksek rakım güneşi güçlü ve gece serindir. Yaz yağışlı, kış kuru; Stone Forest için sıcaklık farkına hazırlanın.",
    budget: "Metro-yemek uygun; Stone Forest girişi ve özel çevre turu ana kalemdir. Trenleri ulusal tatil öncesi erken alın.",
    cautions: ["Yabani mantarı kendi başınıza toplamayın veya az pişmiş yemeyin; zehirlenme belirtilerini acil durum sayın.", "Yaklaşık 1.900 m rakımda güneş ve susuzluk hissedilmeyebilir; ilk gün yoğun aktiviteyi sınırlayın."],
  },
  {
    city: "Dali", countryCode: "CN", focus: "Erhai, Bai Köyleri ve Cangshan", days: "3–5 tam gün",
    lede: "Dali Eski Şehri'ni, Erhai kıyısını, Xizhou Bai evlerini ve Cangshan yürüyüşlerini motorlu çevre turu baskısından uzak planlar.",
    arrival: "Dali Station Xiaguan'dadır; Eski Şehir'e otobüs/taksiyle 40–60 dakika gerekir. Havalimanı da gölün doğusundadır; konaklama transferini Çince adresle ayarlayın.",
    local: "Eski şehir yürünebilir; Erhai çevresi çok büyüktür. E-bike, bisiklet veya şoförlü araç seçerken izinli göl yolu, pil, ehliyet ve gerçek mesafeyi değerlendirin.", best: "Mart–Mayıs · Eylül–Kasım",
    identity: ["Dali, Cangshan dağları ile Erhai Gölü arasında Bai kültürünün yaşayan köylerini, eski ticaret kentini ve uzun konaklama ritmini birleştirir.", "Eski şehirde bir gün, göl batı kıyısında bir gün ve Cangshan/hava yedeği için bir gün ayırmak doğru başlangıçtır."],
    sights: [["Dali Eski Şehri ve Üç Pagoda", "Ana kapı ve Foreigner Street kalabalığından ara sokaklara çıkın. Chongsheng Temple–Three Pagodas alanı geniştir; ışık ve yürüyüş için yarım gün ayırın."], ["Xizhou ve Zhoucheng", "Bai avlu mimarisi, Xizhou baba ve Zhoucheng tie-dye atölyelerini aynı kuzeybatı rotasında görün. Atölyede ürünün gerçekten yerel/el yapımı olduğunu sorun."], ["Cangshan", "Teleferiklerin başlangıç ve ulaştığı parkurlar farklıdır. Hava, bakım, rakım ve son iniş saatini doğrulayın; işaretli patikadan ayrılmayın."]],
    areas: ["**Dali Ancient Town** restoran, otobüs ve ilk ziyaret için pratik ama turistik ve gürültülü olabilir.", "**Caicun/Longkan** göl gün doğumu; **Xizhou** daha sakin Bai köy atmosferi ve kuzey rotası sunar."],
    tastes: ["Xizhou baba, rushan peyniri, Erhai balığı ve Bai usulü üç çay yerel deneyimlerdir. Koruma kuralı nedeniyle balığın kaynağını sorun.", "Yunnan mantarı ve otlu yemekleri güvenilir restoranda tamamen pişmiş tüketin; çiğ su ve hijyene dikkat edin."],
    stay: "İlk seferde eski şehir dışında sessiz bir kapıya yakın veya Caicun'da göl erişimli kalın. Oda manzarası karşılığında taksi ve yemek bağımlılığını değerlendirin.",
    evenings: "Eski şehir barları ve canlı müzik turistik; Xizhou/Caicun erken, sakin akşam sunar. Gürültü hassasiyetinde ana yaya caddesine bakan oda seçmeyin.",
    dayTrips: ["Shaxi, Tea Horse Road mirası için 2–3 saatlik araçla ayrı geceyi hak eder.", "Weishan eski şehri ve Weibaoshan daha az kalabalık tam gün rotasıdır."],
    season: "İlkbahar rüzgârlı ve çiçekli; sonbahar açık olabilir. Yaz yağışlı; yüksek dağda hava göl kıyısından hızlı değişir.",
    budget: "Konaklama ve yemek orta; göl çevresi özel araç, teleferik ve butik otel maliyeti büyütür. E-bike hasar/depozito koşulunu videoyla kaydedin.",
    cautions: ["Erhai koruma alanında kapalı kıyı yoluna, tarım arazisine veya göl kenarı özel mülke girmeyin.", "E-bike ile tüm gölü bir günde dönmeye çalışmayın; pil, rüzgâr, trafik ve sigorta riski vardır."],
  },
  {
    city: "Lijiang", countryCode: "CN", focus: "Naxi Kültürü, Eski Şehir ve Kar Dağı", days: "3–5 tam gün",
    lede: "Lijiang'ın UNESCO eski şehrini, Shuhe-Baisha köylerini, Yeşim Ejder Kar Dağı'nı ve yüksek irtifa etkisini gerçek rezervasyonlarla planlar.",
    arrival: "Sanyi LJG havalimanından otobüs/taksi; Lijiang tren istasyonundan şehir otobüsü veya araç kullanılır. Eski şehir araç trafiğine kapalı olduğundan bagajla son yürüyüşü otelle netleştirin.",
    local: "Dayan Old Town yürüyerek, Shuhe/Baisha araçla gezilir. Jade Dragon Snow Mountain bileti, park servisi ve teleferik rotası gün-saat bağlı olabilir.", best: "Mart–Mayıs · Eylül–Kasım",
    identity: ["Lijiang, Naxi Dongba kültürü ile kanallı eski şehrin turizm ekonomisini aynı anda taşır; ana meydandan birkaç sokak uzaklaşınca daha sakin avlu ve su yolları açılır.", "Bir eski şehir günü, Baisha–Shuhe günü ve hava uygunsa kar dağı günü ayırmak; Shangri-La'yı ayrıca planlamak gerekir."],
    sights: [["Dayan Eski Şehir ve Black Dragon Pool", "Sabah kanalları yürüyüp Wangu Tower bakışına çıkın; öğleden sonra Black Dragon Pool'da dağ yansımasını görün. Yaşayan avlulara izinsiz girmeyin."], ["Baisha ve Shuhe", "Baisha duvar resimleri, Naxi köy yaşamı ve Shuhe'nin Tea Horse Road izlerini aynı kuzey rotasında görün; turistik atölye ile gerçek üretimi ayırın."], ["Jade Dragon Snow Mountain", "Teleferik kotu çok yüksektir; pasaportlu bilet, oksijen/sağlık uyarısı ve park servis sırasını okuyun. Hava nedeniyle kapanışta aracı bilete zorlamayın."]],
    areas: ["**Dayan'ın kuzey/doğu kapıları** eski şehre erişim ve bagaj için pratiktir; merkez gece gürültülüdür.", "**Shuhe** daha sakin konaklama ve kafe; **Baisha** kırsal ritim sağlar fakat akşam seçenekleri sınırlıdır."],
    tastes: ["Naxi hotpot, chickpea jelly, yak eti ve baba ekmeği öne çıkar. Yak ürünü ile gerçek kaynak, et türü ve pişirme yöntemini sorun.", "Yunnan mantarını yalnız güvenilir restoranda tam pişmiş tüketin. Pu'er çayı tadımında gram ve sınıf fiyatını ödeme öncesi görün."],
    stay: "Eski şehir atmosferi için kapıya yakın avlu oteli; sessizlik için Shuhe seçin. Taş sokakta tekerlekli bagaj zor olduğundan otel karşılama noktasını önceden isteyin.",
    evenings: "Eski şehir bar sokağı yüksek sesli; küçük Naxi müzik performansı veya Shuhe akşamı daha sakin alternatiftir. Gösterinin kültürel bağlamını öğrenin.",
    dayTrips: ["Tiger Leaping Gorge fiziksel ve lojistik olarak ayrı 1–2 gün ister; patika, bagaj ve hava durumunu kontrol edin.", "Shangri-La hızlı trenle doğal devamdır ancak 3.000 m üzeri rakıma kademeli çıkın ve en az iki gece ayırın."],
    season: "İlkbahar-sonbahar açık görüş için iyi; yaz yağmurlu, kış geceleri soğuktur. Dağ havası şehirden bağımsız olarak kapanabilir.",
    budget: "Eski şehir yemeği ve butik otel orta-yüksek; dağ parkı, teleferik ve özel araç ana kalemdir. 'Oksijen paketi' satış baskısına karşı sağlık ihtiyacınızı doğru değerlendirin.",
    cautions: ["Lijiang yaklaşık 2.400 m, dağ teleferiği çok daha yüksektir; ilk gün alkol ve aşırı efordan kaçının, ciddi semptomda aşağı inin.", "Çay, gümüş ve şifalı ürün alışverişinde sertifika, gram ve iade koşulunu görmeden yüksek ödeme yapmayın."],
  },
  {
    city: "Harbin", countryCode: "CN", focus: "Buz Festivali, Rus Mirası ve Kış Planı", days: "3–4 tam gün",
    lede: "Harbin'in Ice and Snow World, Sun Island, Central Street ve St Sophia rotasını -25°C altına inebilen gerçek kış koşullarına göre kurar.",
    arrival: "Taiping HRB havalimanından otobüs/taksi; hızlı tren istasyonları Harbin, Harbin West ve North olarak ayrılır. Kış gecesinde araç ve otel girişini önceden ayarlayın.",
    local: "Metro ve taksi kullanışlı; buz parkları nehrin farklı kesimlerindedir. Soğukta açık alanda 60–90 dakikada bir kapalı ısınma molası planlayın.", best: "Aralık sonu–Şubat · festival takvimine göre",
    identity: ["Harbin, Çin Doğu Demiryolu tarihinin Rus etkili mimarisini ve modern dev buz parklarını aşırı karasal iklimde birleştirir.", "Kış ziyareti normal şehir gezisi değildir: pil, cilt, ayakkabı ve ulaşım yedeği en az bilet kadar önemlidir."],
    sights: [["Ice and Snow World", "Açılış tarihi hava sıcaklığına bağlıdır; resmî bileti ve park saatini kontrol edin. Gün batımından önce girip gündüz-buz detayını ve gece ışıklarını birlikte görün."], ["Sun Island Snow Expo", "Kar heykelleri geniş açık alandadır; ayrı bilet ve ulaşım gerekir. Rüzgâr koruması, sıcak içecek ve kapalı mola planlayın."], ["Central Street ve St Sophia", "Zhongyang Dajie'nin Rus cephelerini, St Sophia çevresini ve nehir kıyısını gündüz yürüyün; buzlu zeminde kaymaz taban kullanın."]],
    areas: ["**Daoli / Central Street** mimari, yemek ve ilk ziyaret için en pratik üsdür.", "**Songbei** buz parklarına yakın modern oteller sunar; tarihî merkeze nehir geçişi gerekir."],
    tastes: ["Guo bao rou, Harbin red sausage, dalieba ekmeği ve Demoli balık yemeği Rus-kuzeydoğu etkileşimini gösterir.", "Dongbei porsiyonları büyüktür; paylaşarak sipariş edin. Donmuş meyve ve dondurmayı aşırı soğukta küçük porsiyon deneyin."],
    stay: "Central Street yakınında iyi ısıtmalı, çift camlı otel ilk sefer için uygundur. Isıtmanın merkezi olup olmadığını ve odada nemlendirici seçeneğini sorun.",
    evenings: "Ice World ana gece deneyimidir; Central Street ışıkları ikinci akşam. Açık alandan sonra doğrudan sıcak duş yerine vücudu kademeli ısıtın.",
    dayTrips: ["Yabuli kayak merkezi tren/transferle gidilir; pist, ekipman ve sigorta kapsamını ayrı kontrol edin.", "China Snow Town fotojenik ama uzak ve çok ticaridir; 1–2 gece, resmî transfer ve açık fiyat olmadan gitmeyin."],
    season: "Buz parkları için sürekli sıfır altı gerekir; kesin açılış her yıl hava durumuna göre değişir. Ocak genellikle en soğuk ve en güvenilir dönemdir.",
    budget: "Festival biletleri, kış ekipmanı ve merkezî otel maliyeti yüksektir. Kaliteli termal katman ve bot kiralama/satın alma bütçesini önceden ekleyin.",
    cautions: ["Pamuk tek başına yeterli değildir: nem atan iç katman, yalıtım, rüzgâr geçirmez dış katman, yüz koruması ve kaymaz bot kullanın. Uyuşma ve beyazlaşmayı donma belirtisi sayın.", "Telefon/kamera pili soğukta hızla biter; yedek pili iç cepte tutun. Buz üzerinde resmî olmayan nehir geçişi ve araç turuna katılmayın."],
  },
];

export const chinaGuides = makeWorldExpansionGuides(profiles);
