import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Zagreb", countryCode: "HR", focus: "Orta Avrupa sokakları, müzeler ve pazarlar", lede: "Avusturya-Macaristan bulvarlarını tarihî Yukarı Şehir, yaratıcı müzeler, Dolac pazarı ve Sava çevresindeki çağdaş yaşamla birleştiren başkent.", days: "3–4 gün", arrival: "ZAG · Zagreb Glavni kolodvor · otobüs terminali", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Zagreb kıyıya geçmeden önce görülüp çıkılacak aktarma değildir; Gornji Grad, Donji Grad müze at nalı, Trešnjevka ve Maksimir farklı şehir katmanlarını açar.",
    sights: [["Gornji Grad", "Taş Kapı, Aziz Mark ve Lotrščak çevresini yürüyün; füniküler, kilise ve Parlamento güvenlik erişimini kontrol edin."], ["Aşağı Şehir müzeleri", "Lenuci Yeşil At Nalı üzerindeki kurumlardan ilginize göre iki seçin; deprem sonrası restorasyon ve taşınmış koleksiyonları doğrulayın."], ["Dolac ve Mirogoj", "Pazarı sabah, mezarlık mimarisini saygılı bir ayrı ziyaretle görün; tramvay/otobüs bağlantısını kontrol edin."]],
    areas: [["Donji Grad", "İstasyon, müze, tramvay ve akşam için en işlevsel ilk üs."], ["Britanski trg, Trešnjevka veya Maksimir", "Pazar-kafe, yerel yaşam ya da park için tramvaya bağlı daha sakin alternatifler."]], foods: [["Štrukli", "Peynirli hamur işinin fırın/haşlama biçimini, porsiyon ve süt içeriğini sorun."], ["Zagreb ve Zagorje mutfağı", "Purica s mlincima, güveç ve şarküteride et türü/porsiyonu netleştirin; pazar ürününü mevsiminde deneyin."]], dayTrips: [["Samobor", "Otobüsle barok kasaba, yürüyüş ve kremšnita için yarım/tam gün; son dönüşü doğrulayın."], ["Varaždin", "Tren/otobüsle tarihî merkez ve müzeler; festival döneminde konaklama/seferi erkenden kontrol edin."]], caution: "Deprem sonrası restorasyon bazı merkez yapılarını kapatabilir; güncel kuruma bakın. Tramvay biletini doğru biçimde doğrulayın, kalabalıkta eşyayı gözetin ve istasyon çevresinde lisanssız taksi kullanmayın."
  },
  {
    city: "Dubrovnik", countryCode: "HR", focus: "UNESCO surları, Adriyatik ve şehir devleti tarihi", lede: "Adriyatik kıyısındaki kusursuz sur içini Ragusa Cumhuriyeti tarihi, kayalık plajlar, Elafiti adaları ve sert karst yamaçlarıyla buluşturan kent.", days: "3–5 gün", arrival: "DBV · Gruž Limanı/otobüs terminali", local: "Otobüs, yürüyüş, tekne ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Dubrovnik birkaç saatlik kruvaziyer seti değildir; surlar, Rektör Sarayı, savaş hafızası, Lapad/Gruž yaşamı ve ada günü için kalabalık dışında en az üç gece gerekir.",
    sights: [["Şehir Surları", "Saatli bileti erken/geç saate alın; sıcak, merdiven, tek yön akış ve kapanış duyurusunu kontrol edin."], ["Stradun ve Ragusa kurumları", "Rektör Sarayı, Fransisken kompleksi ve katedrali ilginize göre seçin; ibadet/sergi saatine uyun."], ["Srđ Tepesi", "Teleferik veya yasal rota kullanın; hava, rüzgâr ve son inişi kontrol edin, eski çatışma alanında işaretli yoldan çıkmayın."]],
    areas: [["Eski şehir", "Sabah/akşam atmosferi için benzersiz; pahalı, merdivenli, araçsız ve gemi saatinde çok yoğun."], ["Lapad veya Gruž", "Plaj/yerel akşam ya da liman/otobüs kolaylığı için şehir otobüslü daha dengeli üsler."]], foods: [["Dubrovnik deniz ürünleri", "Balık, ahtapot ve siyah risottoda tür, kilo/porsiyon ve mürekkep/alerjeni sorun."], ["Rozata ve kontonjata", "Yerel krem karamel veya ayva tatlısında yumurta/süt ve porsiyonu netleştirin."]], dayTrips: [["Lokrum veya Elafiti", "Ada teknesinde hava, son dönüş, koruma/yangın ve yüzme kurallarını kontrol edin."], ["Mostar veya Kotor", "İkisi de Schengen dış sınırıdır; pasaport, giriş hakkı, çoklu geçiş ve uzun kuyruk olmadan günübirlik sanmayın."]], caution: "Kruvaziyer takvimini kullanıp surları en yoğun saate bırakmayın. Kayalık kıyıda yalnız güvenli noktadan yüzün; özel merdiven/avluya girmeyin, drone ve sınır geçiş kurallarını ihlal etmeyin."
  },
  {
    city: "Split", countryCode: "HR", focus: "Diocletianus Sarayı, mahalleler ve ada bağlantıları", lede: "Roma imparatorluk sarayının yaşayan sokaklarını Dalmaçya mahalleleri, Marjan tepesi, büyük feribot limanı ve Adriyatik mutfağıyla birleştiren şehir.", days: "4–5 gün", arrival: "SPU · Split tren/otobüs/feribot terminali", local: "Otobüs, yürüyüş, feribot ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Split yalnız adalara geçiş kapısı değildir; saray içindeki yaşayan konutlar, Varoš, pazar, Bačvice ve Marjan şehre kendi başına dört gün verir.",
    sights: [["Diocletianus Sarayı", "Peristil, mahzen, katedral ve dar sokakları sabah/akşam gezin; tek birleşik bilet varsaymayın."], ["Marjan", "İşaretli yürüyüş/bisiklet rotasında yangın, sıcak, bakım ve gün ışığını kontrol edin; kapalı orman yolunu aşmayın."], ["Arkeoloji ve Meštrović", "Koleksiyon/galerilerin restorasyon ve çalışma saatini doğrulayarak Roma mirasını modern sanatla dengeleyin."]],
    areas: [["Grad ve Varoš", "Tarih, akşam ve limana yakın; taş basamak, gece gürültüsü ve yüksek fiyat olabilir."], ["Bačvice, Firule veya Spinut", "Plaj/yerel yaşam ya da Marjan yakınlığı için otobüs-yürüyüşlü alternatifler."]], foods: [["Pašticada", "Uzun pişmiş et ve gnocchi tabağında et türü, şaraplı sos ve porsiyonu sorun."], ["Dalmaçya pazarı ve balık", "Pazar ürününü mevsiminde alın; balık restoranında kilo fiyatını servis öncesi görün."]], dayTrips: [["Trogir", "Otobüs/tekneyle UNESCO ada merkezini yarım/tam gün gezin; havaalanı trafiği ve son dönüşü kontrol edin."], ["Brač, Hvar veya Šolta", "Bir ada seçin; doğru liman, feribot/katamaran, bagaj ve dönüş saatini resmî işletmeden doğrulayın."]], caution: "Liman alanında farklı iskeleleri karıştırmayın ve hareketten önce gemi adını kontrol edin. Marjan'da ateş yasağına uyun; saray içindeki evlerin özel alan olduğunu unutmayın, kaçak tekne turu kullanmayın."
  },
  {
    city: "Zadar", countryCode: "HR", focus: "Roma forumu, gün batımı sanatı ve kuzey Dalmaçya", lede: "Roma ve Venedik katmanlarını Deniz Orgu, Güneşe Selam yerleştirmesi, ada feribotları ve Velebit'e açılan kuzey Dalmaçya doğasıyla birleştiren şehir.", days: "3–5 gün", arrival: "ZAD · Zadar otobüs/feribot terminalleri", local: "Otobüs, yürüyüş, feribot ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Zadar'ın gün batımı kıyısı güçlüdür ancak forum, surlar, pazar ve yarımada dışındaki mahalleler kentin gündelik yüzünü açar. Kornati, Pag ve Paklenica aynı kısa güne sığmaz.",
    sights: [["Roma Forumu ve Aziz Donatus", "Arkeoloji alanı, kilise konseri ve müzeyi açılış/etkinlik takvimine göre birleştirin."], ["Deniz Orgu ve Güneşe Selam", "Gün batımında kalabalık ve kaygan kıyıya dikkat edin; kurulum üzerinde bisiklet sürmeyin veya denize kontrolsüz atlamayın."], ["Şehir surları ve pazar", "Kara Kapısı, yürüyüş yolu ve sabah pazarını yaşayan şehir bağlamında gezin."]],
    areas: [["Poluotok", "Tarih ve akşam için araçsız kolay; yazın gürültülü ve park sınırlı."], ["Borik, Arbanasi veya Voštarnica", "Plaj, sakin konaklama ya da otobüs terminali bağlantısı için farklı alternatifler."]], foods: [["Paški sir", "Pag peynirinde üretici, pastörizasyon ve porsiyon fiyatını sorun."], ["Maraschino ve deniz ürünü", "Likörde alkol/şeker, balıkta tür ile toplam kilo fiyatını netleştirin."]], dayTrips: [["Kornati", "Lisanslı tekne, milli park bileti, öğün kapsamı, hava ve gerçek yüzme süresini yazılı doğrulayın."], ["Paklenica", "Kanyon yürüyüşü/tırmanışında park girişi, rota, sıcak, ekipman ve kurtarma sigortası planlayın."]], caution: "Kıyı yerleştirmelerinde dalga ve kaygan taşa dikkat edin. Ada/park turunun 'her şey dahil' ifadesini yazılı kapsam olmadan kabul etmeyin; rüzgâr ve yangın kapanışına uyun."
  },
  {
    city: "Hvar", countryCode: "HR", focus: "Venedik limanı, lavanta köyleri ve adalar", lede: "Taş Hvar kentini Pakleni Adaları, Stari Grad Ovası, lavanta yamaçları, bağlar ve güçlü gece hayatıyla birleştiren uzun Dalmaçya adası.", days: "4–7 gün", arrival: "Hvar/Stari Grad feribot limanları", local: "Otobüs, taksi, scooter, tekne ve yürüyüş", best: "Mayıs–Haziran · Eylül", pulse: "Hvar kasabası adanın tamamı değildir; Stari Grad, Jelsa, Brusje ve doğu koyları farklı bir ritim sunar. Feribotun hangi limana geldiğini konaklama transferiyle birlikte okuyun.",
    sights: [["Hvar Kalesi ve kent", "Kaleye serin saatte çıkın; katedral, arsenal ve tiyatro saatini doğrulayın, sur kenarında bariyeri aşmayın."], ["Stari Grad Ovası", "UNESCO tarım peyzajını bisiklet/rehberle gezin; özel tarlaya girmeyin ve taş duvarlara zarar vermeyin."], ["Pakleni Adaları", "Lisanslı tekne/deniz taksisi, son dönüş, rüzgâr ve koydaki işletme ücretini önceden kontrol edin."]],
    areas: [["Hvar Town", "Gece hayatı ve tekne için pratik; çok pahalı, gürültülü ve merdivenli olabilir."], ["Stari Grad veya Jelsa", "Tarihî liman, yerel yaşam ve daha sakin fiyat için ada otobüslü alternatif."]], foods: [["Gregada", "Balık güvecinde tür, gramaj ve minimum kişi/porsiyon kuralını sorun."], ["Hvar şarabı ve lavanta", "Plavac mali tadımını sürücülü planlayın; lavanta ürününde gerçek yerel üreticiyi sorun."]], dayTrips: [["Vis", "Katamaran saatine göre çoğu zaman ayrı gece daha iyidir; günübirlik dönüşü resmî tarifeden doğrulayın."], ["Brač", "Limanlar arası mevsimsel bağlantıyı ve ada içi devamı tek bilet sanmayın."]], caution: "Scooter/quad kazası riski ve dar ada yolu ciddidir; deneyimsiz sürmeyin, alkollü araç kullanmayın. Gece kulübü faturası ile tekne fiyatını önceden görün, açık ateş ve izinsiz kamp yasağına uyun."
  },
  {
    city: "Istria", countryCode: "HR", focus: "Rovinj, Pula, tepe köyleri ve gastronomi", lede: "Adriyatik yarımadasında Roma Pula'sını Rovinj'in Venedik silüeti, taş tepe köyleri, bağlar, zeytinlikler ve güçlü bölgesel mutfakla bağlayan rota.", days: "6–9 gün", arrival: "PUY · Pula/Rijeka otobüs bağlantıları", local: "Araç, bölgesel otobüs, bisiklet ve tekne", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Istria tek şehir değil, kıyı ile iç tepe köyleri arasında yayılan bölgedir. Rovinj/Pula kıyı üssü ve Motovun/Grožnjan yönünde iç bölge günü kurmak sürekli valiz taşımaktan iyidir.",
    sights: [["Rovinj", "Eski kenti sabah/akşam yürüyün; Aziz Euphemia çan kulesi, kaygan taş ve yaşayan evlerin mahremiyetine dikkat edin."], ["Pula Arenası", "Roma amfitiyatrosu, forum ve arkeoloji koleksiyonunu etkinlik/konser kurulumuna göre planlayın."], ["Motovun ve Grožnjan", "Tepe köylerine araç/turla gidin; park, festival ve dar yol durumunu önceden kontrol edin."]],
    areas: [["Rovinj veya Pula", "Romantik kıyı/tekne ya da Roma mirası/ulaşım için iki farklı ana üs."], ["İç Istria", "Bağ, trüf ve taş köy deneyimi için araç gerektiren sakin ikinci üs."]], foods: [["Fuži ve trüf", "Trüfün taze mi aroma ürünü mü olduğunu, sos/süt içeriği ve gramajı sorun."], ["Malvazija ve zeytinyağı", "Üretici tadımını randevu ve sürücülü dönüşle yapın; hasat döneminde özel araziye izinsiz girmeyin."]], dayTrips: [["Brijuni", "Fažana'dan resmî tekne, milli park bileti ve ada tur kapsamını doğrulayın."], ["Kvarner", "Rijeka/Opatija yönünü uzun kıyı günü veya ayrı gece olarak planlayın; yaz trafiğine pay bırakın."]], caution: "Bağ/trüf tadımı sonrası araç kullanmayın; dar köy yolunda park ve bisiklet görünürlüğüne dikkat edin. Kıyı/parkta ateş, kamp ve deniz canlısı toplama kurallarına uyun."
  },
  {
    city: "Plitvice Gölleri", countryCode: "HR", focus: "şelale gölleri, ahşap yollar ve milli park", lede: "Orman içindeki traverten eşiklerle birbirine bağlanan turkuaz gölleri, şelaleleri ve korumalı karst ekosistemini ahşap yürüyüş yolları üzerinden gösteren milli park.", days: "2–3 gün", arrival: "Zagreb/Zadar/Split'ten otobüs veya araç", local: "Park shuttle'ı, elektrikli tekne ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim · kış manzarası", pulse: "Plitvice bir saatlik şelale fotoğrafı değil; üst ve alt göller, tekne ve shuttle farklı park rotalarıdır. Parkın yakınında gecelemek erken giriş ve hava yedeği sağlar.",
    sights: [["Alt Göller", "Veliki Slap ve kanyon rotasında giriş/rota harfini, tek yön akışı, yoğunluk ve kaygan ahşap yolu kontrol edin."], ["Üst Göller", "Orman ve çoklu şelale rotasını shuttle/tekne çalışmasına göre planlayın; kapanmış patikayı aşmayın."], ["Seyir noktaları", "Yalnız resmî işaretli erişimi kullanın; yol kenarı veya bariyer dışı kestirmeden kaçının."]],
    areas: [["Giriş 1 çevresi", "Alt göller ve erken Veliki Slap için pratik; oda/otobüs seçeneği sınırlı olabilir."], ["Giriş 2, Jezerce veya Korana", "Üst göl/ulaşım ya da kırsal konaklama için farklı park girişine bağlı alternatifler."]], foods: [["Lika mutfağı", "Fasulye, kuzu ve patates yemeklerinde et/süt içeriği ile porsiyonu sorun."], ["Yerel peynir ve bal", "Üretici, pastörizasyon ve soğuk zinciri doğrulayın; park içinde bitki/mantar toplamayın."]], dayTrips: [["Rastoke", "Slunj'daki değirmen-şelale yerleşimini Zagreb yönünde ayrı yarım gün ekleyin; özel mülke saygı gösterin."], ["Zadar veya Zagreb", "Parkı sıkı şehir transferine bağlamayın; otobüs gecikmesi ve bagaj için geniş pay bırakın."]], caution: "Yüzmek, ahşap yoldan çıkmak, drone ve izinsiz piknik/ateş yasaktır. Su seviyesi, kar, fırtına veya bakım rotayı kapatabilir; eski blog haritasına değil parkın güncel bilet ve rota duyurusuna uyun."
  },
  {
    city: "Šibenik", countryCode: "HR", focus: "taş katedral, kaleler ve Krka kapısı", lede: "Dalmaçya'nın taş sokaklarını UNESCO Aziz James Katedrali, dört kale, yaşayan kıyı mahalleleri ve Krka–Kornati doğa rotalarıyla birleştiren şehir.", days: "3–4 gün", arrival: "Šibenik otobüs/tren istasyonu", local: "Otobüs, yürüyüş, tekne ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Šibenik Split ile Zadar arasında mola değildir; katedralin taş işçiliği, kalelerin çağdaş kullanımı, kanal ve yakın parklar kendi başına birkaç gün oluşturur.",
    sights: [["Aziz James Katedrali", "Dış friz ile taş konstrüksiyonu rehber/müze bağlamında görün; ibadet, konser ve restorasyon saatini kontrol edin."], ["Aziz Michael ve Barone", "İki kalenin farklı sergi/manzara deneyimini ayrı saate bölün; etkinlik bileti ve sıcağı planlayın."], ["Aziz Anthony Kanalı", "Yürüyüş/bisiklet rotasında güneş, su ve ulaşımı ayarlayın; askerî/kapalı yapılara girmeyin."]],
    areas: [["Eski şehir ve Dolac", "Katedral, kale ve akşam için atmosferik; dik basamak ve park sorunu vardır."], ["Mandalina veya Brodarica", "Marina/plaj ve daha sakin konaklama için otobüs/araç bağlantılı alternatif."]], foods: [["Skradinski risotto", "Saatlerce pişen et yemeğini ön sipariş, minimum kişi ve içerikle doğrulayın."], ["Dalmaçya deniz ürünleri", "Kabuklu/balıkta tür, gramaj ve toplam fiyatı siparişten önce sorun."]], dayTrips: [["Krka Milli Parkı", "Doğru giriş, shuttle/tekne, yüzme yasağı, saatli bilet ve kalabalığı resmî park kaynağından kontrol edin."], ["Kornati", "Lisanslı tekne, park ücreti, hava ve süreyi yazılı doğrulayın; kısa satış turunu tam park keşfi sanmayın."]], caution: "Kale merdivenleri ve parlak taş yağmurda kayar. Krka'da yalnız açık rota ve izinli alanı kullanın; tekne kapasitesi/can yeleğini sorun, orman yangını duyurusuna eksiksiz uyun."
  },
];

export const croatiaGuides = makeRegionalGuides(profiles);
