import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Prag", countryCode: "CZ", focus: "Prag Kalesi, tarihî merkez ve mahalle rotaları", lede: "Vltava'nın iki yakasında Gotik kuleleri, Barok sarayları, kübist ayrıntıları ve yaşayan mahalleleri bir araya getiren Çek başkenti.", days: "4–5 gün", arrival: "PRG · Praha hl.n. · Praha-Holešovice", local: "Metro, tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Prag'ın merkez simgeleri olağanüstüdür; fakat şehir yalnız Astronomik Saat ile Karl Köprüsü değildir. Letná, Holešovice, Karlín ve Vinohrady, turistik çekirdeğin dışındaki çağdaş ritmi gösterir.",
    sights: [["Prag Kalesi ve Aziz Vitus", "Katedral, Eski Kraliyet Sarayı ve Altın Yol'un bilet kapsamını okuyun; güvenlik kuyruğu ve tören kapanışı için sabah erken çıkın."], ["Eski Şehir ve Yahudi Mahallesi", "Meydanı Josefov sinagoglarıyla aynı güne koyabilirsiniz; Yahudi Müzesi'nin çok yapılı bileti, Şabat ve dinî gün takvimini önceden kontrol edin."], ["Karl Köprüsü ve Malá Strana", "Köprüyü gün doğumuna yakın yürüyün; Kampa, Lennon Duvarı ve Petřín'i enerjiye göre aynı yaka rotasında birleştirin."]],
    areas: [["Staré Město ve Malá Strana", "İlk ziyaret ve tarihî yerlere yürüme kolaylığı yüksek; gece gürültüsü ile restoran fiyatı sokaktan sokağa değişir."], ["Vinohrady, Karlín ve Holešovice", "Kafe, pazar, tasarım ve daha yerel akşamlar için tramvay/metro bağlantılı güçlü alternatifler."]], foods: [["Svíčková ve knedlík", "Krema-kök sebze soslu et yemeğinde porsiyon ve içerik ağır olabilir; yarım porsiyon veya gün ortası menüsü sorun."], ["Çek bira kültürü", "Pilsner ve tank birasını ölçülü tadın; masaya otomatik yenisi gelebilen geleneksel servis biçiminde hesabı kapatmak istediğinizi açıkça belirtin."]], dayTrips: [["Karlštejn", "Trenle kaleye yürüyüşlü kolay gün; iç mekân turu, rota dili ve Pazartesi/mevsim kapanışını resmî siteden doğrulayın."], ["Kutná Hora", "Sedlec ile tarihî merkezi aynı gün için tren/yerel otobüsle bağlayın; iki farklı istasyon ve son dönüşü not edin."]], caution: "Merkezde döviz bürosu ve bağımsız ATM'nin oran/komisyonunu işlemden önce okuyun; terminalde CZK seçin. Astronomik Saat çevresinde yankesiciliğe, gece takside sahte uygulama ve aşırı ücrete karşı resmî kanal kullanın."
  },
  {
    city: "Český Krumlov", countryCode: "CZ", focus: "UNESCO eski şehir, kale ve Vltava kıvrımı", lede: "Vltava'nın keskin kıvrımı içinde Rönesans kalesi, boyalı cepheler ve Güney Bohemya peyzajıyla korunan masalsı ama yaşayan kasaba.", days: "2–3 gün", arrival: "Český Krumlov otobüs terminali · České Budějovice aktarması", local: "Yürüyüş, bölgesel otobüs ve mevsimlik kano", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Günübirlik otobüsler kasabayı öğlen yoğunlaştırır. En iyi Krumlov deneyimi, kalabalık çekildikten sonra nehir kıyısında kalmak ve sabah ilk ışıkta kale çevresini yürümektir.",
    sights: [["Český Krumlov Kalesi", "Kule, müze, Barok tiyatro ve rehberli daireler farklı biletlerdir; Barok tiyatro kapasitesi sınırlı olduğundan erken rezervasyon yapın."], ["Latrán ve eski şehir", "Boyalı cepheleri, Egon Schiele Art Centrum'u ve küçük avluları ana meydandan nehir kıyısına yavaş bir rota halinde gezin."], ["Vltava seyri", "Kano veya rafting yalnız su seviyesi, hava ve lisanslı işletme uygunsa yapılmalı; can yeleği ile savak talimatını ciddiye alın."]],
    areas: [["Staré Město ve Latrán", "Ana yerlere yürüyerek ulaşmak ve akşam atmosferini yaşamak için en güçlü üs."], ["Horní Brána ve Plešivec", "Otobüs durağı/otoparka daha yakın, daha sakin ve çoğu zaman fiyatı dengeli konaklama seçeneği."]], foods: [["Güney Bohemya mutfağı", "Tatlı su balığı, mantar ve doyurucu sosları mevsimlik menüde arayın; balığın türü ile menşeini sorun."], ["Medovník ve yerel fırınlar", "Ballı katlı pastayı kahveyle paylaşın; yalnız turistik meydandaki trdelník kuyruğunu yerel mutfağın tamamı sanmayın."]], dayTrips: [["České Budějovice", "Büyük meydan, Kara Kule ve Budvar ziyaretini tren/otobüsle ayrı güne bağlayın; fabrika turu rezervasyonludur."], ["Hluboká nad Vltavou", "Şato turu ile Vltava bisiklet rotasını hava ve son otobüse göre planlayın."]], caution: "Arnavut kaldırımı ve dik kale rampası valiz/erişilebilirlik için zordur. Nehir etkinliğini alkollü yapmayın; kasabayı drone ve özel balkon fotoğrafı için izinsiz kullanmayın."
  },
  {
    city: "Brno", countryCode: "CZ", focus: "modern mimari, Moravya kültürü ve yeraltı tarihi", lede: "Špilberk tepesi, işlevselci mimari, canlı üniversite sokakları ve Güney Moravya bağlarıyla Prag'dan farklı bir şehir temposu.", days: "2–4 gün", arrival: "Brno hlavní nádraží · BRQ", local: "Tramvay, troleybüs, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Brno kendini büyük anıtlarla değil, tasarım, kahve, bilim ve Moravya şarap kültürünün birlikte aktığı kompakt mahallelerle açar.",
    sights: [["Villa Tugendhat", "UNESCO villanın iç mekân turları aylar önce dolabilir; saatli bileti resmî kanaldan alın ve fotoğraf/ayakkabı kuralını okuyun."], ["Špilberk Kalesi", "Habsburg hapishane tarihi, kasematlar ve şehir manzarası için tepeye yarım gün ayırın; sergi biletlerini ayırın."], ["Zelný trh ve Brno yeraltı", "Sebze Pazarı, Labirent ve Capuchin Crypt'i içerik ile çalışma saatine göre seçin; dar/kapalı alan herkese uygun değildir."]],
    areas: [["Brno-střed", "İstasyon, pazar, katedral ve gece hayatına yürüyüş için ilk ziyarette pratik."], ["Černá Pole ve Veveří", "Villa Tugendhat, parklar, üniversite ve daha yerel kafe akşamları için tramvaylı alternatif."]], foods: [["Moravya yemekleri", "Ördek, lahana ve knedlík doyurucudur; gün ortası menüsüyle küçük porsiyon deneyin."], ["Moravya şarapları", "Pálava ve Riesling tadımında üretici, ölçü ve dönüşü planlayın; tadım sonrası araç kullanmayın."]], dayTrips: [["Moravya Karstı", "Macocha ve Punkva Mağarası için tren–otobüs, saatli mağara bileti ve son bağlantı gerekir."], ["Mikulov", "Kale, Yahudi mirası ve Pálava bağları için trenle ayrı gün; bağ dönüşünü önceden sabitleyin."]], caution: "Villa Tugendhat için üçüncü taraf bilet almayın. Yeraltı rotasında klostrofobi ve basamakları, bağ gününde alkol ile ulaşımı; gece merkezde tramvay hattı değişikliklerini önceden değerlendirin."
  },
  {
    city: "Karlovy Vary", countryCode: "CZ", focus: "kaplıca kolonadları, mimari ve orman yürüyüşleri", lede: "Teplá vadisinde renkli spa yapıları, sıcak kaynaklar, porselen ve orman seyirleriyle Bohemya'nın tarihî kaplıca kenti.", days: "2–3 gün", arrival: "Karlovy Vary terminal · KVY · Prag'dan otobüs", local: "Yürüyüş, otobüs ve Diana füniküleri", best: "Mayıs–Haziran · Eylül–Ekim · kış spa dönemi", pulse: "Karlovy Vary yalnız kolonaddan sıcak su içmek değildir; vadinin üstündeki yürüyüşler, Moser camı ve spa tarihinin sosyal mimarisi kenti tamamlar.",
    sights: [["Mill ve Market Kolonadları", "Kaynak sıcaklıklarını resmî tabeladan okuyun; tadımı küçük miktarla ve yalnız sağlık durumunuz uygunsa yapın."], ["Diana seyir kulesi", "Füniküler veya orman yürüyüşüyle çıkın; son iniş, bakım ve sis durumunu aynı gün kontrol edin."], ["Moser Cam Müzesi", "Fabrika turu ile müze farklı olabilir; sıcak üretim hattı, yaş ve güvenlik koşullarını rezervasyonda sorun."]],
    areas: [["Spa merkezi ve Teplá kıyısı", "Kolonad, müze ve akşam yürüyüşüne yakın; festival döneminde fiyat ve kalabalık yüksektir."], ["Tuhnice ve Drahovice", "Terminal veya daha yerel konaklama için otobüs bağlantılı, daha sakin seçenekler."]], foods: [["Lázeňské oplatky", "Ilık servis edilen ince spa gofretlerinde fındık/süt alerjenini sorun; yerel üreticiyi seçin."], ["Becherovka", "Bitkisel likör kültürünü müze/tadımda ölçülü deneyin; kaplıca tedavisi veya araçla birleştirmeyin."]], dayTrips: [["Loket", "Nehir kıvrımındaki kale kasabasına otobüs veya bisikletle gidin; kale saati ve son dönüşü kaydedin."], ["Mariánské Lázně", "Bir başka UNESCO spa kentini trenle görün; aynı günde bütün kolonadları aceleyle toplamaya çalışmayın."]], caution: "Kaplıca suyunu tedavi gibi kullanmadan önce doktorunuza danışın; çok sıcak suyu hızla veya fazla içmeyin. Film festivali döneminde konaklama/ulaşımı erken sabitleyin, ormanda işaretli patikadan çıkmayın."
  },
  {
    city: "Kutná Hora", countryCode: "CZ", focus: "Azize Barbara, Sedlec ve gümüş madeni tarihi", lede: "Orta Çağ gümüş zenginliğini görkemli katedral, dar sokaklar, kraliyet darphanesi ve Sedlec'in güçlü hafıza mekânlarıyla anlatan UNESCO kenti.", days: "1–2 gün", arrival: "Kutná Hora hl.n. · Kutná Hora město", local: "Yürüyüş, yerel tren ve otobüs", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Kutná Hora iki ayrı gezi kümesidir: Sedlec ana gara yakın, Azize Barbara ile tarihî merkez ise birkaç kilometre uzaktadır. Doğru istasyon seçimi günü belirler.",
    sights: [["Azize Barbara Katedrali", "Geç Gotik mimariyi Cizvit Koleji terasıyla birleştirin; ayin ve konser nedeniyle erişimi resmî takvimden kontrol edin."], ["Sedlec Ossuary", "İnsan kalıntıları bulunan kutsal mekânda sessizlik, kıyafet ve fotoğraf kuralına uyun; dekor/eğlence dili kullanmayın."], ["İtalyan Sarayı ve gümüş tarihi", "Darphane turu ile orta çağ maden turunu ayırın; yeraltı rotası için kıyafet, yaş ve hareket koşulunu okuyun."]],
    areas: [["Tarihî merkez", "Katedral, koleje ait teraslar ve restoranlar için atmosferik geceleme üssü."], ["Sedlec ve ana gar", "Ossuary ile tren bağlantısına yakın; merkez için yerel tren/otobüs gerekir."]], foods: [["Çek günlük menüsü", "Çorba, ana yemek ve içecekli polední menu hafta içi bütçe dostudur; servis saatini sorun."], ["Bohemya tatlıları", "Koláče ve meyveli hamur işlerinde taze günlük üretim ile alerjeni kontrol edin."]], dayTrips: [["Kačina Şatosu", "Ampir saray ve tarım müzesine sezonluk ulaşım/servis nedeniyle ön plan yapın."], ["Kolín", "Elbe kıyısı, sinagog ve tarihî merkez için kısa trenle sakin bir ek durak."]], caution: "Sedlec'te insan kalıntılarına dokunmayın, flaş/selfie davranışını güncel kurala göre sınırlayın. Maden turunda verilen koruyucu ekipmanı çıkarmayın; ana gar ile şehir istasyonunu karıştırmayın."
  },
  {
    city: "Olomouc", countryCode: "CZ", focus: "Barok miras, üniversite ve Moravya mutfağı", lede: "UNESCO Barok sütunu, astronomik saat, çeşmeler ve güçlü öğrenci hayatıyla Moravya'nın kompakt ve az acele edilen kültür şehri.", days: "2–3 gün", arrival: "Olomouc hlavní nádraží", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Olomouc, Prag'ın kalabalığından kaçış etiketiyle geçiştirilmeyecek kadar zengindir; başpiskoposluk, üniversite ve pazar kültürü kent merkezinde iç içedir.",
    sights: [["Kutsal Üçlü Sütunu", "UNESCO anıtını Horní náměstí çeşmeleri ve belediye binasıyla açık hava rotasında okuyun; restorasyon bariyerlerine uyun."], ["Astronomik Saat ve belediye binası", "Sosyalist gerçekçi kadranın öğle gösterisini güncel saatten kontrol edin; kule turu ayrı olabilir."], ["Başpiskoposluk Müzesi", "Romanesk saraydan resim koleksiyonuna uzanan alan için katedral ziyaretiyle en az yarım gün ayırın."]],
    areas: [["Horní ve Dolní náměstí", "Meydan, pazar, kafe ve tramvay için ilk ziyarette kolay merkez."], ["Üniversite ve park kuşağı", "Öğrenci lokantaları, sur parkları ve daha sakin konaklama için yürünebilir alternatif."]], foods: [["Olomoucké tvarůžky", "Keskin kokulu korumalı peyniri küçük porsiyon ve doğru saklamayla deneyin; süt alerjenini not edin."], ["Moravya hamur işleri", "Frgál, koláče ve mevsim meyveli ürünleri fırından alın; dolgu ile alerjeni sorun."]], dayTrips: [["Bouzov Kalesi", "Masalsı kale için sezon, tur dili ve seyrek otobüsü önceden eşleştirin."], ["Litovel ve Litovelské Pomoraví", "Bira şehri ile sulak alan bisiklet/yürüyüşünü hava ve koruma kuralıyla planlayın."]], caution: "Kilise ve başpiskoposluk yapılarında ibadet saatine uyun. Tvarůžky gibi süt ürününü soğuk zincirsiz taşımayın; park/sulak alanda taşkın veya kene duyurusunu kontrol edin."
  },
  {
    city: "Plzeň", countryCode: "CZ", focus: "Pilsner tarihi, yeraltı ve Batı Bohemya mimarisi", lede: "Düzenli Orta Çağ planını büyük sinagog, sanayi mirası, tarihî yeraltı ve dünyaya yayılan Pilsner bira geleneğiyle birleştiren kent.", days: "2–3 gün", arrival: "Plzeň hlavní nádraží", local: "Tramvay, troleybüs, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim · Aralık", pulse: "Plzeň'in bira markası şehrin tamamını gölgede bırakmamalı; sinagog, Adolf Loos iç mekânları ve yeraltı ağı modern Çek tarihinin farklı yüzlerini açar.",
    sights: [["Pilsner Urquell Bira Fabrikası", "Rehber dili ve üretim turunu önceden ayırın; mahzen soğuktur, tadım yaş sınırı ve ulaşım planı gerektirir."], ["Büyük Sinagog", "Mimari, cemaat tarihi ve konser programını saygılı ziyaretle görün; dinî gün ve fotoğraf kuralını kontrol edin."], ["Plzeň tarihî yeraltı", "Dar, serin ve basamaklı rotaya uygun ayakkabıyla katılın; kask ile rehber talimatına uyun."]],
    areas: [["Náměstí Republiky ve merkez", "Katedral, yeraltı ve müzelere yürüyüş için en işlevsel üs."], ["Bory ve Slovany", "Daha yerel restoran, park ve tramvay bağlantılı sakin konaklama alternatifleri."]], foods: [["Pilsner servis kültürü", "Hladinka, šnyt ve mlíko gibi köpük oranlarını öğrenin; ölçülü için ve servis çentiğini takip edin."], ["Chod ve Batı Bohemya yemekleri", "Et, mantı/knedlík ve lahana ağırlıklı tabaklarda porsiyonu paylaşın; vejetaryen içeriği açıkça sorun."]], dayTrips: [["Kozel Şatosu", "Neoklasik şato ve park için sezonluk tur ile otobüs/taksi dönüşünü planlayın."], ["Klatovy", "Katakomblar, barok eczane ve meydan için bölgesel trenle ayrı sakin gün."]], caution: "Fabrika tadımı sonrası araç veya bisiklet kullanmayın. Sinagogda güvenlik ve ibadet kurallarına, yeraltında koruyucu ekipmana uyun; maç/festival gününde tramvay değişikliğini kontrol edin."
  },
  {
    city: "Bohemya İsviçresi", countryCode: "CZ", focus: "kumtaşı kemerleri, kanyonlar ve milli park yürüyüşleri", lede: "Elbe'nin kuzeyinde kumtaşı kuleleri, orman vadileri, nehir geçitleri ve sınır ötesi Saksonya manzaralarıyla şekillenen koruma alanı.", days: "3–5 gün", arrival: "Děčín · Hřensko otobüs/tekne bağlantısı", local: "Bölgesel tren, otobüs, yürüyüş ve mevsimlik tekne", best: "Mayıs–Haziran · Eylül–Ekim", pulse: "Bohemya İsviçresi tek bir fotoğraf noktası değildir. Hřensko, Jetřichovice ve Děčín farklı rota kapılarıdır; yangın sonrası yenilenme ve dönemsel kapanışlar planın merkezinde olmalıdır.",
    sights: [["Pravčická brána", "Doğal kemere işaretli rota ve özel alan giriş koşuluyla ulaşılır; açıklık, son giriş ve yangın kısıtını aynı gün doğrulayın."], ["Edmund Kanyonu", "Tekne ve yürüyüş bölümleri su, bakım ve heyelan nedeniyle kapanabilir; yalnız resmî açık rota bilgisini kullanın."], ["Jetřichovice seyirleri", "Mariina skála ve çevre seyirleri dik basamaklıdır; hava, gün ışığı ve zemine uygun ayakkabı gerekir."]],
    areas: [["Hřensko ve Mezní Louka", "Pravčická brána/kanyon için ana kapı; son otobüs ve taşkın riskini kontrol edin."], ["Děčín ve Jetřichovice", "Tren bağlantılı şehir üssü veya daha sakin doğu patikaları için iki farklı alternatif."]], foods: [["Kuzey Bohemya mutfağı", "Mantar, patates ve orman ürünü temelli yemeklerde kaynağı sorun; yabani mantarı uzman olmadan toplamayın."], ["Yürüyüş öğünü", "Su ve enerji yiyeceğini Děčín/Hřensko'da tamamlayın; patika üzerindeki büfelerin açık olacağını varsaymayın."]], dayTrips: [["Saksonya İsviçresi", "Almanya'daki Bastei yönü sınır ötesi tren/otobüsle mümkündür; Schengen belgesi, dolaşım ve son dönüşü taşıyın."], ["Děčín", "Şato, Elbe kıyısı ve Pastýřská stěna manzarasıyla kötü hava veya geçiş günü için dengeli üs."]], caution: "Yangın, kuraklık, kaya düşmesi ve heyelan nedeniyle kapalı patikaya kesinlikle girmeyin; ateş yakmayın ve sigara kuralına uyun. Kanyon teknesi veya sınır rotasını eski blogdan değil parkın günlük duyurusundan doğrulayın."
  },
];

export const czechiaGuides = makeRegionalGuides(profiles);
