import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Kopenhag", countryCode: "DK", focus: "saraylar, tasarım, kanallar ve bisiklet şehri", lede: "Rönesans saraylarını çağdaş Nordik tasarım, liman yüzme kültürü, güçlü müzeler ve bisiklet öncelikli mahallelerle birleştiren Danimarka başkenti.", days: "4–6 gün", arrival: "CPH · København H · liman terminalleri", local: "Metro, S-tren, otobüs, liman otobüsü, bisiklet ve yürüyüş", best: "Mayıs–Eylül · Noel atmosferi için Aralık", pulse: "Kopenhag yalnız Nyhavn renkleri ve Küçük Deniz Kızı değildir. Christiansborg'un siyaset tarihini, Rosenborg'un kraliyet koleksiyonunu, Nørrebro ile Vesterbro'nun gündelik yaşamını ve modern liman dönüşümünü aynı sürdürülebilir ulaşım ağıyla okuyun.",
    sights: [["Christiansborg ve Slotsholmen", "Saray salonu, kule, mutfak, harabe ve Parlamento erişiminin ayrı saat/biletleri olabileceğini kontrol edin."], ["Rosenborg ve SMK", "Kraliyet hazinesini Ulusal Galeri ile aynı gün sıkıştırmadan gezin; dolap, fotoğraf ve saatli giriş kurallarını doğrulayın."], ["Nyhavn, kanal ve liman mimarisi", "Kanal turunda iskele, dil, tekne tipi ve rota değişikliğini sorun; Nyhavn'da yalnız vitrin menüsüyle seçim yapmayın."]],
    areas: [["Indre By, Christianshavn veya Vesterbro", "İlk ziyaret, kanal ve istasyon için pratik; merkez pahalı, Vesterbro hafta sonu hareketlidir."], ["Nørrebro, Frederiksberg veya Østerbro", "Mahalle yemeği, park ve daha sakin konaklama için metro/bisikletle güçlü alternatifler."]], foods: [["Smørrebrød", "Çavdar ekmeği üzerindeki balık/et, sos ve alerjenleri sorun; öğlen servisi ve rezervasyon saatini kontrol edin."], ["Wienerbrød ve yeni Nordik mutfak", "Fırında tereyağı/yumurta/kuruyemişi; tadım menüsünde içecek, servis ve iptal koşulunu doğrulayın."]], dayTrips: [["Louisiana Museum", "Humlebæk treninden sonra kısa yürüyüş vardır; sergi, bahçe ve kapanış saatini kontrol ederek yarım günden fazla ayırın."], ["Roskilde", "Trenle katedral ve Viking Gemi Müzesi'ni gezin; iki kurumun saatini ayrı doğrulayın."]], caution: "Bisiklet şeridinde yürümeyin; dönüşte kol işareti ve ışık kuralını bilmeden yoğun trafikte bisiklet kiralamayın. Liman yüzmesini yalnız izinli, açık alanda yapın; su sıcaklığı, akıntı ve su kalitesi uyarısına uyun."
  },
  {
    city: "Aarhus", countryCode: "DK", focus: "ARoS, açık hava tarihi ve genç liman kültürü", lede: "Danimarka'nın ikinci şehrinde ARoS'un çağdaş sanatını Den Gamle By'nin yaşayan tarihi, Moesgaard'ın arkeolojisi, Latin Quarter ve dönüşen limanla birleştiren kültür rotası.", days: "3–4 gün", arrival: "AAR/BLL · Aarhus H · feribot terminali", local: "Letbane, otobüs, bisiklet ve yürüyüş", best: "Mayıs–Eylül · kültür için yıl boyu", pulse: "Aarhus kompakt merkezinden büyük müzelere ve kıyı doğasına açılır. ARoS ile Den Gamle By'yi aynı yarım güne sığdırmak koleksiyonları yüzeyselleştirir; Moesgaard ise şehir dışındaki mimarisi ve tarih öncesi anlatısıyla başlı başına bir gündür.",
    sights: [["ARoS", "Güncel sergi, çatı yürüyüşü ve geç saat programını kontrol edin; renkli panoramayı müzenin tek amacı sanmayın."], ["Den Gamle By", "Tarihî dönemleri kronolojik seçin; yaşayan müze programı, erişilebilirlik ve kışın açık ev sayısını doğrulayın."], ["Moesgaard Museum", "Otobüs bağlantısı, saatli sergi ve sahil/orman yürüyüşünü birlikte planlayın; arkeolojik insan kalıntılarına saygıyla yaklaşın."]],
    areas: [["Midtbyen ve Latin Quarter", "İlk ziyaret, restoran ve kültür için yürünebilir; hafta sonu gürültüsü olabilir."], ["Frederiksbjerg, Trøjborg veya Aarhus Ø", "Yemek pazarı, mahalle yaşamı ya da çağdaş liman mimarisi için farklı karakterler."]], foods: [["Smørrebrød ve balık", "Balık/et türü, çavdar ekmeği içeriği ve porsiyonu sorun; öğle saatini kaçırmayın."], ["Aarhus Street Food ve fırınlar", "Tezgâhta alerjen, ortak fritöz ve et tedarikini doğrudan sorun; yoğun saatte masa garantisi beklemeyin."]], dayTrips: [["Ebeltoft", "Otobüs veya araçla eski şehir ve Fregatten Jylland'ı gezin; müze ile son dönüş saatini kontrol edin."], ["Silkeborg ve Göller", "Tren/otobüs, müze, tekne veya orman rotasından yalnız iki odak seçin; mevsimsel seferi doğrulayın."]], caution: "Liman inşaatı ve bisiklet trafiğinde işaretli yola uyun; denize yalnız izinli alandan girin. Moesgaard kıyısında hava hızla değişebilir; müze kapanışına güvenerek son otobüsü kaçırmayın."
  },
  {
    city: "Odense", countryCode: "DK", focus: "Hans Christian Andersen, Funen ve bisiklet kültürü", lede: "Hans Christian Andersen'in doğduğu kenti yenilikçi müzecilik, tarihî sokaklar, sakin bisiklet ağı ve Funen'in şato–köy peyzajıyla birleştiren ada merkezi.", days: "2–4 gün", arrival: "Odense Banegård · CPH/BLL bağlantısı", local: "Letbane, otobüs, tren, bisiklet ve yürüyüş", best: "Nisan–Eylül", pulse: "Odense'yi yalnız Andersen masallarıyla sınırlamayın. Yeni müzenin mimarisi, Møntergården'in kent tarihi, Brandts'ın çağdaş kültürü ve liman dönüşümü birlikte yürünebilir. Funen kırsalı için toplu taşıma veya bisiklet mesafesini gerçekçi planlayın.",
    sights: [["H.C. Andersen Hus", "Saatli bileti, sesli anlatım dilini ve çocuklu/çocuksuz ziyaret akışını kontrol edin; doğum evi ile ana müzenin ayrımını bilin."], ["Møntergården ve eski sokaklar", "Tarihî evleri seçerek gezin; avlu, geçici sergi ve kapalı bina saatlerini doğrulayın."], ["Brandts ve liman", "Sanat/kültür merkezini güncel sergiye göre planlayın; limanda aktif bisiklet ve dönüşüm alanlarına dikkat edin."]],
    areas: [["Centrum", "Müze, istasyon ve restoranlara yürüyüş için en kolay üs."], ["Skibhus, liman veya Fruens Bøge", "Yerel yaşam, çağdaş kıyı ya da yeşil alan için letbane/otobüslü alternatifler."]], foods: [["Brunsviger", "Funen'in şekerli mayalı kekini taze fırında deneyin; tereyağı/süt içeriğini ve porsiyonu sorun."], ["Funen çiftlik ürünleri", "Peynir, elma ve mevsim tabağında üretici/alerjeni kontrol edin; kırsal çiftlik dükkânının saatini doğrulayın."]], dayTrips: [["Egeskov Şatosu", "Tren/otobüs/son kilometre, sezon, bahçe ve sergi saatini birlikte planlayın; tam gün ayırın."], ["Kerteminde", "Otobüsle kıyı kasabası ve Viking müzesi deneyimini mevsimsel saatlere göre birleştirin."]], caution: "Bisikletle kırsala çıkarken rüzgâr, görünürlük, yağmur ve dönüş trenindeki bisiklet kuralını kontrol edin. Andersen temalı ticari noktaları resmî müzeyle karıştırmayın; çocuk etkinliğinde yaş/dil uygunluğunu önceden sorun."
  },
  {
    city: "Aalborg", countryCode: "DK", focus: "Limfjord, Viking mirası ve kuzey tasarımı", lede: "Limfjord kıyısındaki endüstri dönüşümünü Utzon mimarisi, çağdaş sanat, canlı merkez ve Lindholm Høje'nin Viking öncesi mezarlığıyla birleştiren Kuzey Jutland şehri.", days: "2–4 gün", arrival: "AAL · Aalborg station", local: "Otobüs, bölgesel tren, bisiklet ve yürüyüş", best: "Mayıs–Eylül", pulse: "Aalborg'un merkezi küçük, tarih katmanları geniştir. Eski sanayi kıyısı, Utzon Center ve Musikkens Hus çağdaş yüzü; Lindholm Høje ile tarih müzesi ise fiyordun daha eski yerleşim katmanını gösterir. Jomfru Ane Gade gece hayatını şehrin tamamı sanmayın.",
    sights: [["Utzon Center ve kıyı", "Güncel mimarlık/tasarım sergisini kontrol edin; kamusal kıyı rotasını Musikkens Hus'a uzatın."], ["Kunsten", "Alvar Aalto yapısını koleksiyonla birlikte gezin; bahçe, atölye ve geçici sergi saatini doğrulayın."], ["Lindholm Høje", "Mezarlık alanını müzeyle birlikte görün; höyük/taşlara basmayın, rüzgâr ve otobüs dönüşünü planlayın."]],
    areas: [["Centrum ve waterfront", "Müze, restoran ve istasyon için yürünebilir; bar sokağı çevresi gece gürültülüdür."], ["Vestbyen veya Nørresundby", "Yerel konut dokusu, park ve Lindholm yönü için otobüs/bisiklet bağlantılı alternatifler."]], foods: [["Limfjord deniz ürünleri", "Midye, istiridye ve balığın kaynağı ile alerjenini sorun; toplama alanından kendiniz ürün almayın."], ["Danimarka ev yemekleri", "Et, sos ve süt içeriğini sorun; öğle menüsü ile fırın sandviçi bütçe açısından dengelidir."]], dayTrips: [["Rebild Bakker", "Otobüs/araç, yürüyüş rotası ve hava durumunu kontrol ederek fundalık ve orman günü planlayın."], ["Skagen", "Trenle uzun ama mümkün bir gündür; Grenen ulaşımı ve son dönüş yüzünden geceleme daha rahat olabilir."]], caution: "Jomfru Ane Gade'de içeceğinizi gözetin ve gece dönüşünü planlayın. Limfjord kıyısında rüzgâr, bisiklet köprüsü ve kaygan yüzeylere; Lindholm Høje'de koruma sınırlarına dikkat edin."
  },
  {
    city: "Ribe", countryCode: "DK", focus: "Orta Çağ sokakları, Viking tarihi ve Wadden Denizi", lede: "Danimarka'nın en eski kent dokularından birini katedral kulesi, Viking yorum merkezleri, taşkın hikâyeleri ve UNESCO Wadden Denizi'nin gelgit doğasıyla birleştiren küçük şehir.", days: "2–3 gün", arrival: "Ribe station · Esbjerg/Billund bağlantısı", local: "Tren, otobüs, bisiklet, yürüyüş ve doğa turu", best: "Nisan–Eylül · kuş göçü için ilkbahar/sonbahar", pulse: "Ribe'nin renkli sokakları bir günlük fotoğraf fonundan fazlasıdır. Katedral ve taşkın sütunları, Viking merkezi ile müzesi, gece bekçisi geleneği ve Wadden Denizi'nin gelgit takvimi aynı bölgede bin yılı aşan yaşam uyumunu gösterir.",
    sights: [["Ribe Katedrali", "Kule erişimi, ibadet ve etkinlik saatini kontrol edin; dar merdiven ve hava koşulunu değerlendirin."], ["Museet Ribes Vikinger ve VikingCenter", "Kent müzesi ile canlandırma merkezinin farklı konum/sezonlarını ayırın; gösteri ve ulaşımı önceden doğrulayın."], ["Wadden Sea Centre", "Gelgit, kuş gözlemi ve çamur düzlüğüne yalnız resmî bilgi/rehberle yaklaşın; ziyaretçi merkezinin programını kontrol edin."]],
    areas: [["Ribe eski şehir", "Katedral, müze ve akşam yürüyüşü için ideal; oda ve restoran sayısı sınırlıdır."], ["Esbjerg veya Mandø bağlantısı", "Bölgesel ulaşım ya da doğa turu için alternatif; gelgit ve son araç/otobüs belirleyicidir."]], foods: [["Stjerneskud ve balık", "Balık türü, kızartma yağı, karides ve sos alerjenini sorun; günlük yakalama iddiasını doğrulayın."], ["Rugbrød ve fırın tatlıları", "Çavdar ekmeği, tereyağı ve kuruyemiş içeriğini kontrol edin; küçük işletme saatini önceden görün."]], dayTrips: [["Mandø", "Gelgit yolunu yalnız yetkili araç/tur ve güncel saatle geçin; kendi aracınızla tahmine dayalı deneme yapmayın."], ["Esbjerg", "Trenle denizcilik müzesi ve sahil heykellerini gezin; rüzgâr ve müze saatini planlayın."]], caution: "Wadden Denizi'nde gelgit çok hızlı yükselir; çamur düzlüğüne rehbersiz çıkmayın. Tarihî sokaklarda yaşayan evlerin mahremiyetine saygı gösterin, katedral kulesinde tek yön/kapasite ve gece bekçisi yürüyüşünde grup kurallarına uyun."
  },
  {
    city: "Skagen", countryCode: "DK", focus: "iki deniz, ressamlar ve kumul peyzajı", lede: "Jutland'ın kuzey ucunda Skagerrak ile Kattegat'ın buluşmasını Skagen ressamları, sarı evler, göçen kumullar ve güçlü kıyı ışığıyla birleştiren sanat kasabası.", days: "2–4 gün", arrival: "Skagen station · Aalborg bağlantısı", local: "Tren, otobüs, bisiklet, yürüyüş ve shuttle", best: "Mayıs–Eylül", pulse: "Skagen'i Grenen'de iki denize ayak basma gösterisine indirgemeyin. Sanat müzesindeki ışık araştırması, Anchers Hus, batık kilise ve Råbjerg Mile kıyının sürekli değişimini anlatır. Kuzey ucundaki akıntı fotoğraftan çok daha güçlüdür.",
    sights: [["Grenen", "İşaretli kıyı alanına yürüyün veya Sandormen kullanın; denizlerin birleştiği akıntıya girmeyin, hava ve son shuttle'ı kontrol edin."], ["Skagens Museum ve Anchers Hus", "Tek bilet/ayrı giriş düzenini, rehberli tur ve açık evi kontrol ederek sanatçı kolonisini bağlamıyla gezin."], ["Den Tilsandede Kirke ve Råbjerg Mile", "Batık kilise ile göçen kumulu araç/bisikletle ayırın; koruma rotasından çıkmayın ve kuma çöp bırakmayın."]],
    areas: [["Skagen merkezi ve liman", "Müze, tren ve restoranlara yakın; yazın pahalı ve kalabalık."], ["Gl. Skagen veya Ålbæk", "Gün batımı, sahil ya da daha sakin konaklama için bisiklet/tren bağlantılı alternatifler."]], foods: [["Skagen karidesi ve balık", "Kabuklu deniz ürününün kaynağı, gramajı ve alerjeni sorun; liman menüsünde toplam fiyatı doğrulayın."], ["Yerel dondurma ve fırın ürünleri", "Süt, yumurta ve kuruyemiş içeriğini sorun; yoğun yaz sırasını ana gezi saatine koymayın."]], dayTrips: [["Frederikshavn", "Trenle liman, Bangsbo ve kıyı günü planlayın; İsveç/Norveç feribotunu şehir içi tekne sanmayın."], ["Læsø", "Frederikshavn aktarmalı ada yolculuğu uzun ve mevsimseldir; günübirlik yerine gecelemeyi değerlendirin."]], caution: "Grenen'de yüzmek tehlikelidir; dalga ve akıntı uyarısını ihlal etmeyin. Kumulda rüzgâr/görüş hızla değişebilir; bisiklet yolunda görünür olun ve özel yazlık evlerin avlularına fotoğraf için girmeyin."
  },
  {
    city: "Bornholm", countryCode: "DK", focus: "Baltık adası, kaleler ve yuvarlak kiliseler", lede: "Baltık Denizi'ndeki kayalık kıyıları Hammershus kalıntıları, yuvarlak kiliseler, Gudhjem–Svaneke limanları, tütsühaneler ve güçlü bisiklet ağıyla birleştiren ada rotası.", days: "4–7 gün", arrival: "RNN · Rønne feribot terminali", local: "Bölgesel otobüs, bisiklet, araç, feribot ve yürüyüş", best: "Mayıs–Eylül", pulse: "Bornholm Kopenhag'dan kısa bir ada kaçamağı gibi görünse de Rønne, kuzey kaleleri, doğu limanları ve güney kumsalları ayrı kümelerdir. İsveç üzerinden hızlı feribot uluslararası kara bağlantısı yaratır; belge, tren ve liman aktarmasını birlikte planlayın.",
    sights: [["Hammershus", "Kale kalıntısını ziyaretçi merkeziyle gezin; uçurum kenarı, gevşek taş, rüzgâr ve otobüs/park erişimini kontrol edin."], ["Østerlars ve yuvarlak kiliseler", "İbadet, cenaze ve tur saatine saygı gösterin; dört kiliseyi aynı gün kontrol listesine çevirmeyin."], ["Gudhjem, Svaneke ve kıyı", "İki liman kasabasından birini uzun öğünle gezin; bisiklet mesafesi ve son otobüsü gerçekçi hesaplayın."]],
    areas: [["Rønne", "Feribot, otobüs ve temel hizmetler için en işlevsel üs."], ["Gudhjem, Allinge veya Svaneke", "Kuzey/doğu kıyısı, liman ve daha yavaş ada yaşamı için sezonluk alternatifler."]], foods: [["Sol over Gudhjem ve füme ringa", "Balığın tütsüleme/menşeini, çiğ yumurta ve alerjeni sorun; tütsühane servis saatini kontrol edin."], ["Bornholm dondurması ve yerel ürünler", "Süt/kuruyemiş içeriğini, çiftlik dükkânı saatini ve soğuk zinciri doğrulayın."]], dayTrips: [["Christiansø", "Mevsimsel tekne, rüzgâr, bilet ve koruma kurallarını kontrol edin; dönüş iptaline karşı esnek gün bırakın."], ["Dueodde", "Otobüs/bisikletle kumsal ve deniz fenerini gezin; kumda bisiklet/erişim ve yüzme bayrağına dikkat edin."]], caution: "Bisiklet yolları iyi olsa da mesafe, rüzgâr ve karanlık dönüşü küçümsemeyin; kask/ışık kullanın. Ystad üzerinden seyahatte pasaportu taşıyın, feribot check-in saatini kaçırmayın ve kayalık kıyıda bariyer dışına çıkmayın."
  },
  {
    city: "Roskilde", countryCode: "DK", focus: "Viking gemileri, kraliyet katedrali ve fiyort", lede: "UNESCO Roskilde Katedrali'nin kraliyet tarihini özgün Viking gemileri, yaşayan tekne atölyeleri, fiyort doğası ve çağdaş müzik kültürüyle birleştiren Zealand şehri.", days: "1–3 gün", arrival: "Roskilde station · CPH bağlantısı", local: "Tren, otobüs, bisiklet ve yürüyüş", best: "Nisan–Eylül · festival dışı sakin dönemler", pulse: "Roskilde yalnız Kopenhag'dan iki müzelik günübirlik değildir. Katedralde monarşi ve mimari, Viking Gemi Müzesi'nde deneysel arkeoloji, fiyort kıyısında ise yaşayan denizcilik kültürü okunur. Festival haftası şehrin kapasitesini ve ulaşımını bütünüyle değiştirir.",
    sights: [["Roskilde Katedrali", "İbadet, tören ve turist saatini kontrol edin; kraliyet mezarlarında sessizlik ve fotoğraf kurallarına uyun."], ["Viking Gemi Müzesi", "Gemi salonunu tekne atölyesi ve mevsimsel seyirle birlikte planlayın; seyir için yaş, hava, kıyafet ve rezervasyonu kontrol edin."], ["Roskilde Fiyordu", "İşaretli kıyı/bisiklet rotasını kullanın; kuş alanı, özel iskele ve yüzme güvenliği sınırlarına uyun."]],
    areas: [["İstasyon–katedral merkezi", "Kopenhag treni, yeme içme ve tarih rotası için yürünebilir ana üs."], ["Liman veya festival alanı çevresi", "Fiyort ve müzik deneyimine yakın; etkinlik dışında bağlantı/konaklama seçeneğini kontrol edin."]], foods: [["Smørrebrød ve fırın öğünü", "Balık/et, süt ve alerjenleri sorun; müze arasında acele yerine gerçek öğle saati bırakın."], ["Yerel bira ve çiftlik ürünleri", "Tadımı trenle planlayın; alkol oranı, üretici ve peynir/şarküteri içeriğini doğrulayın."]], dayTrips: [["Lejre", "Deneysel tarih alanı ve müzeyi sezon, otobüs ve etkinlik takvimine göre planlayın."], ["Kopenhag", "Sık trenle kolaydır; Roskilde'yi yalnız sabah gezisi yapacaksanız iki ana kuruma ayrı zaman ayırın."]], caution: "Roskilde Festival döneminde bilet, kamp ve şehir ulaşımı özel düzene geçer; resmî olmayan bilet/konaklama teklifinden kaçının. Tekne etkinliğinde can yeleği ve hava kararına, katedralde yaşayan ibadete saygı gösterin."
  },
];

export const denmarkGuides = makeRegionalGuides(profiles);
