import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Helsinki", countryCode: "FI", focus: "Suomenlinna, tasarım ve şehir saunaları", lede: "Baltık kıyısındaki neoklasik merkezi Suomenlinna deniz kalesi, güçlü tasarım mirası, çağdaş mimari, pazarlar ve yaşayan sauna kültürüyle birleştiren Finlandiya başkenti.", days: "3–5 gün", arrival: "HEL · Helsinki Central · West/Market Square limanları", local: "Tramvay, metro, banliyö treni, otobüs, feribot ve yürüyüş", best: "Mayıs–Eylül · kış/sauna için Aralık–Mart", pulse: "Helsinki'yi Senato Meydanı ve kısa Tallinn feribotuna indirgemeyin. Töölö'nün mimarisi, Design District, Kallio'nun mahalle hayatı ve kıyı adaları kompakt ama farklı ritimlerdir. Suomenlinna yaşayan mahalle ve koruma alanıdır; açık hava müzesi dekoru gibi davranmayın.",
    sights: [["Suomenlinna", "HSL feribotu ile gidin; müze, tünel, ada hizmeti ve son dönüşü kontrol edin. Surların kenarı, buz ve özel ev sınırlarına dikkat edin."], ["Senato Meydanı ve şehir merkezi", "Katedral ibadeti, Belediye Müzesi ve Ulusal Kütüphane erişimini ayrı doğrulayın; sessizlik/fotoğraf kurallarına uyun."], ["Oodi, Kiasma ve Temppeliaukio", "Çağdaş mimari rotasını sergi, etkinlik ve kilise konseri/ibadet saatlerine göre bölün."]],
    areas: [["Kluuvi, Kamppi veya Katajanokka", "İlk ziyaret, tren, tramvay ve liman için kolay; merkez otelleri pahalı olabilir."], ["Kallio, Punavuori veya Töölö", "Gece yaşamı, tasarım/kafe ya da sakin park-müze dengesi için farklı tramvay/metro seçenekleri."]], foods: [["Somon çorbası ve Baltık balığı", "Balık türü, menşe, krema ve alerjeni sorun; pazar tezgâhında porsiyon/toplam fiyatı doğrulayın."], ["Karjalanpiirakka ve korvapuusti", "Karelya böreği ile tarçınlı çörekte süt, yumurta ve tereyağı içeriğini kontrol edin."]], dayTrips: [["Porvoo", "Otobüs veya mevsimsel tekneyle eski şehre gidin; tekne dönüşü ile mağaza/müze saatini kontrol edin."], ["Nuuksio", "Toplu taşıma aktarması, patika, ateş ve kış buzunu planlayın; şehir parkı ekipmanıyla uzun orman rotasına çıkmayın."]], caution: "Saunada mayo, havlu, karma/cinsiyete göre bölüm ve fotoğraf kuralı tesise göre değişir; önceden sorun. Kışın deniz/buz üstüne resmî güvenlik bilgisi olmadan çıkmayın; bisiklet ve tramvay yollarında geçiş hakkına dikkat edin."
  },
  {
    city: "Rovaniemi", countryCode: "FI", focus: "Arktikum, Kuzey Kutup Dairesi ve Lapland doğası", lede: "Kemijoki kıyısındaki yeniden kurulmuş şehri Arktikum'un kuzey bilimi, Kuzey Kutup Dairesi, orman tepeleri ve mevsime göre kuzey ışığı ya da gece yarısı güneşiyle birleştiren Lapland kapısı.", days: "4–6 gün", arrival: "RVN · Rovaniemi station", local: "Otobüs, shuttle, gece treni, taksi, araç ve rehberli tur", best: "Kış için Aralık–Mart · gece yarısı güneşi için Haziran–Temmuz", pulse: "Rovaniemi yalnız Noel Baba Köyü değildir. İkinci Dünya Savaşı sonrası Alvar Aalto planlaması, Arktikum'un çevre ve Sámi anlatısı, Korundi sanatı ve Ounasvaara doğası şehri dört mevsimlik bir Lapland üssüne dönüştürür. Kuzey ışığı hiçbir zaman garanti değildir.",
    sights: [["Arktikum", "Arktik bilim ile Lapland tarihini seçerek gezin; Sámi bölümünü çağdaş yerli yaşam bağlamıyla okuyun ve güncel sergiyi kontrol edin."], ["Kuzey Kutup Dairesi", "Santa Claus Village ulaşım, çalışma saati ve ticari etkinlik fiyatını önceden kontrol edin; çizgiyi fiziksel bir doğa sınırı sanmayın."], ["Ounasvaara ve Korundi", "Tepe yürüyüşü/kayak durumunu sanat müzesiyle hava koşuluna göre değiştirin; gün ışığı ve son otobüsü planlayın."]],
    areas: [["Rovaniemi merkezi", "İstasyon, müze, restoran ve tur buluşmalarına yakın; Noel sezonunda fiyat/kapasite yükselir."], ["Ounasvaara veya Arctic Circle çevresi", "Doğa ya da tematik deneyime yakın; şehir yemeği ve gece transferi için önceden plan gerekir."]], foods: [["Poronkäristys ve Lapland ürünleri", "Ren geyiğinin tedariki, et suyu ve garnitürü sorun; kültürel bağlamı açık yerel işletmeyi tercih edin."], ["Somon, leipäjuusto ve cloudberry", "Balık menşei, süt içeriği ve meyve ürünündeki şekeri/alerjeni doğrulayın."]], dayTrips: [["Ranua Wildlife Park", "Koruma/eğitim yaklaşımını, hayvan refahını, otobüs/tur ve kış çalışma saatini inceleyerek tam gün planlayın."], ["Pyhä–Luosto", "Milli park, ametist madeni veya kayak için yol/hava, ekipman ve dönüşü planlayın; şehirden kısa gezi sanmayın."]], caution: "Kuzey ışığı veya husky/ren geyiği turunda garanti, hayvan refahı, grup büyüklüğü, termal ekipman ve iptal şartını yazılı kontrol edin. Kışın yola, nehir buzuna veya ormana tek başına hazırlıksız çıkmayın; donma belirtilerini ciddiye alın."
  },
  {
    city: "Turku", countryCode: "FI", focus: "Orta Çağ başkenti, Aura Nehri ve takımada", lede: "Finlandiya'nın eski başkentinde büyük kaleyi katedral, Aura Nehri kültür hattı, denizcilik mirası ve dünyanın en parçalı takımadalarından birine açılan rota ile birleştiren güneybatı şehri.", days: "3–5 gün", arrival: "TKU · Turku Central/Logomo · liman", local: "Otobüs, tren, bisiklet, feribot ve yürüyüş", best: "Mayıs–Eylül · Noel geleneği için Aralık", pulse: "Turku'nun tarihi Aura boyunca iki ana kutup arasında uzanır: katedral ve eski akademi alanı ile limandaki kale/Forum Marinum. Nehir teknelerini, pazar salonunu ve çağdaş kültürü bu yürüyüşe ekleyin; takımadayı ayrı gün veya birkaç gecelik rota sayın.",
    sights: [["Turku Kalesi", "Dönem odaları ve sergileri seçerek gezin; aile etkinliği, dar merdiven, dolap ve kapanış saatini kontrol edin."], ["Turku Katedrali ve Aboa Vetus", "İbadet saatine saygı gösterin; yeraltı arkeolojisini nehrin Orta Çağ şehir dokusuyla birlikte okuyun."], ["Forum Marinum ve Aura kıyısı", "Müze gemilerinin mevsimsel erişimini, kombine bileti ve dar gemi merdivenlerini önceden değerlendirin."]],
    areas: [["Merkez ve Aura Nehri", "Katedral, pazar ve restoranlara yürüyüş için en iyi ilk üs."], ["Liman, Port Arthur veya Kakola", "Kale/feribot, ahşap mahalle ya da dönüşmüş hapishane tepesi için farklı otobüs/yürüyüş seçenekleri."]], foods: [["Takımada ekmeği ve balık", "Tatlı koyu ekmekte malt/gluten; balıkta tür, menşe ve alerjeni sorun."], ["Turku pazar salonu", "Tezgâh saatini, günlük çorba ve vejetaryen/helal içerikleri doğrudan satıcıdan doğrulayın."]], dayTrips: [["Naantali", "Otobüsle eski şehir ve kıyıya gidin; Moominworld'ün sezonluk ve ayrı biletli olduğunu kontrol edin."], ["Takımada Yolu", "Kısa halka ile çok günlük bisiklet rotasını ayırın; feribot, bisiklet yeri, konaklama ve rüzgârı planlayın."]], caution: "Takımada feribotları ücretsiz/ücretli ve rezervasyonlu/rezervasyonsuz farklı sistemler kullanabilir; her ayağı doğrulayın. Nehir kıyısında kış buzu, yaz etkinlik kalabalığı ve bisiklet yoluna dikkat edin; gemi içine erişimi hafife almayın."
  },
  {
    city: "Tampere", countryCode: "FI", focus: "endüstri mirası, göller ve halka açık sauna", lede: "Näsijärvi ile Pyhäjärvi arasındaki kırmızı tuğlalı sanayi şehrini Vapriikki müzeleri, çağdaş kültür, Pyynikki sırtı ve güçlü halka açık sauna geleneğiyle birleştiren iç bölge üssü.", days: "3–4 gün", arrival: "TMP · Tampere station", local: "Tramvay, otobüs, tren, bisiklet ve yürüyüş", best: "Mayıs–Eylül · sauna ve kış için yıl boyu", pulse: "Tampere, Helsinki'nin küçük benzeri değil; Finlayson–Tammerkoski sanayi peyzajı ve işçi tarihi kendine özgü bir kent kimliği yaratır. Müze kümelerini, Pyynikki/Pispala yamaçlarını ve göl saunasını ayrı yarım günlere bölün.",
    sights: [["Vapriikki", "Çok bölümlü müzede tarih, oyun, doğa veya hokey koleksiyonlarından seçki yapın; geçici sergi ve dolap saatini kontrol edin."], ["Finlayson ve Tammerkoski", "Aktif dönüşüm bölgesini işçi tarihi ve mimariyle yürüyün; özel ofis/konut alanlarına girmeyin."], ["Pyynikki ve Pispala", "Seyir kulesi, çörek ve sırt yürüyüşünü zemin/hava durumuna göre planlayın; konut sokaklarında sessiz olun."]],
    areas: [["Keskusta ve Tammela", "İstasyon, tramvay, müze ve pazar için pratik; etkinlik gecesinde hareketlidir."], ["Pispala, Pyynikki veya Lapinniemi", "Manzara, doğa ya da sauna erişimi için otobüs/tramvaylı sakin alternatifler."]], foods: [["Mustamakkara", "Kan sosisi içeriğini ve eşlikçileri sorun; beslenme tercihinize uymuyorsa pazar salonunda alternatif seçin."], ["Pyynikki munkki ve yerel bira", "Donut alerjenini, tadımda alkol oranını doğrulayın; sauna öncesi/sonrası alkol tüketimini sınırlayın."]], dayTrips: [["Hämeenlinna", "Trenle kale ve müze günü planlayın; iki kurumun çalışma saatini ayrı kontrol edin."], ["Seitseminen veya Helvetinjärvi", "Milli parka son kilometre bağlantısı sınırlıdır; araç/tur, hava, patika ve gün ışığını planlayın."]], caution: "Saunadan doğrudan soğuk göle giriş sağlık riski yaratabilir; tesiste cankurtaran, merdiven ve su koşulunu sorun, alkollüyken girmeyin. Kışın göl buzuna yalnız resmî güvenlik bilgisiyle çıkın."
  },
  {
    city: "Porvoo", countryCode: "FI", focus: "nehir depoları, ahşap eski şehir ve kırsal kıyı", lede: "Porvoonjoki kıyısındaki kırmızı depoları pastel ahşap evler, Orta Çağ katedrali, küçük tasarım dükkânları ve doğu Uusimaa kırsalıyla birleştiren tarihî kasaba.", days: "1–3 gün", arrival: "Helsinki otobüsü · mevsimsel tekne", local: "Otobüs, yürüyüş, bisiklet ve mevsimsel tekne", best: "Mayıs–Eylül · kış atmosferi için Aralık–Şubat", pulse: "Porvoo, Helsinki'den iki saatlik fotoğraf dekoru değildir. Eski şehrin yaşayan evleri, katedralin karmaşık tarihi, nehir ticareti ve çağdaş Taidetehdas kültür alanı küçük ölçekte katmanlı bir rota verir. Yaz hafta sonu kalabalığını sabah/akşamla dengeleyin.",
    sights: [["Vanha Porvoo ve nehir depoları", "Sokakları erken gezin; depoları yalnız kamusal kıyıdan görün, özel avlu/merdivene girmeyin."], ["Porvoo Katedrali", "İbadet, düğün ve konser saatini kontrol edin; yangın/restorasyon tarihini saygılı bağlamla okuyun."], ["Porvoo Museum ve Taidetehdas", "Tarihî koleksiyon ile çağdaş sergiyi ayrı kurum olarak planlayın; güncel programı doğrulayın."]],
    areas: [["Vanha Porvoo", "Atmosfer ve sabah/akşam için en güzel üs; taş sokak, valiz ve fiyat dezavantajı olabilir."], ["Yeni merkez veya nehir güneyi", "Otobüs, market ve daha dengeli konaklama için kısa yürüyüşlü alternatif."]], foods: [["Runebergintorttu", "Badem, rom aroması/alkol, süt ve yumurta içeriğini sorun; mevsim dışında bulunabilirliğini kontrol edin."], ["Çikolata ve yerel kafe", "Üretim/alerjen bilgisini doğrudan dükkândan alın; yalnız turistik paket yerine taze fırın ürününü deneyin."]], dayTrips: [["Helsinki", "Sık otobüsle kolaydır; yaz teknesini yalnız hava ve dönüş saati uygunsa tek yön deneyim olarak düşünün."], ["Sipoonkorpi", "Kırsal doğa rotasında toplu taşıma, patika, ateş ve kene koşullarını planlayın."]], caution: "Ahşap eski şehir yangına hassastır; sigara/ateş kurallarına uyun ve özel evleri yakından fotoğraflamayın. Kışın taş sokak ile nehir kıyısı buzlu, yaz teknesi ise hava bağımlıdır; uygun ayakkabı ve dönüş yedeği taşıyın."
  },
  {
    city: "Finlandiya Göller Bölgesi", countryCode: "FI", focus: "Saimaa, Savonlinna ve orman-göl rotası", lede: "Saimaa'nın binlerce ada ve koyunu Savonlinna'nın Olavinlinna Kalesi, Punkaharju sırtı, ahşap kasabalar, sauna ve hassas göl ekosistemiyle birleştiren çok merkezli doğa bölgesi.", days: "6–10 gün", arrival: "Savonlinna/Kuopio/Jyväskylä istasyonları ve bölgesel havalimanları", local: "Tren, otobüs, mevsimsel tekne, araç, bisiklet ve kano", best: "Haziran–Eylül · kış doğası için Ocak–Mart", pulse: "Göller Bölgesi tek bir destinasyon adı değil; Saimaa, Päijänne ve Pielinen çevresinde büyük bir coğrafyadır. İlk rotada Savonlinna–Punkaharju–Mikkeli veya Kuopio–Koli kümelerinden birini seçin. Haritadaki su mesafesi doğrudan kara bağlantısı anlamına gelmez.",
    sights: [["Olavinlinna ve Savonlinna", "Kale turu, opera festivali kurulumu, tekne ve dar merdiven koşullarını kontrol edin; şehirde en az iki gece kalın."], ["Punkaharju", "Buzul sırtını işaretli yol/patika ile gezin; tren durağı, bisiklet, müze ve dönüşü birlikte planlayın."], ["Saimaa doğası", "Tekne/kano operatörünün lisans, rota, can yeleği ve hava kararını doğrulayın; Saimaa halkalı fokuna mesafeyi koruyun."]],
    areas: [["Savonlinna veya Mikkeli", "Kale, Saimaa ve tren/otobüs için güneydoğu odaklı işlevsel üsler."], ["Kuopio, Jyväskylä veya Koli çevresi", "Doğu/kuzey gölleri, tasarım/müze ya da milli park için ayrı rota kümeleri."]], foods: [["Muikku ve göl balığı", "Tür, yakalama alanı, kızartma yağı ve alerjeni sorun; koruma/mevsim kuralına uyan tedarik seçin."], ["Kalakukko ve orman ürünleri", "Balık-et dolgusu, gluten ve pişirme içeriğini sorun; yabani mantarı yalnız güvenilir işletmede tüketin."]], dayTrips: [["Koli Milli Parkı", "Kuopio/Joensuu yönünden ulaşım ve son kilometreyi planlayın; hava, patika, teleferik ve koruma kuralını kontrol edin."], ["Lappeenranta ve Imatra", "Trenle kale, Saimaa kanalı ve akarsu tarihini gezin; sınır bölgesi/geçiş kuralını güncel kaynaktan doğrulayın."]], caution: "Göl suyunu hava sıcaklığına göre güvenli sanmayın; can yeleği giyin ve alkollüyken tekne/sauna kullanmayın. Saimaa halkalı fokunun yuva ve dinlenme alanlarına yaklaşmayın; motor, ağ ve kamp kurallarına uyun. Kış buzuna yalnız resmî bilgiyle çıkın."
  },
  {
    city: "Inari ve Saariselkä", countryCode: "FI", focus: "Sámi kültürü, tundra ve Urho Kekkonen Milli Parkı", lede: "Inari Gölü kıyısındaki Sámi kültür merkezini Saariselkä'nın tundra patikaları, Urho Kekkonen Milli Parkı ve mevsime göre aurora ya da gece yarısı güneşiyle birleştiren kuzey rota.", days: "5–8 gün", arrival: "IVL · Ivalo otobüs/transfer bağlantısı", local: "Otobüs, transfer, araç, yürüyüş, kayak ve rehberli tur", best: "Kış için Aralık–Mart · yürüyüş için Haziran sonu–Eylül", pulse: "Inari ile Saariselkä aynı nokta değildir: Inari Sámi parlamentosu, Siida ve göl kültürü; Saariselkä ise turizm hizmetleri ile milli park kapısıdır. İki üssü 70 kilometrelik yol, hava ve seyrek otobüsle planlayın. Sámi kültürünü kostüm/ren geyiği klişesine indirmeyin.",
    sights: [["Siida", "Sámi Müzesi ve doğa merkezini çağdaş yerli yaşamın kendi anlatısı olarak gezin; güncel sergi, fotoğraf ve etkinlik kuralını kontrol edin."], ["Urho Kekkonen Milli Parkı", "Ziyaretçi merkezinden patika, kulübe, ateş ve hava bilgisini alın; kısa halka ile çok günlük vahşi doğa rotasını ayırın."], ["Inari Gölü veya Kaunispää", "Tekne/kış aktivitesi ya da seyir tepesini mevsime göre seçin; buz, rüzgâr, transfer ve gün ışığını doğrulayın."]],
    areas: [["Inari", "Siida, Sámi kurumları ve göl için kültür odaklı sakin üs; akşam hizmeti sınırlıdır."], ["Saariselkä", "Milli park, ekipman ve turlar için daha yoğun turizm üssü; otantik yerli merkez sanılmamalıdır."]], foods: [["Sámi ve Lapland mutfağı", "Yerli topluluk tarafından işletilen, tedarik ve kültürel anlatımı açık yer seçin; ren geyiği etinin menşeini sorun."], ["Göl balığı ve Arctic berry", "Balığın türü/av kuralı, meyve ürününün şeker ve alerjen içeriğini doğrulayın."]], dayTrips: [["Utsjoki", "Finlandiya'nın kuzey ucuna uzun yolculuktur; Sámi yerleşimleri, yol, yakıt ve konaklamayı ayrı rota olarak planlayın."], ["Lemmenjoki", "Milli park teknesi/rehberi, altın tarihi ve patika için mevsim, rezervasyon ve dönüşü kontrol edin."]], caution: "Kışta -30°C altı, beyaz körlük, ren geyiği ve uzak yol koşulları ciddi risktir; araç/giysi/acil ekipman taşıyın. Kuzey ışığını garanti saymayın. Sámi kıyafeti, joik veya törenini izinsiz taklit etmeyin; yerli işletmeyi ve fotoğraf rızasını önemseyin."
  },
  {
    city: "Åland Adaları", countryCode: "FI", focus: "Mariehamn, bisiklet ve özerk takımada", lede: "Finlandiya'nın İsveççe konuşulan özerk takımadasında Mariehamn denizcilik mirasını kırmızı granit kıyılar, küçük feribotlar, bisiklet rotaları ve sakin ada yaşamıyla birleştiren Baltık yolculuğu.", days: "4–7 gün", arrival: "MHQ · Mariehamn/Långnäs feribotları", local: "Otobüs, bisiklet, araç, takımada feribotu ve yürüyüş", best: "Mayıs sonu–Eylül", pulse: "Åland tek ada değil, binlerce adadan oluşan özerk ve büyük ölçüde İsveççe konuşulan bir bölgedir. Mariehamn denizcilik üssü; Kastelholm, Bomarsund ve küçük takımada belediyeleri farklı günler ister. Feribotun gece Långnäs'e varması şehir merkezine vardığınız anlamına gelmez.",
    sights: [["Åland Denizcilik Müzesi ve Pommern", "Müze gemisinin mevsimsel erişimi, güverte/merdiven ve kombine bileti kontrol edin; gemi tarihini denizcilik yaşamıyla birlikte okuyun."], ["Kastelholm ve Jan Karlsgården", "Kale, açık hava müzesi ve hapishane müzesinin ayrı saatlerini planlayın; bisiklet/otobüs dönüşünü doğrulayın."], ["Bomarsund", "Rus kale kalıntılarını işaretli rotada gezin; taşlara tırmanmayın ve savaş tarihini bölgenin özerklik/demilitarizasyon bağlamıyla okuyun."]],
    areas: [["Mariehamn", "Ana feribot, müze, restoran ve bisiklet kiralama için en işlevsel üs."], ["Kastelholm, Eckerö veya küçük adalar", "Tarih, batı kıyısı ya da sessiz takımada için feribot/araç planlı alternatifler."]], foods: [["Åland pannkaka", "İrmik/pirinç tabanı, süt, yumurta ve kakule içeriğini sorun; erik kompostosu ve krema porsiyonunu paylaşın."], ["Takımada balığı ve svartbröd", "Balık türü/menşeini, koyu ekmekte malt/gluteni ve küçük restoranın saatini doğrulayın."]], dayTrips: [["Kökar veya Föglö", "Takımada feribotu, rezervasyon, bisiklet yeri, geceleme ve son dönüşü kontrol edin; bir günde iki uzak ada planlamayın."], ["Eckerö", "Posta ve gümrük evi, kıyı ve müzeyi bisiklet/otobüsle planlayın; rüzgâr ile dönüş süresini hesaba katın."]], caution: "Åland'ın özerk, İsveççe ve demilitarize statüsünü Finlandiya ana karasıyla aynı varsaymayın; yerel tabela ve kurala uyun. Bisiklette dar yol, rüzgâr ve feribot rampasına; teknede can yeleği ve hava kararına dikkat edin. Kamp/ateş hakkı özel araziyi kapsamaz."
  },
];

export const finlandGuides = makeRegionalGuides(profiles);
