import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Atina", countryCode: "GR", focus: "Akropolis, antik kent ve yaşayan mahalleler", lede: "Akropolis'in klasik mirasını Bizans kiliseleri, Osmanlı izleri, çağdaş sanat ve mahalle tavernalarıyla aynı şehir yürüyüşünde buluşturan başkent.", days: "4–5 gün", arrival: "ATH · Pire Limanı · Larissa tren istasyonu", local: "Metro, tramvay, otobüs ve yürüyüş", best: "Mart–Mayıs · Eylül–Kasım", pulse: "Atina yalnız Akropolis çevresindeki açık hava müzesi değildir; Monastiraki, Psyrri, Pangrati, Exarchia ve sahil hattı farklı tarih ve gündelik hayat katmanları açar. Arkeoloji günlerini mahalle ve pazar ritmiyle dengeleyin.",
    sights: [["Akropolis ve Müzesi", "Tepeyi serin erken saatte, müzeyi ayrı zaman diliminde gezin; saatli bilet, sıcaklık veya grev kaynaklı kapanışı resmî kanaldan kontrol edin."], ["Antik Agora ve Roma Agorası", "İki alanı tek bilet varsaymadan planlayın; müze, Stoa ve Rüzgârlar Kulesi için en az yarım gün ayırın."], ["Ulusal Arkeoloji Müzesi", "Koleksiyonu kronolojik seçkiyle gezin; geçici salon, restorasyon ve çalışma saatini ziyaret günü doğrulayın."]],
    areas: [["Plaka, Koukaki ve Monastiraki", "İlk ziyaret ve arkeolojiye yürüyüş için kolay; gündüz kalabalığı ve turistik fiyat yüksektir."], ["Pangrati, Petralona ve Kolonaki", "Yerel yemek/gece ritmi veya müze-alışveriş için metroya bağlı farklı bütçe alternatifleri."]], foods: [["Meze ve taverna", "Horiatiki, fava, dolmades ve ızgarada porsiyon, ekmek/kuver ve deniz ürününün kilo fiyatını sorun."], ["Souvlaki ve fırın ürünleri", "Et türü, sos ve pita içeriğini netleştirin; spanakopita ile koulouri'yi sabah taze deneyin."]], dayTrips: [["Sounion", "Poseidon Tapınağı için kıyı otobüsü/tur, gün batımı sonrası dönüş ve arkeoloji kapanışını birlikte planlayın."], ["Delphi", "Atina'dan uzun gün yerine Arachova/Delphi gecelemeyi düşünün; müze, alan ve otobüs saatini doğrulayın."]], caution: "Yaz sıcaklığında arkeolojik alanlar geçici kapanabilir; su, şapka ve erken saat kullanın. Metro ve kalabalık meydanda yankesiciliğe karşı çantayı kapalı tutun; gösterilerden uzak durun, lisanssız taksi ve bilet satıcısını kullanmayın."
  },
  {
    city: "Selanik", countryCode: "GR", focus: "Bizans, Osmanlı mirası ve kuzey mutfağı", lede: "Ege kıyısında Roma kemerlerini Bizans kiliseleri, Osmanlı yapıları, Yahudi hafızası, öğrenci enerjisi ve güçlü kuzey mutfağıyla birleştiren liman şehri.", days: "3–4 gün", arrival: "SKG · Yeni Demiryolu İstasyonu · KTEL terminalleri", local: "Metro, otobüs, taksi ve yürüyüş", best: "Nisan–Haziran · Eylül–Kasım", pulse: "Selanik'in katmanları sahil ile Ano Poli arasında yükselir. 1917 yangını, nüfus mübadelesi ve Holokost tarihini yalnız birkaç anıtla değil müze ve mahalle bağlamıyla okumak gerekir.",
    sights: [["Beyaz Kule ve sahil", "Kule müzesi ile Nea Paralia yürüyüşünü serin saate bölün; etkinlik ve erişilebilirlik durumunu kontrol edin."], ["Rotunda, Galerius ve Bizans kiliseleri", "Roma saray aksını Aya Dimitri ile birleştirin; yaşayan ibadet alanlarında kıyafet/fotoğraf kuralına uyun."], ["Ano Poli", "Surlar, Trigonion ve geleneksel sokaklara otobüsle çıkıp yürüyerek inin; dik taş zeminde dikkatli olun."]],
    areas: [["Ladadika ve merkez", "Sahil, müze ve gece hayatına yakın; hafta sonu gürültüsü belirgindir."], ["Ano Poli veya Kalamaria", "Tarihî yamaç atmosferi ya da sakin sahil yaşamı için ulaşım gerektiren alternatifler."]], foods: [["Bougatsa ve koulouri", "Kremalı/peynirli/etli dolguyu sorun; kahvaltıda küçük porsiyonla yerel fırınları karşılaştırın."], ["Selanik mezeleri", "Deniz ürünü, soutzoukakia ve şarküteride et türü, kilo fiyatı ve alerjeni netleştirin."]], dayTrips: [["Vergina", "Kraliyet mezarları müzesine otobüs/turla gidin; bilet ve fotoğraf kurallarını resmî kaynaktan kontrol edin."], ["Halkidiki", "Üç yarımadayı tek gün sanmayın; bir sahil alt bölgesi, plaj erişimi ve dönüş aracı seçin."]], caution: "Arkeoloji ve ibadet alanlarında açık saat değişebilir. Gece Ladadika'da içeceği gözetin, takside resmî çağrı kullanın; tarih ve nüfus mübadelesi konularında milliyetçi genellemelerden kaçının."
  },
  {
    city: "Santorini", countryCode: "GR", focus: "kaldera köyleri, volkan ve ada şarapları", lede: "Ege kalderasının siyah kayalıklarını beyaz köyler, volkanik bağlar, arkeoloji ve dramatik gün batımlarıyla birleştiren Kiklad adası.", days: "4–6 gün", arrival: "JTR · Athinios Limanı", local: "KTEL otobüsü, taksi, yürüyüş ve tekne", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Santorini yalnız Oia gün batımı değildir; Fira–Oia patikası, Akrotiri, Pyrgos, Emporio ve volkanik bağlar ada yaşamını fotoğraf kalabalığından çıkarır. Liman, havaalanı ve köy transferlerini birbirinden ayrı planlayın.",
    sights: [["Fira–Oia yürüyüşü", "Açık ve gölgesiz patikaya erken çıkın; rüzgâr, sıcak, su ve dönüş otobüsünü önceden planlayın."], ["Akrotiri", "Tunç Çağı yerleşimini arkeoloji müzesiyle bağlayın; açılış, koruma çatısı ve otobüs saatini doğrulayın."], ["Kaldera teknesi", "Lisans, hava, yüzme durağı, can yeleği, liman transferi ve gerçek tekne kapasitesini yazılı kontrol edin."]],
    areas: [["Fira ve Firostefani", "Otobüs ağı ve manzara için pratik; kruvaziyer saatinde yoğun, uçurum konaklaması merdivenlidir."], ["Pyrgos, Kamari veya Perissa", "Köy/bağ karakteri ya da plaj ve daha dengeli fiyat için kalderadan farklı alternatifler."]], foods: [["Fava ve domatokeftedes", "Santorini bakliyatı ile domates köftesinde peynir, kızartma yağı ve porsiyonu sorun."], ["Assyrtiko", "Volkanik bağ şarabını randevulu üreticide tadın; tadım sonrası araç/ATV kullanmayın."]], dayTrips: [["Thirassia", "Feribot/tekne saatini ve dönüş limanını doğrulayarak daha sakin ada günü kurun."], ["Ios veya diğer Kikladlar", "Günübirlik varsaymadan mevsimsel feribot, liman ve deniz durumuna göre ayrı gece planlayın."]], caution: "Uçurum kenarında bariyer dışına çıkmayın; eşekleri ulaşım/eğlence için kullanmayın. ATV deneyimsiz sürücü için yüksek risktir; feribot iptal yedeği bırakın ve kruvaziyer gününde dar sokak kalabalığını hesaba katın."
  },
  {
    city: "Mikonos", countryCode: "GR", focus: "Kiklad mimarisi, plajlar ve ada gece hayatı", lede: "Kiklad'ın beyaz sokaklarını yel değirmenleri, Delos arkeolojisi, farklı karakterde plajlar ve yüksek enerjili gece hayatıyla birleştiren ada.", days: "4–5 gün", arrival: "JMK · Mykonos Yeni/Eski Limanı", local: "KTEL otobüsü, deniz taksisi, taksi ve yürüyüş", best: "Mayıs–Haziran · Eylül", pulse: "Mikonos pahalı kulüp adası imajından daha geniştir; Chora sabahı, Ano Mera, Delos ve kuzey kıyıları daha sakin kültür katmanı sunar. Liman ile plaj bağlantısını her gün yeniden kontrol edin.",
    sights: [["Chora ve yel değirmenleri", "Dar sokakları erken sabah gezin; Little Venice kıyısında dalga ve özel mekân sınırına dikkat edin."], ["Delos", "Arkeoloji adasına yalnız resmî tekne ve saatli ziyaretle gidin; gölge/su yokluğuna ve kapanışa hazırlanın."], ["Ano Mera", "Manastır ve köy meydanını ibadet kurallarıyla gezin; ada içi otobüs/taksi dönüşünü planlayın."]],
    areas: [["Chora", "Restoran, liman ve gece hayatına yakın; gürültü, merdiven ve yüksek fiyat belirgin."], ["Ornos, Platis Gialos veya Ano Mera", "Aile/plaj bağlantısı ya da sakin köy üssü için farklı otobüs ve bütçe seçenekleri."]], foods: [["Kopanisti ve louza", "Baharatlı peynir ile kurutulmuş ette süt/et türü ve porsiyonu sorun."], ["Ada deniz ürünleri", "Günlük balığın türünü, menşeini ve kilo/porsiyon toplamını siparişten önce netleştirin."]], dayTrips: [["Delos", "Müze ve açık alan için yarım günden fazla ayırın; dönüş teknesini kaçırmayın."], ["Tinos", "Feribotla eklenebilir ancak liman/son sefer ve dinî ziyaret kıyafetini planlayın."]], caution: "Yazın taksi sayısı ve otobüs kapasitesi sınırlıdır; gece dönüşünü önceden kurun. ATV/quad yerine deneyiminize uygun güvenli ulaşım seçin; içecek ve faturayı gözetin, plaj erişiminin özel işletme ücreti olmadığını varsaymayın."
  },
  {
    city: "Girit", countryCode: "GR", focus: "Minos mirası, dağ köyleri ve büyük ada rotası", lede: "Minos saraylarını Venedik limanları, yüksek dağlar, derin boğazlar, zeytinlikler ve Yunanistan'ın en güçlü bölgesel mutfaklarından biriyle birleştiren büyük ada.", days: "8–12 gün", arrival: "HER/CHQ · Heraklion ve Souda limanları", local: "KTEL otobüsü, araç ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Girit tek üsle gezilecek küçük ada değildir. Heraklion–Knossos, Hanya–batı kıyıları, Rethymno ve güney/dağ rotaları ayrı kümelerdir; sekiz günde en fazla iki üs seçin.",
    sights: [["Knossos ve Heraklion Müzesi", "Saray ile özgün eserleri aynı gün veya ardışık günlerde görün; saatli bilet, sıcak ve restorasyonu kontrol edin."], ["Hanya eski limanı", "Venedik, Osmanlı ve Yahudi katmanlarını mahalle yürüyüşüyle gezin; limanı yalnız restoran manzarasına indirmeyin."], ["Samaria Boğazı", "Uzun tek yön yürüyüşü park açılışı, feribot/otobüs zinciri, su, ayakkabı ve kondisyonla planlayın."]],
    areas: [["Heraklion veya Hanya", "Doğu arkeolojisi/ulaşım ya da batı limanı/doğa için iki ayrı ana üs."], ["Rethymno veya güney kıyısı", "Merkezî tarih üssü ya da daha sakin plaj-köy deneyimi için ikinci konaklama kararı."]], foods: [["Dakos ve horta", "Arpa peksimeti, domates, mizithra ve otlarda süt/alerjen ile mevsim ürününü sorun."], ["Girit sofrası", "Kalitsounia, kuzu/keçi ve zeytinyağlılarda et/süt içeriğini; tsikoudia ikramında ölçüyü kontrol edin."]], dayTrips: [["Balos veya Elafonisi", "İkisinden birini seçin; yol/tekne, park, rüzgâr ve koruma kurallarını aynı gün doğrulayın."], ["Lasithi ve doğu Girit", "Knossos gününe sıkıştırmayın; araç/otobüs, mağara ve köy saatleriyle ayrı rota kurun."]], caution: "Dağ ve boğazda yangın, sıcak, taş düşmesi ve kapanış duyurusuna uyun. Ada yolları virajlıdır; gece/alkol sonrası sürmeyin. Koruma altındaki kumsaldan kum/bitki almayın, mesafeleri haritadan küçümsemeyin."
  },
  {
    city: "Rodos", countryCode: "GR", focus: "Orta Çağ şehri, antik Lindos ve plajlar", lede: "Şövalyeler döneminden kalan sur içini Osmanlı mirası, Lindos akropolü, kırsal köyler ve uzun Ege kıyılarıyla birleştiren On İki Ada merkezi.", days: "5–7 gün", arrival: "RHO · Mandraki/Commercial limanları", local: "Otobüs, taksi, araç ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Rodos eski şehir ile Lindos arasında bir otobüs günü değildir; batı kıyısı, Kamiros, iç köyler ve güney plajları adanın ölçeğini büyütür. Bir şehir ve bir kıyı üssü kurmak daha dengelidir.",
    sights: [["Rodos Eski Şehri", "Şövalyeler Sokağı, Büyük Üstat Sarayı ve Osmanlı yapılarını sabah/akşam gezin; müze bileti ve ibadet kuralını kontrol edin."], ["Lindos", "Akropole erken çıkın; sıcak, parlak taş ve dik merdiven için su/ayakkabı kullanın, eşek taşımacılığından kaçının."], ["Kamiros", "Batı kıyısındaki antik kenti araç/otobüs ve güncel saatle planlayın; açık alanda gölge azdır."]],
    areas: [["Rodos şehri", "Müze, liman, otobüs ve akşam için en işlevsel üs; sur içinde valiz/araç zordur."], ["Lindos, Pefkos veya batı kıyısı", "Manzara/plaj ya da rüzgâr-sörf için farklı ulaşım gerektiren ikinci üsler."]], foods: [["Pitaroudia ve meze", "Nohut köftesi, peynir ve kızartmada içerik/yağ ortaklığını sorun."], ["Rodos şarabı ve bal", "Üretici tadımını sürücülü planlayın; bal ve susamlı tatlılarda alerjeni kontrol edin."]], dayTrips: [["Symi", "Feribot limanı, dönüş ve deniz koşulunu doğrulayın; Panormitis eklenirse ada içi süreyi hesaba katın."], ["Marmaris", "Türkiye'ye uluslararası sınır geçişidir; pasaport, giriş hakkı, liman ve check-in olmadan günübirlik sanmayın."]], caution: "Yaz yangını ve sıcaklık yol/park kapanışına neden olabilir. Scooter/ATV'yi deneyimsiz kullanmayın; ortaçağ surlarında bariyeri aşmayın, uluslararası feribotta sınır belgelerini eksiksiz taşıyın."
  },
  {
    city: "Korfu", countryCode: "GR", focus: "Venedik şehri, İyon koyları ve köyler", lede: "İyon Denizi'nde Venedik kent dokusunu kaleler, zeytinlik tepeler, manastırlar, farklı karakterde koylar ve canlı ada mutfağıyla birleştiren yeşil ada.", days: "5–7 gün", arrival: "CFU · Korfu Limanı", local: "Mavi/Yeşil otobüs, taksi, araç ve tekne", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Korfu eski şehir sabahından Paleokastritsa koylarına, kuzey köylerinden güney sulak alanlarına uzanır. Dar kıyı yolları nedeniyle haritadaki mesafeyi kısa transfer sanmayın.",
    sights: [["Korfu Eski Şehri", "Eski/Yeni Kale, Liston ve kiliseleri yürüyün; gemi günü, kale kapanışı ve ibadet saatini kontrol edin."], ["Paleokastritsa", "Manastır, koy ve tekneyi otobüs/araçla planlayın; mağara teknesinde can yeleği ve deniz durumunu sorun."], ["Achilleion", "Sarayın restorasyon ve açılış durumunu resmî kaynaktan teyit edin; kapalı bölgeyi aşmayın."]],
    areas: [["Korfu şehri", "Otobüs, müze ve akşam için araçsız en kolay üs; yazın yoğun ve park zordur."], ["Paleokastritsa, Kassiopi veya güney", "Koy, kuzey köyleri ya da sakin doğa için farklı araç/otobüs kararları."]], foods: [["Sofrito ve pastitsada", "Dana/tavuk ile şaraplı sos içeriğini sorun; ağır et yemeklerini paylaşın."], ["Kumquat ve deniz ürünü", "Likör/tatlıda alkol-şeker, balıkta tür ve kilo fiyatını netleştirin."]], dayTrips: [["Paxos ve Antipaxos", "Lisanslı tekne, hava, gerçek yüzme süresi ve liman transferini yazılı doğrulayın."], ["Arnavutluk/Sarandë", "Uluslararası Schengen dış sınırıdır; pasaport, vize/giriş hakkı ve liman check-in süresini kontrol edin."]], caution: "Dar ada yolunda park, scooter ve gece sürüşünü küçümsemeyin. Tekne ve yüzmede rüzgâr/dalga uyarısına uyun; zeytinlikte yangın yasağına, uluslararası feribotta sınır kurallarına dikkat edin."
  },
  {
    city: "Meteora", countryCode: "GR", focus: "kaya manastırları, yürüyüş ve Tesalya", lede: "Tesalya ovasından yükselen dev kumtaşı sütunlarını yaşayan Ortodoks manastırları, tarihî patikalar ve Kalambaka–Kastraki köy yaşamıyla birleştiren UNESCO bölgesi.", days: "2–4 gün", arrival: "Kalambaka tren/otobüs istasyonu", local: "Otobüs, taksi, yürüyüş ve rehberli tur", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Meteora tek gün batımı turu değildir; altı açık manastırın günleri ve merdivenleri farklıdır. İki-üç manastır, bir yürüyüş ve köy zamanı seçmek saygılı ve sürdürülebilir bir program yaratır.",
    sights: [["Büyük Meteoron ve Varlaam", "Açık gün, kıyafet, yüzlerce basamak ve ziyaret yoğunluğunu önceden kontrol edin; ibadet alanında sessiz olun."], ["Roussanou ve Agios Stefanos", "Farklı erişim düzeylerini karşılaştırın; manastır içi fotoğraf yasağına eksiksiz uyun."], ["Kastraki patikaları", "İşaretli tarihî yolda rehber/harita, su, hava ve gün ışığı planı yapın; kaya tırmanışına izinsiz başlamayın."]],
    areas: [["Kalambaka", "Tren/otobüs, restoran ve transfer için pratik ana üs."], ["Kastraki", "Kayalara daha yakın, sakin köy atmosferi ve patika başlangıçları için alternatif."]], foods: [["Tesalya mutfağı", "Fasulye, turta ve güveçte et suyu/süt içeriğini sorun; yerel mevsim tabağı seçin."], ["Mantar ve peynir", "Yabani mantarı yalnız güvenilir işletmede tüketin; peynirde pastörizasyon/alerjeni doğrulayın."]], dayTrips: [["Trikala", "Müze, kale ve nehir için otobüs/trenle sakin şehir günü; son dönüşü kontrol edin."], ["Delphi", "Meteora'dan uzun kara günüdür; aynı gün gidip dönmek yerine rota üzerinde geceleme planlayın."]], caution: "Manastır kıyafet kuralları işletme değil yaşayan dinî kurum kuralıdır. Kayalık kenar, terk edilmiş hücre ve tırmanış alanına izinsiz girmeyin; taksi/tur ücretini yazılı alın, tren değişikliklerini aynı gün kontrol edin."
  },
];

export const greeceGuides = makeRegionalGuides(profiles);
