import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Budapeşte", countryCode: "HU", focus: "Tuna, termal hamamlar ve tarihî mahalleler", lede: "Buda tepeleriyle Peşte bulvarlarını Tuna boyunca saraylar, kahvehaneler ve termal kültürle birleştiren büyük Orta Avrupa başkenti.", days: "4–5 gün", arrival: "BUD · Keleti/Nyugati/Déli", local: "Metro, tramvay, otobüs, HÉV ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Budapeşte'nin büyük simgeleri etkileyicidir; şehrin gerçek derinliği VIII. ve IX. bölge dönüşümünde, pazarlarında ve Tuna'nın iki yakası arasındaki farklı ritimde belirir.",
    sights: [["Parlamento ve Tuna kıyısı", "Resmî Parlamento turunu kimlik ve saatle eşleştirin; Tuna Ayakkabıları anıtında sessiz ve saygılı davranın."], ["Buda Kalesi ve Balıkçı Tabyası", "Kale bölgesine erken çıkın; müze, kilise ve seyirleri aynı anda tüketmek yerine iki odak seçin."], ["Termal hamam", "Széchenyi, Gellért, Rudas veya daha yerel bir hamamı tarih, havuz ve gün/yaş kurallarına göre seçin."]],
    areas: [["V., VI. ve VII. bölgeler", "İlk ziyaret, anıt, kafe ve gece hayatı için merkezî; gece gürültüsü sokaktan sokağa değişir."], ["VIII., IX. ve Buda", "Pazar–çağdaş kültür ya da daha sakin tepe/konut ritmi için güçlü alternatifler."]], foods: [["Gulyás ve pörkölt", "Çorba ile yahniyi karıştırmayın; paprika yoğunluğu, et ve porsiyonu menüden sorun."], ["Lángos ve rétes", "Kızarmış hamuru pazarda paylaşın; strudel dolgusunda mevsim meyvesi ve alerjeni kontrol edin."]], dayTrips: [["Szentendre", "HÉV veya mevsimlik tekneyle sanat kasabası; şehir içi biletin tüm hattı kapsadığını varsaymayın."], ["Tuna Kıvrımı", "Visegrád ve Esztergom'u tek güne koyacaksanız tren–otobüs–tekne bağlantısını önceden kurun."]], caution: "Lisanssız döviz bürosu ve ATM'den kaçının; terminalde HUF seçin. Gece bar bölgesinde taksimetreli/resmî araç kullanın, Parlamento ve hamam biletini yalnız resmî kanaldan alın."
  },
  {
    city: "Szentendre", countryCode: "HU", focus: "Tuna kıyısı, sanat galerileri ve Sırp mirası", lede: "Pastel Barok sokakları, Ortodoks kiliseleri ve küçük sanat müzeleriyle Budapeşte yakınında yavaş bir Tuna kasabası.", days: "1–2 gün", arrival: "Batthyány tér'den HÉV · tekne mevsimlik", local: "Yürüyüş, bisiklet ve HÉV", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Szentendre öğlen günübirlik kalabalıkla dolabilir; sabah erken veya son tekne sonrası kasabanın gerçek sakin ritmi geri gelir.",
    sights: [["Fő tér ve eski sokaklar", "Ana meydan, Blagoveştenska Kilisesi ve dar yokuşları dükkânlar açılırken gezin."], ["Ferenczy ve küçük müzeler", "Seramik, resim ve yerel sanat koleksiyonlarından iki tanesini seçin; birleşik bilet koşulunu sorun."], ["Skanzen", "Açık hava etnografya müzesi merkez dışında ve büyüktür; otobüs, sezon ve en az yarım gün planlayın."]],
    areas: [["Fő tér ve Tuna promenadı", "Kısa ziyaret, restoran ve HÉV dönüşü için en pratik merkez."], ["Pismány ve Skanzen yönü", "Daha sakin konaklama ve açık hava müzesi için merkezden uzak alternatif."]], foods: [["Sırp ve Macar fırınları", "Balkan etkili börek, çörek ve Macar tatlılarını küçük üreticilerden deneyin."], ["Balık çorbası", "Tuna balığı, kılçık ve acılık düzeyini sorun; menşei belirsiz üründen kaçının."]], dayTrips: [["Visegrád", "Otobüs veya mevsimlik tekneyle kale tepesi; son dönüş ve yürüyüşü planlayın."], ["Esztergom", "Bazilika ve Slovakya manzarası için tren/otobüs bağlantısı; sınır geçişinde belgeyi taşıyın."]], caution: "HÉV için Budapeşte şehir bileti dışında ek banliyö bileti gerekebilir. Kiliselerde ayin, kıyafet ve fotoğraf kuralına uyun; özel avluya izinsiz girmeyin."
  },
  {
    city: "Eger", countryCode: "HU", focus: "Eğri Kalesi, Osmanlı mirası ve şarap vadisi", lede: "1552 savunma tarihini Osmanlı minaresi, Barok merkez, termal su ve Bükk eteklerindeki bağlarla birleştiren kuzey şehri.", days: "2–3 gün", arrival: "Eger vasútállomás · Budapeşte'den tren/otobüs", local: "Yürüyüş, yerel otobüs ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Türkçe kaynaklarda Eğri olarak da bilinen Eger, kale anlatısını Osmanlı dönemi, başpiskoposluk ve yaşayan şarap kültürüyle birlikte okumayı gerektirir.",
    sights: [["Eger Kalesi", "Surlar, kazılar ve 1552 anlatısı için en az iki-üç saat; sergi ve yeraltı turunu resmî saatten kontrol edin."], ["Eger Minaresi ve Türk Hamamı", "Dar minare merdiveni herkese uygun değildir; hamam tedavisi ile turistik spa hizmetini ayırın."], ["Szépasszony-völgy", "Mahzenleri yürüyüş/taksiyle gezin; tadım fiyatı, ölçü ve dönüşü önceden kararlaştırın."]],
    areas: [["Belváros ve kale çevresi", "Ana tarihî yerlere yürüyüş için en pratik ve atmosferik üs."], ["Szépasszony-völgy ve Egerszalók yönü", "Bağ/termal odaklı sakin konaklama; merkeze gece ulaşımını kontrol edin."]], foods: [["Egri yemekleri", "Palóc çorbası ve paprika temelli et yemeklerinde acılık ile içeriği sorun."], ["Egri Bikavér ve Egri Csillag", "Kırmızı ve beyaz kupajları ölçülü tadın; korumalı coğrafi ad ile pazarlama adını ayırın."]], dayTrips: [["Egerszalók", "Tuz tepesi görünümlü termal oluşum ve spa için otobüs/taksi dönüşünü planlayın."], ["Bükk Milli Parkı", "İşaretli yürüyüş, hava ve son otobüs nedeniyle ayrı tam gün gerektirir."]], caution: "Tadım sonrası araç kullanmayın; mahzen paketinde şişe ve servis ücretini sorun. Minare ve kale merdivenlerinde kaygan zemine, Bükk'te kapalı/av rotalarına dikkat edin."
  },
  {
    city: "Pécs", countryCode: "HU", focus: "Roma mezarları, Osmanlı mirası ve Zsolnay", lede: "Sopianae'nin erken Hristiyan kalıntılarını Osmanlı yapıları, Zsolnay seramikleri ve Mecsek eteklerinin Akdenizli ritmiyle birleştiren kent.", days: "2–3 gün", arrival: "Pécs vasútállomás · Budapeşte'den tren", local: "Otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Pécs'in küçük merkezi Roma, Orta Çağ, Osmanlı ve sanayi katmanlarını birkaç sokakta yan yana getirir; müze seçimi şehrin derinliğini belirler.",
    sights: [["Cella Septichora", "UNESCO erken Hristiyan mezar odalarında saatli giriş ve ışık/hareket koşulunu kontrol edin."], ["Széchenyi tér ve Gazi Kasım Paşa Camii", "Bugün kilise olarak kullanılan yapıda Osmanlı ve Hristiyan katmanlarını bağlamıyla okuyun."], ["Zsolnay Kültür Mahallesi", "Seramik, aile tarihi ve çağdaş kültür alanı geniştir; seçtiğiniz sergiler için yarım gün ayırın."]],
    areas: [["Belváros", "Meydan, müze ve restoranlara yürüyüş mesafesinde en işlevsel üs."], ["Tettye ve Zsolnay çevresi", "Mecsek yürüyüşleri ya da yaratıcı kültür mahallesi için iki farklı yerel seçenek."]], foods: [["Baranya mutfağı", "Güney Macaristan'ın paprika, lahana ve et yemeklerini günlük menüde deneyin."], ["Villány şarapları", "Kırmızı şarap tadımını sürücülü transfer veya trenle planlayın; rezervasyon yapın."]], dayTrips: [["Villány", "Bağlar ve mahzenler için tren/transfer; tadım sonrası araç kullanmayın."], ["Orfű ve Mecsek", "Göl ve orman günü için mevsimlik otobüs, yürüyüş ve hava kontrolü gerekir."]], caution: "Dinî yapılarda güncel ibadet işlevine saygı gösterin; Osmanlı mirasını yalnız romantik dekor olarak anlatmayın. Mecsek'te çevrimdışı harita ve kene önlemi kullanın."
  },
  {
    city: "Szeged", countryCode: "HU", focus: "Tisza kıyısı, Art Nouveau ve paprika", lede: "Büyük sel sonrası yeniden kurulan geniş bulvarları Tisza kıyısı, Art Nouveau sarayları ve güneşli güney mutfağıyla birleştiren şehir.", days: "2–3 gün", arrival: "Szeged vasútállomás · Budapeşte'den tren", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Szeged'in düzenli bulvarları 1879 selinin ardından kurulan modern şehir planını anlatır; sinagog, Dóm tér ve Reök Sarayı bu yeniden doğuşun farklı yüzleridir.",
    sights: [["Dóm tér ve Votive Church", "Katedral, kule ve açık hava festivali erişimini etkinlik takvimine göre kontrol edin."], ["Yeni Sinagog", "İç mekân, bahçe ve Yahudi tarihini rehberli saatle görün; ibadet ve fotoğraf kuralına uyun."], ["Reök Sarayı ve Tisza kıyısı", "Art Nouveau sergisini nehir yürüyüşüyle birleştirin; sıcak öğleni gölgeli müzeye ayırın."]],
    areas: [["Belváros", "Dóm tér, müzeler ve tramvaylara yakın; ilk ziyaret için kolay merkez."], ["Újszeged", "Tisza'nın doğusunda parklar, spor ve daha sakin konaklama için iyi alternatif."]], foods: [["Szegedi halászlé", "Tisza usulü balık çorbasında balık türü, kılçık ve acılık düzeyini sorun."], ["Pick salam ve paprika", "Yerel ürünün saklama, gümrük ve et içeriğini kontrol edin; paprika kalitesini güvenilir satıcıdan alın."]], dayTrips: [["Ópusztaszer", "Ulusal tarih parkı için mevsim, otobüs ve geniş alan süresini planlayın."], ["Mórahalom", "Termal banyo için bölgesel otobüs ve dönüş saatini önceden kaydedin."]], caution: "Yaz sıcak ve açık hava etkinlikleri yoğun olabilir; su ve gölge planı kurun. Tisza'da yalnız izinli alanda yüzün, sel/akıntı duyurusuna uyun."
  },
  {
    city: "Debrecen", countryCode: "HU", focus: "Büyük Reform Kilisesi, üniversite ve Hortobágy", lede: "Macar Kalvinist mirasını geniş meydanlar, termal park, üniversite hayatı ve Puszta'nın doğu bozkırlarıyla birleştiren şehir.", days: "2–4 gün", arrival: "Debrecen vasútállomás · DEB", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Ağustos–Ekim", pulse: "Debrecen, Budapeşte'nin küçük kopyası değildir; Reform geleneği, 1849 hafızası ve Hortobágy'a açılan doğu kapısı kendi kimliğini oluşturur.",
    sights: [["Büyük Reform Kilisesi", "1849 tarihini, iç mekânı ve kule erişimini ibadet saatinden ayrı planlayın."], ["Déri Müzesi", "Munkácsy üçlemesi ve bölgesel koleksiyon için geçici kapanış/sergi saatini kontrol edin."], ["Nagyerdő ve Aquaticum", "Üniversite, park, termal banyo ve stadyum çevresinden ilginize göre yarım günlük rota seçin."]],
    areas: [["Belváros", "Ana kilise, meydan ve tramvay için en pratik şehir üssü."], ["Nagyerdő", "Park, üniversite ve termal tesislere yakın daha yeşil konaklama bölgesi."]], foods: [["Debreceni kolbász", "Şehrin adını taşıyan sucuğun et, tütsü ve servis biçimini sorun."], ["Slambuc ve Alföld yemekleri", "Makarna–patates temelli çoban yemeğini mevsimlik etkinlik veya geleneksel lokantada deneyin."]], dayTrips: [["Hortobágy", "Milli parkı gösteri alanıyla karıştırmayın; resmî ziyaret merkezi, rehber ve tren/otobüs saatini kullanın."], ["Nyíregyháza", "Müze köyü veya hayvanat bahçesi için trenle ayrı tam gün; etik koşulları değerlendirin."]], caution: "Hortobágy'da yaz güneşi, fırtına ve açık araziyi küçümsemeyin; izinsiz koruma alanına girmeyin. Termal banyoda sağlık, yaş ve havuz kurallarını okuyun."
  },
  {
    city: "Balaton Gölü", countryCode: "HU", focus: "göl kasabaları, volkanik tepeler ve bağ rotaları", lede: "Orta Avrupa'nın büyük gölünü Balatonfüred, Tihany, Keszthely ve kuzey kıyının volkanik bağlarıyla birleştiren geniş yaz bölgesi.", days: "4–7 gün", arrival: "Budapeşte'den kuzey/güney kıyı trenleri", local: "Tren, otobüs, feribot, bisiklet ve tekne", best: "Mayıs–Eylül · bağlar için Eylül–Ekim", pulse: "Balaton tek kasaba değildir; kuzey kıyı bağ ve tepe, güney kıyı plaj ve gece hayatı, batı uç Keszthely–Hévíz kültür/termal odağı taşır.",
    sights: [["Tihany Yarımadası", "Manastır, lavanta ve işaretli patikaları erken saatte gezin; sezon trafik ve feribotunu kontrol edin."], ["Badacsony", "Volkanik bazalt tepesi ile bağları yürüyüşte birleştirin; tadım sonrası araç veya bisiklet kullanmayın."], ["Keszthely ve Festetics Sarayı", "Batı uçtaki saray, müze ve Hévíz bağlantısı için ayrı tam gün ayırın."]],
    areas: [["Balatonfüred–Tihany", "İlk ziyaret, kuzey kıyı bağları ve feribot için en dengeli üs hattı."], ["Keszthely veya Siófok", "Kültür/termal batı ya da plaj/gece hayatı güneyi için iki farklı alternatif."]], foods: [["Balaton balığı", "Fogas adıyla sunulan balığın türü ve gerçek menşeini sorun; koruma/mevsim kuralına uyun."], ["Kuzey kıyı şarapları", "Olaszrizling ve volkanik bağ tadımında randevu, ölçü ve dönüş transferini planlayın."]], dayTrips: [["Hévíz", "Termal göl için sağlık, yüzme ve kapasite kuralını kontrol edin; Keszthely'den otobüsle kolay."], ["Tapolca ve Káli Havzası", "Mağara gölü, köyler ve pazarlar için araç/seyrek otobüs planı gerekir."]], caution: "Gölde yalnız belirlenmiş plaj ve bayrak koşulunda yüzün; fırtına uyarı ışıklarını izleyin. Bisiklet yolunda kask, ışık ve alkol kuralına uyun; yazın son tren/feribotu önceden kaydedin."
  },
  {
    city: "Sopron", countryCode: "HU", focus: "Orta Çağ merkezi, şarap ve Fertő sınır bölgesi", lede: "Roma surlarından Barok avlulara uzanan merkezi, Kékfrankos bağları ve Avusturya sınırındaki Fertő kültür peyzajıyla birleştiren kent.", days: "2–4 gün", arrival: "Sopron vasútállomás · Győr/Viyana bağlantısı", local: "Yürüyüş, otobüs, bisiklet ve tren", best: "Nisan–Haziran · Eylül–Ekim · Aralık", pulse: "Sopron'un çok katmanlı merkezinde Macarca ve Almanca tarih yan yanadır; şehir Fertő/Neusiedl Gölü'nün iki ülkeye yayılan peyzajına doğal bir kapıdır.",
    sights: [["Tűztorony ve Fő tér", "Yangın Kulesi, Roma forumu ve tarihî evleri tek bilet/rota seçenekleriyle sakin bir yarım güne yayın."], ["Eski Sinagog ve tarihî avlular", "Orta Çağ Yahudi mirasını güncel açılış ve rehberli saatle görün; yaşayan konut avlularına saygı gösterin."], ["Lővérek ve Károly-kilátó", "Ormanlık tepelerde işaretli yürüyüş, hava ve gün ışığı hesabıyla şehir manzarasına çıkın."]],
    areas: [["Belváros", "Kule, müze ve restoranlara yakın, ilk ziyaret için kompakt üs."], ["Lővérek", "Orman, yürüyüş ve sakin konaklama için merkezin güneybatısında yeşil alternatif."]], foods: [["Soproni Kékfrankos", "Yerel kırmızı şarabı lisanslı mahzende tadın; üretici randevusu ve ulaşımı doğrulayın."], ["Burgenland–Macar sınır mutfağı", "Kraut, av eti ve hamur işlerinde bölgenin çift dilli etkisini günlük menülerde arayın."]], dayTrips: [["Fertő-Hanság", "UNESCO göl peyzajında kuş gözlemi ve bisiklet için rüzgâr, sınır ve koruma kuralını kontrol edin."], ["Fertőd", "Esterházy Sarayı için bölgesel ulaşım, tur dili ve açılış saatini önceden planlayın."]], caution: "Bisikletle Avusturya sınırını geçebilirsiniz ama pasaport/vize ve telefon dolaşım koşulunu taşıyın. Bağ sıralarına izinsiz girmeyin, tadım sonrası sürmeyin."
  },
];

export const hungaryGuides = makeRegionalGuides(profiles);
