import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Kotor", countryCode: "ME", focus: "UNESCO surları, körfez ve dağ manzaraları", lede: "Lovćen'in dik yamaçları altında taş surları, Venedik meydanları ve fiyort görünüşlü körfezi birleştiren Karadağ'ın tarihî kıyı merkezi.", days: "3–4 gün", arrival: "TIV · Kotor otobüs terminali", local: "Yürüyüş, otobüs, tekne ve taksi", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Kotor'un sur içi küçük görünür fakat merdiven, müze ve kıyı günleri zaman ister. Kruvaziyer kalabalığı çekildikten sonraki akşam ve sabah, kent deneyiminin en değerli bölümüdür.",
    sights: [["Kotor Eski Şehri", "Aziz Tryphon, Denizcilik Müzesi, kiliseler ve meydanlardan iki-üç odak seçin; ibadet ve gemi gününü kontrol edin."], ["San Giovanni sur yolu", "Basamaklı çıkış için erken saat, su ve uygun ayakkabı gerekir; sıcak, fırtına veya bakım kapanışında devam etmeyin."], ["Kotor Körfezi", "Perast, Our Lady of the Rocks veya kıyı köylerinden birini lisanslı tekne/otobüsle ayrı gün planlayın."]],
    areas: [["Stari Grad", "Atmosfer ve ana yerlere yakın; merdiven, gece gürültüsü ve araçsız erişim valiz için zor olabilir."], ["Dobrota ve Muo", "Kıyı yürüyüşü, manzara ve daha sakin konaklama için merkeze yürüyüş/otobüs bağlantılı alternatif."]], foods: [["Boka deniz ürünleri", "Kalamar, midye ve balıkta günlük fiyatın kilo/porsiyon olduğunu netleştirin; tür ve tazeliği sorun."], ["Njeguški pršut ve peynir", "Kurutulmuş et/peyniri küçük porsiyon tadın; et türü, soğuk zincir ve gümrük kuralını kontrol edin."]], dayTrips: [["Perast", "Kısa otobüs/tekneyle kolay görünse de ada, müze ve akşam için ayrı yarım/tam gün ayırın."], ["Lovćen", "Kotor serpantinleri, Njeguši ve mozole için hava, araç/transfer ve yüzlerce basamak planı gerekir."]], caution: "Kruvaziyer ve yaz trafiğinde kısa mesafe saatler sürebilir; uçuş gününde geniş pay bırakın. Surlarda korkuluk dışına çıkmayın, lisanssız tekneye binmeyin ve şehir vergisi/konaklama kaydını kontrol edin."
  },
  {
    city: "Budva", countryCode: "ME", focus: "eski şehir, Adriyatik plajları ve kıyı gece hayatı", lede: "Taş sur içini uzun Adriyatik sahilleri, yaz festivalleri, yoğun gece hayatı ve Budva Rivierası'nın koylarıyla birleştiren tatil merkezi.", days: "3–5 gün", arrival: "TIV/Podgorica · Budva otobüs terminali", local: "Otobüs, taksi, yürüyüş ve tekne", best: "Mayıs–Haziran · Eylül", pulse: "Budva'nın merkez plaj ve kulüpleri en görünür yüzdür; Petrovac, Pržno ve Paštrovići kıyısı daha sakin tarih/doğa katmanı sunar.",
    sights: [["Budva Stari Grad", "Surlar, sitadel, kiliseler ve küçük müzeleri sabah erken gezin; etkinlik/konser erişimi değiştirebilir."], ["Mogren ve kıyı patikası", "Kaya düşmesi, dalga ve bakım uyarısını kontrol edin; kapalı geçidi aşmayın, yalnız bayraklı alanda yüzün."], ["Sveti Stefan manzarası", "Ada-otelin iç erişimi ve plaj bölümleri işletme koşuluna bağlıdır; özel alana girmeden izinli seyir noktasını kullanın."]],
    areas: [["Stari Grad ve merkez", "Plaj, restoran ve gece hayatına yakın; yazın gürültülü ve pahalı."], ["Bečići, Pržno veya Petrovac", "Daha uzun plaj, aile/sakinlik veya küçük kıyı kasabası için üç farklı otobüslü alternatif."]], foods: [["Adriyatik balığı", "Günlük balığın kilo fiyatını pişirmeden önce tarttırın; kuver, garnitür ve servis ücretini sorun."], ["Balkan ızgarası", "Ćevapi ve pljeskavica'da porsiyon, et türü ve kaymak içeriğini sorun."]], dayTrips: [["Cetinje", "Eski kraliyet başkenti için otobüs/transferle kültür günü; müze saatlerini kontrol edin."], ["Skadar Gölü", "Virpazar teknesi için lisans, can yeleği, rota ve kuş koruma kuralını doğrulayın."]], caution: "Gece kulübünde hesap ve içecek fiyatını siparişten önce görün; lisanssız taksi/tekne kullanmayın. Rip akıntısı, aşırı sıcak ve kaya düşmesi uyarısında plaj/patikayı değiştirin."
  },
  {
    city: "Podgorica", countryCode: "ME", focus: "başkent yaşamı, modern tarih ve Skadar bağlantısı", lede: "Ribnica ile Morača'nın kesişiminde Osmanlı izlerini Yugoslav modernizmi, canlı kafe kültürü ve göl–kanyon geçişleriyle birleştiren başkent.", days: "2–3 gün", arrival: "TGD · Podgorica tren/otobüs istasyonu", local: "Otobüs, taksi ve yürüyüş", best: "Mart–Mayıs · Eylül–Kasım", pulse: "Podgorica kıyı şehirleri gibi anıtsal değildir; Karadağ'ın çağdaş gündelik yaşamını, pazarını ve ülke içi ulaşım düğümünü anlamak için değerlidir.",
    sights: [["Stara Varoš ve Ribnica", "Saat Kulesi, eski köprü ve nehir birleşimini yürüyün; yaz sıcağında sabah/akşam seçin."], ["Millennium Köprüsü ve Nova Varoš", "Morača kıyısını modern merkez, parklar ve kafe meydanlarıyla birleştirin."], ["Karadağ Çağdaş Sanat Merkezi", "Kruševac Sarayı pavyonları ve geçici sergiyi resmî programdan kontrol edin."]],
    areas: [["Nova Varoš", "Kafe, park ve merkez yürüyüşü için ilk ziyarette işlevsel."], ["Preko Morače ve City Kvart", "Modern konut, restoran ve daha yerel akşam için iki farklı alternatif."]], foods: [["Kačamak ve cicvara", "Mısır/patates ile peynir-kaymak temelli dağ yemeklerinde süt içeriği ve porsiyonu sorun."], ["Podgorica pazarı", "Peynir, zeytin ve mevsim meyvesini güvenilir tezgahtan alın; taze ürünü soğukta taşıyın."]], dayTrips: [["Virpazar", "Trenle Skadar Gölü kapısına gidin; tekne rezervasyonunu hava ve lisansla doğrulayın."], ["Ostrog Manastırı", "Dik dağ yoluna tren+taksi veya resmî turla gidin; ibadet, kıyafet ve kalabalık kuralına uyun."]], caution: "Yazın aşırı sıcak öğle yürüyüşünü sınırlayın; nehirde yalnız izinli alanda yüzün. Ostrog yolunda deneyimli sürücü/transfer seçin, istasyon çevresinde lisanslı taksi kullanın."
  },
  {
    city: "Cetinje", countryCode: "ME", focus: "eski kraliyet başkenti, müzeler ve Lovćen", lede: "Karadağ kraliyet ve devlet tarihini küçük saraylar, manastır, elçilik yapıları ve Lovćen'in yüksek karst peyzajıyla birleştiren kültür şehri.", days: "2–3 gün", arrival: "Podgorica/Budva'dan otobüs", local: "Yürüyüş, otobüs ve transfer", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Cetinje'nin sakin sokakları 19. yüzyıl diplomasi ve ulus inşası tarihini birkaç blokta toplar; Lovćen eklenince şehir-doğa dengesi kurulur.",
    sights: [["Kral Nikola Müzesi", "Saray odaları, hanedan ve diplomasi koleksiyonunu resmî saatle gezin; birleşik müze bileti olup olmadığını sorun."], ["Cetinje Manastırı", "Yaşayan Ortodoks ibadet alanında kıyafet, sessizlik ve fotoğraf kuralına uyun; kutsal emanet kuyruğunu zorlamayın."], ["Lovćen ve Njegoš Mozolesi", "461 basamak, rüzgâr, sis ve dağ yolu gerekir; hava kötü olduğunda erteleyin."]],
    areas: [["Tarihî merkez", "Saray, manastır, müze ve kafelere yürüyüş için tek ve güçlü üs."], ["Ivanova Korita", "Lovćen yürüyüşü ve doğa için araç/transfer gerektiren dağ alternatifi."]], foods: [["Njeguši ürünleri", "Pršut, peynir ve balı üreticiden tadın; et türü, saklama ve gümrük kuralını kontrol edin."], ["Karadağ ev yemekleri", "Kuzu, lahana ve süt ürünlerinde önceden sipariş, porsiyon ve içerik sorun."]], dayTrips: [["Njeguši", "Köy üreticileri ve eski yol manzarası için küçük araç/rehber; tadım sonrası sürmeyin."], ["Lipa Mağarası", "Saatli rehber, serin sıcaklık ve servis transferini resmî işletmeden doğrulayın."]], caution: "Mozole ve eski Kotor yolunda sis/rüzgâr görüşü hızla düşer; bariyer dışına çıkmayın. Manastırda hacıların alanına saygı gösterin, tarihî eser veya dinî objeyi izinsiz fotoğraflamayın."
  },
  {
    city: "Perast", countryCode: "ME", focus: "Barok taş kasaba, ada kiliseleri ve Boka tarihi", lede: "Boka Kotorska'nın en dar kıyılarından birinde Barok sarayları, çan kuleleri ve iki küçük ada silüetiyle yavaş bir deniz kasabası.", days: "1–2 gün", arrival: "Kotor/Herceg Novi'den otobüs veya tekne", local: "Yürüyüş ve lisanslı tekne", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Perast günübirlik tekne durağı gibi tüketilse de akşam ve sabah sessizliği, denizcilik müzesi ile taş saray ayrıntılarını görünür kılar.",
    sights: [["Our Lady of the Rocks", "Yapay adadaki kilise/müze için lisanslı kısa tekne kullanın; ibadet, deniz ve kapanış koşuluna uyun."], ["Aziz Nikola Çan Kulesi", "Açık ve güvenliyse dar basamaklarla çıkın; ayin, rüzgâr ve kapasite kuralını kontrol edin."], ["Perast Müzesi", "Denizci aileler, Venedik dönemi ve Boka ticaretini saray koleksiyonuyla bağlama oturtun."]],
    areas: [["Kıyı merkezi", "Kasaba küçük ve araç trafiği sınırlı; ada teknesi ve akşam için en atmosferik üs."], ["Risan", "Roma mozaikleri, daha yerel konaklama ve otobüs bağlantısı için yakın alternatif."]], foods: [["Boka usulü deniz ürünleri", "Midye ve balıkta menşe, kilo/porsiyon, garnitür ve servis ücretini netleştirin."], ["Perast tatlıları", "Peraska torta gibi bademli tatlılarda kuruyemiş ve yumurta alerjenini sorun."]], dayTrips: [["Risan", "Roma mozaikleri ve pazar için kısa otobüs; çalışma saatini önceden kontrol edin."], ["Herceg Novi", "Körfezin batı ucuna otobüsle kale, merdiven ve bahçe rotası için ayrı gün."]], caution: "İki ada da aynı erişime sahip değildir; Saint George adasına izinsiz çıkmayın. Fiyatı konuşmadan özel tekneye binmeyin, fırtına/rüzgârda sefer iptaline uyun."
  },
  {
    city: "Herceg Novi", countryCode: "ME", focus: "kaleler, merdivenli eski şehir ve körfez bahçeleri", lede: "Boka'nın batı girişinde Osmanlı–Venedik kalelerini, Akdeniz bahçelerini, uzun kıyı promenadını ve binlerce basamaklı mahalleleri birleştiren kent.", days: "2–4 gün", arrival: "DBV/TIV · Herceg Novi otobüs terminali", local: "Otobüs, yürüyüş, taksi ve tekne", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Herceg Novi'nin kot farkı manzarayı güzelleştirir ama konaklama kararını belirler; deniz seviyesindeki promenade ile eski şehir arasında günlük merdiven hesabı yapın.",
    sights: [["Forte Mare ve Kanli Kula", "İki kalenin açılış, etkinlik ve güvenlik koşulu farklıdır; gün batımında korkuluk dışına çıkmayın."], ["Stari Grad ve Saat Kulesi", "Meydan, kilise ve taş merdivenleri Savina yönüne yavaş bir rota halinde yürüyün."], ["Savina Manastırı", "Körfez manzaralı yaşayan ibadet alanında kıyafet ve fotoğraf kuralına uyun."]],
    areas: [["Stari Grad", "Kale ve meydanlara yakın; yüksek basamak ve valiz erişimi zor."], ["Topla ve Igalo", "Promenad, plaj ve spa için daha düz/modern konaklama alternatifleri."]], foods: [["Körfez balığı ve kalamar", "Günlük ürünün türü, kilo fiyatı ve pişirme ücretini işlem öncesi sorun."], ["Akdeniz–Balkan sofrası", "Zeytinyağlılar, peynir ve ızgarada mevsimlik yerel ürünü tercih edin."]], dayTrips: [["Mavi Mağara", "Deniz sakinliği, lisanslı tekne, can yeleği ve yüzme koşuluyla planlayın; yoğun saati atlayın."], ["Luštica Yarımadası", "Köy, koy ve zeytinlik için araç/tekne; özel mülk ve kapalı askerî alan tabelalarına uyun."]], caution: "Merdiven ve sıcak erişilebilirliği zorlaştırır; oda seçerken gerçek kotu sorun. Hırvatistan günübirliği Schengen giriş hakkı gerektirir; belgesiz sınır planlamayın."
  },
  {
    city: "Durmitor", countryCode: "ME", focus: "yüksek dağ yürüyüşleri, Tara Kanyonu ve Žabljak", lede: "Buzul gölleri, keskin kireçtaşı zirveleri ve Avrupa'nın derin kanyonlarından Tara'yı Žabljak çevresinde koruyan UNESCO milli parkı.", days: "4–7 gün", arrival: "Žabljak otobüs terminali · Podgorica transferi", local: "Yürüyüş, bisiklet, araç ve lisanslı rafting", best: "Haziran–Eylül · kar sporları için Ocak–Mart", pulse: "Durmitor'da Crno Jezero kolay giriş, Bobotov Kuk ciddi dağ günüdür. Rota seçimini fotoğraf popülerliğine değil kondisyon, hava ve ekipmana göre yapın.",
    sights: [["Crno Jezero", "Žabljak'tan kolay göl rotasını sabah yürüyün; tahta yol, orman ve yüzme kuralını park duyurusundan kontrol edin."], ["Bobotov Kuk", "Uzun ve teknikleşebilen yüksek dağ rotasına yalnız uygun deneyim, erken çıkış, hava ve gerekirse rehberle gidin."], ["Tara Kanyonu", "Raftingte lisanslı operatör, kask, can yeleği, su seviyesi ve sınır/park rotasını yazılı doğrulayın."]],
    areas: [["Žabljak", "Otobüs, restoran, ekipman ve çoğu park transferi için temel üs."], ["Pitomine veya Tepca", "Daha sakin manzara/kanyon erişimi için araç ve ön hazırlık gerektiren alternatif."]], foods: [["Kačamak", "Patates/mısır, peynir ve kaymakla doyurucudur; süt içeriği ve porsiyonu sorun."], ["Dağ kuzusu ve mantar", "Etin kaynağı, mantarın güvenilir üreticisi ve mevsim durumunu sorun; yabani mantar toplamayın."]], dayTrips: [["Đurđevića Tara Köprüsü", "Seyir ve zipline işletmelerini güvenlik/sertifika açısından değerlendirin; yol kenarında kontrolsüz durmayın."], ["Piva Gölü", "Uzak kanyon yolu, tüneller ve manastır için araç, yakıt ve gün ışığı planı gerekir."]], caution: "Dağ havası dakikalar içinde değişir; kapalı patika, fırtına veya kar uyarısında dönün. Kurtarma sigortası, çevrimdışı harita ve katman taşıyın; rafting/zipline için en ucuz değil güvenilir lisanslı işletmeyi seçin."
  },
  {
    city: "Ulcinj", countryCode: "ME", focus: "uzun kumsallar, çok kültürlü eski şehir ve Ada Bojana", lede: "Karadağ'ın güney ucunda taş eski şehri, Arnavutça–Karadağca kültürü, Velika Plaža ve Bojana Deltası'nın geniş doğasıyla birleştiren kıyı kenti.", days: "3–5 gün", arrival: "Podgorica/Tivat üzerinden otobüs", local: "Otobüs, taksi, bisiklet ve yürüyüş", best: "Mayıs–Haziran · Eylül", pulse: "Ulcinj'in kimliği Adriyatik plajından büyüktür; denizcilik tarihi, Arnavut topluluğu, zeytinlikler ve tuzla kuş alanı şehri farklılaştırır.",
    sights: [["Ulcinj Eski Şehri", "Kale, müze ve deniz manzarasını sabah/akşam yürüyün; dik taş zeminde uygun ayakkabı kullanın."], ["Velika Plaža", "Uzun kumsalda doğru plaj bölümü ve dönüşü seçin; rüzgâr, dalga, kite alanı ve cankurtaran bayrağına uyun."], ["Ulcinj Salinası", "Kuş gözlemi erişimi yönetim ve koruma durumuna bağlıdır; resmî açık rota/rehber olmadan alana girmeyin."]],
    areas: [["Stari Grad ve Mala Plaža", "İlk ziyaret ve akşam için merkezî; dik ve yazın yoğun."], ["Velika Plaža ve Ada Bojana yönü", "Uzun plaj, kite ve doğa için araç/taksi gerektiren daha dağınık alternatif."]], foods: [["Arnavut–Karadağ mutfağı", "Biber dolması, börek, kuzu ve süt ürünlerinde bölgesel ev yemeği lokantalarını deneyin."], ["Bojana balığı", "Nehir/deniz balığında tür, mevsim, menşe ve kilo fiyatını sorun."]], dayTrips: [["Bar", "Eski Bar, zeytin ve demiryolu için otobüsle ayrı kültür günü."], ["Skadar Gölü güneyi", "Vladimir/Šas çevresi için araç, arkeoloji erişimi ve sınır yakınlığı kuralı gerekir."]], caution: "Arnavutluk sınırını pasaport ve geçerli giriş koşulu olmadan geçmeyin. Delta, nudist bölge ve özel plaj kurallarına saygı gösterin; kite alanında yüzme koridoruna girmeyin."
  },
];

export const montenegroGuides = makeRegionalGuides(profiles);
