import { makeWorldExpansionGuides, type WorldExpansionProfile } from "./worldExpansionFactory";

const profiles: WorldExpansionProfile[] = [
  {
    city: "Amsterdam", countryCode: "NL", focus: "Kanallar, Müzeler ve 4 Günlük Rota", days: "3–5 tam gün",
    lede: "Amsterdam'ın kanal halkalarını, Rijksmuseum–Van Gogh biletlerini, Jordaan ve Noord mahallelerini bisiklet yollarına saygılı ve kalabalıktan akıllıca kaçarak planlar.",
    arrival: "Schiphol'den NS treni Centraal ve bazı şehir istasyonlarına gider; peron ile bakım durumunu NS uygulamasından kontrol edin. Takside yalnız resmî sıra/uygulama kullanın; oteliniz Zuid veya Sloterdijk'e daha yakın olabilir.",
    local: "Yürüyüş, GVB tramvay-metro ve ücretsiz/ücretli feribotlar yeterlidir. OVpay kullanıyorsanız aynı kart/cihazla giriş-çıkış yapın. Turist olarak bisiklete ancak şehir trafiğine gerçekten hâkimseniz binin.", best: "Nisan–Haziran · Eylül",
    identity: ["Amsterdam'ın UNESCO kanal halkaları 17. yüzyıl ticaret kentini, dar parselleri ve su yönetimini görünür kılar; şehir Dam Meydanı'ndan ibaret değildir.", "Müze bölgesini bir gün, Jordaan–kanal merkezini bir gün ve Noord/Doğu mahallelerini bir gün planlamak kalabalığı dağıtır."],
    sights: [["Rijksmuseum ve Van Gogh Museum", "İki müze de belirli saatli bilet isteyebilir. Aynı güne ikisini ancak uzun müze temposuna alışkınsanız koyun; Museumplein'i öğle molası olarak kullanın."], ["Kanal halkaları ve Jordaan", "Grachtengordel'i sabah yürüyün, Anne Frank House için yalnız resmî belirli saatli bileti kullanın. Jordaan hofje avlularında sessizlik ve özel alan işaretine uyun."], ["Noord ve Doğu Docklands", "Centraal arkasındaki feribotla Noord'a geçip NDSM veya Eye çevresini görün; farklı bir gün Doğu Adaları'nın çağdaş konut-su mimarisini yürüyün."]],
    areas: ["**Jordaan / batı kanal halkası** ilk ziyaret atmosferi için güçlü ama pahalı ve eski binalarda dik merdivenlidir.", "**De Pijp** yemek-pazar; **Oost** yerel ritim; **Noord** yaratıcı alan ve daha uzun merkez bağlantısı sunar."],
    tastes: ["Bitterballen, haring, patat, stroopwafel ve appeltaart hızlı klasiklerdir; yalnız turistik merkezde değil pazar ve kahverengi kafelerde deneyin.", "Endonezya rijsttafel, Surinam roti ve Türk-Fas mutfakları Amsterdam'ın sömürge/göç tarihini sofrada gösterir. Rijsttafel porsiyon ve kişi sayısını önceden sorun."],
    stay: "Centraal çevresine en yüksek fiyatı vermek zorunlu değildir; tramvay/metroya 5–10 dakika mesafede De Pijp, Oud-West veya Oost daha dengeli olabilir. Eski kanal evinde asansör ve merdiveni teyit edin.",
    evenings: "Jordaan kahverengi kafeleri, De Pijp restoranları, Leidseplein çevresi canlı müzik ve Noord kültür alanları farklı akşamlar sunar. Kulüp için kimlik, ön bilet ve gece ulaşımını kontrol edin.",
    dayTrips: ["Haarlem ve Utrecht trenle kısa ama ayrı tam gün değerindedir; Amsterdam'dan yalnız bir fotoğraf molası gibi kullanmayın.", "Zaanse Schans yarım gün, Waterland köyleri bisiklet/otobüs günü olabilir; tek günde iki turistik kırsal kümeyi sıkıştırmayın."],
    season: "Nisan lale dönemi güzel ama çok yoğun; mayıs-haziran uzun günler, eylül daha dengeli kalabalık sunar. Yağmur ve rüzgâr yıl boyu mümkündür.",
    budget: "Konaklama ve büyük müzeler pahalı; market pikniği, ücretsiz feribot, yürüyüş ve seçilmiş iki müze bütçeyi dengeler. Şehir vergisini oda fiyatından ayrı kontrol edin.",
    cautions: ["Bisiklet yolu kaldırım değildir; kırmızı asfaltta durmayın, tramvay rayını dik açıyla geçin ve zil duyunca yana çıkın.", "Sokakta madde satanlardan uzak durun. Coffeeshop kuralları ile kamusal alanda kullanım kuralını aynı sanmayın; alkol/maddeyi bisikletle birleştirmeyin."],
  },
  {
    city: "Rotterdam", countryCode: "NL", focus: "Çağdaş Mimari, Liman ve Çok Kültürlü Mutfak", days: "2–3 tam gün",
    lede: "Rotterdam'ın savaş sonrası mimarisini, Markthal–Cube Houses hattını, liman dönüşümünü ve Katendrecht akşamını yürüyüş ile su ulaşımına göre kurar.",
    arrival: "Amsterdam Schiphol'den ve Belçika yönünden trenler Rotterdam Centraal'a gelir. Intercity Direct ek ücret ve rota koşuluna sahip olabilir; NS uygulamasındaki ürün notunu okuyun.",
    local: "RET metro-tramvay, yürüyüş, Waterbus ve water taxi kullanılır. OVpay'de aynı kartla giriş-çıkış yapın; su taksisinde rezervasyon/ücret sistemi ayrıdır.", best: "Mayıs–Haziran · Eylül",
    identity: ["1940 bombardımanı sonrası kendini yeniden kuran Rotterdam, Hollanda'nın kanal evi klişesinden farklı; deneysel mimari, işleyen dev liman ve göçmen mutfaklarının şehridir.", "Centraal–Coolsingel–Markthal yürüyüşü, Kop van Zuid–Katendrecht ve bir liman günü üç ana kümeyi oluşturur."],
    sights: [["Centraal'dan Markthal'a mimari yürüyüş", "Luchtsingel, Coolsingel, Timmerhuis, Markthal ve Cube Houses hattında binaların kamusal alanla ilişkisini okuyun; yalnız dış cephe fotoğrafıyla geçmeyin."], ["Kop van Zuid ve Katendrecht", "Erasmus Bridge'i yürüyün; Hotel New York, Fenix çevresi ve Deliplein'da liman göçü ile dönüşüm hikâyesini görün."], ["Liman turu ve Depot Boijmans", "Spido gibi liman turunda rota, dil ve dış güverteyi kontrol edin. Aynalı Depot için belirli saatli erişim/çatı koşulunu resmî siteden doğrulayın."]],
    areas: ["**Centrum–Blaak** ilk ziyaret ve mimari yürüyüş için en pratiktir.", "**Kop van Zuid / Katendrecht** manzara, tasarım ve akşam; **Delfshaven** tarihî kanal dokusu ve sakin konaklama sunar."],
    tastes: ["Şehrin gücü Surinam, Cape Verde, Türk, Fas ve Asya mutfaklarıdır. West-Kruiskade boyunca roti, noodle, döner ve fırınları karşılaştırın.", "Kapsalon Rotterdam kökenli ağır bir fast-food klasiğidir; paylaşmak iyi fikir. Markthal'ı görsel durak sayın, tek yemek adresi olarak kullanmayın."],
    stay: "Centraal ile Blaak arasında metroya yakın konum kısa gezi için iyidir. Kop van Zuid manzaralı ama gece köprü/metro bağlantısı gerektirebilir.",
    evenings: "Witte de Withstraat bar ve sanat, Deliplein restoran, Maassilo/Rotown etkinliğe göre müzik sunar. Programı ve son metro/OV-fiets iadesini önceden kontrol edin.",
    dayTrips: ["Delft ve Dordrecht kısa trenle farklı tarihî ölçekler sunar; ikisinden birini seçin.", "Kinderdijk Waterbus+bağlantıyla yapılabilir; sezon, bisiklet ve son dönüş saatini kontrol edin."],
    season: "Geç ilkbahar ve erken sonbahar su-mimari gezisi için dengeli; rüzgâr liman ve köprülerde sert hissedilir.",
    budget: "Amsterdam'a göre oda bazen daha iyi değer sunar; liman turu, Depot ve su taksisi ek maliyettir. Waterbus ile su taksisini fiyat olarak karıştırmayın.",
    cautions: ["Köprü ve liman kenarında güçlü rüzgâra dikkat edin; drone ve endüstriyel liman erişim kurallarına uyun.", "Bisiklet yolunda yürümeyin; çok şeritli modern merkezde yaya ışığı ve tramvay yönünü ayrı kontrol edin."],
  },
  {
    city: "Lahey", countryCode: "NL", focus: "Mauritshuis, Siyaset ve Scheveningen", days: "2–3 tam gün",
    lede: "Lahey'de Mauritshuis, Binnenhof çevresi, barış kurumları ve Scheveningen sahilini yönetim merkezi ile deniz şehrini ayırmadan planlar.",
    arrival: "Den Haag Centraal ve HS iki farklı istasyondur; Amsterdam/Rotterdam treninizin hangisine geldiğini kontrol edin. Tramvaylar merkez ile Scheveningen'i bağlar.",
    local: "HTM tramvay-otobüs ve yürüyüş yeterlidir. OVpay'de aynı kart/cihazı kullanın; sahil dönüşünde etkinlik ve güzel hava kalabalığına pay bırakın.", best: "Nisan–Haziran · Eylül",
    identity: ["Amsterdam anayasal başkent olsa da hükümet, parlamento ve birçok uluslararası hukuk kurumu Lahey'dedir; aynı şehir birkaç kilometre sonra Kuzey Denizi sahiline açılır.", "Bir merkez-sanat günü ile bir uluslararası bölge–Scheveningen günü en doğal plandır."],
    sights: [["Mauritshuis ve Hofvijver", "Vermeer ve Rembrandt koleksiyonu kompakt ama yoğundur; belirli saatli bileti düşünün. Binnenhof yenileme/erişim durumunu ziyaret gününde kontrol edin."], ["Peace Palace ve uluslararası bölge", "Ziyaretçi merkezi, tur ve mahkeme oturum erişimi güvenlik ile programa bağlıdır; pasaport ve çanta kuralını resmî siteden doğrulayın."], ["Scheveningen ve Kunstmuseum", "Kunstmuseum'un Mondrian koleksiyonunu sahil tramvay hattına bağlayın; plajda rüzgâr, yüzme bayrağı ve akşam dönüşünü hesaba katın."]],
    areas: ["**Centrum / Hofkwartier** müze, yemek ve istasyon erişimi için en iyi ilk üs.", "**Statenkwartier** Kunstmuseum ve zarif mahalle; **Scheveningen** deniz önceliği ve merkeze tramvay bağlantısı sunar."],
    tastes: ["Haring, kibbeling ve füme balık sahil klasikleri; taze ürün ve fiyatı görünür balıkçı seçin.", "İndonezya-Hollanda mutfağı ve şehrin uluslararası nüfusu güçlü restoran çeşitliliği yaratır. Rijsttafel kişi sayısı ve porsiyonu sorun."],
    stay: "Kültür ve tren için merkez; plaj tatili için Scheveningen. Sahilde yaz hafta sonu gürültü, otopark ve tramvay yoğunluğunu yorumlardan kontrol edin.",
    evenings: "Grote Markt ve Plein merkez gecesi; sahil pavyonları yaz akşamı sunar. Parlamento çevresindeki güvenlik bariyeri ve etkinliklerde yönlendirmeye uyun.",
    dayTrips: ["Delft tramvay/trenle kolaydır ve bir tam gün tarih-seramik rotası sunar.", "Leiden müzeler ve kanallar için kısa trenle ayrı gün; ikisini tek güne sıkıştırmayın."],
    season: "İlkbahar-sonbahar müze-sahil dengesi için iyi; yaz plaj yoğun, kış rüzgârlıdır. Kuzey Denizi suyu ve hava hızla değişebilir.",
    budget: "Merkez oteli ve müzeler ana maliyet; sahil yürüyüşü ücretsizdir. Scheveningen restoranında manzara primi, servis ve rezervasyon koşulunu okuyun.",
    cautions: ["Elçilik, mahkeme ve hükümet binalarında fotoğraf-güvenlik işaretlerine uyun; bariyer veya protesto alanına izinsiz girmeyin.", "Sahilde kırmızı bayrak ve cankurtaran talimatını ciddiye alın; rüzgârda kumul koruma çitlerini aşmayın."],
  },
  {
    city: "Utrecht", countryCode: "NL", focus: "Dom Kulesi, İki Katlı Kanallar ve Mahalleler", days: "2–3 tam gün",
    lede: "Utrecht'in Oudegracht wharf seviyelerini, Domplein tarihini, Rietveld mimarisini ve ülke çapında tren üssü avantajını yavaş bir şehir rotasına çevirir.",
    arrival: "Utrecht Centraal ülkenin ana demiryolu kavşağıdır; istasyon alışveriş merkeziyle birleştiği için Centrum/Catharijnesingel çıkışını takip edin.",
    local: "Merkez yürünebilir; otobüs ve tramvay dış mahallelere gider. OV-fiets yalnız sistem/üyelik koşulunu karşılıyorsanız kullanılabilir; rastgele turist bisikletiyle yoğun saatten kaçının.", best: "Nisan–Haziran · Eylül",
    identity: ["Utrecht'in Oudegracht'ında sokak kotunun altında suya açılan wharf mahzenleri, Hollanda'da benzersiz iki katlı kanal yaşamı kurar.", "Domplein–Museum Quarter bir gün, Rietveld/De Haar veya sakin mahalleler ikinci gün olarak planlanabilir; Amsterdam'a gidip gelmek zorunlu değildir."],
    sights: [["Domplein ve Dom Kulesi", "Kule çıkışı belirli saatli rehberli olabilir ve yüzlerce basamak içerir. DOMunder arkeoloji deneyimiyle saatleri çakıştırmadan planlayın."], ["Oudegracht ve Museum Quarter", "Wharf seviyesine inip kanalın lojistik tarihini okuyun; Centraal Museum, Museum Speelklok veya Railway Museum'dan ilginize göre birini seçin."], ["Rietveld Schröder House", "UNESCO evine yalnız belirli saatli küçük grup erişimi olabilir; resmî rezervasyon olmadan dış cepheyle yetinmeniz gerekebilir."]],
    areas: ["**Binnenstad / Museum Quarter** ilk ziyaret atmosferi ve yürüyüş için güçlü; hafta sonu gürültülü olabilir.", "**Wittevrouwen** kafe ve yerel yaşam; **Lombok** çok kültürlü yemek ve istasyona yakınlık sunar."],
    tastes: ["Broodje Mario ve Utrechtse sprits hızlı yerel referanslardır; kanal wharf restoranlarında manzara için rezervasyon gerekebilir.", "Lombok/Kanaalstraat Türk, Fas ve dünya mutfağı; Vredenburg pazarı peynir-ekmek için güçlüdür. Kanal merkezinin turist fiyatıyla sınırlı kalmayın."],
    stay: "Binnenstad'da kanal atmosferi veya Centraal'ın batısında daha kolay tren erişimi seçilebilir. Hafta sonu bar sokağına bakan odadan kaçının.",
    evenings: "Oudegracht wharf restoranları, TivoliVredenburg konserleri ve Ledig Erf barları seçeneklerdir. Konser takvimini ve gece trenini kontrol edin.",
    dayTrips: ["Kasteel de Haar bilet ve otobüs/bisiklet bağlantısıyla yarım-tam gün ister.", "Amersfoort Orta Çağ kapıları ve Mondriaan eviyle kısa tren kaçamağıdır."],
    season: "İlkbahar ve erken sonbahar kanal yürüyüşü için ideal; yaz hafta sonu yoğun, kış yağmurlu ama atmosferiktir.",
    budget: "Amsterdam'dan daha iyi konaklama değeri bulunabilir; kule, müze ve konser bütçeyi büyütür. Utrecht'i ülke üssü yaparak otel değişimini azaltın.",
    cautions: ["Wharf kenarlarında bariyer her yerde yoktur; gece ve yağmurda su kenarına dikkat edin.", "Centraal çevresinde bisiklet akışı çok yoğundur; bisiklet şeridinde bavulla durmayın ve park yerini ezberleyin."],
  },
  {
    city: "Haarlem", countryCode: "NL", focus: "Frans Hals, Hofje Avluları ve Kıyı", days: "1–2 tam gün",
    lede: "Haarlem'in Grote Markt, Frans Hals, gizli hofje avluları ve Zandvoort-kumul bağlantısını Amsterdam günübirliğinden daha sakin bir şehir kaçamağına dönüştürür.",
    arrival: "Amsterdam Centraal'dan sık NS trenleriyle yaklaşık 15–20 dakikada ulaşılır; Haarlem istasyonundan Grote Markt yürünebilir.",
    local: "Merkez yürüyerek gezilir; sahil ve kumullar için tren, otobüs veya bisiklet kullanılır. OVpay'de tren ve otobüste doğru giriş-çıkış cihazını kullanın.", best: "Nisan–Haziran · Eylül",
    identity: ["Haarlem, Altın Çağ portreleri, bira-kilise dönüşümleri ve küçük avlu evleriyle Amsterdam'ın yoğunluğuna yakın ama daha sakin bir tarih şehridir.", "Bir merkez-sanat günü, hava iyiyse ikinci gün Zuid-Kennemerland kumulları veya Zandvoort kıyısı dengeli plandır."],
    sights: [["Grote Markt ve Grote Kerk", "Meydanı pazar gününe denk getirirseniz saatini kontrol edin; kilisenin Müller orgu, ziyaret/konser programına göre görülebilir."], ["Frans Hals Museum", "Müzenin koleksiyon ve çağdaş sergi mekânları farklı adreste/programda olabilir; bilet kapsamını resmî siteden okuyun."], ["Hofjes ve De Adriaan", "Açık avluları sessizce ve yalnız izinli saatlerde ziyaret edin; De Adriaan yel değirmeni turunu belirli saatle rezerve edin."]],
    areas: ["**Centrum** tüm tarihî alanlara yürüyüş ve ilk ziyaret için en iyi üsdür.", "**Kleverpark** yerel kafe ve istasyona yakınlık; **Zandvoort/Bloemendaal** deniz önceliği için farklı konaklama sunar."],
    tastes: ["Jopenkerk eski kilisede bira üretimiyle bilinir; tadımda araç/bisiklet kullanmayın. Haarlemse hopjes kahve aromalı yerel şekerdir.", "Grote Markt çevresi turistik olabilir; Kleine Houtstraat ve çevresinde bağımsız fırın, kahve ve bistro arayın."],
    stay: "Merkezde yürünebilir butik otel veya Amsterdam'a göre daha uygun istasyon çevresi seçilebilir. Eski binada merdiven/asansörü kontrol edin.",
    evenings: "Grote Markt terasları, Patronaat konserleri ve Spaarne kıyısı sakin akşam sunar. Programı etkinlik takviminden doğrulayın.",
    dayTrips: ["Zuid-Kennemerland Milli Parkı kumul yürüyüşü ve bisiklet için güçlüdür; koruma alanı rotalarına uyun.", "Zandvoort trenle kolay sahildir; rüzgâr, yüzme bayrağı ve yarış pisti etkinliğini kontrol edin."],
    season: "Lale ve kumul çiçekleri için ilkbahar; kıyı için yaz, daha sakin şehir için eylül iyidir. Deniz rüzgârı yıl boyu serindir.",
    budget: "Şehir yürüyüşü ucuz; müze ve sahil ulaşımı ana eklerdir. Amsterdam yerine Haarlem'de kalmanın tren masrafıyla birlikte toplamını karşılaştırın.",
    cautions: ["Hofje avluları yaşayan konutlardır; kapalı kapıyı zorlamayın, sessizlik ve fotoğraf kuralına uyun.", "Kumulda işaretli patikadan çıkmayın; kene, güneş ve su ihtiyacına hazırlıklı olun."],
  },
  {
    city: "Leiden", countryCode: "NL", focus: "Kanallar, Bilim Müzeleri ve Üniversite", days: "1–2 tam gün",
    lede: "Leiden'ın üniversite avlularını, Rijksmuseum van Oudheden, Boerhaave ve botanik bahçesini kompakt kanal yürüyüşünde ilgi alanına göre seçer.",
    arrival: "Schiphol, Amsterdam, Rotterdam ve Lahey'den trenle Leiden Centraal'a kolay ulaşılır; eski merkez istasyondan yürünebilir.",
    local: "Yürüyüş ana yöntemdir; otobüs çevreye gider. Kanal teknesi sezonluk olabilir; rota ve dilini kontrol edin.", best: "Nisan–Haziran · Eylül",
    identity: ["Hollanda'nın en eski üniversitesine ev sahipliği yapan Leiden, bilim tarihi, Rembrandt'ın doğum kenti ve birbirini kesen sakin kanallarıyla küçük alanda olağanüstü müze yoğunluğu sunar.", "Bir günde iki müze ve kanal yürüyüşü yeterlidir; tüm koleksiyonları işaretlemek şehrin avlu-kafe ritmini kaçırır."],
    sights: [["Rijksmuseum van Oudheden", "Mısır, Roma ve Hollanda arkeolojisi koleksiyonunda ilginize göre kat seçin; geçici sergi ve bilet saatini kontrol edin."], ["Hortus Botanicus ve akademi", "Avrupa'nın eski botanik bahçelerinden birini üniversite binaları ve Rapenburg kanalıyla birleştirin; sera kapanışını kontrol edin."], ["Boerhaave veya De Lakenhal", "Bilim tarihine Museum Boerhaave, Leiden sanat-tarihine De Lakenhal ile derinleşin; ikisini aynı kısa güne doldurmayın."]],
    areas: ["**Pieterskwartier / Rapenburg** tarih, kanal ve akşam için en güzel ilk üsdür.", "**Stationsdistrict** ulaşım kolaylığı; **Haven** daha sakin kanal ve yerel restoran sunar."],
    tastes: ["Leidse kaas kimyonlu peynirdir; pazar gününde üretici ve olgunluk derecesini sorun. Haring ve kibbeling kolay öğle seçeneğidir.", "Üniversite kenti uygun kafe, Endonezya ve dünya mutfakları sunar. Turistik meydandan bir sokak dışarı çıkın."],
    stay: "Bir gece kalacaksanız Pieterskwartier karakterli; erken tren için istasyon çevresi pratiktir. Eski kanal evinde dik merdiveni kontrol edin.",
    evenings: "Nieuwe Rijn ve Pieterskerk çevresi terasları, küçük tiyatro ve öğrenci barları vardır. 3 Ekim Ontzet festivalinde kalabalık ve kapanışlar değişir.",
    dayTrips: ["Keukenhof/Lisse yalnız açılış sezonunda otobüs-bisikletle doğal bağlantıdır.", "Katwijk sahili ve Corpus müzesi farklı aile/deniz yarım günleri sunar."],
    season: "İlkbahar botanik ve çiçek tarlaları, eylül şehir yürüyüşü için güçlüdür. 3 Ekim festivali benzersiz ama çok yoğundur.",
    budget: "Merkez yürüyüşü ücretsiz; iki büyük müze günlük maliyeti belirler. Kombine/öğrenci koşullarını resmî sayfadan kontrol edin.",
    cautions: ["Üniversite avluları ve kütüphaneler kamusal müze değildir; açık saat ve sessizlik kuralına uyun.", "Kanal kenarında dar bisiklet yollarında bavulla durmayın; kiralık bisikleti yalnız işaretli alana bırakın."],
  },
  {
    city: "Delft", countryCode: "NL", focus: "Vermeer, Delft Blue ve Kanallar", days: "1–2 tam gün",
    lede: "Delft'in Markt meydanını, Vermeer bakışlarını, Royal Delft üretimini ve Oude/Nieuwe Kerk tarihini kısa ama dolu bir kanal rotasında toplar.",
    arrival: "Rotterdam ve Lahey'den trenle dakikalar içinde Delft istasyonuna ulaşılır; modern istasyon tavanındaki tarihî haritayı kaçırmayın.",
    local: "Tarihî merkez tamamen yürünebilir. Royal Delft merkezin dışında kısa yürüyüş/otobüs mesafesindedir; bisiklet şart değildir.", best: "Nisan–Haziran · Eylül",
    identity: ["Delft, Vermeer'in ışığı, Orange Hanedanı'nın mezar kilisesi ve mavi-beyaz seramik üretimiyle küçük ölçekte Hollanda tarihini yoğunlaştırır.", "Markt–Oude Delft kanal yürüyüşü, bir kilise kulesi ve gerçek üretim odaklı seramik ziyareti bir tam güne rahatça sığar."],
    sights: [["Markt, Nieuwe Kerk ve Oude Kerk", "Nieuwe Kerk kulesinde çok sayıda dar basamak vardır; hava ve fiziksel duruma göre çıkın. Oude Kerk'in eğik kulesini kanal yürüyüşünden görün."], ["Vermeer Centrum", "Merkez özgün tablo koleksiyonu değil, sanatçının ışık, kompozisyon ve şehir bağlamını anlatan yorum merkezidir; beklentinizi buna göre kurun."], ["Royal Delft", "Fabrika/müze turunda el boyama aşamalarını görün; 'Delft Blue' adı taşıyan her hediyenin aynı üretim ve kalite standardında olmadığını etiketten kontrol edin."]],
    areas: ["**Markt–Oude Delft** yürüyüş, akşam ve tarih için tek doğru ilk üs sayılabilir.", "**İstasyon güneyi** modern, daha uygun ve merkeze birkaç dakika yürüyüş mesafesindedir."],
    tastes: ["Delft'e özgü tek büyük yemek yerine Hollanda peyniri, poffertjes, elmalı turta ve pazar atıştırmalıklarını deneyin.", "Öğrenci nüfusu uygun kafe ve uluslararası yemek sağlar. Beestenmarkt akşam restoranları için güçlüdür."],
    stay: "Bir gece için kanal evi atmosferi güzeldir; günübirlik de mümkündür. Eski yapıda asansör, banyo ve çan sesi yorumlarını okuyun.",
    evenings: "Beestenmarkt terasları ve kanalların akşam ışığı sakin bir gece sunar. Tiyatro veya klasik konser takvimini şehir kültür sayfasından kontrol edin.",
    dayTrips: ["Lahey tramvay/trenle, Rotterdam trenle çok yakındır; ikisinden birini Delft gününe değil ayrı güne ayırın.", "Kinderdijk daha uzak su yönetimi rotasıdır; Rotterdam üzerinden planlayın."],
    season: "İlkbahar ve eylül yürüyüş için ideal; yaz günübirlik kalabalığı öğlen artar. Sabah veya konaklamalı akşam daha sakindir.",
    budget: "Kompakt merkez ulaşım maliyetini düşürür; kilise, Vermeer ve Royal Delft biletleri birikir. İlginize göre ikisini seçin.",
    cautions: ["Kule basamakları dar ve çift yönlüdür; kalp, denge veya kapalı alan sorununuz varsa çıkmayın.", "Seramikte el boyaması, transfer baskı ve üretim yerini etiketten ayırın; kırılabilir ürünün bagaj paketini isteyin."],
  },
  {
    city: "Maastricht", countryCode: "NL", focus: "Maas Kıyısı, Mağaralar ve Burgonya Mutfağı", days: "2–3 tam gün",
    lede: "Maastricht'in Vrijthof, Onze Lieve Vrouweplein, Céramique ve Sint Pietersberg mağaralarını Hollanda'nın güneyindeki farklı dil-yemek ritmiyle anlatır.",
    arrival: "Amsterdam/Utrecht'ten direkt veya aktarmalı NS trenleri yaklaşık 2,5 saat sürer; Maastricht istasyonundan Wyck üzerinden merkeze yürünür.",
    local: "Merkez yürünebilir; Sint Pietersberg için otobüs/bisiklet/taksi gerekir. Mağara turları yalnız rehberli ve belirli saatlidir.", best: "Nisan–Haziran · Eylül–Ekim",
    identity: ["Roma kökleri, Maas köprüleri ve Belçika-Almanya sınırına yakın konumu Maastricht'e ülkenin kuzeyinden daha taş cepheli, yavaş ve yemek odaklı bir karakter verir.", "Bir eski şehir günü ile bir Sint Pietersberg–Céramique günü dengeli; Güney Limburg kırsalı ek gün ister."],
    sights: [["Vrijthof ve Basilica of Saint Servatius", "Meydan etkinlik takvimine göre tamamen dönüşebilir. Bazilikanın hazine ve ibadet alanı saatlerini ayrı kontrol edin."], ["Onze Lieve Vrouweplein ve Stokstraat", "Dar Roma çekirdeğini, bazilika ve Jekerkwartier sokaklarıyla birleştirin; eski sur parçalarını takip edin."], ["Sint Pietersberg mağaraları ve Fort", "Mağaralara yalnız rehberle girilir; içerisi yıl boyu serin, karanlık ve basamaklıdır. Tur dili, süre ve hareket kısıtını rezervasyonda seçin."]],
    areas: ["**Binnenstad / Jekerkwartier** ilk ziyaret atmosferi ve yürüyüş için en güçlü üsdür.", "**Wyck** istasyon, butik ve restoran; **Céramique** çağdaş mimari ve nehir yürüyüşü sunar."],
    tastes: ["Limburgse vlaai, zuurvlees ve bölgesel bira güneyin klasikleridir. Vlaai diliminde gerçek yerel fırın ve mevsim meyvesini sorun.", "Şehir 'Burgonya' yemek kültürüyle uzun öğünü sever; servis temposuna zaman bırakın. Bira tadımını bisiklet/araçla birleştirmeyin."],
    stay: "Wyck tren erişimi ve iyi restoran; Jekerkwartier tarihî atmosfer sunar. Vrijthof etkinliğinde ses ve fiyat çok artabilir.",
    evenings: "Onze Lieve Vrouweplein terasları, Wyck şarap barları ve Vrijthof konserleri öne çıkar. André Rieu ve TEFAF haftalarında aylar önceden rezervasyon gerekebilir.",
    dayTrips: ["Valkenburg mağaraları ve tepe kalesi kısa trenle farklı bir gün sunar.", "Aachen veya Liège uluslararası kısa tren/otobüs kaçamağıdır; bilet ve dolaşım koşulunu ayrı kontrol edin."],
    season: "İlkbahar kırsal yürüyüş, sonbahar yemek-şehir için güzel; yaz etkinlik yoğun, kış Noel pazarları atmosferiktir.",
    budget: "Merkez restoranları ülke ortalamasından ucuz olmayabilir; uzun öğün ve etkinlik oteli ana maliyettir. Şehir içi yürüyüş tasarruf sağlar.",
    cautions: ["Mağaraya rehbersiz girmeyin; yön kaybı ve karanlık gerçek risktir. Katmanlı kıyafet giyin.", "Sınır ötesi günübirlikte aynı banka kartıyla OVpay'in yabancı taşıyıcıda otomatik çalışacağını varsaymayın."],
  },
  {
    city: "Groningen", countryCode: "NL", focus: "Forum, Bisiklet Şehri ve Kuzey Kültürü", days: "2–3 tam gün",
    lede: "Groningen'in kompakt merkezini, Forum panoramasını, Groninger Museum'u ve kuzey kırsalına açılan genç şehir ritmini planlar.",
    arrival: "Amsterdam/Schiphol'den tren yaklaşık iki saat sürer; bakım gününde Zwolle aktarması değişebilir. İstasyondan merkeze yürüyün veya otobüs kullanın.",
    local: "Merkez otomobilden arındırılmış ve yürünebilir; bisiklet trafiği çok yoğundur. Kiralık bisiklette park zonu, ışık ve kilit kuralını öğrenin.", best: "Mayıs–Haziran · Eylül",
    identity: ["Kuzey Hollanda'nın üniversite merkezi Groningen, genç nüfus, cesur müze mimarisi ve bisiklete göre kurulmuş kamusal alanıyla Amsterdam'dan bağımsız güçlü bir şehir kültürüne sahiptir.", "Merkez-müze günü, Noorderplantsoen–Hoge der A yürüyüşü ve bir Wadden/kırsal günü ideal yapıdır."],
    sights: [["Forum Groningen ve Grote Markt", "Forum'un ücretsiz terasından şehir ölçeğini okuyun; sergi/sinema biletini ayrı kontrol edin. Martinitoren için basamak ve saatli tur koşulunu öğrenin."], ["Groninger Museum", "İstasyon karşısındaki postmodern yapıda koleksiyon ve geçici sergiyi seçerek gezin; dış mimariyi de çevre köprülerden görün."], ["Hoge der A ve Noorderplantsoen", "Tarihî depoları kanal boyunca yürüyüp parka bağlayın; Noorderzon gibi festival döneminde program ve kalabalığı kontrol edin."]],
    areas: ["**Binnenstad** tüm gezi, yemek ve gece için yürünebilir en iyi üs.", "**Oosterpoort** istasyon ve konser; **Noorderplantsoen** daha sakin yerel yaşam sunar."],
    tastes: ["Groninger eierbal ve mosterdsoep yerel hızlı tatlardır; hardallı çorbanın et suyu içerebileceğini sorun.", "Öğrenci şehri uygun dünya mutfakları ve güçlü kahve-bira sahnesi sunar. Vismarkt pazar gününü kontrol edin."],
    stay: "Merkezde kalmak bisiklet ihtiyacını azaltır; hafta sonu Grote Markt gece sesini hesaba katın. İstasyon yakınlığı kuzey günübirliklerinde değerlidir.",
    evenings: "Vera ve Simplon canlı müzik, Grote Markt bar, Oosterpoort konser sunar. Etkinlik biletini ve gece otobüsünü önceden kontrol edin.",
    dayTrips: ["Lauwersmeer Milli Parkı ve Wadden kıyısı araç/otobüs-bisiklet kombinasyonu ister; hava ve son dönüşü planlayın.", "Bourtange yıldız kale köyü daha uzun otobüs/araç günüdür; açılış programını kontrol edin."],
    season: "Mayıs-haziran uzun gün, eylül öğrenci enerjisi sunar. Kuzeyde rüzgâr ve yağmur belirgindir; katman taşıyın.",
    budget: "Amsterdam'a göre daha uygun oda-yemek bulunabilir; Wadden/kırsal ulaşımı ek maliyettir. Bisiklet kiralama ve depozitoyu okuyun.",
    cautions: ["Bisiklet trafiği çok hızlıdır; şeritte durmayın, karanlıkta ışıksız bisiklete binmeyin ve kilitli park kullanın.", "Wadden kıyısında gelgit alanına rehbersiz yürümeyin; su çok hızlı döner."],
  },
  {
    city: "Eindhoven", countryCode: "NL", focus: "Dutch Design, Strijp-S ve Teknoloji Mirası", days: "1–2 tam gün",
    lede: "Eindhoven'ı transit havaalanından çıkarıp Philips mirası, Strijp-S dönüşümü, Van Abbemuseum ve tasarım haftasıyla okur.",
    arrival: "Eindhoven Havalimanı'ndan şehir merkezine otobüs gider; tren istasyonu yoktur. Amsterdam, Rotterdam ve Utrecht'ten NS trenleri Eindhoven Centraal'a ulaşır.",
    local: "Merkez ve Strijp-S tren/otobüs-yürüyüşle kolaydır. Dutch Design Week'te özel servisler ve kapanışlar olabilir; resmî programı kullanın.", best: "Nisan–Haziran · Ekim tasarım haftası",
    identity: ["Philips'in endüstri şirket kentinden tasarım-teknoloji merkezine dönüşen Eindhoven, tarihî kanal yerine yeniden kullanılan fabrika, ışık ve deneysel üretim üzerinden okunur.", "Merkez müze günü ile Strijp-S–Strijp-R tasarım hattı bir buçuk güne sığar; etkinlik döneminde iki tam gün ayırın."],
    sights: [["Strijp-S", "Eski Philips fabrikalarında tasarım mağazası, etkinlik, restoran ve kamusal alanları yürüyün; bina programını önceden seçin."], ["Van Abbemuseum", "Modern ve çağdaş koleksiyonda sergi programını kontrol edin; müzenin erişilebilirlik ve çoklu anlatı yaklaşımına zaman bırakın."], ["Philips Museum ve ışık rotası", "Şirketin ampulden sağlık-teknolojiye dönüşümünü görün. GLOW festivali yalnız belirli tarihlerde ve farklı açık hava güzergâhında gerçekleşir."]],
    areas: ["**Centrum** tren, müze ve akşam için pratik.", "**Strijp-S** endüstriyel tasarım atmosferi ve etkinlik; **De Bergen** bağımsız butik-restoran sunar."],
    tastes: ["Brabant worstenbroodje bölgesel atıştırmalıktır; fırında et türü ve vegan alternatifini sorun.", "Strijp-S ve Downtown Gourmet yaratıcı/uluslararası seçenekler sunar; etkinlik haftasında rezervasyon yapın."],
    stay: "Kısa ziyaret için Centraal-De Bergen; tasarım etkinliği için Strijp-S iyi üsdür. Havalimanı sabah uçuşuna otobüs ilk seferini kontrol edin.",
    evenings: "Strijp-S etkinlikleri, Effenaar konserleri ve De Bergen barları öne çıkar. Dutch Design Week/GLOW döneminde rota ve saat her gün değişebilir.",
    dayTrips: ["Nuenen, Van Gogh'un patates yiyenler dönemini yürüyüş-bisikletle takip eder.", "Den Bosch kısa trenle tarihî merkez ve Brabant mutfağı sunar."],
    season: "Normal şehir gezisi için ilkbahar; Dutch Design Week ekim, GLOW kasım takvimine bağlıdır. Etkinlikte otel erken dolar.",
    budget: "Etkinlik dışı oda daha iyi değer sunabilir; festival bileti, tasarım alışverişi ve havaalanı otobüsü eklenir.",
    cautions: ["Havaalanını tren istasyonu sanmayın; yoğun saatte otobüs ve güvenlik için ek süre bırakın.", "Endüstriyel alanlarda etkinlik kurulumu ve kapalı bina sınırlarına uyun; drone kullanmayın."],
  },
  {
    city: "Giethoorn", countryCode: "NL", focus: "Kanallar, Tekne ve Kalabalıksız Köy Planı", days: "1 tam gün · sakinlik için 1 gece",
    lede: "Giethoorn'da saz çatılı çiftlikler, yaya köprüleri ve sessiz elektrikli tekne deneyimini tur otobüsü saatleri ile dar kanallardaki güvenliğe göre planlar.",
    arrival: "Trenle Steenwijk'e, ardından otobüsle Giethoorn'a ulaşılır; Amsterdam'dan kapıdan kapıya günübirlik uzundur. 9292'den son dönüş ve sezon bağlantısını kontrol edin.",
    local: "Köy yürüyüş ve tekneyle gezilir. Tekne kiralarken rota, süre, depozito, sigorta ve kullanım eğitimini alın; kanalda sağdan ve düşük hızda ilerleyin.", best: "Nisan–Haziran · Eylül · hafta içi",
    identity: ["Giethoorn, araçsız tarihî çekirdeği ve saz çatılı çiftliklerini küçük kanallar üzerinden bağlayan yaşayan bir köydür; 'Hollanda'nın Venedik'i' etiketi ölçeğini abartır.", "Kalabalık günübirlik saatlerinden önce veya sonra bir gece kalmak, köprüleri ve Weerribben-Wieden doğasını daha gerçek ritimde görmeyi sağlar."],
    sights: [["Dorpsgracht yürüyüşü", "Köprüler ve özel bahçeler arasında yalnız kamusal yolu kullanın; ev kapısı ve bahçeyi fotoğraf seti sanmayın."], ["Sessiz elektrikli tekne", "1–2 saatlik köy halkası veya daha uzun göl-doğa rotası seçin. Yoğun kanalda acemi sürücüler için talimatı dinleyin ve alkol kullanmayın."], ["Weerribben-Wieden", "Milli parkta kano, tekne veya bisikletle köy kalabalığından uzaklaşın; rota, rüzgâr ve batarya/yakıt sınırını bilin."]],
    areas: ["**Köy merkezi / Binnenpad** ilk ziyaret ve tekne kiralama için pratik ama gündüz kalabalıktır.", "**Giethoorn Noord veya Dwarsgracht** daha sakin konaklama ve doğa erişimi sunar; restoran/otobüs seyrek olabilir."],
    tastes: ["Pannenkoeken, elmalı turta ve yerel balık turistik köy menüsünün temelidir; su kenarı restoranında rezervasyon gerekebilir.", "Piknik yapacaksanız çöpü geri taşıyın ve özel iskeleye oturmayın. Market seçeneği sınırlı olduğundan su-atıştırmalık getirin."],
    stay: "Sessizlik istiyorsanız merkezde geceleyin; son turist otobüsünden sonra köy belirgin biçimde sakinleşir. Otele araç/otobüs ve bagaj erişimini sorun.",
    evenings: "Gece hayatı yoktur; kanal kıyısı yürüyüşü, erken yemek ve doğa sesi deneyimin özüdür. Karanlıkta tekneyi yalnız kiralama koşulu izin veriyorsa kullanın.",
    dayTrips: ["Zwolle Hansa mimarisi ve müzelerle tren bağlantılı şehir günüdür.", "Lemmer veya Blokzijl su kasabaları araç/bisikletle kuzey Hollanda rotasını uzatır."],
    season: "Hafta içi ilkbahar ve eylül en iyi dengedir; yaz ortası 11.00–16.00 çok yoğun olabilir. Yağmur ve rüzgâr tekne kullanımını etkiler.",
    budget: "Köy yürüyüşü ücretsiz; tekne ve su kenarı restoranı ana maliyettir. Kişi başı tur ile saatlik özel tekneyi grup sayısına göre karşılaştırın.",
    cautions: ["Özel ev, bahçe ve iskeleye girmeyin; köy gerçek yerleşimdir. Drone ve yüksek sesli grup davranışından kaçının.", "Teknede can yeleği şartını, çocuk ekipmanını ve hasar sorumluluğunu öğrenin; köprü altında ayağa kalkmayın."],
  },
  {
    city: "Zaanse Schans", countryCode: "NL", focus: "Yel Değirmenleri, El Sanatları ve Yarım Gün", days: "Yarım–1 tam gün",
    lede: "Zaanse Schans'ta çalışan değirmenleri, ahşap evleri ve Zaan endüstri tarihini yalnız ücretsiz fotoğraf köyü sanmadan, bilet ve kalabalığa göre planlar.",
    arrival: "Amsterdam Centraal'dan Zaandijk Zaanse Schans istasyonuna tren ve yaklaşık 15 dakika yürüyüş; otobüsle doğrudan bağlantı seçenekleri vardır. 9292'den güncel hattı kontrol edin.",
    local: "Alan yürüyerek gezilir. Her değirmen/müze ayrı giriş ve saat uygulayabilir; Zaanse Schans Card kapsamını gerçekten gireceğiniz yerlere göre değerlendirin.", best: "Nisan–Haziran · Eylül · açılış saati",
    identity: ["Zaanse Schans açık hava dekoru değil; Zaan bölgesinin değirmen gücüyle gelişen boya, yağ, kereste ve gıda endüstrisini bir araya getiren miras alanıdır.", "İki çalışan değirmenin içini görüp Zaans Museum veya zanaat atölyesi eklemek, yalnız köprü fotoğrafından daha anlamlı yarım gün verir."],
    sights: [["Çalışan yel değirmenleri", "De Kat boya ve diğer değirmenlerin çalışma/açık günleri rüzgâr ile sezona bağlıdır. Dar merdiven ve hareketli mekanizma için görevli talimatına uyun."], ["Zaans Museum ve Verkade", "Bölgenin endüstri tarihini ve gıda üretimini müzede bağlama oturtun; kartın sergi kapsamını kontrol edin."], ["Ahşap evler ve zanaat", "Peynir, takunya ve kalay atölyelerinde gösteri ücretsiz olabilir ama satış odaklıdır; ürünün üretim yeri ve kalitesini etiketten okuyun."]],
    areas: ["**Zaanse Schans** gündüz gezi alanıdır; konaklama seçeneği sınırlı.", "**Zaandam merkezi** Inntel mimarisi, tren ve daha fazla otel/restoran sunar; Amsterdam'a kısa bağlantılıdır."],
    tastes: ["Peynir tadımı, stroopwafel ve çikolata kokusu bölge deneyimidir; tadım sonrası satın alma zorunlu değildir.", "Zaandam merkezinde daha yerel öğle seçenekleri vardır. Tur otobüsü saatinde alandaki restoran kuyruğunu hesaba katın."],
    stay: "Çoğu ziyaretçi Amsterdam/Zaandam'dan gelir. Sabah fotoğraf ve sessizlik önceliğinde Zaandam veya alana yakın küçük konaklama düşünülebilir.",
    evenings: "Alan işletmeleri erken kapanır; akşamı Zaandam veya Amsterdam'da planlayın. Gün batımı için kamusal yürüyüş yolları ve kapanış işaretine uyun.",
    dayTrips: ["Zaandam'da Czaar Peter House ve çağdaş merkez mimarisi yarım gün ekidir.", "Edam, Volendam ve Marken başka turistik kümedir; aynı kısa güne hepsini doldurmayın."],
    season: "İlkbahar-sonbahar yürüyüş için iyi; rüzgâr değirmenin çalışmasını sağlar ama yağmur sert hissedilir. Hafta içi açılış saati en sakin dönemdir.",
    budget: "Dış alan ücretsiz, değirmen ve müzeler ücretlidir. Kartı en az iki-üç ücretli giriş yapacaksanız alın; ulaşım dahilini ayrıca okuyun.",
    cautions: ["Değirmende dik merdiven, alçak tavan ve hareketli parçalara dikkat edin; çocukları yakın tutun.", "Özel çim, ev ve iskeleye fotoğraf için girmeyin. Bisiklet yolunda grup hâlinde durmayın."],
  },
  {
    city: "Keukenhof ve Lisse", countryCode: "NL", focus: "Lale Sezonu, Bilet ve Tarlalar", days: "1 tam gün · yalnız açılış sezonunda",
    lede: "Keukenhof bahçesi ile Lisse soğan tarlalarını kısa bahar sezonunda; belirli saatli bilet, ulaşım, bisiklet ve tarla etiğine göre planlar.",
    arrival: "Keukenhof yalnız sınırlı ilkbahar tarihlerinde açılır. Schiphol, Leiden veya bölgesel duraklardan sezon otobüsü olabilir; bilette gün-saat ve ulaşım kombinasyonunu resmî kanaldan kontrol edin.",
    local: "Bahçe yürüyerek; Lisse çevresi kiralık bisiklet veya işaretli araç rotasıyla gezilir. Çiçek tarlaları özel üretim alanıdır; yalnız yol ve izinli seyir noktalarını kullanın.", best: "Mart sonu–Mayıs ortası · yıllık açılışa göre",
    identity: ["Keukenhof bir tarla değil, yetiştiricilerin tasarladığı büyük sergi bahçesidir; çevredeki Lisse tarlaları ise kesme çiçek ve soğan üretimi yapılan özel arazilerdir.", "Bahçeyi açılışta gezip öğleden sonra izinli bisiklet rotasına çıkmak, tek kalabalık fotoğraf noktasından daha iyi bahar günü verir."],
    sights: [["Keukenhof bahçeleri", "Yıllık açılış, çiçeklenme ve belirli saatli giriş değişir. Pavyonları gün ortası kalabalığına, açık bahçeyi sabah ışığına koyun."], ["Lisse soğan tarlaları", "Tarlaya girmeyin; bitki hastalığı ve ürün zararı gerçek sorundur. Yol kenarında güvenli, izinli noktada durun ve çiftçi tabelasına uyun."], ["Kasteel Keukenhof ve çevre", "Bahçenin karşısındaki kale arazisi/programı ayrı olabilir. Bisiklet rotasını Hillegom veya Noordwijk yönüne uzatırken rüzgâr ve süreyi hesaplayın."]],
    areas: ["**Lisse merkezi** bahçe, bisiklet ve sakin akşam için sezonda pratiktir.", "**Leiden** daha çok otel-müze ve sezon otobüsü bağlantısı; **Haarlem** kuzey çiçek tarlalarına alternatif üs sunar."],
    tastes: ["Bahçe içi yemek yoğun ve pahalı olabilir; su, küçük atıştırmalık ve piknik kurallarını önceden kontrol edin.", "Lisse merkezinde Hollanda fırını, peynir ve mevsimlik restoranla tur otobüsü alanından uzaklaşın."],
    stay: "Günübirlik mümkündür; fotoğraf ve erken giriş önceliğinde Lisse/Leiden'da bir gece kalın. Sezon hafta sonunda oda çok erken dolar.",
    evenings: "Keukenhof çoğunlukla akşam erken kapanır; Lisse sakin, Leiden daha canlıdır. Son sezon otobüsünü kaçırmayın.",
    dayTrips: ["Leiden bilim müzeleri ve kanallarıyla aynı konaklama bloğunda güçlü ikinci gündür.", "Noordwijk sahili bisikletle bağlanabilir; rüzgâr ve karanlık dönüşünü değerlendirin."],
    season: "Kesin çiçeklenme hava sıcaklığına bağlıdır; açılış tarihi çiçek garantisi vermez. Resmî çiçek raporu ve güncel fotoğrafları kontrol edin.",
    budget: "Giriş, sezon ulaşımı ve bisiklet kiralama birlikte pahalılaşabilir. Kombine biletin saat ve kalkış noktasını dikkatle okuyun.",
    cautions: ["Çiçek tarlasına fotoğraf için girmeyin, sırayı ezmeyin ve drone uçurmayın; üreticinin geçim alanına zarar verir.", "Yol kenarında aniden durmayın; bisiklet yolu ve tarım aracına öncelik verin. Bahçede yankesiciliğe karşı çantayı kapalı tutun."],
  },
  {
    city: "Texel", countryCode: "NL", focus: "Wadden Adası, Bisiklet ve Doğa", days: "2–4 tam gün",
    lede: "Texel'e Den Helder feribotunu, kumul bisikletlerini, De Slufter, Ecomare ve deniz fenerini rüzgâr ile kuş koruma dönemlerine göre kurar.",
    arrival: "NS treniyle Den Helder, istasyondan otobüsle feribot terminali ve kısa TESO geçişi kullanılır. Yaya/bisiklet/araç bileti ile ada otobüs bağlantısını ayrı kontrol edin.",
    local: "Bisiklet ağı güçlü; otobüs ve taksi sınırlıdır. Rüzgâr yönünü rotaya baştan katın, e-bike pilini tam çevre turuna göre değerlendirin.", best: "Mayıs–Haziran · Eylül",
    identity: ["Wadden Denizi'nin en büyük Hollanda adası Texel, Kuzey Denizi plajı, tuzlu bataklık, koyun çiftliği ve kuş göçünü kısa mesafede birleştirir.", "De Koog/Den Burg üssüyle batı kumulları bir gün, De Slufter–deniz feneri ikinci gün planlanabilir; hava yedeği bırakın."],
    sights: [["De Slufter", "Denizin kumul açıklığından içeri girdiği tuzlu alanı işaretli patikadan görün. Gelgit, kuş üreme kapanışı ve su seviyesini doğa kurumundan kontrol edin."], ["Ecomare ve kumullar", "Fok rehabilitasyonu ve Wadden ekolojisini öğrenin; besleme saatini şov değil bakım-eğitim bağlamında izleyin. Park yürüyüşüne uygun ayakkabı giyin."], ["Vuurtoren ve kuzey", "Deniz feneri tırmanışı saatli olabilir; kuzey plajı ve Cocksdorp'u bisikletle birleştirin. Rüzgârlı dönüşte enerji payı bırakın."]],
    areas: ["**Den Burg** market, restoran ve ada merkezi; plaja bisiklet gerekir.", "**De Koog** plaj ve gece; **De Cocksdorp** kuzey doğası ve sessizlik için uygundur."],
    tastes: ["Texel kuzu eti, yerel bira, peynir ve deniz ürünü ada üretimini gösterir. Kuzu sezonu ve ürün kaynağını sorun.", "Oudeschild limanında balık ve karides; çiftlik dükkânlarında süt-peynir bulunur. Alkollü bisiklet kullanmayın."],
    stay: "İlk seferde Den Burg veya De Koog lojistik olarak kolaydır; doğa sessizliği için kuzey çiftlik konaklaması seçilebilir. Son otobüs ve yemek saatini kontrol edin.",
    evenings: "De Koog daha hareketli, Den Burg restoran-kafe, kırsal konaklama sessizdir. Karanlıkta bisiklet için ön-arka ışık zorunlu ve hayatidir.",
    dayTrips: ["Vlieland'a yalnız sezonluk tekne/özel bağlantı olabilir; dönüş ve bisiklet koşulunu resmî operatörden doğrulayın.", "Den Helder Denizcilik Müzesi feribot öncesi/sonrası yarım gün ekidir."],
    season: "Mayıs-haziran kuş ve uzun günler, eylül sakinlik için iyidir. Rüzgâr ve sağanak her mevsimde planı değiştirebilir.",
    budget: "Feribot yaya için genellikle makul; bisiklet/e-bike, doğa müzesi ve ada konaklaması ana maliyettir. Otomobil götürmenin park ve feribot bedelini karşılaştırın.",
    cautions: ["Gelgit çamurluğuna rehbersiz çıkmayın; su hızla döner. Koruma alanı ve kuş yuvalama kapanışına uyun.", "Bisiklette rüzgârı küçümsemeyin; ışık, fren, yağmurluk ve kilit taşıyın. Kumulda işaretli patikadan çıkmayın."],
  },
];

export const netherlandsGuides = makeWorldExpansionGuides(profiles);
