import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Oslo", countryCode: "NO", focus: "fiyort kıyısı, dünya müzeleri ve mahalle yaşamı", lede: "Oslofjord kıyısındaki çağdaş mimariyi Viking ve kutup keşfi mirası, orman içi ulaşım ve sakin İskandinav mahalleleriyle birleştiren Norveç başkenti.", days: "3–5 gün", arrival: "OSL · Oslo S · feribot terminalleri", local: "Metro, tramvay, otobüs, banliyö treni, feribot ve yürüyüş", best: "Mayıs–Eylül · kış kültürü için Aralık–Mart", pulse: "Oslo yalnız Opera Binası ile Karl Johans gate değildir. Bjørvika'nın yeni mimarisi, Bygdøy müzeleri, Grünerløkka'nın bağımsız yaşamı ve Nordmarka'nın orman hatları toplu taşımayla tek şehir planında birleşir. Müze kapanışlarını ve ada feribotlarını mevsime göre doğrulayın.",
    sights: [["Bjørvika, Opera ve MUNCH", "Opera çatısını hava ve kayganlık durumuna göre yürüyün; MUNCH ile Deichman Bjørvika için sergi, saatli giriş ve dolap kurallarını önceden kontrol edin."], ["Bygdøy müzeleri", "Fram, Kon-Tiki, Norsk Folkemuseum ve diğer koleksiyonlardan en fazla ikisini seçin; kışın feribot yerine otobüs gerekebileceğini hesaba katın."], ["Vigeland ve Ulusal Müze", "Frogner Parkı'nı açık hava yürüyüşü, Ulusal Müze'yi seçilmiş koleksiyon rotası olarak ayrı zamanlara bölün."]],
    areas: [["Sentrum, Bjørvika ve Aker Brygge", "İlk ziyaret, tren ve müze erişimi için kolay; liman manzaralı konaklama ile restoranlar pahalı olabilir."], ["Grünerløkka, Majorstuen veya Frogner", "Kafe ve gündelik yaşam, metro erişimi ya da sakin konut dokusu için farklı bütçe seçenekleri."]], foods: [["Somon, karides ve balık çorbası", "Tür, menşe, porsiyon ve alerjeni sorun; liman manzarasının otomatik kalite garantisi olmadığını unutmayın."], ["Kanelbolle ve brunost", "Tarçınlı çörek ile kahverengi peyniri fırın/kafede deneyin; süt, tereyağı ve jelatin içeriğini beslenme tercihinize göre doğrulayın."]], dayTrips: [["Oslofjord adaları", "Ruter bölgesi, mevsimsel iskele ve son feribotu kontrol ederek Hovedøya veya Gressholmen'den yalnız bir-ikisini seçin."], ["Drøbak veya Kistefos", "Drøbak'a otobüs; Kistefos'a sezon, müze bileti ve son kilometre transferiyle gidilir. İkisini aynı güne koymayın."]], caution: "Kalabalık istasyon ve tramvayda eşyayı kapalı tutun; buzlu zeminde taban tutuşuna dikkat edin. Nordmarka veya ada rotasına şehir parkı rahatlığıyla hazırlıksız çıkmayın; gün ışığı, buz, ateş ve kamp kurallarını kontrol edin."
  },
  {
    city: "Bergen", countryCode: "NO", focus: "Bryggen, yedi dağ ve fiyort kapısı", lede: "UNESCO Bryggen'in ahşap ticaret mirasını Fløyen–Ulriken dağları, güçlü deniz kültürü ve Batı Norveç fiyort bağlantılarıyla birleştiren yağmurlu liman şehri.", days: "3–5 gün", arrival: "BGO · Bergen stasjon · Strandkaiterminalen", local: "Hafif raylı sistem, otobüs, füniküler, teleferik, feribot ve yürüyüş", best: "Mayıs–Eylül · kültür için yıl boyu", pulse: "Bergen'i yalnız Bryggen fotoğrafı ve hızlı bir fiyort turuna indirmeyin. Hanseatik ticaretin kent üzerindeki izini müzelerle, Nordnes'i gündelik mahalle olarak, Fløyen ile Ulriken'i de hava koşullu doğa günleri olarak okuyun. Yağmur bir istisna değil plan değişkenidir.",
    sights: [["Bryggen ve Hanseatik miras", "Ahşap geçitleri gündüz kalabalığından önce gezin; müze, restorasyon, yangın güvenliği ve özel atölye sınırlarına uyun."], ["Fløibanen ve Fløyen", "Füniküler sırasını, son seferi ve patika durumunu kontrol edin; sisli havada manzara yerine orman yürüyüşü alternatifi tutun."], ["KODE ve Bergenhus", "Sanat koleksiyonu ile kale alanını iki ayrı odak olarak gezin; salon, konser ve mevsimsel kapanışı doğrulayın."]],
    areas: [["Sentrum, Vågen ve Bryggen çevresi", "İlk ziyaret, iskele ve istasyon için pratik; kruvaziyer saatinde yoğun ve konaklama pahalıdır."], ["Nordnes, Møhlenpris veya Sandviken", "Yerel kıyı, öğrenci yaşamı ya da tarihî ahşap evler için yürünebilir alternatifler."]], foods: [["Fiskesuppe ve deniz ürünleri", "Balığın türü, porsiyon/kilo fiyatı ve kabuklu deniz ürünü alerjenini siparişten önce sorun."], ["Skillingsbolle", "Bergen'in büyük tarçınlı çöreğini taze fırında paylaşın; süt, tereyağı ve kuruyemiş çapraz bulaşmasını kontrol edin."]], dayTrips: [["Hardangerfjord", "Meyve bahçesi, tekne, otobüs ve dönüş zincirini tek işletme varsaymadan planlayın; bir alt bölge seçin."], ["Voss veya Mostraumen", "Voss doğa/aktivite, Mostraumen tekne günüdür. Hava, lisans, ekipman ve gerçek dönüş saatini doğrulayın."]], caution: "Islak taş, ani rüzgâr ve sis dağ patikasını hızla zorlaştırır; uygun ayakkabı ve katman taşıyın. Balık pazarında tür ve toplam fiyatı, fiyort turunda tekne kapasitesi ile iptal koşulunu yazılı teyit edin."
  },
  {
    city: "Tromsø", countryCode: "NO", focus: "kuzey ışıkları, Arktik kültür ve ada doğası", lede: "Arktik Okyanusu kıyısında kutup araştırması, Sámi tarihi, dağ manzaraları ve mevsime göre kuzey ışığı ya da gece yarısı güneşini birleştiren kuzey üssü.", days: "4–6 gün", arrival: "TOS · Prostneset terminali", local: "Otobüs, havaalanı ekspresi, feribot, rehberli tur ve yürüyüş", best: "Kuzey ışığı için Eylül–Mart · gece yarısı güneşi için Mayıs–Temmuz", pulse: "Tromsø'de kuzey ışığı satın alınabilen bir gösteri değildir; bulut, güneş etkinliği, ulaşım ve güvenli dönüş birlikte sonuç verir. Şehrin Polarmuseet, üniversite müzesi ve Sámi bağlamını doğa turlarından önce okuyarak Arktik deneyimini daha anlamlı kurun.",
    sights: [["Polarmuseet ve liman", "Kutup keşfi ve avcılık tarihini eleştirel bağlamla okuyun; çalışma saatini ve erişilebilirliği kontrol edin."], ["Fjellheisen", "Teleferik biletini, rüzgâr kaynaklı kapanışı ve son inişi doğrulayın; kışın seyir terasında krampon/tutuş yardımına ihtiyaç olabilir."], ["Ishavskatedralen ve Tromsø Müzesi", "Katedral konseri ile ibadet saatini ayırın; üniversite müzesinde Sámi kültürü ve kuzey doğası bölümlerine zaman ayırın."]],
    areas: [["Tromsøya merkez", "Restoran, müze, otobüs ve turların buluşma noktalarına yakın; hafta sonu gürültüsü olabilir."], ["Tromsdalen veya güney Tromsøya", "Teleferik/doğa yakınlığı ya da daha sakin konaklama için köprü/otobüs süreli alternatifler."]], foods: [["Arktik balık ve ren geyiği", "Menşe, av/çiftlik tedariki, pişirme ve alerjeni sorun; Sámi mutfağını pazarlama klişesine indirgemeyen işletme seçin."], ["Kafe ve fırın kültürü", "Kanelbolle, waffle ve sıcak içecek molalarını kısa kış gününe dağıtın; alerjenleri doğrulayın."]], dayTrips: [["Kvaløya ve Sommarøy", "Kış yolunda hava, buz ve gün ışığını kontrol edin; deneyimsizseniz resmî operatörlü tur veya otobüs kullanın."], ["Lyngen Alpleri", "Kayak, yürüyüş ve fiyort geçişi ciddi dağ planıdır; çığ raporu, rehber, ekipman ve feribot saatini birlikte doğrulayın."]], caution: "Kuzey ışığı hiçbir turda garanti değildir; aşırı vaat eden veya yol kenarında güvensiz duran operatörden kaçının. Balina/yaban hayatı turunda mesafe, hız ve refah kurallarını; kış sürüşünde lastik, görüş, ren geyiği ve kapalı yol bilgisini kontrol edin."
  },
  {
    city: "Lofoten", countryCode: "NO", focus: "balıkçı köyleri, sivri dağlar ve Arktik sahiller", lede: "Norveç Denizi'nden yükselen sivri dağları rorbuer balıkçı evleri, morina kültürü, beyaz kumsallar ve küçük sanat köyleriyle birleştiren takımada rotası.", days: "6–9 gün", arrival: "EVE/BOO/LEK · Moskenes ve Svolvær feribotları", local: "Bölgesel otobüs, araç, feribot, bisiklet ve yürüyüş", best: "Haziran–Ağustos · kuzey ışığı için Eylül–Mart", pulse: "Lofoten tek bir Reine fotoğraf noktası değildir. Moskenesøya'nın dramatik köyleri, Vestvågøya'nın tarım ve Viking tarihi, Vågan'ın sanat/liman yaşamı farklı üsler ister. E10 üzerindeki kısa kilometreleri tek şerit, hava ve fotoğraf trafiği nedeniyle uzun sürüş olarak planlayın.",
    sights: [["Reine, Hamnøy ve Å", "Köyleri özel iskele/ev sınırlarına saygıyla gezin; yol kenarında değil işaretli parkta durun ve otobüs/feribot dönüşünü kontrol edin."], ["Henningsvær ve Vågan", "Balık kurutma alanları, galeri ve limanı yürüyün; tırmanış, tekne ve restoranı ayrı rezervasyonlarla planlayın."], ["Lofotr Viking Müzesi ve sahiller", "Borg müzesini Haukland/Uttakleiv gününe eklerken etkinlik saati, rüzgâr ve yol durumunu doğrulayın."]],
    areas: [["Reine, Sørvågen veya Hamnøy", "Güney manzaraları ve Moskenes feribotu için güçlü; oda, market ve park kapasitesi sınırlıdır."], ["Svolvær, Kabelvåg veya Leknes", "Ulaşım, market ve tur için daha işlevsel; takımadanın iki ucuna da uzun gün sürüşü gerekebilir."]], foods: [["Skrei ve tørrfisk", "Mevsim, tür, üretim yöntemi ve porsiyonu sorun; kurutma raflarının çalışan gıda alanı olduğunu unutmayın."], ["Balık çorbası ve tarçınlı çörek", "Küçük liman kafelerinde çalışma saatini, günlük menüyü ve alerjenleri aynı gün doğrulayın."]], dayTrips: [["Værøy veya Røst", "Feribot/uçuş, hava ve konaklama kapasitesini bağımsız ada yolculuğu olarak planlayın; dönüşe güvenlik payı bırakın."], ["Nusfjord ve Flakstad", "Koruma/ziyaret düzeni, giriş ve parkı kontrol edin; plaj ile köyü gün ışığına göre birleştirin."]], caution: "Reinebringen ve kıyı patikaları ıslaklık, rüzgâr, kar ve taş düşmesiyle tehlikeli olabilir; kapanışı aşmayın. Norveç'in doğaya erişim hakkı özel bahçe, ekili alan, vahşi kamp parkı veya ateş yasağı anlamına gelmez; yerel tabela ve tuvalet kurallarına uyun."
  },
  {
    city: "Geirangerfjord", countryCode: "NO", focus: "UNESCO fiyordu, şelaleler ve yüksek seyir yolları", lede: "Dik dağ duvarları arasındaki UNESCO fiyordunu Seven Sisters şelaleleri, terk edilmiş çiftlik patikaları ve kartpostal seyir noktalarıyla birleştiren Batı Norveç rotası.", days: "2–4 gün", arrival: "Geiranger feribot iskelesi · Ålesund/Åndalsnes bağlantıları", local: "Feribot, mevsimsel otobüs, shuttle, araç, tekne ve yürüyüş", best: "Mayıs sonu–Eylül", pulse: "Geirangerfjord bir kruvaziyer molasından daha fazlasıdır; su seviyesinden şelaleleri, Ørnesvingen–Dalsnibba yüksekliklerini ve tarihî çiftlik peyzajını ayrı gün ışığında görmek gerekir. Sezon dışı yol/işletme kapanışı ile gemi günlerindeki yoğunluk rotanın merkezidir.",
    sights: [["Geirangerfjord tekne/feribotu", "Geiranger–Hellesylt hattı veya küçük tekne turunda iskele, araç yeri, can yeleği, hava ve iptal koşulunu doğrulayın."], ["Ørnesvingen ve Flydalsjuvet", "Seyir noktalarına yalnız işaretli platform ve park üzerinden yaklaşın; yol kenarı ve bariyer dışı fotoğraf noktasından kaçının."], ["Fjord çiftlikleri ve şelale yürüyüşleri", "Skageflå gibi patikaları zemin, tekne bırakma/geri dönüş, kondisyon ve gün ışığına göre planlayın; rehber gerekebilir."]],
    areas: [["Geiranger köyü", "İskele, tur ve restoranlara yakın; kruvaziyer gününde kalabalık, gece ise sakin ve kapasitesi sınırlı."], ["Hellesylt veya Stranda", "Fiyort geçişi ve bölgesel rota için alternatif; son feribot/otobüs ile araç gereksinimini kontrol edin."]], foods: [["Fiyort çiftliği ürünleri", "Keçi peyniri, süt ve şarküteri ürünlerinde menşe, pastörizasyon ve et türünü sorun."], ["Balık ve yerel tatlılar", "Günün balığı ile meyveli tatlılarda porsiyon, alerjen ve servis saatini önceden doğrulayın."]], dayTrips: [["Ålesund", "Geiranger'den kara/deniz bağlantısı mevsimseldir; Art Nouveau şehrini aynı gün dönüş yerine rota devamı olarak düşünün."], ["Trollstigen", "Yolun açık olduğunu asla varsaymayın; resmî yol durumu, heyelan/çalışma ve otobüs güzergâhını kontrol edin."]], caution: "Dağ yolu kar, heyelan, çığ veya bakım nedeniyle yaz içinde bile kapanabilir. Kruvaziyer saatinde dar köy yollarında yayaya dikkat edin; bariyer dışına çıkmayın, drone ve özel arazi kurallarını ihlal etmeyin."
  },
  {
    city: "Flåm", countryCode: "NO", focus: "Flåmsbana, Nærøyfjord ve Aurland", lede: "Aurlandsfjord ucundaki küçük köyü ünlü Flåmsbana, UNESCO Nærøyfjord, dik vadiler ve Stegastein seyir noktasıyla birleştiren demiryolu–fiyort kavşağı.", days: "2–4 gün", arrival: "Flåm stasjon/limanı · Myrdal bağlantısı", local: "Tren, feribot, shuttle, otobüs, bisiklet ve yürüyüş", best: "Mayıs–Eylül · sakinlik için Nisan/Ekim", pulse: "Flåm'ın ölçeği küçük, ulaşım zinciri büyüktür. Oslo–Bergen treninden Myrdal aktarması, Flåmsbana, Nærøyfjord teknesi ve Gudvangen otobüsü aynı gün kurulabilir; fakat gecikme ve kruvaziyer kalabalığı yüzünden bir gece konaklamak bölgeyi daha iyi açar.",
    sights: [["Flåmsbana", "Yön, koltuk, bisiklet ve Myrdal aktarmasını ayrı doğrulayın; kısa fotoğraf molasının istasyon inişi anlamına gelmediğini unutmayın."], ["Nærøyfjord", "Flåm–Gudvangen teknesinde iskele, tekne tipi, bagaj ve dönüş otobüsünü birlikte alın; hava/kapasiteyi kontrol edin."], ["Stegastein ve Aurland", "Shuttle ya da araçla seyir noktasına çıkarken yolun dar olduğunu bilin; Aurland köyüne ayrı yürüyüş zamanı bırakın."]],
    areas: [["Flåm merkezi", "Tren ve tekneye en kolay erişim; gemi saatinde yoğun, yemek ve oda seçeneği sınırlıdır."], ["Aurland veya Gudvangen", "Daha sakin köy/fiyort hissi için güçlü alternatif; son otobüs ve bagaj transferi planı gerekir."]], foods: [["Keçi peyniri ve çiftlik ürünleri", "Undredal/Aurland üretiminde süt türü, olgunlaştırma ve pastörizasyonu sorun; üretici ziyaretini önceden ayarlayın."], ["Yerel bira ve fırın ürünleri", "Tadımı araçsız planlayın; fırında süt/tereyağı ile menüde et suyu ve alerjenleri doğrulayın."]], dayTrips: [["Undredal", "Tekne/otobüs sıklığını kontrol ederek küçük köy ve stave kilisesini sessiz, özel mülke saygılı bir yarım gün olarak gezin."], ["Bergen veya Oslo demiryolu", "İkisi de rota devamıdır; Flåm'dan günübirlik dönüş yerine Myrdal bağlantılı tek yön gezi ayağı kurun."]], caution: "Tekne, tren ve otobüs zincirini ayrı ayrı alınca aktarma koruması olmayabilir; geniş pay bırakın. Bisikletle Rallarvegen için sezon, kar, fren ve tek yön kiralama şartını; patikalarda sel/heyelan durumunu kontrol edin."
  },
  {
    city: "Trondheim", countryCode: "NO", focus: "Nidaros, Bakklandet ve Orta Norveç tarihi", lede: "Nidaros Katedrali'nin hac mirasını renkli Bakklandet, üniversite kültürü, müzik müzeleri ve Trøndelag mutfağıyla birleştiren tarihî kuzey şehri.", days: "3–4 gün", arrival: "TRD · Trondheim S · Hurtigruten/Havila iskelesi", local: "Otobüs, tramvay, tren, bisiklet ve yürüyüş", best: "Mayıs–Eylül · kış atmosferi için Aralık–Mart", pulse: "Trondheim, Oslo ile kuzey arasında yalnız gece treni durağı değildir. Nidaros'un Orta Çağ hac ağını, Bakklandet'in ahşap evlerini, NTNU çevresindeki genç şehri ve Lade kıyısını aynı kompakt rotada okuyabilirsiniz. Müze ve kilise saatleri mevsime göre kısalır.",
    sights: [["Nidaros Katedrali ve Başpiskoposluk Sarayı", "İbadet, konser ve turist giriş saatini ayırın; kule turu, fotoğraf ve kıyafet kurallarını önceden kontrol edin."], ["Bakklandet ve Gamle Bybro", "Ahşap mahalleyi sakin saatlerde yürüyün; bisiklet yolunu kapatmayın ve özel evlerin fotoğrafında mahremiyete saygı gösterin."], ["Ringve veya Sverresborg", "Müzik koleksiyonu ya da açık hava tarih müzesinden birini seçin; sezonluk bina/tur saatini doğrulayın."]],
    areas: [["Midtbyen ve Solsiden", "İstasyon, katedral, restoran ve gece hayatına yakın; hafta sonu gürültüsü olabilir."], ["Bakklandet, Ila veya Lademoen", "Mahalle dokusu, tramvay ya da daha yerel konaklama için merkezden kısa yürüyüşlü alternatifler."]], foods: [["Trøndelag yerel sofrası", "Deniz ürünü, av eti ve çiftlik ürünlerinde menşe, et türü ve alerjeni sorun; tadım menüsünü rezervasyonla planlayın."], ["Sodd ve fırın ürünleri", "Geleneksel çorbanın et/süt içeriğini, çörek ve pastalarda alerjenleri doğrulayın."]], dayTrips: [["Røros", "Trenle tarihî maden kasabasına giderken müze, son dönüş ve kış soğuğunu planlayın; mümkünse bir gece ayırın."], ["Stiklestad veya Munkholmen", "Tarih merkezi kara yönünde, ada teknesi mevsimseldir; ilginize ve sezona göre yalnız birini seçin."]], caution: "Kışın kaldırım ve köprüler buzlu olabilir; nehir kıyısında bariyer dışına çıkmayın. Katedralde yaşayan ibadet düzenine, bisiklet yollarında geçiş hakkına ve kıyı yürüyüşünde hava uyarılarına uyun."
  },
  {
    city: "Stavanger", countryCode: "NO", focus: "eski liman, enerji tarihi ve Lysefjord yürüyüşleri", lede: "Beyaz ahşap Gamle Stavanger'i çağdaş enerji müzesi, sokak sanatı, deniz mutfağı ve Lysefjord'un yüksek kaya yürüyüşleriyle birleştiren güneybatı limanı.", days: "3–5 gün", arrival: "SVG · Stavanger stasjon · Fiskepiren", local: "Otobüs, tren, feribot, tekne, yürüyüş ve tur transferi", best: "Mayıs–Eylül", pulse: "Stavanger yalnız Preikestolen'e açılan bir otel üssü değildir. Konserve ve petrol tarihini, renkli Fargegaten'i, ahşap eski şehri ve Jæren kıyısını okuyun; sonra Lysefjord gününü hava ve kondisyon uygun olduğunda ekleyin.",
    sights: [["Gamle Stavanger ve Konserve Müzesi", "Ahşap sokakları sessiz gezin; özel ev sınırına saygı duyun ve müze atölye/çalışma saatini kontrol edin."], ["Norveç Petrol Müzesi", "Enerji tarihini yalnız teknoloji vitrini değil ekonomi, iş güvenliği ve iklim tartışmasıyla birlikte okuyun; sergi saatini doğrulayın."], ["Preikestolen", "Otobüs/feribot transferi, park, hava, zemin, gün ışığı ve kondisyonu birlikte planlayın; uçurum kenarında fotoğraf için risk almayın."]],
    areas: [["Vågen, Sentrum ve Gamle Stavanger", "İlk ziyaret, feribot ve müzelere yürüyüş için pratik; liman cephesi pahalı ve yoğun olabilir."], ["Storhaug veya Sandnes", "Daha yerel konaklama ya da bölgesel tren/otobüs için farklı fiyatlı alternatifler."]], foods: [["Deniz ürünü ve fiskesuppe", "Balık/kabuklu türünü, menşeini, porsiyon/kilo fiyatını ve alerjeni siparişten önce sorun."], ["Jæren çiftlik ürünleri", "Peynir, kuzu ve sebzede üreticiyi sorun; et/süt içeriğini beslenme tercihinize göre doğrulayın."]], dayTrips: [["Lysefjord teknesi", "Preikestolen manzaralı tekne turunda hava, iskele, gerçek rota, lisans ve iptal şartını yazılı kontrol edin."], ["Kjerag veya Jæren", "Kjerag uzun, hava bağımlı ve ciddi yürüyüştür; Jæren sahilleri daha esnek kara günüdür. Aynı zorlukta sanmayın."]], caution: "Preikestolen ve özellikle Kjerag'ı şehir parkı gibi değerlendirmeyin; sis, buz, rüzgâr ve ıslak kaya ölümcül olabilir. Uçurum bariyerini aşmayın, drone ve kurtarma sigortası koşullarını kontrol edin; dönüş ulaşımını kaçırmayın."
  },
];

export const norwayGuides = makeRegionalGuides(profiles);
