import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Varşova", countryCode: "PL", focus: "yeniden kurulan eski şehir, müzeler ve modern mahalleler", lede: "Savaş yıkımından yeniden doğan tarihî çekirdeği büyük hafıza müzeleri, Vistül kıyısı ve hızla dönüşen mahallelerle birleştiren başkent.", days: "4–5 gün", arrival: "WAW · WMI · Warszawa Centralna", local: "Metro, tramvay, otobüs, tren ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Varşova'nın gücü eski görünmekten değil, yıkım ve yeniden inşayı saklamadan anlatmasından gelir. Her gün bir ağır hafıza müzesini park, nehir veya yaşayan mahalleyle dengeleyin.",
    sights: [["Eski Şehir ve Kraliyet Yolu", "UNESCO yeniden inşa hikâyesini Kale Meydanı, pazar ve Krakowskie Przedmieście boyunca bağlayın; Kraliyet Şatosu biletini önceden alın."], ["POLIN ve Varşova Ayaklanması Müzesi", "İki kapsamlı müzeyi aynı güne sıkıştırmayın; saatli bilet, güvenlik ve duygusal yoğunluk için ayrı yarım günler ayırın."], ["Łazienki ve Wilanów", "Łazienki parkını ücretsiz açık alan, Wilanów'u saray/sergi bileti olarak planlayın; ışık etkinliği ve konser günlerini kontrol edin."]],
    areas: [["Śródmieście ve Eski Şehir", "Müze, tren ve ilk ziyaret kolaylığı yüksek; büyük caddelerde gece gürültüsü değişir."], ["Praga, Powiśle ve Mokotów", "Endüstri mirası, nehir, kafe ve daha yerel akşam için metro/tramvaylı alternatifler."]], foods: [["Pierogi ve żurek", "Mantı dolgusu ile ekşi çorbadaki sosis/yumurta içeriğini sorun; süt barında ekonomik günlük menü deneyin."], ["Pączki ve sernik", "Reçelli çörek ile Polonya cheesecake'ini iyi bir fırında paylaşın; turistik zincir yerine günlük üretimi arayın."]], dayTrips: [["Żelazowa Wola", "Chopin'in doğum evi ve park için banliyö tren–otobüs bağlantısını, konser takvimini önceden kurun."], ["Łódź", "Piotrkowska, tekstil sanayi mirası ve çağdaş kültür için hızlı trenle ayrı tam gün veya iki gece ayırın."]], caution: "Hafıza müzelerinde selfie, kostüm ve yüksek sesli davranıştan kaçının. WMI Modlin ile WAW Chopin havalimanını karıştırmayın; bilet kontrolünde uygulama bileti etkinleştirme kuralını okuyun."
  },
  {
    city: "Kraków", countryCode: "PL", focus: "Wawel, Kazimierz ve güçlü hafıza rotaları", lede: "Orta Çağ meydanını Wawel tepesi, Yahudi mirası, öğrenci kültürü ve yakın çevredeki dünya çapında hafıza mekânlarıyla buluşturan kent.", days: "4–6 gün", arrival: "KRK · Kraków Główny", local: "Tramvay, otobüs, tren ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Kraków'un kartpostal merkezi güçlüdür; asıl derinlik Kazimierz ile Podgórze'deki Yahudi, savaş ve sanayi katmanlarını dikkatli okumakla ortaya çıkar.",
    sights: [["Wawel Kalesi ve Katedral", "Devlet odaları, kraliyet daireleri, hazine ve katedral ayrı bilet/kurallara sahiptir; iki-üç odak seçin."], ["Rynek Główny ve yeraltı müzesi", "Azize Meryem Bazilikası, Kumaş Pazarı ve Rynek Underground için ayin ile saatli bilet çakışmasını kontrol edin."], ["Kazimierz ve Podgórze", "Sinagog, mezarlık, Ghetto Heroes Square ve Schindler Fabrikası'nı tarihsel bağlamla gezin; Fabrika bileti erken dolar."]],
    areas: [["Stare Miasto ve Kazimierz", "İlk ziyaret, akşam ve ana yerlere yürüyüş için güçlü; gece gürültüsü sokaktan sokağa değişir."], ["Podgórze ve Grzegórzki", "Hafıza rotası, nehir ve daha yerel kafe/konaklama için tramvaylı alternatif."]], foods: [["Obwarzanek ve zapiekanka", "Sokak atıştırmalıklarında taze üretim ve sos içeriğini kontrol edin; Kazimierz kuyruğunu kalite garantisi sanmayın."], ["Kraków mutfağı", "Maczanka krakowska, pierogi ve çorbalarda et suyu/yağ içeriğini sorun; süt barı iyi başlangıçtır."]], dayTrips: [["Wieliczka Tuz Madeni", "Saatli rehber, dil, uzun merdiven ve yeraltı sıcaklığını önceden okuyun; dönüş asansörü koşulları değişir."], ["Auschwitz-Birkenau", "Bir anma ve eğitim alanıdır; resmî ziyaretçi merkezi üzerinden saat/rehber alın, saygılı kıyafet ve davranışla ayrı tam gün ayırın."]], caution: "Auschwitz-Birkenau'yu eğlence turu diliyle pazarlayan üçüncü taraflara güvenmeyin; resmî kuralları izleyin. Merkezde sahte bağış/petisyon ve lisanssız döviz bürosuna, gece alkollü ulaşımda resmî araç kullanımına dikkat edin."
  },
  {
    city: "Gdańsk", countryCode: "PL", focus: "Baltık limanı, Dayanışma ve sahil rotası", lede: "Renkli Hansa cephelerini tersane hafızası, kehribar geleneği, güçlü müzeler ve üç şehirli Baltık kıyısıyla birleştiren liman kenti.", days: "3–5 gün", arrival: "GDN · Gdańsk Główny", local: "SKM treni, tramvay, otobüs ve yürüyüş", best: "Mayıs–Haziran · Eylül · Aralık", pulse: "Gdańsk'ın yeniden kurulan Ana Şehri yalnız estetik bir dekor değildir; Avrupa Dayanışma Merkezi ve İkinci Dünya Savaşı Müzesi kentin modern Avrupa tarihindeki yerini açıklar.",
    sights: [["Długi Targ ve Motława", "Altın Kapı'dan nehir kıyısına ana hattı sabah yürüyün; belediye binası, Artus Court ve vinçten ilginize göre ikisini seçin."], ["Avrupa Dayanışma Merkezi", "Tersane kapısı ve kapsamlı sergi için en az üç saat ayırın; kapanış ve geçici sergiyi resmî takvimden görün."], ["İkinci Dünya Savaşı Müzesi", "Yoğun koleksiyon için saatli bilet ve uzun ziyaret planlayın; aynı güne ikinci ağır tarih müzesi eklemeyin."]],
    areas: [["Główne Miasto", "İlk ziyaret, nehir ve restoranlara yakın; hafta sonu yoğun ve daha pahalı."], ["Wrzeszcz ve Oliwa", "SKM hattı, park, katedral ve yerel yeme içme için dengeli konaklama alternatifi."]], foods: [["Baltık balığı", "Ringa, morina ve füme balıkta tür, menşe ve günlük tazeliği sorun; sürdürülebilir seçime öncelik verin."], ["Goldwasser ve kehribar ürünleri", "Bitkisel likörü ölçülü deneyin; kehribarda gerçeklik belgesi ve iade koşulu isteyin."]], dayTrips: [["Sopot ve Gdynia", "SKM ile plaj, iskele ve modern limanı aynı hat üzerinde görün; yaz dönüş yoğunluğunu hesaba katın."], ["Malbork", "Büyük Töton Kalesi için tren istasyonundan yürüyüş ve en az dört saat; resmî bileti önceden alın."]], caution: "Ana Şehir ile resmî Eski Şehir adlarını karıştırmak rotayı şaşırtabilir. Baltık'ta bayrak ve cankurtaran uyarısına uyun; sahte/işlenmiş kehribarı güvenilir belge olmadan almayın."
  },
  {
    city: "Wrocław", countryCode: "PL", focus: "ada ve köprüler, pazar meydanı ve modern mimari", lede: "Odra adaları, renkli pazar meydanı, yüzlerce köprü ve Alman–Polonya–Silezya katmanlarıyla canlı batı şehri.", days: "3–4 gün", arrival: "WRO · Wrocław Główny", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Wrocław'ın cüce heykelleri eğlenceli bir rota verir; ancak şehir kimliği savaş sonrası nüfus değişimi, Silezya tarihi ve Centennial Hall modernizmiyle çok daha büyüktür.",
    sights: [["Rynek ve belediye binası", "Gotik belediye binası, renkli evler ve üniversite yönünü sabah ışığında bir yürüyüşe bağlayın."], ["Ostrów Tumski", "Katedral Adası'nı Botanik Bahçesi ve akşam gaz lambalarıyla görün; ayin ve köprü çalışmalarını kontrol edin."], ["Centennial Hall", "UNESCO yapıyı Japon Bahçesi ve multimedya çeşmeyle birleştirin; etkinlik günü iç mekân erişimi değişebilir."]],
    areas: [["Stare Miasto", "Meydan, müze ve akşam için merkezi; hafta sonu gürültüsü yükselebilir."], ["Nadodrze ve Ołbin", "Sanat atölyesi, mahalle kafesi ve daha yerel ritim için tramvaylı alternatif."]], foods: [["Silezya mutfağı", "Kluski śląskie, lahana ve et yemeklerinde porsiyon ile sos içeriğini sorun."], ["Wrocław fırınları", "Drożdżówka ve makowiec gibi hamur işlerini sabah taze üretimde deneyin; haşhaş/kuruyemiş alerjenini kontrol edin."]], dayTrips: [["Książ Kalesi", "Wałbrzych üzerinden tren/otobüs bağlantısı ve yeraltı turu için ayrı tam gün ayırın."], ["Świdnica ve Jawor", "UNESCO Barış Kiliseleri için açılış, ayin ve iki kasaba arası ulaşımı önceden eşleştirin."]], caution: "Cüce avında bisiklet/tramvay yoluna dikkatsizce çıkmayın. Odra kıyısında taşkın ve buz uyarısını, Centennial Hall etkinlik günü çevre ulaşımını kontrol edin."
  },
  {
    city: "Poznań", countryCode: "PL", focus: "Rönesans meydanı, ilk Polonya tarihi ve tasarım", lede: "Renkli Rönesans meydanını katedral adası, güçlü ticaret mirası, çağdaş tasarım ve Büyük Polonya mutfağıyla birleştiren kent.", days: "2–3 gün", arrival: "POZ · Poznań Główny", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Poznań, Varşova–Berlin hattında yalnız aktarma değildir. Ostrów Tumski Polonya devletinin erken tarihini, Jeżyce ve Śródka ise bugünün yaratıcı kentini gösterir.",
    sights: [["Stary Rynek ve keçiler", "Belediye binasının öğle gösterisini restorasyon ve saat bilgisiyle doğrulayın; meydanı yalnız fotoğraf molasına indirmeyin."], ["Ostrów Tumski ve Brama Poznania", "Katedral adasının arkeoloji ve devlet kurma hikâyesini etkileşimli merkezle birlikte en az yarım günde okuyun."], ["Enigma Şifre Merkezi", "Polonyalı matematikçilerin Enigma çalışmalarını anlatan sergi için sesli rehber ve saatli girişi kontrol edin."]],
    areas: [["Stare Miasto ve Śródka", "Tarih, nehir ve ilk ziyaret için yürünebilir/ulaşımlı iki komşu odak."], ["Jeżyce", "Pazar, kafe, Art Nouveau apartmanlar ve daha yerel akşam için tramvaylı alternatif."]], foods: [["Rogal świętomarciński", "Korumalı Aziz Martin kruvasanını sertifikalı üreticiden alın; beyaz haşhaş, badem ve süt alerjenini sorun."], ["Pyry ve Büyük Polonya mutfağı", "Patates temelli pyry z gzikiem gibi sade tabakları süt barı veya yerel lokantada deneyin."]], dayTrips: [["Gniezno", "İlk başkent ve katedral kapıları için kısa trenle ayrı yarım/tam gün; ayin saatini kontrol edin."], ["Rogalin", "Saray, sanat koleksiyonu ve yaşlı meşeler için sezonluk otobüs/transfer planı gerekir."]], caution: "Ana meydandaki uzun restorasyonlar görüş ve geçişi değiştirebilir; ziyaret günü kontrol edin. Kruvasan adını her ürünün taşıyamayacağını bilin, tramvay biletini süre/bölge kuralına göre etkinleştirin."
  },
  {
    city: "Zakopane", countryCode: "PL", focus: "Tatra yürüyüşleri, ahşap mimari ve dağ kültürü", lede: "Tatra Dağları'nın eteklerinde yürüyüş, kayak, Gorál kültürü, ahşap villalar ve termal kasabaları bir araya getiren yoğun dağ üssü.", days: "4–6 gün", arrival: "Zakopane tren/otobüs terminali · Kraków bağlantısı", local: "Yürüyüş, yerel minibüs, otobüs ve teleferik", best: "Haziran–Eylül · kayak için Ocak–Mart", pulse: "Zakopane'nin Krupówki kalabalığı Tatra deneyiminin kendisi değildir. Ana planı milli park patikası ve hava penceresi üzerine kurun; kasaba kültürünü dinlenme gününe yerleştirin.",
    sights: [["Morskie Oko", "Park girişi/otopark ve servis koşulunu önceden ayırın; asfalt rota uzun, göl çevresi hava ve buz koşuluna bağlıdır."], ["Kasprowy Wierch", "Teleferik saatli ve hava hassastır; zirve koşulu şehirden farklı olduğundan canlı kamera, rüzgâr ve son inişi kontrol edin."], ["Zakopane Stili rotası", "Willa Koliba, ahşap kilise ve eski mezarlığı saygılı bir kasaba yürüyüşünde birleştirin."]],
    areas: [["Merkez ve Krupówki çevresi", "İlk ziyaret, terminal ve restoranlar için pratik; gece gürültüsü ve kalabalık yüksektir."], ["Kościelisko ve Jaszczurówka", "Vadiler, ahşap mimari ve daha sakin konaklama için minibüs/otobüs bağlantılı alternatif."]], foods: [["Oscypek", "Korumalı tütsülü koyun peynirini lisanslı üreticiden alın; inek sütlü benzerleri ve süt alerjenini ayırın."], ["Kwaśnica ve moskole", "Ekşi lahana çorbası ile patates ekmeğinde et suyu, tereyağı ve porsiyonu sorun."]], dayTrips: [["Chochołów ve termaller", "Ahşap köy ile termal tesisi otobüs/transferle birleştirin; hamam sağlık ve yaş kuralını okuyun."], ["Dunajec ve Niedzica", "Sal/tekne, kale ve bisiklet rotası mevsimliktir; lisanslı işletme ve dönüş saatini doğrulayın."]], caution: "TOPR/TPN kapanışına rağmen patikaya girmeyin; fırtına, çığ ve ayı uyarısını ciddiye alın. Spor ayakkabısını her rotaya yeterli sanmayın, helikopter kurtarma kapsamını sigortadan kontrol edin."
  },
  {
    city: "Toruń", countryCode: "PL", focus: "Gotik UNESCO merkezi, Kopernik ve zencefilli kurabiye", lede: "Vistül kıyısında tuğla Gotik şehir dokusunu Kopernik mirası, Orta Çağ surları ve yaşayan piernik geleneğiyle koruyan kompakt kent.", days: "2–3 gün", arrival: "Toruń Główny · Toruń Miasto", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Toruń'un küçük merkezi hızlı tüketilebilir görünür; gece aydınlatması, müze atölyeleri ve Vistül'ün karşı kıyısından silüet için en az bir gece kalmak şehri değiştirir.",
    sights: [["UNESCO eski şehir", "Belediye binası, katedral, surlar ve Eğik Kule'yi tek bir Gotik rota olarak yürüyün; kule çıkışını hava ve kapasiteye göre seçin."], ["Kopernik Evi ve Planetaryum", "Biyografik müze ile gösteri seansını ayrı saatlere alın; dil ve yaş önerisini rezervasyonda kontrol edin."], ["Piernik Müzesi", "Canlı zencefilli kurabiye atölyeleri saatli ve dil odaklıdır; alerjen ile katılım koşulunu önceden sorun."]],
    areas: [["Stare Miasto ve Nowe Miasto", "Ana müze, restoran ve akşam yürüyüşüne yakın, kompakt ilk üs."], ["Bydgoskie Przedmieście", "Art Nouveau evler, park ve daha yerel konaklama için tramvaylı alternatif."]], foods: [["Toruń pierniki", "Baharatlı kurabiyede dolgulu/geleneksel çeşitleri karşılaştırın; bal, gluten ve kuruyemiş alerjenini kontrol edin."], ["Kujawy mutfağı", "Patates, lahana ve ördek temelli tabakları günlük menüde arayın; ağır porsiyonu paylaşın."]], dayTrips: [["Bydgoszcz", "Kanallar, değirmen adası ve çağdaş müzeler için kısa trenle ayrı tam gün."], ["Chełmno", "Surlu küçük şehir ve Gotik kiliseler için seyrek otobüs/transfer dönüşünü önceden kaydedin."]], caution: "Toruń Główny nehrin karşı kıyısındadır; bağlantı süresini hesaba katın. Müze atölyesinde sıcak ekipman talimatına, Vistül kıyısında taşkın ve buz bariyerine uyun."
  },
  {
    city: "Lublin", countryCode: "PL", focus: "Doğu Polonya mirası, eski şehir ve hafıza mekânları", lede: "Renkli eski şehri kale, çok kültürlü sınır tarihi, Brama Grodzka anlatısı ve çevredeki Rönesans kasabalarıyla birleştiren doğu merkezi.", days: "3–4 gün", arrival: "Lublin Główny · LUZ", local: "Otobüs, troleybüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Lublin, Polonya–Litvanya Birliği ve Yahudi yaşamının önemli kentlerinden biridir. Bu çoğul tarih, Majdanek ve savaş kaybıyla birlikte dikkatli bir dil gerektirir.",
    sights: [["Lublin Kalesi ve Kutsal Üçlü Şapeli", "Bizans–Ruten freskli şapel için saatli bilet alın; kale müzesinin kapsamı geniş olduğundan iki odak seçin."], ["Brama Grodzka ve eski şehir", "Yahudi mahallesi hafızasını Kapı Merkezi'nin arşiv/anlatılarıyla yürüyün; yalnız renkli cephe fotoğrafıyla yetinmeyin."], ["Majdanek Devlet Müzesi", "Eski kamp ve anma alanına en az yarım gün ayırın; resmî erişim, hava ve fotoğraf kurallarına saygıyla uyun."]],
    areas: [["Stare Miasto ve Śródmieście", "Kale, kapılar ve restoranlara yürüyüş için ilk ziyarette işlevsel."], ["Wieniawa ve Czechów", "Üniversite, park ve daha sakin konaklama için otobüs/troleybüs bağlantılı alternatif."]], foods: [["Cebularz lubelski", "Soğan ve haşhaşlı korumalı ekmeği taze fırından alın; gluten/haşhaş içeriğini not edin."], ["Doğu Polonya mutfağı", "Pierogi, karabuğday ve çiftlik peyniri temelli tabaklarda et suyu ile süt içeriğini sorun."]], dayTrips: [["Kazimierz Dolny", "Vistül kasabası, tahıl ambarları ve kale tepesi için otobüs dönüşünü önceden kaydedin."], ["Zamość", "İdeal Rönesans şehrine tren/otobüsle ayrı tam gün; belediye binası ve sinagog saatini kontrol edin."]], caution: "Majdanek'te sessiz, saygılı ve bağlama uygun davranın; kalıntılara dokunmayın. Eski şehirde dik arnavut kaldırımını, kırsal günübirlikte son otobüs ve kış hava koşullarını hesaba katın."
  },
];

export const polandGuides = makeRegionalGuides(profiles);
