import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Moskova", countryCode: "RU", focus: "Kremlin, büyük müzeler ve mahalle rotaları", lede: "Kremlin surları, avangart mimari, görkemli metro istasyonları ve çağdaş kültür alanlarıyla ölçeği sürekli değişen Rusya başkenti.", days: "5–7 gün", arrival: "SVO · DME · VKO · merkez tren istasyonları", local: "Metro, MCC/MCD trenleri, otobüs ve yürüyüş", best: "Mayıs–Haziran · Eylül · kış atmosferi için Ocak–Şubat", timezone: "UTC+3", pulse: "Moskova'nın anıtları birbirine yakın görünse de müze güvenliği, uzun yürüyüş ve ulaşım aktarması günü büyütür. Her gün tek büyük kurum ve tek mahalle seçmek daha gerçekçi bir ritimdir.",
    sights: [["Kremlin ve Kızıl Meydan", "Kremlin müzeleri, Silahhane ve meydan erişimi tören/güvenlik nedeniyle değişebilir; yalnız resmî bilet ve aynı gün duyurusunu kullanın."], ["Tretyakov Galerileri", "Lavrushinsky Lane'deki klasik koleksiyon ile New Tretyakov'daki 20. yüzyılı ayrı yarım günlere bölün."], ["VDNKh ve Kozmonotluk Müzesi", "Geniş alanda pavyon, müze ve parkı ilginize göre seçin; etkinlik, buz pisti ve bina erişimini kontrol edin."]],
    areas: [["Tverskoy, Kitay-Gorod ve Zamoskvorechye", "İlk ziyaret, müze ve merkez yürüyüşü için güçlü; güvenlik kapanışı ile fiyatlar değişebilir."], ["Arbat, Khamovniki ve Basmanny", "Müze, konut mimarisi ve daha yerel akşam için metro bağlantılı seçenekler."]], foods: [["Pelmeni ve blini", "Dolgu, et türü ve ekşi krema içeriğini sorun; günlük lokantada küçük porsiyonla çeşitlendirin."], ["Gürcü ve Orta Asya mutfakları", "Moskova'nın çok kültürlü sofrasında khinkali, plov ve mantı deneyin; helal/vegan gereksinimi doğrudan mutfaktan doğrulayın."]], dayTrips: [["Sergiyev Posad", "Trinity Lavra için banliyö treni, ibadet saatleri, kıyafet ve fotoğraf kuralıyla ayrı gün planlayın."], ["Kolomna", "Kremlin, pastila geleneği ve Oka kıyısı için uzun banliyö trenine erken başlayın; son dönüşü kaydedin."]], caution: "Gösteri ve kalabalık siyasi etkinliklerden uzak durun; askerî, güvenlik ve altyapı tesislerini fotoğraflamayın. Pasaport/konaklama kaydı, metro erişimi, ödeme ve uygulama kullanımını seyahat günü resmî kaynaklarla doğrulayın."
  },
  {
    city: "St. Petersburg", countryCode: "RU", focus: "Hermitage, saraylar ve kanal kentinin kültür rotası", lede: "Neva deltası üzerinde imparatorluk saraylarını dünya çapında sanat, beyaz geceler, köprüler ve edebiyat mahalleleriyle birleştiren kültür başkenti.", days: "5–7 gün", arrival: "LED · Moskovsky/Vitebsky/Finlyandsky", local: "Metro, tramvay, otobüs, banliyö treni ve mevsimlik tekne", best: "Mayıs sonu–Temmuz · Eylül · karlı dönem için Şubat", timezone: "UTC+3", pulse: "St. Petersburg'da Hermitage'ı bir sabah, Peterhof'u bir öğleden sonra bitirme fikri gerçekçi değildir. Sarayları tek tek seçip kanallar ve mahallelerle dengeleyin.",
    sights: [["Hermitage ve Kışlık Saray", "Ana kompleks çok büyüktür; çevrimiçi resmî saatli bilet alın, iki koleksiyon odağı belirleyin ve ayrı depo/şube biletini kontrol edin."], ["Peterhof", "Alt Park, saray ve çeşme sezonu farklı çalışır; hidrofil/tren–otobüs dönüşünü hava ve son sefere göre kurun."], ["Isaac, Kanlı Kilise ve kanallar", "İç mekân, kubbe ve tekne seçeneklerini ayrı biletlerle planlayın; gece köprü açılışı dönüş rotasını değiştirebilir."]],
    areas: [["Tsentralny ve Admiralteysky", "İlk ziyaret, müze ve kanal yürüyüşü için merkezî; Beyaz Geceler'de pahalı ve kalabalık."], ["Petrogradsky ve Vasilyevsky", "Mimari, küçük müze ve daha yerel akşam için köprü/metro saatine dikkat gerektiren alternatifler."]], foods: [["Pışki ve smelt", "Sıcak halka tatlıyı klasik büfede; mevsimlik koruşka balığını tür ve tazelik sorarak deneyin."], ["Gürcü ve Rus kuzey mutfağı", "Khachapuri, balık çorbası ve mantarlı tabaklarda porsiyon, süt ve et suyu içeriğini sorun."]], dayTrips: [["Tsarskoye Selo", "Catherine Sarayı ve Amber Room için sahte olmayan resmî saatli bileti, banliyö tren/otobüs bağlantısını önceden kurun."], ["Kronstadt", "Deniz katedrali ve savunma tarihine otobüs/tekneyle gidin; liman ve askerî bölge fotoğraf kısıtına uyun."]], caution: "Gece açılan köprüler bazı kara yollarını keser; son metro ve otel yakasını önceden kontrol edin. Neva teknesinde yalnız lisanslı işletme, can yeleği ve hava duyurusu kullanın; donmuş suya resmî izin olmadan çıkmayın."
  },
  {
    city: "Kazan", countryCode: "RU", focus: "Kazan Kremlini, Tatar kültürü ve Volga rotası", lede: "Beyaz Kremlin surları içinde cami ile Ortodoks katedralini, Tatar dili, Volga manzarası ve canlı yerel mutfakla yan yana getiren başkent.", days: "3–5 gün", arrival: "KZN · Kazan-Passazhirskaya", local: "Metro, otobüs, tramvay ve yürüyüş", best: "Mayıs–Haziran · Ağustos–Eylül", timezone: "UTC+3", pulse: "Kazan, Moskova'nın bölgesel kopyası değildir. Tataristan'ın dili, İslamî mirası, tüccar mahalleleri ve çağdaş kimliği rotanın merkezindedir.",
    sights: [["Kazan Kremlini", "Qol Şärif Camii, Müjde Katedrali ve müzeleri saygılı bir rota halinde gezin; ibadet, kıyafet ve güvenlik kuralını kontrol edin."], ["Staro-Tatarskaya Sloboda", "Göller çevresindeki camiler, tüccar evleri ve Tatar kültürünü rehberli yürüyüş veya müzeyle bağlama oturtun."], ["Aile Merkezi ve Kremlin kıyısı", "Volga–Kazanka manzarasını gün batımında yürüyün; etkinlik ve kış buz koşuluna göre erişim değişebilir."]],
    areas: [["Vakhitovsky ve Bauman Caddesi", "Kremlin, yaya bölgesi ve ilk ziyaret için merkezî; hafta sonu kalabalık."], ["Staro-Tatarskaya Sloboda ve Novo-Savinovsky", "Kültürel miras veya nehir/modern şehir yaşamı için iki farklı alternatif."]], foods: [["Eçpoçmak ve kystybyi", "Üçgen börek ile patatesli gözleme benzeri üründe et, tereyağı ve üretim saatini sorun."], ["Çak-çak ve Tatar çayı", "Ballı tatlıyı küçük porsiyonla deneyin; kuruyemiş ve bal içeriğini kontrol edin."]], dayTrips: [["Sviyazhsk", "Ada-kasaba müzeleri ve manastırlar için otobüs/tekne mevsimi, kıyafet ve son dönüşü planlayın."], ["Bolgar", "Volga Bulgar mirası ve Beyaz Cami için uzun kara/tekne günü; resmî müze ve ulaşım saatini doğrulayın."]], caution: "Cami ve kiliselerde yaşayan ibadet alanına saygı gösterin; Tatar kimliğini yalnız yemek/dekor olarak genellemeyin. Nehir buzu, tekne ve kırsal transferde resmî açık/kapalı bilgisini kullanın."
  },
  {
    city: "Soçi", countryCode: "RU", focus: "Karadeniz kıyısı, Kafkas dağları ve subtropik parklar", lede: "Uzun Karadeniz sahilini subtropik bahçeler, Olimpiyat mirası ve Krasnaya Polyana'nın Kafkas dağlarıyla birleştiren geniş tatil bölgesi.", days: "5–7 gün", arrival: "AER · Soçi/Adler tren istasyonları", local: "Banliyö treni, otobüs, taksi ve teleferik", best: "Mayıs–Haziran · Eylül · dağ için Ocak–Mart", timezone: "UTC+3", pulse: "Soçi tek merkez değildir: şehir merkezi, Adler, Sirius ve Krasnaya Polyana onlarca kilometreye yayılır. Konaklamayı plaj, dağ veya şehir odağına göre seçin.",
    sights: [["Arboretum ve merkez sahili", "Teleferik/park bileti, bitki koleksiyonu ve deniz promenadını sıcak öğleye göre ayrı zamanlayın."], ["Krasnaya Polyana", "Rosa Khutor ve diğer dağ işletmelerinin biletleri aynı değildir; teleferik, patika, kar ve son inişi ilgili işletmeden kontrol edin."], ["Olimpiyat Parkı ve Sirius", "Büyük alanı bisiklet/servisle gezin; etkinlik, güvenlik ve akşam gösterisi saatini resmî kaynaktan doğrulayın."]],
    areas: [["Soçi Merkez", "Arboretum, liman ve şehir plajlarına yakın; dağ için uzun transfer gerekir."], ["Adler, Sirius veya Krasnaya Polyana", "Havalimanı/park, kıyı ya da dağ odağına göre üç farklı üs; aralarındaki süreyi hesaplayın."]], foods: [["Kafkas mutfağı", "Khachapuri, khinkali ve ızgaralarda peynir, et türü ve porsiyonu sorun; bölgesel çeşitleri tek tarif sanmayın."], ["Karadeniz balığı ve meyvesi", "Mevsimlik balığın türü/menşei ile pazardaki yerel ürünün fiyatını işlem öncesi netleştirin."]], dayTrips: [["Agura Şelaleleri ve Akhun", "Patika, sıcak, su seviyesi ve seyir kulesi erişimini aynı gün kontrol edin; uygun ayakkabı taşıyın."], ["Abhazya sınırı çevresi", "Uluslararası/siyasi sınır koşulları değişkendir; resmî dışişleri ve sınır kurallarını doğrulamadan geçiş planlamayın."]], caution: "Sınır ve askerî alanlara yaklaşmayın; harita kestirmesine güvenmeyin. Karadeniz'de yalnız izinli plaj/bayrak koşulunda yüzün, dağda teleferik veya patika kapanışını aşmayın."
  },
  {
    city: "Kaliningrad", countryCode: "RU", focus: "Baltık kıyısı, Königsberg mirası ve Kuron Dili", lede: "Rusya'nın Baltık kıyısındaki eksklavında Königsberg tarihini Sovyet mirası, kehribar kültürü ve kumul koruma alanlarıyla birleştiren bölge.", days: "4–6 gün", arrival: "KGD · Kaliningrad South/North", local: "Otobüs, bölgesel tren, tramvay ve kontrollü araç", best: "Mayıs–Haziran · Ağustos–Eylül", timezone: "UTC+2", pulse: "Kaliningrad şehir ile oblastı ayırarak planlanmalıdır. Katedral ve müzeler bir-iki gün; Zelenogradsk, Svetlogorsk ve Kuron Dili ayrı kıyı günleridir.",
    sights: [["Königsberg Katedrali ve Kant Adası", "Kant müzesi, org konseri ve ada yürüyüşünü resmî saatle eşleştirin; etkinlik bileti ayrı olabilir."], ["Amber Müzesi", "Kehribarın jeolojisi, bölgesel sanayi ve tasarımını görün; alışverişte gerçeklik belgesi isteyin."], ["Kuron Dili", "Milli parkın kumul, orman ve kuş istasyonlarını yalnız açık güzergâhta gezin; sınır ve koruma bölgesi kurallarını okuyun."]],
    areas: [["Merkez ve Kant Adası", "Müze, tramvay ve ilk ziyaret için işlevsel; tarihî doku parçalıdır."], ["Zelenogradsk veya Svetlogorsk", "Baltık plajı ve kıyı ritmi için tren bağlantılı alternatif üsler."]], foods: [["Baltık balığı", "Ringa, tütsülenmiş balık ve stroganina benzeri ürünlerde tazelik, saklama ve türü sorun."], ["Königsberg klops", "Kapari soslu köftenin et ve süt içeriğini sorun; bölgesel tarih anlatısıyla deneyin."]], dayTrips: [["Zelenogradsk", "Trenle kolay sahil kasabası; plaj bayrağı, kedi temalı turistikleşme ve sezon kalabalığını hesaba katın."], ["Svetlogorsk ve Yantarny", "Spa mimarisi ile kehribar kıyısını tren/otobüsle bağlayın; maden/üretim alanına izinsiz girmeyin."]], caution: "Eksklava kara yoluyla ulaşım Litvanya/Polonya transit vizesi ve güncel sınır düzenine bağlıdır; uçuşu da resmî kanaldan doğrulayın. Sınır, liman ve askerî tesisi fotoğraflamayın; Kuron Dili'nde kumula çıkmayın."
  },
  {
    city: "Murmansk", countryCode: "RU", focus: "Arktik şehir, kuzey ışıkları ve Kola kıyıları", lede: "Kuzey Kutup Dairesi ötesinde liman tarihini tundra, uzun kutup gecesi, gece yarısı güneşi ve Kola Yarımadası seferleriyle birleştiren şehir.", days: "4–6 gün", arrival: "MMK · Murmansk tren istasyonu", local: "Otobüs, taksi ve lisanslı tur transferi", best: "Kuzey ışığı için Eylül–Mart · açık doğa için Haziran–Ağustos", timezone: "UTC+3", pulse: "Murmansk'ta doğa deneyimi şehirden bağımsız değildir: hızla değişen hava, karanlık, yol durumu ve sınır bölgesi kuralları lisanslı yerel planı gerekli kılar.",
    sights: [["Alyosha Anıtı", "Şehir ve Kola Körfezi manzarasını savaş anıtının bağlamına saygıyla görün; rüzgâr ve buz için uygun katman taşıyın."], ["Lenin Nükleer Buzkıranı", "Müze gemi turları saatli, güvenlik kontrollü ve kapasitelidir; yalnız resmî işletme gününü kullanın."], ["Kuzey ışığı ve tundra", "Aurora garanti değildir; bulut, güneş aktivitesi ve güvenli yol için lisanslı küçük grup/operatör ile esnek gece planlayın."]],
    areas: [["Şehir merkezi", "Tren, müze, restoran ve hava kötü olduğunda pratik ana üs."], ["Kola Körfezi çevresi", "Manzara için uygun ama ulaşım, rüzgâr ve liman güvenliği nedeniyle yalnız izinli noktalar seçilmeli."]], foods: [["Arktik balık ve deniz ürünleri", "Morina, halibut ve deniz kestanesinde tazelik, sürdürülebilirlik ve soğuk zinciri sorun."], ["Kuzey meyveleri", "Cloudberry/lingonberry reçeli ve çayını deneyin; yabani ürünü koruma alanında izinsiz toplamayın."]], dayTrips: [["Teriberka", "Yol kapanışı, fırtına ve uzun transfer nedeniyle lisanslı araç, tam gün ve iptal yedeği gerekir."], ["Khibiny", "Kirovsk çevresinde kayak/yürüyüş ayrı konaklama, çığ raporu ve uzman rehber isteyen bir rota uzatmasıdır."]], caution: "Kola Yarımadası'nda sınır/kapalı bölge izinleri ve kontrol noktaları olabilir; resmî rota dışında ilerlemeyin. Aurora için yol kenarında kontrolsüz durmayın, liman/askerî tesisi fotoğraflamayın, aşırı soğukta yalnız yürümeyin."
  },
  {
    city: "Baykal Gölü", countryCode: "RU", focus: "Irkutsk, Olkhon ve dünyanın derin gölünde doğa rotası", lede: "Sibirya'nın büyük tatlı su gölünü Irkutsk ahşap mimarisi, Listvyanka kıyısı, Olkhon bozkırı ve mevsimsel buz deneyimiyle birleştiren dev bölge.", days: "7–10 gün", arrival: "IKT · Irkutsk tren istasyonu", local: "Tren, lisanslı minibüs/transfer, feribot ve yürüyüş", best: "Haziran–Eylül · güvenli buz sezonu için Şubat–Mart", timezone: "UTC+8", pulse: "Baykal tek nokta değildir. Irkutsk–Listvyanka kısa giriş; Olkhon, doğu kıyısı ve Circum-Baikal birbirinden uzak ayrı rotalardır. En az bir alt bölge seçin.",
    sights: [["Irkutsk ve Listvyanka", "Dekabrist evleri ile ahşap mahalleyi şehirde; göl müzesi ve kıyıyı Listvyanka'da ayrı günlere bölün."], ["Olkhon Adası", "Feribot/buz yolu ve Khuzhir transferi uzun ve mevsime bağlıdır; kayıtlı araç, konaklama ve yedek gün kullanın."], ["Circum-Baikal Demiryolu", "Turistik tren/tekne işletmesi mevsimliktir; başlangıç, bitiş, yemek ve dönüşü resmî paketten okuyun."]],
    areas: [["Irkutsk", "Uçuş/tren, müze ve ikmal için zorunlu denebilecek ulaşım üssü."], ["Listvyanka veya Khuzhir", "Kolay kısa göl erişimi ya da daha uzak Olkhon deneyimi için iki farklı konaklama seçeneği."]], foods: [["Omul", "Baykal'ın simgesel balığında av/satış koruma kuralları değişebilir; yalnız yasal ve belgeli ürünü, türünü sorarak alın."], ["Buryat buuz", "Buharda mantının et/suyu sıcak olabilir; içeriği ve doğru yeme biçimini yerel lokantada sorun."]], dayTrips: [["Taltsy", "Irkutsk–Listvyanka hattındaki açık hava müzesini otobüs/transfer ve mevsim saatiyle ekleyin."], ["Arshan", "Sayan eteklerindeki kaplıca ve yürüyüşler Baykal'dan ayrı uzun kara rotasıdır; en az iki gece düşünün."]], caution: "Resmî güvenlik ölçümü ve lisanslı yerel rehber olmadan göl buzuna araçla ya da yürüyerek çıkmayın; çatlak ve akıntı görünmez olabilir. Çöp bırakmayın, deterjan kullanmayın ve kutsal Şaman/Buryat alanlarına saygı gösterin."
  },
  {
    city: "Vladivostok", countryCode: "RU", focus: "Pasifik limanı, köprüler ve Primorye doğası", lede: "Altın Boynuz çevresinde dik sokakları, denizcilik tarihi, Asya etkili mutfağı ve Russky Adası manzaralarıyla Rusya'nın Pasifik kapısı.", days: "4–6 gün", arrival: "VVO · Vladivostok tren istasyonu", local: "Otobüs, tren, taksi, yürüyüş ve lisanslı tekne", best: "Haziran sonu–Ekim", timezone: "UTC+10", pulse: "Vladivostok'un harita mesafeleri dik yokuş ve koylar nedeniyle yanıltır. Merkez yürüyüşünü Russky Adası ile aynı güne sıkıştırmadan, sis ve Pasifik hava yedeği bırakın.",
    sights: [["Altın Köprü ve merkez tepeleri", "Köprü manzarasını izinli seyir noktalarından görün; yol/altyapı üzerinde tehlikeli fotoğraf için durmayın."], ["Russky Adası", "Primorsky Akvaryumu, üniversite kıyısı ve burun rotalarından birini seçin; bazı kıyı/askerî alanlar kısıtlı olabilir."], ["Vladivostok Kalesi Müzesi", "Tabyalar farklı noktalara yayılır; yalnız resmî açık müze alanlarını ziyaret edin ve kapalı tünele girmeyin."]],
    areas: [["Svetlanskaya ve Millionka", "Tren, liman, tarihî merkez ve restoranlara yürüme kolaylığı yüksek."], ["Egersheld ve Russky yönü", "Deniz manzarası veya ada erişimi için ulaşım süresi daha uzun, sakin alternatifler."]], foods: [["Primorye deniz ürünleri", "Tarak, yengeç ve deniz hıyarında mevsim, ağırlık/fiyat ve yasal kaynağı işlemden önce netleştirin."], ["Kore ve Uzak Doğu etkileri", "Kimchi, erişte ve deniz ürünlü tabaklarda acılık, alerjen ve çiğ ürün riskini sorun."]], dayTrips: [["Primorye safari/doğa parkları", "Hayvan refahı, lisans, besleme ve transfer koşulunu değerlendirerek yalnız güvenilir resmî tesis seçin."], ["Ussuriysk", "Trenle bölgesel tarih ve Kore diasporası izleri için ayrı gün; sınır yönündeki özel bölgelerden uzak durun."]], caution: "Liman, donanma, askerî ve sınır altyapısını fotoğraflamayın; drone kullanmayın. Sis, tayfun ve rip akıntısı uyarısında kıyı/tekne planını iptal edin; deniz ürününde soğuk zincir ve kabuklu alerjisini ciddiye alın."
  },
];

export const russiaGuides = makeRegionalGuides(profiles);
