import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Belgrad", countryCode: "RS", focus: "Kalemegdan, nehir mahalleleri ve yakın tarih", lede: "Sava ile Tuna'nın birleştiği noktada Roma'dan Yugoslavya'ya uzanan katmanları, güçlü gece hayatı ve yaratıcı mahallelerle buluşturan başkent.", days: "4–5 gün", arrival: "BEG · Beograd Centar/Prokop", local: "Otobüs, tramvay, troleybüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Belgrad gösterişli bir kartpostal kentinden çok, tarih katmanlarını gündelik hayatın içinde açan enerjik bir metropoldür. Kalemegdan, Dorćol, Zemun ve Novi Beograd birbirinden farklı dört şehir hissi verir.",
    sights: [["Kalemegdan ve Belgrad Kalesi", "Surlar, askerî müze, kiliseler ve nehir manzarası için yarım gün ayırın; açık alan etkinliği ve restorasyon bariyerlerini kontrol edin."], ["Aziz Sava Katedrali ve Vračar", "İç mozaikleri ibadet saatine saygıyla görün; Nikola Tesla Müzesi'nin sınırlı kapasiteli turunu ayrı saatte planlayın."], ["Yugoslavya Müzesi ve Novi Beograd", "20. yüzyıl tarihini brutalist mimari ve Sava kıyısıyla bağlayın; müze kapsamını propaganda/dekor değil tarihsel bağlamla okuyun."]],
    areas: [["Stari Grad ve Dorćol", "İlk ziyaret, kale, müze, kafe ve akşam için yürünebilir merkez; hafta sonu gürültülü olabilir."], ["Vračar, Zemun ve Novi Beograd", "Yerel lokanta/konut ritmi, Tuna kıyısı veya modernist mimari için üç farklı ulaşım bağlantılı alternatif."]], foods: [["Ćevapi ve pljeskavica", "Et türü, gramaj ve kaymak/soğan eşlikçisini sorun; dumanlı ızgara ile ağır porsiyonu paylaşın."], ["Burek ve kafana kültürü", "Sabah bureğini yoğurtla deneyin; kafanada canlı müzik, kuver ve porsiyon ücretini siparişten önce netleştirin."]], dayTrips: [["Novi Sad", "Hızlı trenle kolay görünse de Petrovaradin, merkez ve akşam için ayrı tam gün veya iki gece daha iyidir."], ["Avala", "Kule ve anıt için şehir otobüsü/transfer, sis ve son dönüşü kontrol edin; askerî/kapalı alana girmeyin."]], caution: "Siyasi gösteri ve kalabalıklardan uzak durun; 1990'lar, Kosova ve savaş hafızası üzerine hassas dil kullanın. Lisanssız taksiye binmeyin, doğru tren garını bilette kontrol edin ve gece nehir kulübünden dönüşü önceden planlayın."
  },
  {
    city: "Novi Sad", countryCode: "RS", focus: "Petrovaradin, Tuna ve Vojvodina kültürü", lede: "Petrovaradin Kalesi'nin karşısında düzenli Orta Avrupa merkezini çok dilli Vojvodina mirası, Tuna parkları ve yaratıcı sahneyle birleştiren şehir.", days: "2–3 gün", arrival: "Novi Sad tren/otobüs istasyonu", local: "Otobüs, bisiklet ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Novi Sad yalnız EXIT Festival alanı değildir; Sırp, Macar, Slovak ve diğer Vojvodina topluluklarının mimari, yemek ve dil izleri merkezi zenginleştirir.",
    sights: [["Petrovaradin Kalesi", "Üst şehri, saat kulesini ve stüdyo alanlarını yürüyün; yeraltı tüneline yalnız resmî rehberli turla girin."], ["Trg Slobode ve Zmaj Jovina", "Belediye binası, Name of Mary Kilisesi ve yaya caddelerini galeriler ile pazar molasıyla birleştirin."], ["Tuna kıyısı ve Štrand", "Plaj, park ve bisiklet rotasını su seviyesi, yüzme bayrağı ve sezon hizmetleriyle planlayın."]],
    areas: [["Stari Grad", "Meydan, kafe, müze ve gece için kompakt ilk üs."], ["Petrovaradin ve Liman", "Kale atmosferi ya da nehir/yerel yaşam için merkezden köprü veya otobüs bağlantılı alternatifler."]], foods: [["Vojvodina mutfağı", "Gulaş, hamur işi ve paprika etkili yemeklerde bölgesel Macar/Orta Avrupa katmanlarını arayın."], ["Fruška Gora şarapları", "Riesling, Bermet ve yerel üretici tadımını randevu ve sürücülü dönüşle planlayın."]], dayTrips: [["Sremski Karlovci", "Barok merkez, patrikhane ve bağlar için tren/otobüsle kolay; tadım sonrası sürmeyin."], ["Fruška Gora", "Manastır ve işaretli yürüyüş için bir alt bölge seçin; seyrek ulaşım, kene ve yangın duyurusunu kontrol edin."]], caution: "EXIT haftasında konaklama, köprü ve ulaşım düzeni ciddi değişir. Tuna'da yalnız izinli alanda yüzün; Petrovaradin tünellerine izinsiz girmeyin, manastırlarda kıyafet/fotoğraf kuralına uyun."
  },
  {
    city: "Niş", countryCode: "RS", focus: "Roma mirası, Osmanlı kalesi ve savaş hafızası", lede: "Konstantin'in doğduğu kentte Roma kalıntılarını Osmanlı kalesi, canlı güney mutfağı ve zorlayıcı 20. yüzyıl hafıza mekânlarıyla birleştiren şehir.", days: "2–3 gün", arrival: "INI · Niš tren/otobüs istasyonu", local: "Otobüs, taksi ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Niş'in Roma, Osmanlı, Balkan savaşları ve İkinci Dünya Savaşı katmanları birbirinin yerine geçmez; her mekânı kendi tarihsel bağlamında okumak gerekir.",
    sights: [["Niş Kalesi", "Osmanlı surlarını arkeolojik kalıntı, park ve açık hava etkinlikleriyle gezin; festival kurulumu erişimi değiştirebilir."], ["Mediana", "Konstantin dönemi villası ve mozaikleri için güncel açılış/restorasyon durumunu kontrol edin; şehir dışında ulaşım planlayın."], ["Kafatası Kulesi ve Kızılhaç Kampı", "İnsan kalıntısı ve toplama kampı hafızasında sessiz, saygılı davranın; iki alanı eğlence rotası gibi sunmayın."]],
    areas: [["Merkez ve kale çevresi", "Müze, lokanta ve nehir yürüyüşüne yakın, ilk ziyaret için işlevsel."], ["Medijana", "Arkeolojik alan, park ve daha sakin konaklama için otobüs/taksi bağlantılı alternatif."]], foods: [["Niş ızgarası", "Pljeskavica, ćevapi ve sakatat çeşitlerinde et, gramaj ve acı sosu sorun; porsiyonlar büyüktür."], ["Balkan böreği", "Peynirli veya etli bureği sabah taze fırından alın; et ve süt içeriğini açıkça sorun."]], dayTrips: [["Sićevo Kanyonu", "Manzara ve yürüyüş için yol, tünel, hava ve dönüş aracını önceden kurun; demiryolu/karayolunda kestirme yapmayın."], ["Nişka Banja", "Kaplıca parkı ve kısa yürüyüş için yerel otobüs; tedavi hizmeti ile turistik spa'yı ayırın."]], caution: "Kafatası Kulesi ve kamp alanında selfie/dekor dilinden kaçının. Kanyonda ray ve araç yoluna girmeyin; yaz sıcağında su ve gölge planı, gece takside resmî çağrı kullanın."
  },
  {
    city: "Subotica", countryCode: "RS", focus: "Art Nouveau, çok dilli Vojvodina ve Palić Gölü", lede: "Macar Secession cepheleri, çok kültürlü sınır kimliği, sinagog ve Palić'in göl peyzajıyla Sırbistan'ın farklı yüzünü gösteren kuzey şehri.", days: "2–3 gün", arrival: "Subotica tren/otobüs istasyonu", local: "Otobüs, bisiklet ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Subotica'da Sırpça ve Macarca kamusal yaşam yan yanadır; şehir mimarisi Budapeşte ile Vojvodina arasındaki kültürel akışı görünür kılar.",
    sights: [["Belediye Binası", "Renkli çatı, vitray ve kuleyi yalnız resmî rehberli saatle görün; toplantı/etkinlik erişimini kontrol edin."], ["Subotica Sinagogu", "Restore edilmiş Secession yapısında cemaat tarihini saygılı ziyaretle öğrenin; bilet ve dinî gün saatini doğrulayın."], ["Palić Gölü", "Su Kulesi, Büyük Teras ve parkı bisiklet/otobüsle gezin; su kalitesi ile izinli yüzme alanını güncel kaynaktan kontrol edin."]],
    areas: [["Centar", "Belediye binası, sinagog, kafe ve istasyona yürüyüş için kompakt üs."], ["Palić", "Göl, park ve daha sakin konaklama için şehirden otobüs/bisiklet bağlantılı alternatif."]], foods: [["Vojvodina–Macar mutfağı", "Paprika, gulaş ve hamur işlerinde acılık, et ve porsiyonu sorun."], ["Yerel şarap ve tatlı", "Kadarka, Riesling ve Dobos benzeri tatlıları ölçülü tadın; bağ dönüşünü planlayın."]], dayTrips: [["Sombor", "Ağaçlı bulvar, galeri ve sakin merkez için otobüs/trenle ayrı gün."], ["Ludaš Gölü", "Sulak alan kuş gözlemi için ziyaret merkezi, sezon ve koruma rotasını önceden doğrulayın."]], caution: "Sınır bölgesinde pasaportu yanınızda taşıyın; Macaristan'a geçişi Schengen belgesi olmadan planlamayın. Göl ve sulak alanda bariyeri aşmayın, sinagogda kıyafet/fotoğraf kuralına uyun."
  },
  {
    city: "Zlatibor", countryCode: "RS", focus: "yayla yürüyüşleri, mağaralar ve köy rotaları", lede: "Yuvarlak yayla peyzajını çam ormanları, geleneksel köyler, mağaralar ve dört mevsim gelişen tatil altyapısıyla birleştiren dağ bölgesi.", days: "3–5 gün", arrival: "Užice üzerinden otobüs/transfer", local: "Otobüs, taksi, yürüyüş ve teleferik", best: "Mayıs–Ekim · kar için Ocak–Mart", pulse: "Zlatibor merkezi yoğun ve yapılaşmış olabilir; bölgenin asıl gücü Tornik, Stopića, Sirogojno ve kırsal peyzajı ayrı günlere yaymaktır.",
    sights: [["Gold Gondola ve Tornik", "Uzun teleferikte hava, rüzgâr, bakım ve son dönüşü kontrol edin; zirve koşulu merkezden farklıdır."], ["Stopića Mağarası", "Kask/rehber ve kaygan basamak koşuluyla gezin; yüksek su veya bakım kapanışına uyun."], ["Sirogojno", "Açık hava müzesinde ahşap ev, tekstil ve köy yaşamını yerel üreticiyle bağlama oturtun."]],
    areas: [["Zlatibor merkez", "Restoran, otobüs ve teleferik için pratik; kalabalık ve yapılaşma yoğundur."], ["Ribnica ve Sirogojno yönü", "Doğa/köy odağı için araç veya önceden ayarlanmış transfer gerektiren sakin alternatif."]], foods: [["Komplet lepinja", "Yumurta, kaymak ve et suyuyla ağır bir yerel kahvaltıdır; içeriği ve porsiyonu sorun."], ["Pršuta ve süt ürünleri", "Kurutulmuş et ile kajmakta üretici, soğuk zincir ve et türünü doğrulayın."]], dayTrips: [["Mokra Gora", "Šargan Eight treni ve Drvengrad için resmî sefer, saatli bilet ve uzun transferi planlayın."], ["Uvac", "Menderes seyri ve tekne için Zlatibor'dan uzun yol, lisanslı operatör ve hava yedeği gerekir."]], caution: "Merkez pazarlamasını bütün bölgenin doğa koşulu sanmayın. Teleferik/mağara kapanışını aşmayın; pršuta ve süt ürününü gümrük/soğuk zincir kuralı olmadan taşımayın."
  },
  {
    city: "Tara Milli Parkı", countryCode: "RS", focus: "Drina manzaraları, orman ve yaban hayatı", lede: "Drina Kanyonu üzerindeki yoğun ormanları seyir noktaları, göller ve hassas boz ayı habitatıyla koruyan batı Sırbistan milli parkı.", days: "3–5 gün", arrival: "Bajina Bašta üzerinden araç/transfer", local: "Araç, lisanslı transfer, bisiklet ve yürüyüş", best: "Mayıs–Ekim", pulse: "Tara tek bir Banjska Stena fotoğrafı değildir; Mitrovac, Kaluđerske Bare, Perućac ve Zaovine farklı yönlerde yer alır. Tek konaklama üssü ve iki ana rota seçin.",
    sights: [["Banjska Stena", "İşaretli patikadan seyir noktasına gidin; sis, buz, ormancılık ve yangın kapanışını park duyurusundan kontrol edin."], ["Zaovine Gölü", "Seyir ve kıyı yürüyüşünü yol durumuyla planlayın; baraj/enerji altyapısında kısıtlı bölgeye girmeyin."], ["Perućac ve Drina", "Göl teknesi, Vrelo nehri ve kıyıyı lisanslı işletme, can yeleği ve su seviyesiyle planlayın."]],
    areas: [["Mitrovac", "Ziyaretçi merkezi ve aile rotaları için en işlevsel park üssü."], ["Kaluđerske Bare veya Zaovine", "Konaklama/kolay erişim ya da daha uzak göl-doğa odağı için iki farklı alternatif."]], foods: [["Dağ lokantaları", "Fasulye, ızgara ve mısır ekmeğinde et suyu/porsiyonu sorun; çalışma saatini önceden teyit edin."], ["Orman ürünleri", "Yaban mersini, mantar ve balı yalnız yasal yerel üreticiden alın; koruma alanında izinsiz toplamayın."]], dayTrips: [["Bajina Bašta", "Drina üzerindeki ev manzarası, ikmal ve park giriş/çıkış günü için pratik kasaba."], ["Višegrad", "Bosna-Hersek sınırı ötesindedir; pasaport, araç belgesi, sigorta ve giriş hakkını doğrulamadan eklemeyin."]], caution: "Boz ayı habitatında yiyeceği açık bırakmayın, yavruya yaklaşmayın ve gece yalnız yürümeyin. Çevrimdışı harita, su ve katman taşıyın; bariyer/kapalı orman yolunu aşmayın."
  },
  {
    city: "Kopaonik", countryCode: "RS", focus: "kayak, yüksek yayla ve milli park patikaları", lede: "Sırbistan'ın büyük kayak alanını yüksek dağ çayırları, panoramik yürüyüşler, spa üsleri ve mevsimsel doğa deneyimleriyle birleştiren bölge.", days: "4–6 gün", arrival: "Kraljevo/Niş üzerinden araç veya transfer", local: "Shuttle, teleferik ve yürüyüş", best: "Kayak için Ocak–Mart · yürüyüş için Haziran–Eylül", pulse: "Kopaonik'te Konaci kayak merkezi ile Brzeće alt istasyonu farklı konaklama/ulaşım kararlarıdır. Pist günü ve milli park yürüyüşünü aynı ekipmanla değerlendirmeyin.",
    sights: [["Kayak alanı", "Pist, lift, kar, rüzgâr ve skipass kapsamını resmî işletmeden günlük kontrol edin; seviyenize uygun rota seçin."], ["Pančićev vrh", "Yürüyüş/teleferik erişimini hava ve kısıtlı alan tabelalarıyla planlayın; zirve çevresinde izin dışına çıkmayın."], ["Nebeske Stolice", "Arkeoloji ve yüksek yayla manzarasına yalnız işaretli rotayla gidin; fırtına ve gün ışığı dönüşünü hesaba katın."]],
    areas: [["Konaci", "Piste yürüyüş ve restoran için en pratik; yüksek sezon pahalı/kalabalık."], ["Brzeće", "Alt teleferik ve daha sakin konaklama için transfer/lift saatine bağlı alternatif."]], foods: [["Dağ yemekleri", "Kajmak, et güveci ve hamur işlerinde ağır porsiyonu paylaşın; et/süt içeriğini sorun."], ["Sıcak içecek ve rakija", "Rakijayı rakım, soğuk ve kayakla birleştirmeyin; su içip ölçülü tüketin."]], dayTrips: [["Jošanička Banja", "Kaplıca köyüne araç/taksiyle dinlenme günü; tedavi suyu için sağlık önerisi alın."], ["Studenica Manastırı", "Uzun dağ yolu, ibadet ve açılış saatini planlayarak ayrı gün ayırın."]], caution: "Pist dışı kayak, çığ raporu ve uzman rehber olmadan yapılmamalı; sis ve rüzgârda lift kapanışına uyun. Kar zinciri, kış lastiği ve park koşulunu yola çıkmadan doğrulayın."
  },
  {
    city: "Demir Kapı", countryCode: "RS", focus: "Tuna kanyonu, Roma mirası ve Đerdap Milli Parkı", lede: "Tuna'nın Karpatlar arasından daraldığı büyük kanyonu Roma sınır mirası, tarih öncesi Lepenski Vir ve tekne manzaralarıyla birleştiren doğu rotası.", days: "3–5 gün", arrival: "Belgrad'dan Donji Milanovac/Kladovo otobüs veya araç", local: "Araç, bölgesel otobüs, yürüyüş ve lisanslı tekne", best: "Mayıs–Haziran · Eylül–Ekim", pulse: "Demir Kapı tek seyir noktası değildir; Golubac, Lepenski Vir, Donji Milanovac, Đerdap yürüyüşleri ve Kladovo yüzlerce kilometrelik nehir hattına yayılır.",
    sights: [["Golubac Kalesi", "Saatli bilet, kule zorluk seviyesi ve yaş/boy koşulunu okuyun; bazı kuleler rehber/ekipman gerektirir."], ["Lepenski Vir", "Tarih öncesi yerleşimi müze anlatısıyla görün; Donji Milanovac bağlantısı ve çalışma saatini kontrol edin."], ["Đerdap kanyonları", "Ploče veya Veliki Štrbac yürüyüşünde park rehberi/izin, hava, su ve gün ışığı planı yapın."]],
    areas: [["Donji Milanovac", "Lepenski Vir, park ve tekne için dengeli orta rota üssü."], ["Golubac veya Kladovo", "Batıdaki kale başlangıcı ya da doğudaki Roma/nehir rotası için iki ayrı uç üs."]], foods: [["Tuna balığı", "Yayın, sazan ve balık çorbasında tür, menşe, kılçık ve koruma/mevsim kuralını sorun."], ["Vlah–Doğu Sırbistan mutfağı", "Mısır unu, peynir ve yavaş pişmiş etlerde bölgesel çeşitleri küçük lokantada deneyin."]], dayTrips: [["Felix Romuliana", "Gamzigrad UNESCO Roma sarayı Demir Kapı'dan uzun kara günüdür; açılış ve araç planı gerekir."], ["Romanya kıyısı", "Karşı kıyı AB/Schengen sınırıdır; geçiş belgesi ve araç sigortası olmadan tekne/karayolu planı yapmayın."]], caution: "Tuna'da uluslararası sınır ve hidroelektrik altyapısı bulunur; yalnız izinli tekne rotası kullanın ve tesisi/drone'u kısıtlı alana yöneltmeyin. Kanyon yürüyüşünde park izni ve rehber şartını atlamayın."
  },
];

export const serbiaGuides = makeRegionalGuides(profiles);
