import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Ljubljana", countryCode: "SI", focus: "nehir kıyısı, Plečnik mimarisi ve yeşil başkent", lede: "Ljubljanica kıyısında Plečnik'in köprü ve pazarlarını kale manzarası, araçsız merkez, çağdaş kültür ve yakın doğa rotalarıyla birleştiren kompakt başkent.", days: "3–4 gün", arrival: "LJU · Ljubljana tren/otobüs istasyonu", local: "Otobüs, bisiklet ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Ljubljana küçük merkezine rağmen yalnız yarım günlük bir mola değildir; Plečnik mimarisi, pazar, Tivoli, Metelkova ve bataklık peyzajı farklı şehir katmanları sunar.",
    sights: [["Ljubljana Kalesi", "Füniküler veya yürüyüşle çıkın; sergi, kule bileti, hava ve son inişi kontrol edin."], ["Plečnik rotası", "Üçlü Köprü, Merkez Pazar, Ulusal ve Üniversite Kütüphanesi ile nehir kıyısını kullanım bağlamında gezin."], ["Tivoli ve müzeler", "Parkı Ulusal Galeri, modern sanat veya çağdaş tarih kurumlarından biriyle birleştirin; çalışma gününü doğrulayın."]],
    areas: [["Eski şehir ve merkez", "Araçsız gezi, pazar ve akşam için en kolay; hafta sonu pahalı ve gürültülü olabilir."], ["Trnovo, Krakovo veya Šiška", "Plečnik/yerel yaşam ya da yaratıcı mahalle için bisiklet/otobüslü alternatifler."]], foods: [["Štruklji ve jota", "Hamur rulosunun tatlı/tuzlu dolgusunu; fasulye-lahana güvecinde et suyu ve sosis içeriğini sorun."], ["Pazar ve gostilna", "Mevsim sebzesi, peynir ve nehir balığında menşe/alerjeni netleştirin; servis ücretini kontrol edin."]], dayTrips: [["Škofja Loka", "Otobüsle Orta Çağ merkezi ve kısa tepe yürüyüşü; müze/son dönüş saatini kontrol edin."], ["Velika Planina", "Teleferik/servis, hava, çoban yerleşimi sezonu ve işaretli patikayı aynı gün doğrulayın."]], caution: "Bisiklet yolunda yaya olarak çizgiye dikkat edin; kilit ve ışık kullanın. Metelkova'da kişisel sınıra saygı gösterin; nehir taşkını, protesto veya etkinlikte kapalı güzergâhı aşmayın."
  },
  {
    city: "Bled Gölü", countryCode: "SI", focus: "ada kilisesi, kale ve Julian Alpleri", lede: "Julian Alpleri önünde zümrüt gölü ada kilisesi, kayalık kale, geleneksel pletna tekneleri ve çevre yürüyüşleriyle birleştiren Slovenya'nın simge rotası.", days: "2–4 gün", arrival: "Lesce-Bled/Bled Jezero istasyonu · Ljubljana otobüsü", local: "Otobüs, yürüyüş, bisiklet ve pletna", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Bled tek fotoğraf noktası değildir; göl çevresi, kale, ada, Ojstrica/Osojnica ve yakın Radovljica günün farklı saatlerine dağılır. Yoğun saatte araç yerine yürüyüş/otobüs tercih edin.",
    sights: [["Bled Kalesi", "Dik çıkış, müze ve manzara için bilet/saat planlayın; uçurum kenarında bariyer dışına çıkmayın."], ["Bled Adası", "Pletna veya kiralık tekne koşullarını, can yeleğini, dönüş saatini ve kilise biletini netleştirin."], ["Ojstrica/Osojnica", "Kısa ama dik/çamurlu patikaya sağlam ayakkabı ve gün ışığıyla çıkın; fırtınada devam etmeyin."]],
    areas: [["Bled merkezi ve doğu kıyısı", "Otobüs, restoran ve çoğu hizmete yakın; kalabalık ve fiyat yüksek."], ["Mlino, Zaka veya Radovljica", "Ada teknesi/doğa ya da daha yerel tarih üssü için farklı ulaşım alternatifleri."]], foods: [["Kremna rezina", "Kremalı dilimi paylaşın; süt/yumurta ve porsiyonu sorun."], ["Gorenjska mutfağı", "Karabuğday, sosis, peynir ve mantarda et/süt içeriği ile güvenilir üreticiyi doğrulayın."]], dayTrips: [["Vintgar", "Saatli giriş, shuttle/tek yön çıkış, su seviyesi ve sezon kapanışını resmî kaynaktan planlayın."], ["Bohinj", "Bled'den aynı gün mümkün olsa da göl ve teleferik için ayrı konaklama daha dengelidir."]], caution: "Göl kıyısında yalnız izinli alanda yüzün; kuşları beslemeyin. Vintgar ve seyir patikasında kapanışı aşmayın, yoğun sezonda yol kenarına park etmeyin ve tekne hava kararına uyun."
  },
  {
    city: "Bohinj", countryCode: "SI", focus: "Triglav gölü, şelaleler ve yüksek dağ erişimi", lede: "Triglav Milli Parkı içinde büyük buzul gölünü Savica Şelalesi, Vogel teleferiği, dağ köyleri ve ciddi Alp patikalarıyla birleştiren doğa üssü.", days: "4–6 gün", arrival: "Bohinjska Bistrica tren istasyonu · Ljubljana/Bled otobüsü", local: "Otobüs, shuttle, tekne, bisiklet ve yürüyüş", best: "Haziran–Eylül · sakin dönem Mayıs/Ekim", pulse: "Bohinj tek göl kıyısı değildir; Ribčev Laz, Ukanc, Stara Fužina ve Bohinjska Bistrica farklı rota başlangıçlarıdır. Triglav zirvesi sıradan günübirlik gezi değildir.",
    sights: [["Bohinj Gölü", "Kıyı yürüyüşü/teknesini hava ve son seferle planlayın; yalnız izinli yüzme ve su sporu alanını kullanın."], ["Savica Şelalesi", "Basamaklı girişe otobüs/shuttle ve biletle gidin; yüksek su, buz veya bakım kapanışına uyun."], ["Vogel", "Teleferik ve yüksek rota için rüzgâr, son iniş, ayakkabı ve katman planı yapın; sisli havada işaretten çıkmayın."]],
    areas: [["Ribčev Laz veya Stara Fužina", "Göl/Mostnica erişimi ve köy atmosferi için pratik üsler."], ["Ukanc veya Bohinjska Bistrica", "Vogel/Savica yakınlığı ya da tren/market kolaylığı için iki farklı alternatif."]], foods: [["Bohinj peyniri", "Üretici, pastörizasyon ve soğuk zinciri sorun; yayla hayvanlarına yaklaşmayın."], ["Ajdovi žganci", "Karabuğday yemeğinde süt, domuz yağı ve et eşlikçisini netleştirin."]], dayTrips: [["Mostnica Kanyonu", "Giriş, su seviyesi ve Voje rotasını işaretli patikada planlayın; kenara yaklaşmayın."], ["Triglav", "Çok günlük yüksek dağ, kulübe rezervasyonu, kask/via ferrata deneyimi ve sigorta gerektirir; rehbersiz hafife almayın."]], caution: "Milli parkta kamp, ateş, drone ve bitki toplama kısıtlıdır. Fırtına/kar uyarısında yüksek rotaya çıkmayın; gölde motor/tekne ve yüzme kurallarına, shuttle park düzenine uyun."
  },
  {
    city: "Piran", countryCode: "SI", focus: "Venedik kıyısı, tuzlalar ve kısa Sloven sahili", lede: "Adriyatik'e uzanan yarımadada Venedik cephelerini Tartini Meydanı, sur manzarası, deniz kültürü ve Sečovlje tuzlalarıyla birleştiren kıyı kenti.", days: "2–4 gün", arrival: "Koper tren/otobüs bağlantısı · Trieste/LJU transferi", local: "Otobüs, yürüyüş ve bisiklet", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Piran'ın eski şehri küçük fakat Koper, Izola, Portorož ve tuzlalar kısa sahilin farklı katmanlarını açar. Araçsız merkez ve park sistemi konaklama kararını doğrudan etkiler.",
    sights: [["Tartini Meydanı", "Meydan, Venedik evi ve limanı sabah/akşam gezin; etkinlik ve kilise saatini kontrol edin."], ["Aziz George ve surlar", "Çan kulesi/sur manzarasına dik basamakla çıkın; rüzgâr ve bariyer kurallarına uyun."], ["Sečovlje Tuzlaları", "Ziyaretçi girişi, kuş sezonu, bisiklet rotası ve sıcaklığı park duyurusundan doğrulayın."]],
    areas: [["Piran eski şehir", "Atmosfer ve denize yürüyüş için ideal; araçsız, merdivenli ve yazın pahalı."], ["Portorož, Izola veya Koper", "Plaj/otel, balıkçı kasabası ya da tren/şehir hizmeti için otobüslü alternatifler."]], foods: [["İstria deniz ürünleri", "Levrek, kalamar ve midyede tür, menşe ve kilo/porsiyon fiyatını sorun."], ["Fritaja ve zeytinyağı", "Yumurta/ot yemeğinde peynir ve mevsim içeriğini; yağda üreticiyi doğrulayın."]], dayTrips: [["Koper ve Izola", "Sahil otobüsü/bisikletle iki kasabayı acele etmeden bağlayın; tünel ve bisiklet güvenliğine dikkat edin."], ["Trieste", "İtalya yönünde Schengen içi olsa da bilet/kimlik kontrolü olabilir; doğru istasyon ve son dönüşü doğrulayın."]], caution: "Eski şehre araç erişimini zorlamayın; resmî park-shuttle kullanın. Kayalık kıyıda fırtına ve kaygan zemine, tuzlalarda koruma bariyerine uyun; sınır yakınında kimliğinizi taşıyın."
  },
  {
    city: "Postojna ve Predjama", countryCode: "SI", focus: "Karst mağaraları, yeraltı treni ve kaya kalesi", lede: "Dinar Karstı'nın büyük mağara sistemini yeraltı treni, biyolojik miras ve uçurum ağzına kurulmuş Predjama Kalesi'yle birleştiren iç Slovenya rotası.", days: "2–3 gün", arrival: "Postojna tren/otobüs istasyonu", local: "Otobüs, shuttle, taksi ve yürüyüş", best: "Yıl boyu · yüzey için Nisan–Ekim", pulse: "Postojna günübirlik yapılabilir fakat mağaranın bilimsel bağlamı, Predjama ve yakın Škocjan'ı aceleye getirmemek için en az bir gece değerlidir. Mağara sıcaklığı yazdan bağımsızdır.",
    sights: [["Postojna Mağarası", "Saatli tur, yeraltı treni, yürüyüş mesafesi, 10°C civarı ortam ve fotoğraf kurallarını resmî kaynaktan okuyun."], ["Predjama Kalesi", "Mağara ağzındaki kaleyi shuttle/araç ve sesli turla gezin; mağara bölümü mevsimsel olabilir."], ["Vivarium", "Proteus ve karst biyolojisini hayvan refahı/koruma bağlamında görün; dokunma ve flaş yasağına uyun."]],
    areas: [["Postojna merkezi", "Tren, otobüs ve restoran için işlevsel; mağaraya yürüyüş mümkündür."], ["Predjama veya kırsal Karst", "Sessiz konaklama ve kale sabahı için araç/taksi gerektiren alternatif."]], foods: [["Karst mutfağı", "Jota, mantar ve et yemeklerinde et suyu/süt içeriğini sorun."], ["Kraški pršut", "Kurutulmuş ette hayvan türü, üretici ve soğuk zincir/gümrük kuralını kontrol edin."]], dayTrips: [["Škocjan Mağaraları", "Ayrı işletme ve ciddi basamaklı turdur; tren/otobüs, saatli rezervasyon ve fiziksel koşulu planlayın."], ["Lipica", "Lipizzaner mirasını resmî çiftlik turu, hayvan refahı ve ulaşım saatine göre gezin."]], caution: "Mağarada rehber grubundan ayrılmayın, oluşumlara dokunmayın ve katmanlı kıyafet kullanın. Yeraltı turu klostrofobi/erişilebilirlik açısından uygun olmayabilir; bileti yalnız resmî siteden alın."
  },
  {
    city: "Soča Vadisi", countryCode: "SI", focus: "turkuaz nehir, I. Dünya Savaşı ve açık hava sporları", lede: "Julian Alpleri'nden akan turkuaz Soča'yı rafting, şelaleler, Triglav patikaları ve I. Dünya Savaşı'nın Isonzo Cephesi hafızasıyla birleştiren vadi.", days: "5–7 gün", arrival: "Most na Soči tren istasyonu · Ljubljana/Nova Gorica otobüsü", local: "Otobüs, shuttle, araç, bisiklet ve yürüyüş", best: "Mayıs–Eylül", pulse: "Soča Vadisi Bovec, Kobarid, Tolmin ve Most na Soči arasında uzanır. Tek üs seçimi etkinliğe göre değişir; nehir sporu için Bovec, tarih/yürüyüş için Kobarid güçlüdür.",
    sights: [["Kobarid Müzesi ve tarih yolu", "Isonzo Cephesi'ni anma ve kaynak bağlamıyla gezin; siper/mağarada işaretli rotadan çıkmayın."], ["Kozjak ve Tolmin", "Şelale/kanyon giriş, tek yön akış, su seviyesi ve kaygan zemini resmî park kaynağından kontrol edin."], ["Soča rafting", "Lisanslı operatör, seviye, yaş, kask, can yeleği, su sıcaklığı ve sigorta kapsamını yazılı alın."]],
    areas: [["Bovec", "Rafting, Kanin ve üst vadi için en güçlü etkinlik üssü."], ["Kobarid veya Tolmin", "Tarih/yemek ya da festival-tren bağlantısı için daha sakin alternatifler."]], foods: [["Soča alabalığı", "Tür, menşe ve sürdürülebilirlik bilgisini sorun; koruma alanında kaçak av ürününden kaçının."], ["Kobarid štruklji", "Cevizli tatlıda süt, yumurta ve alerjeni netleştirin."]], dayTrips: [["Mangart", "Yüksek yol ve yürüyüşü açık/ücretli yol, kar, fırtına ve araç boyutuna göre planlayın."], ["Gorizia/Nova Gorica", "İki ülkeye yayılan şehir için kimlik, bisiklet ve tren/otobüs bağlantısını kontrol edin."]], caution: "Nehir buz gibi ve akıntılıdır; lisanssız spor/yüzme yapmayın. Eski savaş mühimmatına dokunmayın; fırtına, kaya düşmesi, teleferik veya yüksek yol kapanışına uyun."
  },
  {
    city: "Maribor", countryCode: "SI", focus: "Drava, bağ tepeleri ve doğu Slovenya", lede: "Drava kıyısındaki tarihî merkezi dünyanın en eski asması, Pohorje ormanları, çağdaş kültür ve Steiermark bağlarıyla birleştiren ikinci büyük şehir.", days: "3–4 gün", arrival: "Maribor tren/otobüs istasyonu", local: "Otobüs, bisiklet ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Maribor yalnız Ljubljana'dan kısa durak değildir; Lent kıyısı, bağ kültürü, savaş tarihi ve Pohorje şehri doğa ile birlikte okumayı sağlar.",
    sights: [["Lent ve Eski Asma", "Drava kıyısı ile müzeyi gezin; festival kurulumu ve asma etkinlik saatini kontrol edin."], ["Glavni trg ve müzeler", "Veba sütunu, sinagog ve bölge müzesini açılış gününe göre birleştirin; hafıza mekânlarında saygılı olun."], ["Pohorje", "Teleferik/yürüyüş veya kayak için hava, bakım, son iniş ve işaretli patikayı doğrulayın."]],
    areas: [["Merkez ve Lent", "Tren, nehir, müze ve akşam için yürünebilir ana üs."], ["Pohorje etekleri", "Doğa, spa veya kayak için şehir otobüsü/teleferik bağlantılı alternatif."]], foods: [["Štajerska mutfağı", "Bograč, kızartma ve sosislerde et türü/yağ ile porsiyonu sorun."], ["Steiermark şarabı", "Sauvignon/Riesling tadımını randevu ve sürücülü dönüşle planlayın."]], dayTrips: [["Ptuj", "Tren/otobüsle kale, kurent kültürü ve termal kasaba; müze saatini doğrulayın."], ["Jeruzalem bağları", "Araç/tur, tadım rezervasyonu ve bisiklet eğimini planlayın; tadım sonrası sürmeyin."]], caution: "Bağ tadımı sonrası araç/bisiklet kullanmayın. Pohorje'de hava, orman çalışması ve kayak kapanışına uyun; Drava kıyısında etkinlik kalabalığında eşyayı gözetin."
  },
  {
    city: "Kranjska Gora", countryCode: "SI", focus: "Julian Alpleri, göller ve dağ geçitleri", lede: "Slovenya'nın kuzeybatısında Alp köyünü Jasna Gölü, Vršič Geçidi, Planica vadisi ve dört mevsim yürüyüş–kayak altyapısıyla birleştiren dağ üssü.", days: "4–6 gün", arrival: "Jesenice tren istasyonu üzerinden otobüs/transfer", local: "Otobüs, shuttle, bisiklet ve yürüyüş", best: "Haziran–Eylül · kayak için Ocak–Mart", pulse: "Kranjska Gora pist merkezinden fazlasıdır; Zelenci, Planica, Tamar ve Vršič farklı zorluk ve ulaşım kararlarıdır. Sınır üçgeni, uluslararası rotayı belge ve sigorta açısından önemli kılar.",
    sights: [["Jasna ve Zelenci", "Göl ile kaynak rezervini yürüyüş/bisikletle bağlayın; tahta yol ve koruma bariyerinden çıkmayın."], ["Vršič Geçidi", "Virajlı yüksek yol, kar, otobüs, park ve dağ rotasını güncel yol duyurusuna göre planlayın."], ["Planica ve Tamar", "Nordik merkezden vadi yürüyüşüne hava, etkinlik erişimi, ayakkabı ve gün ışığıyla gidin."]],
    areas: [["Kranjska Gora merkezi", "Otobüs, restoran, ekipman ve pist için en pratik üs."], ["Podkoren, Rateče veya Mojstrana", "Sakin köy, Planica ya da Triglav vadileri için farklı otobüs/araç alternatifleri."]], foods: [["Dağ gostilnası", "Jota, karabuğday ve güveçte et/süt içeriğini sorun; kulübe saatini önceden doğrulayın."], ["Peynir ve tatlı", "Üretici/pastörizasyon ile cevizli potica alerjenini kontrol edin."]], dayTrips: [["Peričnik Şelalesi", "Mojstrana'dan yol/patika, su seviyesi ve arkasından geçiş güvenliğini park duyurusuna göre değerlendirin."], ["Tarvisio veya Villach", "İtalya/Avusturya Schengen içi bağlantıda kimlik, bisiklet sigortası ve son tren/otobüsü kontrol edin."]], caution: "Vršič ve yüksek patikada kar/fırtına kapanışını aşmayın; kayak ve dağ kurtarma kapsamlı sigorta taşıyın. Yaban hayatını beslemeyin, koruma alanında kamp/ateş yakmayın ve sınır geçişinde kimliğinizi taşıyın."
  },
];

export const sloveniaGuides = makeRegionalGuides(profiles);
