import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Stockholm", countryCode: "SE", focus: "Gamla Stan, dünya müzeleri ve takımadalar", lede: "On dört adaya yayılan tarihî başkenti Vasa gibi dünya müzeleri, çağdaş tasarım, mahalle kahveleri ve binlerce adalı takımada peyzajıyla birleştiren İsveç rotası.", days: "4–6 gün", arrival: "ARN/BMA · Stockholm Central · feribot terminalleri", local: "Metro, tramvay, banliyö treni, otobüs, feribot ve yürüyüş", best: "Mayıs–Eylül · kış kültürü için Aralık–Mart", pulse: "Stockholm'ü yalnız Gamla Stan ve fotojenik metro istasyonlarından ibaret görmeyin. Djurgården müzeleri, Södermalm'ın gündelik yaşamı, City/Norrmalm kamusal mimarisi ve takımada vapurları farklı günler ister. Su üzerindeki kısa mesafe, iskele ve mevsim yüzünden uzun bağlantıya dönüşebilir.",
    sights: [["Gamla Stan ve Kraliyet Sarayı", "Dar sokakları sabah erken yürüyün; saray töreni, temsil salonu, kilise ve Parlamento erişimini güncel programdan kontrol edin."], ["Vasa Müzesi ve Djurgården", "Vasa'yı Skansen, Nordiska veya ABBA Müzesi'nden yalnız biriyle eşleştirin; ada üzerindeki müze saatleri ve tramvay yoğunluğunu planlayın."], ["Stadshuset ve Fotografiska", "Belediye binası kulesi/rehberli tur rezervasyonunu önceden yapın; Fotografiska'nın güncel sergisiyle Södermalm yürüyüşünü birleştirin."]],
    areas: [["Norrmalm, Vasastan veya Gamla Stan", "İlk ziyaret ve bağlantılar için kolay; Gamla Stan'da turistik yoğunluk, Norrmalm'da iş merkezi hissi belirgindir."], ["Södermalm veya Kungsholmen", "Kafe, tasarım, park ve daha yerel akşamlar için metro/otobüsle güçlü alternatifler."]], foods: [["Köttbullar ve husmanskost", "Köftenin et karışımı, sos ve süt içeriğini sorun; öğle 'dagens rätt' menüsü bütçeyi dengeleyebilir."], ["Fika ve kardemummabulle", "Kakuleli çöreği bağımsız fırında deneyin; süt, yumurta, tereyağı ve kuruyemiş alerjenini doğrulayın."]], dayTrips: [["Vaxholm veya Sandhamn", "Takımada deneyimi için yalnız bir ada seçin; iskele, operatör, bilet geçerliliği ve son tekneyi kontrol edin."], ["Uppsala veya Sigtuna", "Uppsala trenle tam kültür günü, Sigtuna otobüs bağlantılı küçük kasaba günüdür; ikisini aceleyle birleştirmeyin."]], caution: "Metro ve kalabalık merkezde yankesiciliğe karşı çantayı kapalı tutun; taksi fiyatlarının serbestçe değişebildiği yerlerde birim fiyatı ve toplam tahmini görün. Kışın buzlu kıyı/merdiven, yazın takımada dönüş kapasitesi için yedek bırakın."
  },
  {
    city: "Göteborg", countryCode: "SE", focus: "batı kıyısı, tasarım ve araçsız takımada", lede: "Göta älv kıyısındaki denizcilik ve sanayi mirasını Haga kafeleri, yaratıcı mahalleler, güçlü deniz mutfağı ve araçsız güney takımadalarıyla birleştiren batı limanı.", days: "3–5 gün", arrival: "GOT · Göteborg Central · Nils Ericson Terminali", local: "Tramvay, otobüs, feribot, banliyö treni ve yürüyüş", best: "Mayıs–Eylül · Noel pazarı için Kasım–Aralık", pulse: "Göteborg'un gücü büyük simgelerden çok su, tramvay ve mahalleler arasındaki dengededir. Haga'yı kanelbulle dekoruna indirgemeden Masthugget, Majorna ve liman dönüşümünü gezin; güney takımadasını şehir ulaşım kartıyla erişilebilen bağımsız bir gün olarak planlayın.",
    sights: [["Göteborg Sanat Müzesi ve Götaplatsen", "Nordik koleksiyonu seçerek gezin; konser, tiyatro ve geçici sergi saatini aynı kültür aksında kontrol edin."], ["Maritiman ve liman hattı", "Yüzen müze gemilerinde dar merdiven ve erişilebilirliği değerlendirin; Älvsborg bağlantısını ayrı bilet/saatle planlayın."], ["Haga, Masthugget ve Majorna", "Kafe molasını mahalle yürüyüşüyle dengeleyin; özel avluya girmeyin ve dik yokuşlarda tramvay seçeneğini kullanın."]],
    areas: [["Centrum, Haga veya Lorensberg", "İlk ziyaret, kültür ve tramvay ağında pratik; etkinlik gecelerinde gürültü/fiyat artabilir."], ["Majorna, Linné veya Eriksberg", "Yerel kafe/akşam, park ya da yenilenmiş liman yaşamı için nehir geçişli alternatifler."]], foods: [["Karides, istiridye ve balık çorbası", "Kabuklu deniz ürününün kaynağını, porsiyon/kilo fiyatını ve alerjenleri sorun; Feskekörka çalışma saatini doğrulayın."], ["Haga çöreği ve fika", "Büyük kanelbulle'yi paylaşın; porsiyonun turistik şovdan ibaret olmadığı bağımsız fırınları karşılaştırın."]], dayTrips: [["Güney takımadaları", "Saltholmen bağlantısı ile Styrsö, Donsö veya Vrångö'den yalnız bir-ikisini seçin; araçsız ada kuralı ve son feribotu kontrol edin."], ["Marstrand", "Otobüs ve kısa feribotla kaleye ulaşın; rüzgâr, kale saati ve dönüş kapasitesini planlayın."]], caution: "Tramvay hattını bisikletle veya fotoğraf için kapatmayın; biletinizi araca binmeden etkinleştirin. Takımada kayalıkları ıslak ve yosunlu olabilir; yüzmede soğuk su, akıntı ve tekne rotalarına dikkat edin."
  },
  {
    city: "Malmö", countryCode: "SE", focus: "Öresund, çağdaş mimari ve çok kültürlü mutfak", lede: "Orta Çağ Malmöhus çevresini Västra Hamnen'in sürdürülebilir mimarisi, Möllevången'in çok kültürlü pazarı ve Öresund üzerindeki Kopenhag bağlantısıyla birleştiren güney şehri.", days: "2–4 gün", arrival: "MMX/CPH · Malmö Central · Hyllie", local: "Otobüs, bölgesel tren, bisiklet ve yürüyüş", best: "Mayıs–Eylül", pulse: "Malmö, Kopenhag'a giden trenin kısa durağı değildir. Gamla Väster'in küçük ölçeği, Malmöhus'un bölgesel tarihi, Västra Hamnen'in planlama tartışması ve Möllevången'in göçle şekillenen yemek kültürü kent kimliğini birlikte kurar.",
    sights: [["Malmöhus ve müzeler", "Kale içindeki tarih, sanat, doğa ve teknoloji bölümlerinden seçki yapın; akvaryum/sergi yenilemesini kontrol edin."], ["Västra Hamnen ve Turning Torso", "Yapıyı dışarıdan ve kamusal sahil hattından görün; özel konut alanlarına girmeyin, rüzgârlı kıyıda bisiklet/yaya yoluna dikkat edin."], ["Stortorget, Lilla Torg ve St. Petri", "Meydanları Gamla Väster ile yürüyün; kilisede ibadet, etkinlik ve fotoğraf kurallarına uyun."]],
    areas: [["Gamla Staden veya Centralen çevresi", "İlk ziyaret ve Kopenhag/Lund treni için işlevsel; Lilla Torg çevresi gece gürültülüdür."], ["Möllevången, Davidshall veya Västra Hamnen", "Yemek ve yerel yaşam, butik şehir hissi ya da modern kıyı için farklı karakterler."]], foods: [["Falafel ve çok kültürlü sokak yemeği", "Et suyu, kızartma yağı, sos ve helal belgesini doğrudan işletmeden doğrulayın; yoğun saat dışında gidin."], ["Skåne ürünleri", "Hardal, peynir, elma ve mevsim tabağında üretici/alerjenleri sorun; öğle menüsünü değerlendirin."]], dayTrips: [["Lund", "Sık trenle katedral, üniversite ve Kulturen'i tam gün gezin; ders/ibadet alanlarında sessiz olun."], ["Kopenhag", "Öresund treni uluslararası sınır geçişidir; pasaport ve Schengen giriş hakkını taşıyın, bakım/gece seferini kontrol edin."]], caution: "Malmö ile Kopenhag arasında rutin tren olsa da kimlik kontrolü yapılabilir; belgeyi yanınızda tutun. Bisiklet yolunda yürümeyin, gece tenha park/istasyonlarda olağan şehir dikkati gösterin ve tartışmalı mahalle etiketleriyle yerel yaşamı genellemeyin."
  },
  {
    city: "Uppsala", countryCode: "SE", focus: "üniversite, katedral ve Viking öncesi hafıza", lede: "İskandinavya'nın büyük katedralini tarihî üniversite koleksiyonları, Linnaeus mirası, Fyris nehri ve Gamla Uppsala höyükleriyle birleştiren akademik şehir.", days: "2–3 gün", arrival: "Uppsala Central · ARN bağlantısı", local: "Otobüs, bisiklet, banliyö/bölgesel tren ve yürüyüş", best: "Nisan–Eylül · öğrenci geleneği için Nisan sonu", pulse: "Uppsala'nın kompakt merkezinde din, bilim, monarşi ve öğrenci gelenekleri birkaç sokakta buluşur. Katedral ile Gustavianum'u hızlıca işaretlemek yerine Carolina Rediviva, Linnaeus bahçesi ve nation kültürünün erişim kurallarını da okuyun; Gamla Uppsala ayrı yarım gündür.",
    sights: [["Uppsala Katedrali", "İbadet ve ziyaret saatini ayırın; kraliyet mezarları, sanat ve kule alanında sessizlik/fotoğraf kurallarına uyun."], ["Gustavianum ve Carolina Rediviva", "Üniversite koleksiyonlarının açık salon ve rehberli tur durumunu kontrol edin; araştırma alanlarını ziyaret mekânı sanmayın."], ["Gamla Uppsala", "Höyükleri müze ve kiliseyle birlikte gezin; arkeolojik alanda işaretli patikadan çıkmayın ve mezar tepelerine zarar vermeyin."]],
    areas: [["Centrum ve nehir çevresi", "Katedral, istasyon ve üniversite yapılarına yürüyüş için en kolay üs."], ["Kåbo veya Luthagen", "Bahçeler, kampüs ve sakin konut dokusu için bisiklet/otobüsle bağlı alternatifler."]], foods: [["Fika ve öğrenci kafeleri", "Nation mekânlarının üye/konuk kuralını kontrol edin; halka açık fırınlarda kakuleli çörek ve kahve deneyin."], ["İsveç ev yemekleri", "Köfte, balık ve bezelye çorbasında et/süt içeriğini sorun; günün öğle menüsü fiyat avantajı sağlar."]], dayTrips: [["Sigtuna", "Otobüsle runik taşlar ve göl kasabasını gezin; arkeolojik alan, kilise ve son dönüşü kontrol edin."], ["Stockholm", "Sık tren bağlantısıyla mümkün; ancak Uppsala'yı yalnız yatak üssüne çevirmemek için en az bir tam şehir günü bırakın."]], caution: "Valborg gibi öğrenci etkinliklerinde kalabalık, alkol ve ulaşım yoğunluğu artar; köprü/nehir kenarında bariyer dışına çıkmayın. Bisiklet yolunda geçiş hakkına, üniversite binalarında çalışma ortamına ve mezar alanlarında saygıya dikkat edin."
  },
  {
    city: "Gotland", countryCode: "SE", focus: "Visby surları, Fårö kayalıkları ve Baltık adası", lede: "UNESCO Visby'nin Orta Çağ surlarını Fårö'nün rauk kayalıkları, taş kiliseler, kırsal çiftlikler ve Baltık Denizi'nin uzun yaz günleriyle birleştiren ada rotası.", days: "4–7 gün", arrival: "VBY · Visby feribot terminali", local: "Bölgesel otobüs, bisiklet, araç, feribot ve yürüyüş", best: "Mayıs–Eylül", pulse: "Gotland yalnız Visby'nin gül kaplı duvarları değildir. Ada kuzey–güney doğrultusunda büyüktür; Fårö, Ljugarn, Ekstakusten ve taş kiliseler farklı günler ister. Orta Çağ Haftası ve Almedalen gibi etkinlikler fiyat ile kapasiteyi tamamen değiştirir.",
    sights: [["Visby surları ve eski şehir", "Surları işaretli rota ve açık kulelerle gezin; özel avluya girmeyin, gevşek taş ve dar merdivende dikkatli olun."], ["Gotlands Museum", "Viking hazineleri, resim taşları ve ada tarihini kırsal kilise/mezarlık gezisinden önce bağlama oturtun."], ["Fårö ve rauk alanları", "Kısa araç feribotu, bisiklet/araç, yakıt ve dönüşü planlayın; koruma alanında kayalara tırmanmayın ve kamp/ateş kuralına uyun."]],
    areas: [["Visby", "Feribot, müze ve akşam için en kolay üs; yaz festivallerinde çok pahalı ve kalabalık olabilir."], ["Fårö, Ljugarn veya güney Gotland", "Sahil/kırsal yaşam için güçlü; market, otobüs ve akşam yemeği saatleri sınırlıdır."]], foods: [["Saffranspannkaka", "Safranlı pirinç tatlısında süt, yumurta ve badem içeriğini sorun; salmbär reçeliyle yerel porsiyon deneyin."], ["Kuzu ve füme balık", "Et/balığın menşeini, porsiyonu ve tütsüleme içeriğini sorun; kırsal işletmeyi önceden arayın."]], dayTrips: [["Fårö", "Visby'den uzun gün olabilir; kuzeyde en az iki ana durak seçin ve feribot kuyruğuna pay bırakın."], ["Stora Karlsö", "Koruma adasına yalnız mevsimsel tekne ve belirlenmiş rotayla gidin; kuş üreme alanı kurallarına eksiksiz uyun."]], caution: "Kıyı kayalıklarında dalga, rüzgâr ve gevşek kireçtaşı risklidir; işaretli patikayı terk etmeyin. Bisikletle dar yolda görünürlük ekipmanı taşıyın, adanın ölçeğini küçümsemeyin ve festival döneminde konaklama/feribotu aylar önce kontrol edin."
  },
  {
    city: "Kiruna", countryCode: "SE", focus: "taşınan şehir, maden tarihi ve Sámi coğrafyası", lede: "Maden nedeniyle yeniden kurulan kent merkezini ikonik ahşap kilise, endüstri tarihi, Sámi kültür coğrafyası ve İsveç Laponyası'nın geniş tundrasıyla birleştiren Arktik şehir.", days: "3–5 gün", arrival: "KRN · Kiruna istasyonu", local: "Otobüs, transfer, tren, araç ve rehberli tur", best: "Kış için Aralık–Mart · gece yarısı güneşi için Haziran–Temmuz", pulse: "Kiruna'nın taşınması yaşayan bir şehircilik ve maden ekonomisi hikâyesidir. Yeni merkez ile taşınan yapıları, LKAB'nin etkisini ve bölgenin Sápmi içindeki yerini birlikte okuyun. Kuzey ışığı veya kar oteli deneyimini şehir halkının gündelik yaşamının önüne koymayın.",
    sights: [["Yeni merkez ve Kiruna Kilisesi", "Şehrin taşınma takvimini, kilisenin erişim/restorasyon durumunu ve kamusal sergileri güncel kaynaktan kontrol edin."], ["LKAB maden ziyareti", "Yalnız resmî rehberli turla gidin; yaş, sağlık, güvenlik, fotoğraf ve yeraltı erişim kurallarına uyun."], ["Sámi kültürü ve çevre doğası", "Yerli topluluk tarafından işletilen, hayvan refahı ve kültürel anlatımı açık deneyim seçin; kıyafet/ritüeli dekor gibi kullanmayın."]],
    areas: [["Yeni Kiruna merkezi", "Otobüs, restoran ve kamusal yapılara yakın; eski haritadaki adresler güncelliğini yitirmiş olabilir."], ["Jukkasjärvi veya kamp alanları", "Buz oteli/doğa erişimi için alternatif; transfer, yemek ve gece dönüşü önceden sabitlenmelidir."]], foods: [["Ren geyiği ve Arktik ürünler", "Etin menşei, Sámi işletme bağı ve alerjeni sorun; kültürel bağlamı olmayan gösterişli sunumu sorgulayın."], ["Lingonberry, cloudberry ve fika", "Mevsim meyvesi, reçel/tatlı şeker oranı ve süt/kuruyemiş içeriğini doğrulayın."]], dayTrips: [["Jukkasjärvi", "ICEHOTEL mevsimlerine, kilise ve Sámi deneyiminin rezervasyon/etik ilkelerine göre yarım veya tam gün planlayın."], ["Abisko", "Tren/otobüs saatini, park hava durumunu ve son dönüşü kontrol edin; yoğun program yerine en az bir gece kalmak daha güvenlidir."]], caution: "Kışın sıcaklık, rüzgâr ve karayolu kapanışı yaşamı tehdit edebilir; araçta acil ekipman ve yakıt taşıyın. Kuzey ışığını garanti saymayın, maden/şantiye sınırını aşmayın ve kar motorunda lisans, kask, hız ile sigortayı doğrulayın."
  },
  {
    city: "Abisko", countryCode: "SE", focus: "milli park, Kungsleden ve Arktik gökyüzü", lede: "Torneträsk Gölü kıyısındaki milli parkı Kungsleden başlangıcı, U biçimli Lapporten vadisi, huş ormanı ve mevsimsel kuzey ışığı gözlemleriyle birleştiren doğa üssü.", days: "3–6 gün", arrival: "Abisko Östra/Turiststation tren durakları · KRN bağlantısı", local: "Tren, sınırlı otobüs, yürüyüş, kayak ve rehberli tur", best: "Yürüyüş için Haziran sonu–Eylül · kuzey ışığı için Eylül–Mart", pulse: "Abisko küçük bir yerleşim ve büyük bir doğa alanıdır. İstasyonda yanlış durakta inmek, market/öğün saatini kaçırmak veya dağ havasını şehir tahminiyle okumak rotayı bozar. Aurora Sky Station tek hedef değil; milli park ekolojisi ve Sámi coğrafyası temel bağlamdır.",
    sights: [["Abisko Milli Parkı ve kanyon", "Naturum'dan güncel patika, köprü, yangın ve hava bilgisini alın; işaretli rotada kalın ve çöpünüzü geri taşıyın."], ["Kungsleden başlangıcı", "Günlük kısa yürüyüş ile çok günlük dağ rotasını ayırın; kulübe, su, ekipman, telefon kapsaması ve kurtarma sigortasını planlayın."], ["Aurora Sky Station veya gece gözlemi", "Teleferik/aktivite açılışı rüzgâra bağlıdır; kuzey ışığı garantisi olmadığını kabul edin ve iade/yeniden rezervasyon şartını okuyun."]],
    areas: [["Abisko Turiststation", "Park patikaları, ekipman ve rehberli faaliyetlere yakın; oda/yemek kapasitesi erken dolar."], ["Abisko Östra veya Björkliden", "Market/yerleşim ya da kayak/konaklama alternatifi; istasyon ve gece transferini doğru seçin."]], foods: [["Dağ istasyonu öğünleri", "Paket/servis saatini, vejetaryen-alerjen seçeneğini ve erken kahvaltıyı rezervasyonla netleştirin."], ["Arktik meyve ve yerel balık", "Menşe, sürdürülebilir tedarik ve süt/et içeriğini sorun; doğadan tanımadığınız bitki/mantar toplamayın."]], dayTrips: [["Björkliden ve Riksgränsen", "Tren, kayak/patika açılışı ve Norveç sınırı yönündeki hava koşulunu kontrol edin."], ["Narvik", "Norveç'e uluslararası geçiştir; pasaport, bilet, saat dilimi ve tren/otobüs çalışmasını doğrulayın."]], caution: "Çığ, beyaz körlük, hızlı sıcaklık düşüşü ve zayıf telefon kapsaması ciddi risklerdir. Kışın işaretli rota dışına rehbersiz çıkmayın; yazın nehir seviyesi ve sivrisinek durumuna hazırlanın. Kuzey ışığı için ray, karayolu veya özel araziye girmeyin."
  },
  {
    city: "Dalarna", countryCode: "SE", focus: "Siljan Gölü, Falun madeni ve kırsal gelenekler", lede: "Falun'un UNESCO bakır madeni mirasını Siljan Gölü köyleri, kırmızı ahşap evler, halk sanatı, müzik ve dört mevsim orman yaşamıyla birleştiren Orta İsveç bölgesi.", days: "4–7 gün", arrival: "Falun/Borlänge/Mora istasyonları", local: "Bölgesel tren, otobüs, bisiklet, araç ve yürüyüş", best: "Mayıs–Eylül · kış sporları için Aralık–Mart", pulse: "Dalarna tek bir kasaba değil, Falun–Borlänge ile Siljan çevresinde yayılan bir bölgedir. Falun sanayi tarihini, Sundborn sanat mirasını ve Mora–Rättvik–Leksand göl kültürünü ayrı kümeler olarak kurun. Midsommar yaşayan topluluk geleneğidir; sahne dekoru gibi davranmayın.",
    sights: [["Falun Büyük Bakır Dağı", "UNESCO alanında yalnız açık resmî rota ve rehberli maden turunu kullanın; yeraltı sıcaklığı, merdiven ve kıyafet gereksinimini kontrol edin."], ["Siljan Gölü köyleri", "Mora, Rättvik ve Leksand'dan en fazla iki üs seçin; otobüs, tekne ve mevsimsel etkinliği birlikte planlayın."], ["Carl Larsson-gården ve Sundborn", "Saatli rehberli turu önceden alın; ev içi fotoğraf ve grup kurallarına uyun."]],
    areas: [["Falun veya Borlänge", "Tren, müze ve temel hizmetler için işlevsel şehir üssü."], ["Mora, Rättvik veya Leksand", "Siljan kıyısı ve geleneksel köy atmosferi için araç/otobüs planı isteyen alternatifler."]], foods: [["Tunnbröd ve yerel peynir", "İnce ekmek ile peynir/şarküteride süt, et ve alerjenleri sorun; çiftlik dükkânının saatini kontrol edin."], ["Orman meyvesi ve mantar", "Yalnız tanımlanmış ve güvenilir tedarikli ürünü tüketin; toplama hakkını özel arazi/koruma kuralıyla karıştırmayın."]], dayTrips: [["Sundborn", "Falun'dan otobüs/araçla sanatçı evini ve köyü sakin bir yarım gün olarak planlayın; rezervasyonu kontrol edin."], ["Mora ve Zorn", "Zorn Müzesi, Vasaloppet tarihi ve gölü birlikte gezin; etkinlik döneminde konaklama/ulaşımı erken alın."]], caution: "Kırsal otobüs seyrek, kış yolu buzlu ve vahşi yaşam geçişi yoğun olabilir. Midsommar veya özel kültür etkinliğinde yerel davet/alan kurallarına uyun; ormanda ateş yasağı, kene ve av sezonu duyurularını kontrol edin."
  },
];

export const swedenGuides = makeRegionalGuides(profiles);
