import { makeRegionalGuides, type RegionalProfile } from "./regionalFactory";

const profiles: RegionalProfile[] = [
  {
    city: "Zürih", countryCode: "CH", focus: "eski şehir, göl kıyısı ve çağdaş kültür", lede: "Limmat kıyısındaki tarihî sokakları göl yüzmeleri, tasarım, sanat ve canlı mahallelerle birleştiren İsviçre metropolü.", days: "2–4 gün", arrival: "ZRH · Zürich HB", local: "Tramvay, S-Bahn, tekne ve yürüyüş", best: "Nisan–Haziran · Eylül–Aralık", pulse: "Zürih'i yalnız pahalı finans merkezi olarak okumak hata olur; şehir göl ve nehirle yaşayan, eski sanayi alanlarını kültür mahallelerine dönüştüren kompakt bir kenttir.",
    sights: [["Altstadt ve Grossmünster", "Limmat'ın iki yakasındaki lonca evleri, dar sokaklar ve kilise kulelerini sabah yürüyüşünde birleştirin."], ["Kunsthaus Zürich", "Eski ustalardan modern sanata uzanan büyük koleksiyonda geçici sergi ile ana bina saatlerini önceden kontrol edin."], ["Zürih Gölü ve Uetliberg", "Hava açıksa göl teknesi veya Uetliberg seyriyle şehir–Alp ilişkisini görün; son bağlantıyı SBB'den doğrulayın."]],
    areas: [["Altstadt ve Enge", "İlk ziyaret, göl ve ana istasyon için çok pratik; oda fiyatı yüksek olabilir."], ["Zürich-West ve Aussersihl", "Viadukt, tasarım mekânları, farklı mutfaklar ve daha canlı akşamlar için iyi seçenek."]], foods: [["Zürcher Geschnetzeltes", "Kremalı dana eti ve rösti klasiğinde porsiyon ile et tercihini siparişten önce sorun."], ["Rösti, peynir ve fırınlar", "Günlük bütçeyi dengelemek için yerel fırın, market ve öğle menülerini kullanın."]], dayTrips: [["Ren Şelalesi", "Schaffhausen bağlantısıyla kolaydır; tekne sezonu, su seviyesi ve son treni kontrol edin."], ["Rapperswil", "Göl teknesi veya trenle kale, kıyı ve sakin bir yarım gün rotası sunar."]], caution: "Nehir yüzmesinde yalnız işaretli giriş–çıkışı ve güncel akıntı bilgisini kullanın; değerli eşyayı kıyıda gözetimsiz bırakmayın, tramvay yolunda bisiklet şeridine çıkmayın."
  },
  {
    city: "Luzern", countryCode: "CH", focus: "Kapellbrücke, göl tekneleri ve dağ gezileri", lede: "Orta Çağ köprülerini Luzern Gölü, Pilatus ve Rigi manzaralarıyla birleştiren merkezi İsviçre üssü.", days: "2–4 gün", arrival: "Luzern Bahnhof · ZRH üzerinden tren", local: "Yürüyüş, otobüs, tekne ve dağ treni", best: "Mayıs–Haziran · Eylül · Aralık–Şubat", pulse: "Luzern'in merkezini bir günde görmek mümkündür; asıl karar göl, Rigi ve Pilatus'tan hangisine zaman ayıracağınızdır.",
    sights: [["Kapellbrücke ve Eski Şehir", "Köprünün resimli iç panellerini, Reuss kıyısını ve Weinmarkt sokaklarını sabah ışığında gezin."], ["İsviçre Ulaşım Müzesi", "Tren, otomobil, havacılık ve uzay koleksiyonları için en az yarım gün bırakın; ek deneyimlerin ayrı biletini kontrol edin."], ["Pilatus veya Rigi", "İki dağı aynı güne koymayın; hava, sezonluk hat, tekne bağlantısı ve son inişi resmî işletmeden doğrulayın."]],
    areas: [["Altstadt ve Neustadt", "İstasyon, köprü ve tekne iskelesine yakın; kısa ziyaret için en rahat üs."], ["Tribschen ve Bruchquartier", "Göl yürüyüşü, yerel kafeler ve merkezden biraz daha sakin akşamlar sunar."]], foods: [["Luzerner Chügelipastete", "Etli–kremalı yerel hamur işi; içeriği ve porsiyonu menüden teyit edin."], ["Älplermagronen", "Peynirli makarnayı patates, soğan ve elma püresiyle sunan doyurucu dağ klasiği."]], dayTrips: [["Rigi", "Tekne–dişli tren–teleferik halkası hava açıksa güçlü bir tam gün oluşturur."], ["Engelberg ve Titlis", "Yüksek irtifa, rüzgâr ve son teleferik nedeniyle şehir gününden ayrı planlanmalıdır."]], caution: "Dağ bileti almak hattın açık olduğu anlamına gelmez; canlı operasyonu ve görünürlüğü aynı sabah kontrol edin. Kapellbrücke çevresinde kalabalıkta çanta ve telefonunuza dikkat edin."
  },
  {
    city: "Bern", countryCode: "CH", focus: "UNESCO eski şehir, Aare ve federal başkent", lede: "Kumtaşı kemerleri, çeşmeleri ve Aare kıvrımıyla İsviçre'nin sakin ama katmanlı federal başkenti.", days: "2–3 gün", arrival: "Bern Hauptbahnhof · ZRH/BSL üzerinden tren", local: "Tramvay, otobüs ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim · Aralık", pulse: "Bern'in gücü anıt sayısından çok, altı kilometrelik kemerler altında yürüyen gündelik hayat ile nehrin şekillendirdiği kent dokusundadır.",
    sights: [["UNESCO Eski Şehir ve Zytglogge", "Saat kulesi, çeşmeler, Münster ve kemerli sokakları tek çizgide değil, ara avlularla keşfedin."], ["Bundeshaus", "Parlamento meydanı ve resmî tur takvimini kontrol edin; güvenlik ve oturum günleri erişimi değiştirebilir."], ["Rosengarten ve Aare kıyısı", "Eski şehir panoraması için gün batımına yakın çıkın; nehir parkurunda hava ve akıntıya göre hareket edin."]],
    areas: [["Altstadt", "Ana simgeler ve istasyona yakın, yürünebilir ama konaklama seçenekleri sınırlı."], ["Matte ve Breitenrain", "Nehir dibi tarihî doku ya da yerel pazar–kafe hayatı için iki farklı sakin alternatif."]], foods: [["Berner Platte", "Et ağırlıklı büyük porsiyonu paylaşmayı veya daha hafif günün yemeğini sorun."], ["Soğan tartı ve pazar ürünleri", "Haftalık pazarda peynir, ekmek ve mevsim ürünleri ekonomik bir öğle molası sağlar."]], dayTrips: [["Thun", "Göl, kale ve Aare hattı trenle kısa; tekne sezonunda Luzern değil Bern bölgesine sakin bir alternatif."], ["Emmental", "Peynir üretimi ve kırsal rota için toplu taşıma bağlantısını önceden kurun."]], caution: "Aare güçlü akıntılı bir nehirdir; yerel deneyim ve uygun koşul olmadan yüzmeyin. Federal binalarda güvenlik kuralına, eski şehirde tramvay hattına dikkat edin."
  },
  {
    city: "Cenevre", countryCode: "CH", focus: "Cenevre Gölü, uluslararası kurumlar ve müzeler", lede: "Rhone çıkışında göl manzarasını diplomasi tarihi, bilim ve Fransızca konuşulan mahallelerle buluşturan sınır kenti.", days: "2–4 gün", arrival: "GVA · Genève-Cornavin", local: "Tramvay, otobüs, mouette teknesi ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Cenevre'nin uluslararası yüzü Place des Nations'da görünür; gerçek şehir ritmi Carouge, Plainpalais ve göl kıyısındaki gündelik yaşamda tamamlanır.",
    sights: [["Jet d'Eau ve göl kıyısı", "Rüzgârda su sütununa fazla yaklaşmadan iki yakayı yürüyün; tekne ve fıskiye operasyonu hava nedeniyle durabilir."], ["Eski Şehir ve Saint-Pierre", "Katedral, Maison Tavel ve Bourg-de-Four üzerinden Reform tarihi ile arkeolojiyi birleştirin."], ["Palais des Nations ve CERN", "İki kurum da ön rezervasyon, kimlik ve güvenlik kontrolü isteyebilir; aynı güne dar saatle sıkıştırmayın."]],
    areas: [["Vieille Ville ve Eaux-Vives", "Tarih, göl ve restoranlar için merkezî; eğimli sokak ve yüksek fiyatı hesaba katın."], ["Carouge ve Plainpalais", "Pazar, atölye, kafe ve daha mahalle ölçekli akşamlar için iyi üsler."]], foods: [["Fondü ve raclette", "Peynir yemeğini kişi sayısı, alkol içeriği ve yan ürünlerle birlikte siparişten önce konuşun."], ["Longeole ve göl balığı", "Cenevre sucuğu ya da mevsimlik balıkta menşei ve servis biçimini sorun."]], dayTrips: [["Lozan", "Trenle yaklaşık kırk dakika; eğimli şehir ve Ouchy için tam gün ayırın."], ["Montreux ve Lavaux", "UNESCO bağ terasları ile göl kıyısını tren üzerinden bağlayın; özel bağa izinsiz girmeyin."]], caution: "Uluslararası kurum gezilerinde pasaport, rezervasyon adı ve çanta kuralını önceden okuyun. Sınırı fark etmeden Fransa'ya geçen rota ve telefon dolaşım koşulunu kontrol edin."
  },
  {
    city: "Lozan", countryCode: "CH", focus: "Olimpiyat mirası, Lavaux ve eğimli göl şehri", lede: "Katedral tepesinden Ouchy kıyısına inen, sanat ve Olimpiyat tarihini Lavaux bağlarıyla birleştiren Fransızca şehir.", days: "2–3 gün", arrival: "Lausanne Gare · GVA/ZRH üzerinden tren", local: "Metro, otobüs, tren ve yürüyüş", best: "Nisan–Haziran · Eylül–Ekim", pulse: "Lozan haritada küçük ama dikeydir; yukarı şehir, Flon ve Ouchy'yi aynı düz yürüyüş gibi düşünmemek günün enerjisini korur.",
    sights: [["Lozan Katedrali ve Cité", "Gotik katedrali, şehir tarih müzesini ve Escaliers du Marché merdivenlerini sabah gezin."], ["Olimpiyat Müzesi ve Ouchy", "Göl bahçeleriyle birlikte en az yarım gün ayırın; özel sergi ve bilet saatini kontrol edin."], ["Collection de l'Art Brut", "Ana sanat rotasından farklı, güçlü bir koleksiyon; merkeze ulaşımı ve kapanış gününü önceden görün."]],
    areas: [["Cité, Flon ve Gare", "İstasyon–merkez arasında pratik; yokuş yerine metro kullanmak zaman kazandırır."], ["Ouchy ve Sous-Gare", "Göl akşamı, parklar ve daha sakin konaklama için güçlü seçenek."]], foods: [["Papet vaudois", "Pırasa–patates ve sosisli Vaud klasiğinde et içeriğini ve porsiyonu sorun."], ["Vaud şarabı ve peynir", "Lavaux üretimini tadarken trenle dönün; şarap sonrası araç kullanmayın."]], dayTrips: [["Lavaux", "Tren ve işaretli yürüyüşle UNESCO bağ terasları; hasat ve özel mülk kurallarına uyun."], ["Vevey ve Montreux", "Göl kıyısında kısa trenlerle sanat, pazar ve Château de Chillon hattı kurulabilir."]], caution: "Yokuşları harita mesafesiyle küçümsemeyin; valizle metro kullanın. Lavaux'da üzüm sıraları fotoğraf dekoru değil özel üretim alanıdır, yalnız işaretli yolu izleyin."
  },
  {
    city: "Interlaken", countryCode: "CH", focus: "Jungfrau, göller ve Alp maceraları", lede: "Thun ile Brienz gölleri arasında Jungfrau bölgesinin tren, teleferik ve açık hava bağlantılarını yöneten ulaşım üssü.", days: "3–6 gün", arrival: "Interlaken Ost/West · Bern/Zürih üzerinden tren", local: "Bölgesel tren, otobüs, tekne ve teleferik", best: "Mayıs–Ekim · Aralık–Mart", pulse: "Interlaken'in değeri kendi merkezinden çok Lauterbrunnen, Grindelwald ve göl hatlarına erişimidir; her yüksek dağ deneyimi ayrı hava ve bütçe kararıdır.",
    sights: [["Harder Kulm", "Kısa fünikülerle iki göl panoraması; saatli bilet, kalabalık ve son inişi kontrol edin."], ["Lauterbrunnen Vadisi", "Şelaleler, Wengen/Mürren bağlantısı ve yürüyüşleri tek güne sığdırmak yerine bir alt bölge seçin."], ["Jungfraujoch veya Grindelwald-First", "Yüksek irtifa, pahalı bilet ve hava görünürlüğünü birlikte değerlendirin; kötü havada erteleyin."]],
    areas: [["Interlaken Ost", "Jungfrau ve Brienz bağlantıları için en pratik; erken tren günlerinde zaman kazandırır."], ["Matten ve Unterseen", "Daha sakin sokaklar, yerel restoranlar ve merkeze yürüyüş için iyi alternatifler."]], foods: [["Raclette ve fondü", "Turistik menü yerine peynir kaynağı, kişi başı koşulu ve içecek dahilini sorun."], ["Rösti ve dağ kahvaltısı", "Erken tren gününde market/fırın hazırlığı pahalı zirve öğününe iyi alternatiftir."]], dayTrips: [["Lauterbrunnen ve Mürren", "Vadi–teleferik hattında bakım ve son bağlantı belirleyicidir."], ["Brienz Gölü ve Giessbach", "Tekne sezonu ile şelale erişimini aynı tarifede eşleştirin."]], caution: "Yamaç paraşütü, kanyon, kayak ve dağ yürüyüşünde yalnız lisanslı işletme, uygun sigorta ve hava koşuluyla hareket edin; zirve biletini sırf önceden aldınız diye kapalı havada kullanmayın."
  },
  {
    city: "Zermatt", countryCode: "CH", focus: "Matterhorn, araçsız köy ve yüksek dağ rotaları", lede: "Matterhorn eteklerinde araçsız köy düzenini dişli trenler, buzullar ve dört mevsim patikalarla buluşturan Alp üssü.", days: "3–5 gün", arrival: "Täsch aktarmalı Zermatt Bahnhof", local: "Yürüyüş, elektrikli taksi, dağ treni ve teleferik", best: "Haziran–Eylül · Aralık–Nisan", pulse: "Zermatt'ta en pahalı hat her zaman en iyi gün değildir; Matterhorn görünürlüğü ve fiziksel kapasite, bilet listesinden önce gelir.",
    sights: [["Gornergrat", "Dişli trenle buzul ve Matterhorn panoraması; hangi durakta yürüyeceğinizi hava ve kar durumuna göre seçin."], ["Matterhorn Glacier Paradise", "Yüksek irtifada hızlı çıkış baş dönmesi yaratabilir; katman, güneş koruması ve yavaş tempo kullanın."], ["Five Lakes ve köy yürüyüşü", "Sunnegga hattı ile gölleri birleştirin; patika açılışını ve son füniküleri kontrol edin."]],
    areas: [["Bahnhofstrasse ve köy merkezi", "İstasyon, restoran ve dağ hatlarına yakın; fiyat en yüksek bölgelerden."], ["Winkelmatten ve Täsch", "Sakin köy kenarı veya bütçe/otopark için vadide alternatif; son tren saatine bakın."]], foods: [["Walliser Teller", "Kurutulmuş et ve peynir tabağında porsiyon ile içerik tercihlerinizi belirtin."], ["Raclette du Valais", "Yerel peynirin tek tek eritildiği servis için rezervasyon ve kişi başı koşulu sorun."]], dayTrips: [["Riffelsee", "Rüzgâr ve ışık uygunsa Matterhorn yansıması; bariyer dışına çıkmadan işaretli yolu kullanın."], ["Saas-Fee", "Komşu vadiye toplu taşıma uzundur; günübirlik yerine rota devamı olarak düşünün."]], caution: "Zermatt araçsızdır; kiralık araç Täsch'ta bırakılır. Yüksek irtifa belirtisini küçümsemeyin, kapalı patika veya buzul alanına rehbersiz girmeyin ve kurtarma kapsamlı sigorta kontrolü yapın."
  },
  {
    city: "St. Moritz", countryCode: "CH", focus: "Engadin gölleri, panoramik trenler ve kış sporları", lede: "Yüksek Engadin'de göl manzarasını dünya çapında demiryolu mühendisliği, sanat ve dört mevsim dağ sporlarıyla birleştiren tatil kenti.", days: "3–6 gün", arrival: "St. Moritz Bahnhof · Chur üzerinden RhB", local: "Rhätische Bahn, otobüs, füniküler ve yürüyüş", best: "Haziran–Eylül · Aralık–Mart", pulse: "St. Moritz lüks otellerden ibaret değildir; Engadin köyleri, göl patikaları ve Rhaetian Railway hattı bölgenin asıl derinliğini oluşturur.",
    sights: [["St. Moritz Gölü ve merkez", "Göl çevresini mevsime göre yürüyün; kışın buz üstü etkinliğe yalnız resmî güvenlik onayıyla çıkın."], ["Muottas Muragl veya Corviglia", "Gün batımı ya da yürüyüş için seçtiğiniz hatta son iniş ve rüzgâr bilgisini doğrulayın."], ["Bernina hattı", "UNESCO demiryolu peyzajını Tirano yönünde tam gün planlayın; panoramik tren rezervasyonu ile normal bölgesel treni ayırın."]],
    areas: [["St. Moritz Dorf", "Füniküler, mağaza ve restoranlara yakın; dik yokuş ve yüksek fiyatlı."], ["St. Moritz Bad ve Pontresina", "Göl/spa ya da Bernina–Morteratsch bağlantıları için daha işlevsel iki üs."]], foods: [["Engadiner Nusstorte", "Cevizli karamelli tart yoğun ve iyi taşınır; alerjen ile saklama koşulunu sorun."], ["Capuns ve pizzoccheri", "Pazı ruloları ya da karabuğday eriştesi bölgenin doyurucu dağ mutfağını gösterir."]], dayTrips: [["Pontresina ve Morteratsch", "Trenle kolay buzul vadisi; patika kapanışı ve geri çekilen buzul sınırına uyun."], ["Bernina–Tirano", "Rakım ve iklim değişir; dönüş trenini kaçırmayacak durak sayısı seçin."]], caution: "Donmuş göle yalnız resmî olarak açıldığında çıkın; kayak pistinde kapalı işareti aşmayın. Bernina Express adının her bağlantıda koltuk garantisi vermediğini, rezervasyon ve biletin ayrı olabileceğini okuyun."
  },
];

export const switzerlandGuides = makeRegionalGuides(profiles);
